{{ config(
    materialized='table',
    tags=['audit', 'gold']
) }}

-- Gold Layer Process Audit Log
-- This table must be created first to support audit tracking

SELECT 
    UUID_STRING() as AUDIT_LOG_ID,
    'INITIAL_AUDIT_LOG_CREATION' as PROCESS_NAME,
    'SETUP' as PROCESS_TYPE,
    CURRENT_TIMESTAMP() as EXECUTION_START_TIMESTAMP,
    CURRENT_TIMESTAMP() as EXECUTION_END_TIMESTAMP,
    0 as EXECUTION_DURATION_SECONDS,
    'SUCCESS' as EXECUTION_STATUS,
    'SYSTEM' as SOURCE_TABLE_NAME,
    'GO_PROCESS_AUDIT_LOG' as TARGET_TABLE_NAME,
    1 as RECORDS_READ,
    1 as RECORDS_PROCESSED,
    1 as RECORDS_INSERTED,
    0 as RECORDS_UPDATED,
    0 as RECORDS_FAILED,
    100.0 as DATA_QUALITY_SCORE,
    0 as ERROR_COUNT,
    0 as WARNING_COUNT,
    'MANUAL' as PROCESS_TRIGGER,
    'DBT_SYSTEM' as EXECUTED_BY,
    'SNOWFLAKE' as SERVER_NAME,
    '1.0' as PROCESS_VERSION,
    PARSE_JSON('{}') as CONFIGURATION_PARAMETERS,
    PARSE_JSON('{}') as PERFORMANCE_METRICS,
    CURRENT_DATE() as LOAD_DATE,
    CURRENT_DATE() as UPDATE_DATE,
    'DBT_GOLD_LAYER' as SOURCE_SYSTEM
WHERE 1=1
