{{ config(
    materialized='table',
    tags=['audit', 'gold']
) }}

-- Gold Layer Process Audit Log
-- This table must be created first to support audit tracking for all other models

SELECT 
    UUID_STRING() AS AUDIT_LOG_ID,
    'GOLD_LAYER_INITIALIZATION' AS PROCESS_NAME,
    'AUDIT_TABLE_CREATION' AS PROCESS_TYPE,
    CURRENT_TIMESTAMP() AS EXECUTION_START_TIMESTAMP,
    CURRENT_TIMESTAMP() AS EXECUTION_END_TIMESTAMP,
    0 AS EXECUTION_DURATION_SECONDS,
    'SUCCESS' AS EXECUTION_STATUS,
    'SYSTEM' AS SOURCE_TABLE_NAME,
    'GO_PROCESS_AUDIT_LOG' AS TARGET_TABLE_NAME,
    1 AS RECORDS_READ,
    1 AS RECORDS_PROCESSED,
    1 AS RECORDS_INSERTED,
    0 AS RECORDS_UPDATED,
    0 AS RECORDS_FAILED,
    100.0 AS DATA_QUALITY_SCORE,
    0 AS ERROR_COUNT,
    0 AS WARNING_COUNT,
    'MANUAL' AS PROCESS_TRIGGER,
    'DBT_SYSTEM' AS EXECUTED_BY,
    'SNOWFLAKE' AS SERVER_NAME,
    '1.0' AS PROCESS_VERSION,
    PARSE_JSON('{}') AS CONFIGURATION_PARAMETERS,
    PARSE_JSON('{}') AS PERFORMANCE_METRICS,
    CURRENT_DATE AS LOAD_DATE,
    CURRENT_DATE AS UPDATE_DATE,
    'DBT_GOLD_LAYER' AS SOURCE_SYSTEM

UNION ALL

SELECT 
    UUID_STRING() AS AUDIT_LOG_ID,
    'GOLD_LAYER_READY' AS PROCESS_NAME,
    'SYSTEM_READY' AS PROCESS_TYPE,
    CURRENT_TIMESTAMP() AS EXECUTION_START_TIMESTAMP,
    CURRENT_TIMESTAMP() AS EXECUTION_END_TIMESTAMP,
    0 AS EXECUTION_DURATION_SECONDS,
    'SUCCESS' AS EXECUTION_STATUS,
    'SYSTEM' AS SOURCE_TABLE_NAME,
    'ALL_GOLD_TABLES' AS TARGET_TABLE_NAME,
    0 AS RECORDS_READ,
    0 AS RECORDS_PROCESSED,
    0 AS RECORDS_INSERTED,
    0 AS RECORDS_UPDATED,
    0 AS RECORDS_FAILED,
    100.0 AS DATA_QUALITY_SCORE,
    0 AS ERROR_COUNT,
    0 AS WARNING_COUNT,
    'SYSTEM' AS PROCESS_TRIGGER,
    'DBT_SYSTEM' AS EXECUTED_BY,
    'SNOWFLAKE' AS SERVER_NAME,
    '1.0' AS PROCESS_VERSION,
    PARSE_JSON('{}') AS CONFIGURATION_PARAMETERS,
    PARSE_JSON('{}') AS PERFORMANCE_METRICS,
    CURRENT_DATE AS LOAD_DATE,
    CURRENT_DATE AS UPDATE_DATE,
    'DBT_GOLD_LAYER' AS SOURCE_SYSTEM
