{{ config(
    materialized='table',
    tags=['audit'],
    cluster_by=['PROCESS_START_TIME', 'PROCESS_NAME']
) }}

-- Audit log table for tracking all Gold layer transformations
-- This model runs first and tracks execution of all other models

SELECT 
    CAST(NULL AS VARCHAR(255)) AS PROCESS_ID,
    CAST(NULL AS VARCHAR(255)) AS PROCESS_NAME,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_TABLE,
    CAST(NULL AS VARCHAR(255)) AS TARGET_TABLE,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS PROCESS_START_TIME,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS PROCESS_END_TIME,
    CAST(NULL AS VARCHAR(50)) AS PROCESS_STATUS,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_PROCESSED,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_SUCCESS,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_FAILED,
    CAST(NULL AS VARCHAR(500)) AS ERROR_MESSAGE,
    CAST(NULL AS DATE) AS LOAD_DATE,
    CAST(NULL AS DATE) AS UPDATE_DATE,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_SYSTEM,
    CAST(NULL AS VARCHAR(255)) AS EXECUTED_BY
WHERE 1=0  -- Creates empty table structure

UNION ALL

-- Initial audit record for the audit log creation itself
SELECT 
    '{{ invocation_id }}' AS PROCESS_ID,
    'go_audit_log' AS PROCESS_NAME,
    'SYSTEM' AS SOURCE_TABLE,
    'GO_AUDIT_LOG' AS TARGET_TABLE,
    CURRENT_TIMESTAMP() AS PROCESS_START_TIME,
    CURRENT_TIMESTAMP() AS PROCESS_END_TIME,
    'COMPLETED' AS PROCESS_STATUS,
    1 AS RECORDS_PROCESSED,
    1 AS RECORDS_SUCCESS,
    0 AS RECORDS_FAILED,
    NULL AS ERROR_MESSAGE,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    'DBT_GOLD_PIPELINE' AS SOURCE_SYSTEM,
    '{{ target.user }}' AS EXECUTED_BY
