{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'ERROR_DATA_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_ERROR_DATA_SETUP', CURRENT_TIMESTAMP(), 'SYSTEM', 'GO_ERROR_DATA', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, RECORDS_PROCESSED, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'ERROR_DATA_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_ERROR_DATA_SETUP', CURRENT_TIMESTAMP(), 'SYSTEM', 'GO_ERROR_DATA', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, (SELECT COUNT(*) FROM {{ this }}), 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
) }}

-- Gold Layer Error Data Table
-- Tracks data quality issues and transformation errors
-- Supports data governance and error resolution workflows

WITH error_structure AS (
    SELECT 
        'INIT_ERROR_' || CURRENT_TIMESTAMP()::VARCHAR AS ERROR_KEY,
        CURRENT_TIMESTAMP() AS PIPELINE_RUN_TIMESTAMP,
        'SYSTEM'::VARCHAR(255) AS SOURCE_TABLE,
        'INIT_RECORD'::VARCHAR(255) AS SOURCE_RECORD_KEY,
        'INITIALIZATION'::VARCHAR(100) AS ERROR_TYPE,
        'SYSTEM'::VARCHAR(255) AS ERROR_COLUMN,
        'INITIAL_SETUP'::VARCHAR(255) AS ERROR_VALUE,
        'Initial error data table setup'::VARCHAR(255) AS ERROR_DESCRIPTION,
        'SYSTEM_SETUP'::VARCHAR(255) AS VALIDATION_RULE,
        'INFO'::VARCHAR(50) AS ERROR_SEVERITY,
        CURRENT_TIMESTAMP() AS ERROR_TIMESTAMP,
        'INIT_BATCH'::VARCHAR(255) AS PROCESSING_BATCH_KEY,
        'RESOLVED'::VARCHAR(50) AS RESOLUTION_STATUS,
        'System initialization complete'::VARCHAR(255) AS RESOLUTION_NOTES,
        'SYSTEM'::VARCHAR(255) AS RESOLVED_BY,
        CURRENT_TIMESTAMP() AS RESOLUTION_TIMESTAMP,
        CURRENT_DATE() AS LOAD_DATE,
        'DBT_GOLD_LAYER'::VARCHAR(255) AS SOURCE_SYSTEM
)

SELECT 
    ERROR_KEY,
    PIPELINE_RUN_TIMESTAMP,
    SOURCE_TABLE,
    SOURCE_RECORD_KEY,
    ERROR_TYPE,
    ERROR_COLUMN,
    ERROR_VALUE,
    ERROR_DESCRIPTION,
    VALIDATION_RULE,
    ERROR_SEVERITY,
    ERROR_TIMESTAMP,
    PROCESSING_BATCH_KEY,
    RESOLUTION_STATUS,
    RESOLUTION_NOTES,
    RESOLVED_BY,
    RESOLUTION_TIMESTAMP,
    LOAD_DATE,
    SOURCE_SYSTEM
FROM error_structure
