{{ config(
    materialized='table'
) }}

-- Audit table for Gold layer process tracking
-- This table must be created first and run before any other models

SELECT 
    CAST('INIT_001' AS VARCHAR(255)) AS AUDIT_LOG_ID,
    CAST('AUDIT_TABLE_INITIALIZATION' AS VARCHAR(255)) AS PROCESS_NAME,
    CAST('Gold Layer Process Audit' AS VARCHAR(255)) AS PROCESS_TYPE,
    CURRENT_TIMESTAMP() AS EXECUTION_START_TIMESTAMP,
    CURRENT_TIMESTAMP() AS EXECUTION_END_TIMESTAMP,
    0.0 AS EXECUTION_DURATION_SECONDS,
    CAST('SUCCESS' AS VARCHAR(255)) AS EXECUTION_STATUS,
    CAST('SYSTEM' AS VARCHAR(255)) AS SOURCE_TABLE_NAME,
    CAST('GO_PROCESS_AUDIT_LOG' AS VARCHAR(255)) AS TARGET_TABLE_NAME,
    1 AS RECORDS_READ,
    1 AS RECORDS_PROCESSED,
    1 AS RECORDS_INSERTED,
    0 AS RECORDS_UPDATED,
    0 AS RECORDS_FAILED,
    100.0 AS DATA_QUALITY_SCORE,
    0 AS ERROR_COUNT,
    0 AS WARNING_COUNT,
    CAST('MANUAL' AS VARCHAR(255)) AS PROCESS_TRIGGER,
    CAST('DBT_SYSTEM' AS VARCHAR(255)) AS EXECUTED_BY,
    CAST('SNOWFLAKE' AS VARCHAR(255)) AS SERVER_NAME,
    CAST('1.0.0' AS VARCHAR(255)) AS PROCESS_VERSION,
    PARSE_JSON('{}') AS CONFIGURATION_PARAMETERS,
    PARSE_JSON('{}') AS PERFORMANCE_METRICS,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    CAST('DBT_GOLD_ETL' AS VARCHAR(255)) AS SOURCE_SYSTEM
