{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ this }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'AUDIT_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_PROCESS_AUDIT_BUILD', CURRENT_TIMESTAMP(), 'SYSTEM', '{{ this }}', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER' WHERE '{{ this }}' != '{{ this }}'",
    post_hook="INSERT INTO {{ this }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'AUDIT_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_PROCESS_AUDIT_BUILD', CURRENT_TIMESTAMP(), 'SYSTEM', '{{ this }}', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0, 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER' WHERE '{{ this }}' != '{{ this }}'"
) }}

-- Gold Layer Process Audit Table
-- This table tracks all pipeline executions and transformations
-- Must be created first to support audit logging for other models

WITH audit_structure AS (
    SELECT 
        'INIT_AUDIT_' || CURRENT_TIMESTAMP()::VARCHAR AS AUDIT_KEY,
        'INITIAL_AUDIT_SETUP'::VARCHAR(255) AS PIPELINE_NAME,
        CURRENT_TIMESTAMP() AS PIPELINE_RUN_TIMESTAMP,
        'SYSTEM'::VARCHAR(255) AS SOURCE_TABLE,
        'GO_PROCESS_AUDIT'::VARCHAR(255) AS TARGET_TABLE,
        CURRENT_TIMESTAMP() AS EXECUTION_START_TIME,
        CURRENT_TIMESTAMP() AS EXECUTION_END_TIME,
        0::NUMBER(10,2) AS EXECUTION_DURATION_SECONDS,
        0::NUMBER(38,0) AS RECORDS_READ,
        1::NUMBER(38,0) AS RECORDS_PROCESSED,
        1::NUMBER(38,0) AS RECORDS_INSERTED,
        0::NUMBER(38,0) AS RECORDS_UPDATED,
        0::NUMBER(38,0) AS RECORDS_REJECTED,
        'SUCCESS'::VARCHAR(50) AS EXECUTION_STATUS,
        NULL::VARCHAR(16777216) AS ERROR_MESSAGE,
        CURRENT_USER()::VARCHAR(255) AS PROCESSED_BY,
        CURRENT_TIMESTAMP() AS DATA_FRESHNESS_TIMESTAMP,
        CURRENT_DATE() AS LOAD_DATE,
        'DBT_GOLD_LAYER'::VARCHAR(255) AS SOURCE_SYSTEM
)

SELECT 
    AUDIT_KEY,
    PIPELINE_NAME,
    PIPELINE_RUN_TIMESTAMP,
    SOURCE_TABLE,
    TARGET_TABLE,
    EXECUTION_START_TIME,
    EXECUTION_END_TIME,
    EXECUTION_DURATION_SECONDS,
    RECORDS_READ,
    RECORDS_PROCESSED,
    RECORDS_INSERTED,
    RECORDS_UPDATED,
    RECORDS_REJECTED,
    EXECUTION_STATUS,
    ERROR_MESSAGE,
    PROCESSED_BY,
    DATA_FRESHNESS_TIMESTAMP,
    LOAD_DATE,
    SOURCE_SYSTEM
FROM audit_structure
