{{ config(
    materialized='table',
    pre_hook=none,
    post_hook=none
) }}

-- Process Audit Log Table for Gold Layer Pipeline
-- This table must be created first and run before any other models

SELECT 
    'INITIAL_SETUP' AS AUDIT_LOG_ID,
    'INITIAL_SETUP' AS PROCESS_NAME,
    'AUDIT_TABLE_CREATION' AS PROCESS_TYPE,
    CURRENT_TIMESTAMP() AS EXECUTION_START_TIMESTAMP,
    CURRENT_TIMESTAMP() AS EXECUTION_END_TIMESTAMP,
    0 AS EXECUTION_DURATION_SECONDS,
    'SUCCESS' AS EXECUTION_STATUS,
    'SYSTEM' AS SOURCE_TABLE_NAME,
    'GO_PROCESS_AUDIT' AS TARGET_TABLE_NAME,
    1 AS RECORDS_READ,
    1 AS RECORDS_PROCESSED,
    1 AS RECORDS_INSERTED,
    0 AS RECORDS_UPDATED,
    0 AS RECORDS_FAILED,
    100.0 AS DATA_QUALITY_SCORE,
    0 AS ERROR_COUNT,
    0 AS WARNING_COUNT,
    'MANUAL' AS PROCESS_TRIGGER,
    'DBT_SYSTEM' AS EXECUTED_BY,
    'DBT_CLOUD' AS SERVER_NAME,
    '1.0.0' AS PROCESS_VERSION,
    PARSE_JSON('{}') AS CONFIGURATION_PARAMETERS,
    PARSE_JSON('{}') AS PERFORMANCE_METRICS,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    'DBT_GOLD_PIPELINE' AS SOURCE_SYSTEM

WHERE FALSE -- This ensures the initial record is not inserted, table structure is created
