version: 2

models:
  - name: go_audit_log
    description: "Audit log for Gold layer pipeline execution tracking"
    
  - name: go_dim_user
    description: "User dimension table with enhanced attributes"
    
  - name: go_dim_date
    description: "Date dimension with calendar and fiscal attributes"
    
  - name: go_dim_feature
    description: "Feature dimension with categorization"
    
  - name: go_dim_license
    description: "License dimension with entitlements"
    
  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    
  - name: go_dim_support_category
    description: "Support category dimension with SLA attributes"
    
  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with comprehensive metrics"
    
  - name: go_fact_feature_usage
    description: "Feature usage fact table with adoption metrics"
    
  - name: go_fact_revenue_events
    description: "Revenue events fact table with financial metrics"
    
  - name: go_fact_support_metrics
    description: "Support metrics fact table with SLA tracking"
