version: 2

models:
  - name: go_audit_log
    description: "Gold layer audit log for tracking all pipeline executions"
    columns:
      - name: audit_log_id
        description: "Unique audit log identifier"
        tests:
          - unique
          - not_null
      - name: process_name
        description: "Name of the process being audited"
        tests:
          - not_null
      - name: execution_status
        description: "Status of process execution"
        tests:
          - accepted_values:
              values: ['RUNNING', 'SUCCESS', 'FAILED']

  - name: go_dim_date
    description: "Date dimension table for time-based analysis"
    columns:
      - name: date_id
        description: "Unique date identifier"
        tests:
          - unique
          - not_null
      - name: date_key
        description: "Date value used as natural key"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year component"
        tests:
          - not_null

  - name: go_dim_user
    description: "User dimension table with enhanced attributes"
    columns:
      - name: user_dim_id
        description: "Unique user dimension identifier"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Business key for user"
        tests:
          - not_null
      - name: plan_type
        description: "User subscription plan type"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Unknown']

  - name: go_dim_feature
    description: "Feature dimension table with categorization"
    columns:
      - name: feature_id
        description: "Unique feature identifier"
        tests:
          - unique
          - not_null
      - name: feature_name
        description: "Name of the feature"
        tests:
          - not_null
      - name: feature_category
        description: "Feature category classification"
        tests:
          - accepted_values:
              values: ['Collaboration', 'Recording', 'Communication', 'Advanced Meeting', 'Engagement', 'General']

  - name: go_dim_license
    description: "License dimension table with entitlements"
    columns:
      - name: license_id
        description: "Unique license identifier"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Type of license"
        tests:
          - not_null
      - name: monthly_price
        description: "Monthly price for license"
        tests:
          - not_null

  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    columns:
      - name: meeting_type_id
        description: "Unique meeting type identifier"
        tests:
          - unique
          - not_null
      - name: duration_category
        description: "Meeting duration category"
        tests:
          - accepted_values:
              values: ['Brief', 'Standard', 'Extended', 'Long']

  - name: go_dim_support_category
    description: "Support category dimension with SLA information"
    columns:
      - name: support_category_id
        description: "Unique support category identifier"
        tests:
          - unique
          - not_null
      - name: support_category
        description: "Support ticket category"
        tests:
          - not_null
      - name: priority_level
        description: "Priority level for support tickets"
        tests:
          - accepted_values:
              values: ['Critical', 'High', 'Medium', 'Low']

  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with comprehensive metrics"
    columns:
      - name: meeting_activity_id
        description: "Unique meeting activity identifier"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_id
      - name: participant_count
        description: "Number of meeting participants"
        tests:
          - not_null

  - name: go_fact_feature_usage
    description: "Feature usage fact table with adoption metrics"
    columns:
      - name: feature_usage_id
        description: "Unique feature usage identifier"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_id
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null

  - name: go_fact_revenue_events
    description: "Revenue events fact table with financial metrics"
    columns:
      - name: revenue_event_id
        description: "Unique revenue event identifier"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_id
      - name: gross_amount
        description: "Gross revenue amount"
        tests:
          - not_null

  - name: go_fact_support_metrics
    description: "Support metrics fact table with SLA tracking"
    columns:
      - name: support_metrics_id
        description: "Unique support metrics identifier"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_id
      - name: resolution_time_hours
        description: "Time taken to resolve ticket in hours"
