version: 2

models:
  - name: go_audit_log
    description: "Audit log table for Gold layer pipeline execution tracking"
    
  - name: go_dim_user
    description: "User dimension table with enhanced attributes for analytics"
    
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    
  - name: go_dim_feature
    description: "Feature dimension with categorization and characteristics"
    
  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with comprehensive metrics"
