version: 2

models:
  - name: go_audit_log
    description: "Audit log for Gold layer pipeline execution tracking"
    columns:
      - name: audit_log_id
        description: "Unique audit log identifier"
      - name: process_name
        description: "Name of the executed process"
      - name: execution_status
        description: "Status of process execution"
      - name: records_processed
        description: "Number of records processed"
        
  - name: go_dim_user
    description: "User dimension table with enhanced attributes"
    columns:
      - name: user_dim_id
        description: "Surrogate key for user dimension"
      - name: user_key
        description: "Business key for user"
      - name: user_id
        description: "Original user identifier"
      - name: user_name
        description: "Standardized user name"
      - name: plan_type
        description: "Standardized subscription plan type"
      - name: is_current_record
        description: "Flag indicating current record for SCD Type 2"
        
  - name: go_dim_date
    description: "Date dimension with calendar and fiscal attributes"
    columns:
      - name: date_id
        description: "Surrogate key for date dimension"
      - name: date_value
        description: "Actual date value"
      - name: year
        description: "Calendar year"
      - name: fiscal_year
        description: "Fiscal year starting April 1st"
      - name: is_weekend
        description: "Weekend flag"
        
  - name: go_dim_feature
    description: "Feature dimension with categorization"
    columns:
      - name: feature_id
        description: "Surrogate key for feature dimension"
      - name: feature_name
        description: "Standardized feature name"
      - name: feature_category
        description: "Feature category classification"
      - name: is_premium_feature
        description: "Premium feature flag"
        
  - name: go_dim_license
    description: "License dimension with entitlements"
    columns:
      - name: license_id
        description: "Surrogate key for license dimension"
      - name: license_type
        description: "Standardized license type"
      - name: license_category
        description: "License category classification"
      - name: monthly_price
        description: "Monthly subscription price"
        
  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    columns:
      - name: meeting_type_id
        description: "Surrogate key for meeting type dimension"
      - name: meeting_category
        description: "Meeting category based on duration"
      - name: time_of_day_category
        description: "Time of day classification"
      - name: is_weekend_meeting
        description: "Weekend meeting flag"
        
  - name: go_dim_support_category
    description: "Support category dimension with SLA attributes"
    columns:
      - name: support_category_id
        description: "Surrogate key for support category dimension"
      - name: support_category
        description: "Standardized support category"
      - name: priority_level
        description: "Priority level classification"
      - name: sla_target_hours
        description: "SLA target resolution time in hours"
        
  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with comprehensive metrics"
    columns:
      - name: meeting_activity_id
        description: "Surrogate key for meeting activity fact"
      - name: date_id
        description: "Foreign key to date dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension (host)"
      - name: participant_count
        description: "Number of meeting participants"
      - name: duration_minutes
        description: "Meeting duration in minutes"
      - name: meeting_quality_score
        description: "Calculated meeting quality score"
        
  - name: go_fact_feature_usage
    description: "Feature usage fact table with adoption metrics"
    columns:
      - name: feature_usage_id
        description: "Surrogate key for feature usage fact"
      - name: date_id
        description: "Foreign key to date dimension"
      - name: feature_id
        description: "Foreign key to feature dimension"
      - name: usage_count
        description: "Number of times feature was used"
      - name: feature_adoption_score
        description: "Calculated feature adoption score"
        
  - name: go_fact_revenue_events
    description: "Revenue events fact table with financial metrics"
    columns:
      - name: revenue_event_id
        description: "Surrogate key for revenue event fact"
      - name: date_id
        description: "Foreign key to date dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension"
      - name: gross_amount
        description: "Gross revenue amount"
      - name: net_amount
        description: "Net revenue amount after taxes"
      - name: mrr_impact
        description: "Monthly recurring revenue impact"
        
  - name: go_fact_support_metrics
    description: "Support metrics fact table with SLA tracking"
    columns:
      - name: support_metrics_id
        description: "Surrogate key for support metrics fact"
      - name: date_id
        description: "Foreign key to date dimension"
      - name: support_category_id
        description: "Foreign key to support category dimension"
      - name: resolution_time_hours
        description: "Time to resolve ticket in hours"
      - name: sla_met
        description: "Flag indicating if SLA was met"
      - name: customer_satisfaction_score
        description: "Customer satisfaction rating"
