version: 2

models:
  - name: go_audit_log
    description: "Gold layer audit log tracking all pipeline executions"
    columns:
      - name: audit_log_id
        description: "Unique identifier for each audit log entry"
        tests:
          - unique
          - not_null
      - name: process_name
        description: "Name of the process being executed"
      - name: execution_status
        description: "Status of the process execution"
        tests:
          - accepted_values:
              values: ['RUNNING', 'SUCCESS', 'FAILED']
              
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: date_id
        description: "Unique identifier for each date"
        tests:
          - unique
          - not_null
      - name: date_value
        description: "The actual date value"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year component of the date"
      - name: quarter
        description: "Quarter component of the date"
      - name: month
        description: "Month component of the date"
        
  - name: go_dim_user
    description: "User dimension with enhanced attributes"
    columns:
      - name: user_dim_id
        description: "Unique identifier for each user dimension record"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Business key for the user"
        tests:
          - not_null
      - name: user_name
        description: "Display name of the user"
      - name: plan_type
        description: "Subscription plan type"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Unknown']
              
  - name: go_dim_feature
    description: "Feature dimension with categorization"
    columns:
      - name: feature_id
        description: "Unique identifier for each feature"
        tests:
          - unique
          - not_null
      - name: feature_name
        description: "Name of the feature"
        tests:
          - not_null
      - name: feature_category
        description: "Category classification of the feature"
        
  - name: go_dim_license
    description: "License dimension with entitlements"
    columns:
      - name: license_id
        description: "Unique identifier for each license type"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Type of license"
        tests:
          - not_null
      - name: monthly_price
        description: "Monthly price for the license"
        tests:
          - not_null
          
  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    columns:
      - name: meeting_type_id
        description: "Unique identifier for each meeting type"
        tests:
          - unique
          - not_null
      - name: meeting_category
        description: "Category of the meeting based on duration"
        
  - name: go_dim_support_category
    description: "Support category dimension with SLA information"
    columns:
      - name: support_category_id
        description: "Unique identifier for each support category"
        tests:
          - unique
          - not_null
      - name: support_category
        description: "Support ticket category"
        tests:
          - not_null
      - name: sla_target_hours
        description: "SLA target in hours for resolution"
        
  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with comprehensive metrics"
    columns:
      - name: meeting_activity_id
        description: "Unique identifier for each meeting activity record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Business key for the meeting"
        tests:
          - not_null
      - name: scheduled_duration_minutes
        description: "Duration of the meeting in minutes"
        tests:
          - not_null
          
  - name: go_fact_feature_usage
    description: "Feature usage fact table with adoption metrics"
    columns:
      - name: feature_usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - unique
          - not_null
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
          
  - name: go_fact_revenue_events
    description: "Revenue events fact table with financial metrics"
    columns:
      - name: revenue_event_id
        description: "Unique identifier for each revenue event"
        tests:
          - unique
          - not_null
      - name: gross_amount
        description: "Gross revenue amount"
        tests:
          - not_null
          
  - name: go_fact_support_metrics
    description: "Support metrics fact table with resolution performance"
    columns:
      - name: support_metrics_id
        description: "Unique identifier for each support metrics record"
        tests:
          - unique
          - not_null
      - name: ticket_id
        description: "Business key for the support ticket"
        tests:
          - not_null
