version: 2

models:
  - name: go_process_audit
    description: "Gold layer process audit table for tracking pipeline executions"
    columns:
      - name: AUDIT_LOG_ID
        description: "Unique identifier for each audit log entry"
        data_type: VARCHAR(255)
      - name: PROCESS_NAME
        description: "Name of the process being executed"
        data_type: VARCHAR(255)
      - name: PROCESS_TYPE
        description: "Type of process (DIMENSION_LOAD, FACT_LOAD, etc.)"
        data_type: VARCHAR(255)
      - name: EXECUTION_STATUS
        description: "Status of process execution"
        data_type: VARCHAR(255)
      - name: SOURCE_TABLE_NAME
        description: "Name of source table"
        data_type: VARCHAR(255)
      - name: TARGET_TABLE_NAME
        description: "Name of target table"
        data_type: VARCHAR(255)

  - name: go_dim_date
    description: "Gold layer date dimension for time-based analysis"
    columns:
      - name: DATE_KEY
        description: "Primary key for date dimension"
        data_type: DATE
      - name: DATE_ID
        description: "Surrogate key for date dimension"
        data_type: NUMBER
      - name: YEAR
        description: "Year component of the date"
        data_type: NUMBER
      - name: QUARTER
        description: "Quarter component of the date"
        data_type: NUMBER
      - name: MONTH
        description: "Month component of the date"
        data_type: NUMBER
      - name: MONTH_NAME
        description: "Name of the month"
        data_type: VARCHAR(20)

  - name: go_dim_user
    description: "Gold layer user dimension with enhanced attributes"
    columns:
      - name: USER_KEY
        description: "Primary key for user dimension"
        data_type: VARCHAR(255)
      - name: USER_DIM_ID
        description: "Surrogate key for user dimension"
        data_type: NUMBER
      - name: USER_ID
        description: "Business key for user"
        data_type: VARCHAR(255)
      - name: USER_NAME
        description: "Display name of the user"
        data_type: VARCHAR(255)
      - name: EMAIL_DOMAIN
        description: "Email domain of the user"
        data_type: VARCHAR(255)
      - name: COMPANY
        description: "Company or organization name"
        data_type: VARCHAR(255)
      - name: PLAN_TYPE
        description: "Standardized subscription plan type"
        data_type: VARCHAR(255)
      - name: IS_CURRENT_RECORD
        description: "Flag indicating if this is the current record"
        data_type: BOOLEAN

  - name: go_dim_feature
    description: "Gold layer feature dimension with categorization"
    columns:
      - name: FEATURE_KEY
        description: "Primary key for feature dimension"
        data_type: VARCHAR(255)
      - name: FEATURE_ID
        description: "Surrogate key for feature dimension"
        data_type: NUMBER
      - name: FEATURE_NAME
        description: "Name of the feature"
        data_type: VARCHAR(255)
      - name: FEATURE_CATEGORY
        description: "Category of the feature"
        data_type: VARCHAR(255)
      - name: IS_PREMIUM_FEATURE
        description: "Flag indicating if this is a premium feature"
        data_type: BOOLEAN

  - name: go_dim_license
    description: "Gold layer license dimension with entitlements"
    columns:
      - name: LICENSE_KEY
        description: "Primary key for license dimension"
        data_type: VARCHAR(255)
      - name: LICENSE_ID
        description: "Surrogate key for license dimension"
        data_type: NUMBER
      - name: LICENSE_TYPE
        description: "Type of license"
        data_type: VARCHAR(255)
      - name: LICENSE_CATEGORY
        description: "Category of the license"
        data_type: VARCHAR(255)
      - name: MONTHLY_PRICE
        description: "Monthly price of the license"
        data_type: NUMBER
      - name: IS_CURRENT_RECORD
        description: "Flag indicating if this is the current record"
        data_type: BOOLEAN

  - name: go_dim_meeting
    description: "Gold layer meeting dimension with characteristics"
    columns:
      - name: MEETING_KEY
        description: "Primary key for meeting dimension"
        data_type: VARCHAR(255)
      - name: MEETING_ID
        description: "Surrogate key for meeting dimension"
        data_type: NUMBER
      - name: MEETING_TYPE
        description: "Type of meeting"
        data_type: VARCHAR(255)
      - name: DURATION_CATEGORY
        description: "Category based on meeting duration"
        data_type: VARCHAR(255)
      - name: IS_WEEKEND
        description: "Flag indicating if meeting was on weekend"
        data_type: BOOLEAN

  - name: go_dim_support_category
    description: "Gold layer support category dimension"
    columns:
      - name: SUPPORT_CATEGORY_KEY
        description: "Primary key for support category dimension"
        data_type: VARCHAR(255)
      - name: SUPPORT_CATEGORY_ID
        description: "Surrogate key for support category dimension"
        data_type: NUMBER
      - name: SUPPORT_CATEGORY
        description: "Support ticket category"
        data_type: VARCHAR(255)
      - name: PRIORITY_LEVEL
        description: "Priority level of the support category"
        data_type: VARCHAR(255)
      - name: SLA_TARGET_HOURS
        description: "SLA target in hours"
        data_type: NUMBER

  - name: go_fact_meeting_activity
    description: "Gold layer fact table for meeting activities"
    columns:
      - name: MEETING_ACTIVITY_ID
        description: "Unique identifier for meeting activity"
        data_type: NUMBER
      - name: USER_KEY
        description: "Foreign key to user dimension"
        data_type: VARCHAR(255)
      - name: MEETING_KEY
        description: "Foreign key to meeting dimension"
        data_type: VARCHAR(255)
      - name: DATE_KEY
        description: "Foreign key to date dimension"
        data_type: DATE
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes"
        data_type: NUMBER
      - name: PARTICIPANT_COUNT
        description: "Number of participants in the meeting"
        data_type: NUMBER

  - name: go_fact_support_activity
    description: "Gold layer fact table for support activities"
    columns:
      - name: SUPPORT_ACTIVITY_ID
        description: "Unique identifier for support activity"
        data_type: NUMBER
      - name: USER_KEY
        description: "Foreign key to user dimension"
        data_type: VARCHAR(255)
      - name: DATE_KEY
        description: "Foreign key to date dimension"
        data_type: DATE
      - name: SUPPORT_CATEGORY_KEY
        description: "Foreign key to support category dimension"
        data_type: VARCHAR(255)
      - name: RESOLUTION_TIME_HOURS
        description: "Time taken to resolve the ticket in hours"
        data_type: NUMBER
      - name: SLA_MET
        description: "Flag indicating if SLA was met"
        data_type: BOOLEAN

  - name: go_fact_revenue_activity
    description: "Gold layer fact table for revenue activities"
    columns:
      - name: REVENUE_ACTIVITY_ID
        description: "Unique identifier for revenue activity"
        data_type: NUMBER
      - name: USER_KEY
        description: "Foreign key to user dimension"
        data_type: VARCHAR(255)
      - name: LICENSE_KEY
        description: "Foreign key to license dimension"
        data_type: VARCHAR(255)
      - name: DATE_KEY
        description: "Foreign key to date dimension"
        data_type: DATE
      - name: AMOUNT
        description: "Transaction amount"
        data_type: NUMBER
      - name: NET_REVENUE_AMOUNT
        description: "Net revenue amount after refunds"
        data_type: NUMBER

  - name: go_fact_feature_usage
    description: "Gold layer fact table for feature usage"
    columns:
      - name: FEATURE_USAGE_ID
        description: "Unique identifier for feature usage"
        data_type: NUMBER
      - name: DATE_KEY
        description: "Foreign key to date dimension"
        data_type: DATE
      - name: FEATURE_KEY
        description: "Foreign key to feature dimension"
        data_type: VARCHAR(255)
      - name: USER_KEY
        description: "Foreign key to user dimension"
        data_type: VARCHAR(255)
      - name: USAGE_COUNT
        description: "Number of times feature was used"
        data_type: NUMBER
      - name: FEATURE_ADOPTION_SCORE
        description: "Score indicating feature adoption level"
        data_type: NUMBER
