version: 2

models:
  - name: go_dim_date
    description: "Date dimension table for time-based analysis"
    columns:
      - name: date_value
        description: "The actual date value"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year component of the date"
      - name: quarter
        description: "Quarter component (1-4)"
      - name: month
        description: "Month component (1-12)"
      - name: month_name
        description: "Full month name"
      - name: day_of_month
        description: "Day of month (1-31)"
      - name: day_of_week
        description: "Day of week (1-7)"
      - name: day_name
        description: "Full day name"
      - name: is_weekend
        description: "Boolean flag for weekend days"
      - name: is_holiday
        description: "Boolean flag for holidays"
      - name: fiscal_year
        description: "Fiscal year (starting April 1st)"
      - name: fiscal_quarter
        description: "Fiscal quarter (1-4)"
      - name: week_of_year
        description: "Week number in the year"

  - name: go_dim_user
    description: "User dimension table with enhanced attributes"
    columns:
      - name: user_id
        description: "Business key - original user identifier"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "Standardized user display name"
      - name: email_domain
        description: "Extracted email domain for analysis"
      - name: company
        description: "Standardized company name"
      - name: plan_type
        description: "Standardized subscription plan type"
      - name: plan_category
        description: "High-level plan categorization (Free/Paid)"
      - name: registration_date
        description: "User registration date"
      - name: user_status
        description: "Current user status (Active/Inactive)"
      - name: geographic_region
        description: "Derived geographic region"
      - name: industry_sector
        description: "Derived industry classification"
      - name: user_role
        description: "User role classification"
      - name: account_type
        description: "Account type (Individual/Business)"
      - name: language_preference
        description: "User language preference"
      - name: effective_start_date
        description: "SCD Type 2 - Record effective start date"
      - name: effective_end_date
        description: "SCD Type 2 - Record effective end date"
      - name: is_current_record
        description: "SCD Type 2 - Current record flag"

  - name: go_dim_feature
    description: "Feature dimension table with categorization"
    columns:
      - name: feature_name
        description: "Standardized feature name"
        tests:
          - unique
          - not_null
      - name: feature_category
        description: "Feature category classification"
      - name: feature_type
        description: "Feature type (Core/Standard/Advanced)"
      - name: feature_complexity
        description: "Feature complexity level (Low/Medium/High)"
      - name: is_premium_feature
        description: "Boolean flag for premium features"
      - name: feature_release_date
        description: "Feature release date"
      - name: feature_status
        description: "Current feature status"
      - name: usage_frequency_category
        description: "Expected usage frequency"
      - name: feature_description
        description: "Feature description"
      - name: target_user_segment
        description: "Target user segment for feature"

  - name: go_dim_license
    description: "License dimension table with entitlements"
    columns:
      - name: license_type
        description: "Standardized license type"
        tests:
          - unique
          - not_null
      - name: license_category
        description: "License category classification"
      - name: license_tier
        description: "License tier (Tier 0-3)"
      - name: max_participants
        description: "Maximum participants allowed"
      - name: storage_limit_gb
        description: "Storage limit in GB"
      - name: recording_limit_hours
        description: "Recording limit in hours"
      - name: admin_features_included
        description: "Boolean flag for admin features"
      - name: api_access_included
        description: "Boolean flag for API access"
      - name: sso_support_included
        description: "Boolean flag for SSO support"
      - name: monthly_price
        description: "Monthly subscription price"
      - name: annual_price
        description: "Annual subscription price"
      - name: license_benefits
        description: "License benefits description"
      - name: effective_start_date
        description: "License effective start date"
      - name: effective_end_date
        description: "License effective end date"
      - name: is_current_record
        description: "Current record flag"

  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    columns:
      - name: meeting_type
        description: "Meeting type classification"
      - name: meeting_category
        description: "Meeting category based on duration"
      - name: duration_category
        description: "Duration category (Brief/Standard/Extended/Long)"
      - name: participant_size_category
        description: "Participant size category"
      - name: time_of_day_category
        description: "Time of day category (Morning/Afternoon/Evening/Night)"
      - name: day_of_week
        description: "Day of week"
      - name: is_weekend_meeting
        description: "Boolean flag for weekend meetings"
      - name: is_recurring_type
        description: "Boolean flag for recurring meetings"
      - name: meeting_quality_threshold
        description: "Quality threshold for meeting type"
      - name: typical_features_used
        description: "Typical features used in this meeting type"
      - name: business_purpose
        description: "Business purpose classification"

  - name: go_dim_support_category
    description: "Support category dimension with SLA information"
    columns:
      - name: support_category
        description: "Support category classification"
        tests:
          - unique
          - not_null
      - name: support_subcategory
        description: "Support subcategory"
      - name: priority_level
        description: "Priority level (Critical/High/Medium/Low)"
      - name: expected_resolution_time_hours
        description: "Expected resolution time in hours"
      - name: requires_escalation
        description: "Boolean flag for escalation requirement"
      - name: self_service_available
        description: "Boolean flag for self-service availability"
      - name: knowledge_base_articles
        description: "Number of related knowledge base articles"
      - name: common_resolution_steps
        description: "Common resolution steps"
      - name: customer_impact_level
        description: "Customer impact level (High/Medium/Low)"
      - name: department_responsible
        description: "Responsible department"
      - name: sla_target_hours
        description: "SLA target in hours"

  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with comprehensive metrics"
    columns:
      - name: host_user_dim_id
        description: "Foreign key to user dimension (meeting host)"
        tests:
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
      - name: meeting_type_id
        description: "Foreign key to meeting type dimension"
      - name: meeting_id
        description: "Business key - meeting identifier"
        tests:
          - unique
          - not_null
      - name: meeting_date
        description: "Meeting date"
      - name: meeting_start_time
        description: "Meeting start timestamp"
      - name: meeting_end_time
        description: "Meeting end timestamp"
      - name: scheduled_duration_minutes
        description: "Scheduled meeting duration in minutes"
      - name: actual_duration_minutes
        description: "Actual meeting duration in minutes"
      - name: participant_count
        description: "Total number of participants"
      - name: unique_participants
        description: "Number of unique participants"
      - name: host_duration_minutes
        description: "Host participation duration in minutes"
      - name: total_participant_minutes
        description: "Total participant minutes across all attendees"
      - name: average_participation_minutes
        description: "Average participation time per participant"
      - name: peak_concurrent_participants
        description: "Peak concurrent participants"
      - name: late_joiners_count
        description: "Number of participants who joined late"
      - name: early_leavers_count
        description: "Number of participants who left early"
      - name: features_used_count
        description: "Number of different features used"
      - name: screen_share_duration_minutes
        description: "Screen sharing duration in minutes"
      - name: recording_duration_minutes
        description: "Recording duration in minutes"
      - name: chat_messages_count
        description: "Number of chat messages"
      - name: file_shares_count
        description: "Number of files shared"
      - name: breakout_rooms_used
        description: "Number of breakout rooms used"
      - name: polls_conducted
        description: "Number of polls conducted"
      - name: meeting_quality_score
        description: "Overall meeting quality score (1-5)"
      - name: audio_quality_score
        description: "Audio quality score (1-5)"
      - name: video_quality_score
        description: "Video quality score (1-5)"
      - name: connection_issues_count
        description: "Number of connection issues"
      - name: meeting_satisfaction_score
        description: "Meeting satisfaction score (1-5)"

  - name: go_fact_feature_usage
    description: "Feature usage fact table with adoption metrics"
    columns:
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
      - name: feature_id
        description: "Foreign key to feature dimension"
        tests:
          - not_null
      - name: user_dim_id
        description: "Foreign key to user dimension"
      - name: meeting_id
        description: "Associated meeting identifier"
      - name: usage_date
        description: "Date of feature usage"
      - name: usage_timestamp
        description: "Timestamp of feature usage"
      - name: feature_name
        description: "Name of the feature used"
      - name: usage_count
        description: "Number of times feature was used"
      - name: usage_duration_minutes
        description: "Duration of feature usage in minutes"
      - name: session_duration_minutes
        description: "Total session duration in minutes"
      - name: feature_adoption_score
        description: "Feature adoption score (1-5)"
      - name: user_experience_rating
        description: "User experience rating (1-5)"
      - name: feature_performance_score
        description: "Feature performance score (1-5)"
      - name: concurrent_features_count
        description: "Number of concurrent features used"
      - name: usage_context
        description: "Context of feature usage"
      - name: device_type
        description: "Device type used"
      - name: platform_version
        description: "Platform version"
      - name: error_count
        description: "Number of errors encountered"
      - name: success_rate
        description: "Success rate percentage"

  - name: go_fact_revenue_events
    description: "Revenue events fact table with financial metrics"
    columns:
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
      - name: license_id
        description: "Foreign key to license dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension"
        tests:
          - not_null
      - name: billing_event_id
        description: "Business key - billing event identifier"
        tests:
          - unique
          - not_null
      - name: transaction_date
        description: "Transaction date"
      - name: transaction_timestamp
        description: "Transaction timestamp"
      - name: event_type
        description: "Type of billing event"
      - name: revenue_type
        description: "Revenue type (Recurring/One-time/Other)"
      - name: gross_amount
        description: "Gross transaction amount"
      - name: tax_amount
        description: "Tax amount"
      - name: discount_amount
        description: "Discount amount"
      - name: net_amount
        description: "Net transaction amount"
      - name: currency_code
        description: "Currency code"
      - name: exchange_rate
        description: "Exchange rate to USD"
      - name: usd_amount
        description: "Amount in USD"
      - name: payment_method
        description: "Payment method used"
      - name: subscription_period_months
        description: "Subscription period in months"
      - name: license_quantity
        description: "Number of licenses"
      - name: proration_amount
        description: "Prorated amount"
      - name: commission_amount
        description: "Commission amount"
      - name: mrr_impact
        description: "Monthly Recurring Revenue impact"
      - name: arr_impact
        description: "Annual Recurring Revenue impact"
      - name: customer_lifetime_value
        description: "Customer lifetime value"
      - name: churn_risk_score
        description: "Churn risk score (1-5)"
      - name: payment_status
        description: "Payment status"
      - name: refund_reason
        description: "Refund reason if applicable"
      - name: sales_channel
        description: "Sales channel"
      - name: promotion_code
        description: "Promotion code used"

  - name: go_fact_support_metrics
    description: "Support metrics fact table with SLA tracking"
    columns:
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
      - name: support_category_id
        description: "Foreign key to support category dimension"
        tests:
          - not_null
      - name: user_dim_id
        description: "Foreign key to user dimension"
        tests:
          - not_null
      - name: ticket_id
        description: "Business key - support ticket identifier"
        tests:
          - unique
          - not_null
      - name: ticket_created_date
        description: "Ticket creation date"
      - name: ticket_created_timestamp
        description: "Ticket creation timestamp"
      - name: ticket_closed_date
        description: "Ticket closure date"
      - name: ticket_closed_timestamp
        description: "Ticket closure timestamp"
      - name: first_response_timestamp
        description: "First response timestamp"
      - name: resolution_timestamp
        description: "Resolution timestamp"
      - name: ticket_category
        description: "Ticket category"
      - name: ticket_subcategory
        description: "Ticket subcategory"
      - name: priority_level
        description: "Priority level"
      - name: severity_level
        description: "Severity level"
      - name: resolution_status
        description: "Resolution status"
      - name: first_response_time_hours
        description: "First response time in hours"
      - name: resolution_time_hours
        description: "Total resolution time in hours"
      - name: active_work_time_hours
        description: "Active work time in hours"
      - name: customer_wait_time_hours
        description: "Customer wait time in hours"
      - name: escalation_count
        description: "Number of escalations"
      - name: reassignment_count
        description: "Number of reassignments"
      - name: reopened_count
        description: "Number of times ticket was reopened"
      - name: agent_interactions_count
        description: "Number of agent interactions"
      - name: customer_interactions_count
        description: "Number of customer interactions"
      - name: knowledge_base_articles_used
        description: "Number of knowledge base articles used"
      - name: customer_satisfaction_score
        description: "Customer satisfaction score (1-5)"
      - name: first_contact_resolution
        description: "Boolean flag for first contact resolution"
      - name: sla_met
        description: "Boolean flag for SLA compliance"
      - name: sla_breach_hours
        description: "SLA breach time in hours"
      - name: resolution_method
        description: "Method used for resolution"
      - name: root_cause_category
        description: "Root cause category"
      - name: preventable_issue
        description: "Boolean flag for preventable issues"
      - name: follow_up_required
        description: "Boolean flag for follow-up requirement"
      - name: cost_to_resolve
        description: "Cost to resolve the ticket"
