version: 2

models:
  - name: go_dim_user
    description: "Gold layer user dimension with enhanced attributes for analytics"
    columns:
      - name: user_id
        description: "Business key - original user identifier"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Standardized user display name"
      - name: email_domain
        description: "Extracted and standardized email domain"
      - name: company
        description: "Standardized company name"
      - name: plan_type
        description: "Standardized subscription plan type"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Unknown']
      - name: plan_category
        description: "High-level plan categorization"
        tests:
          - accepted_values:
              values: ['Free', 'Paid']
      - name: user_status
        description: "Current user status"
        tests:
          - accepted_values:
              values: ['Active', 'Inactive']
      - name: is_current_record
        description: "SCD Type 2 current record flag"
        tests:
          - not_null
      - name: load_timestamp
        description: "Record load timestamp"
        tests:
          - not_null
      - name: update_timestamp
        description: "Record update timestamp"
        tests:
          - not_null

  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: date_value
        description: "Actual date value"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year component"
        tests:
          - not_null
      - name: month
        description: "Month component"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: is_weekend
        description: "Weekend flag"
        tests:
          - not_null

  - name: go_dim_feature
    description: "Feature dimension with categorization and characteristics"
    columns:
      - name: feature_name
        description: "Standardized feature name"
        tests:
          - not_null
          - unique
      - name: feature_category
        description: "Feature category classification"
        tests:
          - accepted_values:
              values: ['Collaboration', 'Recording', 'Communication', 'Advanced Meeting', 'Engagement', 'General']
      - name: is_premium_feature
        description: "Premium feature flag"
        tests:
          - not_null

  - name: go_dim_license
    description: "License dimension with entitlements and pricing"
    columns:
      - name: license_type
        description: "Standardized license type"
        tests:
          - not_null
          - unique
      - name: license_category
        description: "License category classification"
        tests:
          - accepted_values:
              values: ['Standard', 'Professional', 'Enterprise', 'Other']
      - name: monthly_price
        description: "Monthly pricing"
        tests:
          - not_null

  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    columns:
      - name: duration_category
        description: "Meeting duration category"
        tests:
          - accepted_values:
              values: ['Brief', 'Standard', 'Extended', 'Long']
      - name: time_of_day_category
        description: "Time of day category"
        tests:
          - accepted_values:
              values: ['Morning', 'Afternoon', 'Evening', 'Night']

  - name: go_dim_support_category
    description: "Support category dimension with SLA and characteristics"
    columns:
      - name: support_category
        description: "Standardized support category"
        tests:
          - not_null
          - unique
      - name: priority_level
        description: "Priority level classification"
        tests:
          - accepted_values:
              values: ['Critical', 'High', 'Medium', 'Low']
      - name: sla_target_hours
        description: "SLA target in hours"
        tests:
          - not_null

  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with comprehensive metrics"
    columns:
      - name: meeting_id
        description: "Meeting identifier"
        tests:
          - not_null
          - unique
      - name: meeting_date
        description: "Meeting date"
        tests:
          - not_null
      - name: actual_duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
      - name: participant_count
        description: "Number of participants"
        tests:
          - not_null
      - name: meeting_quality_score
        description: "Calculated meeting quality score"

  - name: go_fact_feature_usage
    description: "Feature usage fact table with adoption and performance metrics"
    columns:
      - name: usage_date
        description: "Usage date"
        tests:
          - not_null
      - name: feature_name
        description: "Feature name"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
      - name: feature_adoption_score
        description: "Calculated feature adoption score"

  - name: go_fact_revenue_events
    description: "Revenue events fact table with financial metrics"
    columns:
      - name: billing_event_id
        description: "Billing event identifier"
        tests:
          - not_null
          - unique
      - name: transaction_date
        description: "Transaction date"
        tests:
          - not_null
      - name: gross_amount
        description: "Gross revenue amount"
        tests:
          - not_null
      - name: net_amount
        description: "Net revenue amount"
        tests:
          - not_null
      - name: currency_code
        description: "Currency code"
        tests:
          - not_null
          - accepted_values:
              values: ['USD']

  - name: go_fact_support_metrics
    description: "Support metrics fact table with resolution and SLA tracking"
    columns:
      - name: ticket_id
        description: "Ticket identifier"
        tests:
          - not_null
          - unique
      - name: ticket_created_date
        description: "Ticket creation date"
        tests:
          - not_null
      - name: resolution_time_hours
        description: "Resolution time in hours"
      - name: sla_met
        description: "SLA compliance flag"
        tests:
          - not_null
