version: 2

models:
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: date_id
        description: "Primary date key"
        tests:
          - unique
          - not_null
      - name: date_value
        description: "Actual date value"
      - name: year
        description: "Year component"
      - name: quarter
        description: "Quarter component"
      - name: month
        description: "Month component"
      - name: month_name
        description: "Month name"
      - name: day_of_month
        description: "Day of month"
      - name: day_of_week
        description: "Day of week (1-7)"
      - name: day_name
        description: "Day name"
      - name: is_weekend
        description: "Weekend flag"
      - name: is_holiday
        description: "Holiday flag"
      - name: fiscal_year
        description: "Fiscal year"
      - name: fiscal_quarter
        description: "Fiscal quarter"
      - name: week_of_year
        description: "Week of year"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_dim_user
    description: "User dimension with enhanced attributes"
    columns:
      - name: user_dim_id
        description: "Surrogate key for user dimension"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Business key - original user ID"
      - name: user_name
        description: "Standardized user name"
      - name: email_domain
        description: "Email domain for analysis"
      - name: company
        description: "Standardized company name"
      - name: plan_type
        description: "Standardized plan type"
      - name: plan_category
        description: "High-level plan category"
      - name: registration_date
        description: "User registration date"
      - name: user_status
        description: "Current user status"
      - name: geographic_region
        description: "Derived geographic region"
      - name: industry_sector
        description: "Derived industry sector"
      - name: user_role
        description: "User role"
      - name: account_type
        description: "Account type classification"
      - name: language_preference
        description: "Language preference"
      - name: effective_start_date
        description: "SCD effective start date"
      - name: effective_end_date
        description: "SCD effective end date"
      - name: is_current_record
        description: "SCD current record flag"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_dim_feature
    description: "Feature dimension with categorization"
    columns:
      - name: feature_id
        description: "Surrogate key for feature dimension"
        tests:
          - unique
          - not_null
      - name: feature_name
        description: "Standardized feature name"
      - name: feature_category
        description: "Feature category"
      - name: feature_type
        description: "Feature type classification"
      - name: feature_complexity
        description: "Feature complexity level"
      - name: is_premium_feature
        description: "Premium feature flag"
      - name: feature_release_date
        description: "Feature release date"
      - name: feature_status
        description: "Feature status"
      - name: usage_frequency_category
        description: "Usage frequency category"
      - name: feature_description
        description: "Feature description"
      - name: target_user_segment
        description: "Target user segment"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_dim_license
    description: "License dimension with pricing and entitlements"
    columns:
      - name: license_id
        description: "Surrogate key for license dimension"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Standardized license type"
      - name: license_category
        description: "License category"
      - name: license_tier
        description: "License tier"
      - name: max_participants
        description: "Maximum participants allowed"
      - name: storage_limit_gb
        description: "Storage limit in GB"
      - name: recording_limit_hours
        description: "Recording limit in hours"
      - name: admin_features_included
        description: "Admin features included flag"
      - name: api_access_included
        description: "API access included flag"
      - name: sso_support_included
        description: "SSO support included flag"
      - name: monthly_price
        description: "Monthly price"
      - name: annual_price
        description: "Annual price"
      - name: license_benefits
        description: "License benefits description"
      - name: effective_start_date
        description: "License effective start date"
      - name: effective_end_date
        description: "License effective end date"
      - name: is_current_record
        description: "SCD current record flag"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    columns:
      - name: meeting_type_id
        description: "Surrogate key for meeting type dimension"
        tests:
          - unique
          - not_null
      - name: meeting_type
        description: "Meeting type"
      - name: meeting_category
        description: "Meeting category"
      - name: duration_category
        description: "Duration category"
      - name: participant_size_category
        description: "Participant size category"
      - name: time_of_day_category
        description: "Time of day category"
      - name: day_of_week
        description: "Day of week"
      - name: is_weekend_meeting
        description: "Weekend meeting flag"
      - name: is_recurring_type
        description: "Recurring type flag"
      - name: meeting_quality_threshold
        description: "Meeting quality threshold"
      - name: typical_features_used
        description: "Typical features used"
      - name: business_purpose
        description: "Business purpose"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_dim_support_category
    description: "Support category dimension with SLA information"
    columns:
      - name: support_category_id
        description: "Surrogate key for support category dimension"
        tests:
          - unique
          - not_null
      - name: support_category
        description: "Support category"
      - name: support_subcategory
        description: "Support subcategory"
      - name: priority_level
        description: "Priority level"
      - name: expected_resolution_time_hours
        description: "Expected resolution time in hours"
      - name: requires_escalation
        description: "Requires escalation flag"
      - name: self_service_available
        description: "Self service available flag"
      - name: knowledge_base_articles
        description: "Number of knowledge base articles"
      - name: common_resolution_steps
        description: "Common resolution steps"
      - name: customer_impact_level
        description: "Customer impact level"
      - name: department_responsible
        description: "Department responsible"
      - name: sla_target_hours
        description: "SLA target hours"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_fact_feature_usage
    description: "Feature usage fact table"
    columns:
      - name: feature_usage_id
        description: "Surrogate key for feature usage fact"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
      - name: feature_id
        description: "Foreign key to feature dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension"
      - name: meeting_id
        description: "Meeting identifier"
      - name: usage_date
        description: "Usage date"
      - name: usage_timestamp
        description: "Usage timestamp"
      - name: feature_name
        description: "Feature name"
      - name: usage_count
        description: "Usage count"
      - name: usage_duration_minutes
        description: "Usage duration in minutes"
      - name: session_duration_minutes
        description: "Session duration in minutes"
      - name: feature_adoption_score
        description: "Feature adoption score"
      - name: user_experience_rating
        description: "User experience rating"
      - name: feature_performance_score
        description: "Feature performance score"
      - name: concurrent_features_count
        description: "Concurrent features count"
      - name: usage_context
        description: "Usage context"
      - name: device_type
        description: "Device type"
      - name: platform_version
        description: "Platform version"
      - name: error_count
        description: "Error count"
      - name: success_rate
        description: "Success rate"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_fact_meeting_activity
    description: "Meeting activity fact table"
    columns:
      - name: meeting_activity_id
        description: "Surrogate key for meeting activity fact"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
      - name: meeting_type_id
        description: "Foreign key to meeting type dimension"
      - name: host_user_dim_id
        description: "Foreign key to user dimension for host"
      - name: meeting_id
        description: "Meeting identifier"
      - name: meeting_date
        description: "Meeting date"
      - name: meeting_start_time
        description: "Meeting start time"
      - name: meeting_end_time
        description: "Meeting end time"
      - name: scheduled_duration_minutes
        description: "Scheduled duration in minutes"
      - name: actual_duration_minutes
        description: "Actual duration in minutes"
      - name: participant_count
        description: "Participant count"
      - name: unique_participants
        description: "Unique participants"
      - name: host_duration_minutes
        description: "Host duration in minutes"
      - name: total_participant_minutes
        description: "Total participant minutes"
      - name: average_participation_minutes
        description: "Average participation minutes"
      - name: peak_concurrent_participants
        description: "Peak concurrent participants"
      - name: late_joiners_count
        description: "Late joiners count"
      - name: early_leavers_count
        description: "Early leavers count"
      - name: features_used_count
        description: "Features used count"
      - name: screen_share_duration_minutes
        description: "Screen share duration in minutes"
      - name: recording_duration_minutes
        description: "Recording duration in minutes"
      - name: chat_messages_count
        description: "Chat messages count"
      - name: file_shares_count
        description: "File shares count"
      - name: breakout_rooms_used
        description: "Breakout rooms used"
      - name: polls_conducted
        description: "Polls conducted"
      - name: meeting_quality_score
        description: "Meeting quality score"
      - name: audio_quality_score
        description: "Audio quality score"
      - name: video_quality_score
        description: "Video quality score"
      - name: connection_issues_count
        description: "Connection issues count"
      - name: meeting_satisfaction_score
        description: "Meeting satisfaction score"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_fact_revenue_events
    description: "Revenue events fact table"
    columns:
      - name: revenue_event_id
        description: "Surrogate key for revenue event fact"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
      - name: license_id
        description: "Foreign key to license dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension"
      - name: billing_event_id
        description: "Billing event identifier"
      - name: transaction_date
        description: "Transaction date"
      - name: transaction_timestamp
        description: "Transaction timestamp"
      - name: event_type
        description: "Event type"
      - name: revenue_type
        description: "Revenue type"
      - name: gross_amount
        description: "Gross amount"
      - name: tax_amount
        description: "Tax amount"
      - name: discount_amount
        description: "Discount amount"
      - name: net_amount
        description: "Net amount"
      - name: currency_code
        description: "Currency code"
      - name: exchange_rate
        description: "Exchange rate"
      - name: usd_amount
        description: "USD amount"
      - name: payment_method
        description: "Payment method"
      - name: subscription_period_months
        description: "Subscription period in months"
      - name: license_quantity
        description: "License quantity"
      - name: proration_amount
        description: "Proration amount"
      - name: commission_amount
        description: "Commission amount"
      - name: mrr_impact
        description: "MRR impact"
      - name: arr_impact
        description: "ARR impact"
      - name: customer_lifetime_value
        description: "Customer lifetime value"
      - name: churn_risk_score
        description: "Churn risk score"
      - name: payment_status
        description: "Payment status"
      - name: refund_reason
        description: "Refund reason"
      - name: sales_channel
        description: "Sales channel"
      - name: promotion_code
        description: "Promotion code"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"

  - name: go_fact_support_metrics
    description: "Support metrics fact table"
    columns:
      - name: support_metrics_id
        description: "Surrogate key for support metrics fact"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
      - name: support_category_id
        description: "Foreign key to support category dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension"
      - name: ticket_id
        description: "Ticket identifier"
      - name: ticket_created_date
        description: "Ticket created date"
      - name: ticket_created_timestamp
        description: "Ticket created timestamp"
      - name: ticket_closed_date
        description: "Ticket closed date"
      - name: ticket_closed_timestamp
        description: "Ticket closed timestamp"
      - name: first_response_timestamp
        description: "First response timestamp"
      - name: resolution_timestamp
        description: "Resolution timestamp"
      - name: ticket_category
        description: "Ticket category"
      - name: ticket_subcategory
        description: "Ticket subcategory"
      - name: priority_level
        description: "Priority level"
      - name: severity_level
        description: "Severity level"
      - name: resolution_status
        description: "Resolution status"
      - name: first_response_time_hours
        description: "First response time in hours"
      - name: resolution_time_hours
        description: "Resolution time in hours"
      - name: active_work_time_hours
        description: "Active work time in hours"
      - name: customer_wait_time_hours
        description: "Customer wait time in hours"
      - name: escalation_count
        description: "Escalation count"
      - name: reassignment_count
        description: "Reassignment count"
      - name: reopened_count
        description: "Reopened count"
      - name: agent_interactions_count
        description: "Agent interactions count"
      - name: customer_interactions_count
        description: "Customer interactions count"
      - name: knowledge_base_articles_used
        description: "Knowledge base articles used"
      - name: customer_satisfaction_score
        description: "Customer satisfaction score"
      - name: first_contact_resolution
        description: "First contact resolution flag"
      - name: sla_met
        description: "SLA met flag"
      - name: sla_breach_hours
        description: "SLA breach hours"
      - name: resolution_method
        description: "Resolution method"
      - name: root_cause_category
        description: "Root cause category"
      - name: preventable_issue
        description: "Preventable issue flag"
      - name: follow_up_required
        description: "Follow up required flag"
      - name: cost_to_resolve
        description: "Cost to resolve"
      - name: load_date
        description: "Record load date"
      - name: update_date
        description: "Record update date"
      - name: source_system
        description: "Source system identifier"
