version: 2

models:
  - name: go_audit_log
    description: "Audit log table for tracking all Gold layer transformations"
    columns:
      - name: PROCESS_ID
        description: "Unique identifier for each process execution"
      - name: PROCESS_NAME
        description: "Name of the transformation process"
      - name: SOURCE_TABLE
        description: "Source table name for the transformation"
      - name: TARGET_TABLE
        description: "Target table name for the transformation"
      - name: PROCESS_STATUS
        description: "Status of the process (STARTED, COMPLETED, FAILED)"

  - name: go_dim_user
    description: "User dimension table containing user profile and subscription information"
    columns:
      - name: USER_DIM_ID
        description: "Surrogate key for user dimension"
      - name: USER_ID
        description: "Business key - unique identifier for each user account"
      - name: USER_NAME
        description: "Display name of the user"
      - name: EMAIL_DOMAIN
        description: "Domain extracted from user email address"
      - name: PLAN_CATEGORY
        description: "Standardized plan category (Basic, Professional, Enterprise, Other)"

  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: DATE_ID
        description: "Surrogate key for date dimension"
      - name: DATE_VALUE
        description: "Actual date value"
      - name: YEAR
        description: "Year component"
      - name: QUARTER
        description: "Quarter component (1-4)"
      - name: MONTH
        description: "Month component (1-12)"

  - name: go_dim_feature
    description: "Feature dimension containing platform features and their characteristics"
    columns:
      - name: FEATURE_ID
        description: "Surrogate key for feature dimension"
      - name: FEATURE_NAME
        description: "Name of the platform feature"
      - name: FEATURE_CATEGORY
        description: "Category of the feature (Collaboration, Recording, Communication, etc.)"
      - name: IS_PREMIUM_FEATURE
        description: "Flag indicating if feature requires premium subscription"

  - name: go_dim_license
    description: "License dimension containing license types and entitlements"
    columns:
      - name: LICENSE_ID
        description: "Surrogate key for license dimension"
      - name: LICENSE_TYPE
        description: "Type of license"
      - name: LICENSE_CATEGORY
        description: "Category of license (Basic, Professional, Business, Enterprise)"
      - name: MONTHLY_PRICE
        description: "Monthly subscription price"

  - name: go_dim_meeting_type
    description: "Meeting type dimension containing meeting types and characteristics"
    columns:
      - name: MEETING_TYPE_ID
        description: "Surrogate key for meeting type dimension"
      - name: MEETING_TYPE
        description: "Type of meeting"
      - name: MEETING_CATEGORY
        description: "Category of meeting (Instant, Scheduled, Webinar, etc.)"
      - name: IS_RECURRING_TYPE
        description: "Flag indicating if meeting type supports recurring meetings"

  - name: go_dim_support_category
    description: "Support category dimension containing support ticket categories"
    columns:
      - name: SUPPORT_CATEGORY_ID
        description: "Surrogate key for support category dimension"
      - name: SUPPORT_CATEGORY
        description: "Category of support ticket"
      - name: PRIORITY_LEVEL
        description: "Priority level (Critical, High, Medium, Low)"
      - name: EXPECTED_RESOLUTION_HOURS
        description: "Expected resolution time in hours"

  - name: go_fact_feature_usage
    description: "Fact table capturing detailed feature usage metrics and patterns"
    columns:
      - name: USAGE_DATE
        description: "Date when feature usage occurred"
      - name: FEATURE_NAME
        description: "Name of the feature used"
      - name: USAGE_COUNT
        description: "Number of times feature was used"
      - name: USAGE_INTENSITY
        description: "Intensity level of usage (High, Medium, Low)"
      - name: USER_EXPERIENCE_SCORE
        description: "Calculated user experience score (0-10)"

  - name: go_fact_meeting_activity
    description: "Fact table capturing comprehensive meeting activities and engagement metrics"
    columns:
      - name: MEETING_DATE
        description: "Date when meeting occurred"
      - name: MEETING_START_TIME
        description: "Meeting start timestamp"
      - name: ACTUAL_DURATION_MINUTES
        description: "Actual meeting duration in minutes"
      - name: PARTICIPANT_COUNT
        description: "Total number of participants"
      - name: PARTICIPANT_ENGAGEMENT_SCORE
        description: "Calculated participant engagement score (0-10)"

  - name: go_fact_revenue_events
    description: "Fact table capturing all revenue-generating events and financial transactions"
    columns:
      - name: TRANSACTION_DATE
        description: "Date when transaction occurred"
      - name: EVENT_TYPE
        description: "Type of revenue event"
      - name: REVENUE_TYPE
        description: "Classification of revenue (Recurring, Expansion, Add-on, One-time)"
      - name: GROSS_AMOUNT
        description: "Gross transaction amount"
      - name: IS_RECURRING_REVENUE
        description: "Flag indicating if this is recurring revenue"

  - name: go_fact_support_metrics
    description: "Fact table capturing support ticket activities and resolution performance"
    columns:
      - name: TICKET_OPEN_DATE
        description: "Date when ticket was opened"
      - name: TICKET_TYPE
        description: "Type of support ticket"
      - name: RESOLUTION_STATUS
        description: "Current resolution status"
      - name: PRIORITY_LEVEL
        description: "Priority level (P1, P2, P3, P4)"
      - name: SLA_MET_FLAG
        description: "Flag indicating if SLA was met"
