version: 2

models:
  - name: go_audit_log
    description: "Audit log table for tracking all Gold layer transformations"
    
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    
  - name: go_dim_user
    description: "User profile and subscription information with SCD Type 2"
    
  - name: go_dim_feature
    description: "Platform features and their characteristics"
    
  - name: go_dim_license
    description: "License types and entitlements"
    
  - name: go_dim_meeting_type
    description: "Meeting types and characteristics"
    
  - name: go_dim_support_category
    description: "Support ticket categories and characteristics"
    
  - name: go_fact_feature_usage
    description: "Detailed feature usage metrics and patterns"
    
  - name: go_fact_meeting_activity
    description: "Comprehensive meeting activities and engagement metrics"
    
  - name: go_fact_revenue_events
    description: "Revenue-generating events and financial transactions"
    
  - name: go_fact_support_metrics
    description: "Support ticket activities and resolution performance metrics"
