version: 2

models:
  - name: go_audit_log
    description: "Audit log table for tracking all Gold layer pipeline executions"
    
  - name: go_dim_date
    description: "Date dimension table for time-based analysis"
    
  - name: go_dim_user
    description: "User dimension with enhanced attributes"
    
  - name: go_dim_feature
    description: "Feature dimension with categorization"
    
  - name: go_dim_license
    description: "License dimension with pricing information"
    
  - name: go_dim_meeting_type
    description: "Meeting type dimension"
    
  - name: go_dim_support_category
    description: "Support category dimension"
    
  - name: go_fact_feature_usage
    description: "Feature usage fact table"
    
  - name: go_fact_meeting_activity
    description: "Meeting activity fact table"
    
  - name: go_fact_revenue_events
    description: "Revenue events fact table"
    
  - name: go_fact_support_metrics
    description: "Support metrics fact table"
