version: 2

models:
  - name: go_process_audit
    description: "Process audit table for Gold layer pipeline execution"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
      - name: pipeline_name
        description: "Name of the executed pipeline"
      - name: execution_status
        description: "Status of pipeline execution"
              
  - name: go_dim_date
    description: "Date dimension table for time-based analysis"
    columns:
      - name: dim_date_id
        description: "Unique identifier for date dimension record"
      - name: date_key
        description: "Primary date key"
      - name: year
        description: "Year component"
              
  - name: go_dim_user
    description: "User dimension with SCD Type 2 implementation"
    columns:
      - name: dim_user_id
        description: "Unique surrogate key for user dimension"
      - name: user_business_key
        description: "Business key for the user"
      - name: is_current
        description: "Flag indicating current version"
              
  - name: go_dim_meeting_type
    description: "Meeting type classification dimension"
    columns:
      - name: dim_meeting_type_id
        description: "Unique identifier for meeting type dimension"
      - name: meeting_type_key
        description: "Meeting type identifier"
              
  - name: go_dim_feature
    description: "Platform feature dimension for usage analysis"
    columns:
      - name: dim_feature_id
        description: "Unique identifier for feature dimension"
      - name: feature_key
        description: "Feature identifier key"
      - name: is_active
        description: "Whether feature is currently active"
              
  - name: go_dim_support_category
    description: "Support ticket categorization dimension"
    columns:
      - name: dim_support_category_id
        description: "Unique identifier for support category dimension"
      - name: category_key
        description: "Support category identifier"
      - name: sla_hours
        description: "Service level agreement in hours"
              
  - name: go_dim_license
    description: "License type and pricing dimension with SCD Type 2"
    columns:
      - name: dim_license_id
        description: "Unique identifier for license dimension"
      - name: license_type_key
        description: "License type identifier"
      - name: is_current
        description: "Whether this is current pricing"
              
  - name: go_fact_meeting_activity
    description: "Meeting activities and usage metrics fact table"
    columns:
      - name: fact_meeting_activity_id
        description: "Unique identifier for meeting activity fact"
      - name: date_key
        description: "Foreign key to date dimension"
      - name: user_key
        description: "Foreign key to user dimension"
      - name: meeting_duration_minutes
        description: "Meeting duration in minutes"
              
  - name: go_fact_support_metrics
    description: "Support ticket metrics and resolution tracking fact table"
    columns:
      - name: fact_support_metrics_id
        description: "Unique identifier for support metrics fact"
      - name: date_key
        description: "Foreign key to date dimension"
      - name: resolution_time_hours
        description: "Time to resolve ticket in hours"
              
  - name: go_fact_revenue_events
    description: "Billing events and revenue metrics fact table"
    columns:
      - name: fact_revenue_events_id
        description: "Unique identifier for revenue events fact"
      - name: date_key
        description: "Foreign key to date dimension"
      - name: transaction_amount_usd
        description: "Transaction amount in USD"
              
  - name: go_fact_feature_usage
    description: "Feature usage analytics fact table"
    columns:
      - name: fact_feature_usage_id
        description: "Unique identifier for feature usage fact"
      - name: date_key
        description: "Foreign key to date dimension"
      - name: usage_count
        description: "Number of times feature was used"
