version: 2

models:
  - name: go_audit_log
    description: "Audit log table for tracking all Gold layer pipeline executions"
    columns:
      - name: process_name
        description: "Name of the DBT model or process being executed"
        tests:
          - not_null
      - name: source_table
        description: "Source table name for the transformation"
      - name: target_table
        description: "Target table name for the transformation"
      - name: process_status
        description: "Status of the process execution (STARTED, COMPLETED, FAILED)"
      - name: start_time
        description: "Process start timestamp"
      - name: end_time
        description: "Process end timestamp"
      - name: load_date
        description: "Date when the audit record was created"
      - name: source_system
        description: "System that created the audit record"

  - name: go_dim_date
    description: "Date dimension table for time-based analysis"
    columns:
      - name: date_id
        description: "Unique identifier for each date"
        tests:
          - unique
          - not_null
      - name: date_value
        description: "The actual date value"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year component of the date"
      - name: quarter
        description: "Quarter component of the date (1-4)"
      - name: month
        description: "Month component of the date (1-12)"
      - name: is_weekend
        description: "Boolean flag indicating if the date is a weekend"
      - name: fiscal_year
        description: "Fiscal year (starting April 1st)"

  - name: go_dim_user
    description: "User dimension with SCD Type 2 implementation"
    columns:
      - name: user_dim_id
        description: "Surrogate key for the user dimension"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Business key for the user"
        tests:
          - not_null
      - name: user_name
        description: "Standardized user name in proper case"
      - name: email_domain
        description: "Email domain extracted from user email"
      - name: plan_type
        description: "Standardized plan type (Basic, Pro, Enterprise)"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Unknown']
      - name: is_current_record
        description: "SCD Type 2 flag indicating current record"

  - name: go_dim_feature
    description: "Feature dimension with categorization and characteristics"
    columns:
      - name: feature_id
        description: "Unique identifier for each feature"
        tests:
          - unique
          - not_null
      - name: feature_name
        description: "Standardized feature name"
        tests:
          - not_null
      - name: feature_category
        description: "Feature category classification"
      - name: is_premium_feature
        description: "Boolean flag indicating if feature requires premium license"

  - name: go_dim_license
    description: "License dimension with SCD Type 2 and pricing information"
    columns:
      - name: license_id
        description: "Unique identifier for each license type"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Standardized license type name"
        tests:
          - not_null
      - name: monthly_price
        description: "Monthly price for the license"
        tests:
          - not_null
      - name: is_current_record
        description: "SCD Type 2 flag indicating current record"

  - name: go_dim_meeting_type
    description: "Meeting type dimension with duration and time categorization"
    columns:
      - name: meeting_type_id
        description: "Unique identifier for each meeting type"
        tests:
          - unique
          - not_null
      - name: meeting_category
        description: "Meeting category based on duration"
      - name: time_of_day_category
        description: "Time of day categorization"

  - name: go_dim_support_category
    description: "Support category dimension with SLA and resolution characteristics"
    columns:
      - name: support_category_id
        description: "Unique identifier for each support category"
        tests:
          - unique
          - not_null
      - name: support_category
        description: "Standardized support category name"
        tests:
          - not_null
      - name: sla_target_hours
        description: "SLA target resolution time in hours"

  - name: go_fact_feature_usage
    description: "Feature usage fact table with adoption and performance metrics"
    columns:
      - name: feature_usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_id
      - name: feature_id
        description: "Foreign key to feature dimension"
        tests:
          - relationships:
              to: ref('go_dim_feature')
              field: feature_id
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
      - name: feature_adoption_score
        description: "Calculated feature adoption score (1-5)"

  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with comprehensive meeting metrics"
    columns:
      - name: meeting_activity_id
        description: "Unique identifier for each meeting activity record"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_id
      - name: host_user_dim_id
        description: "Foreign key to user dimension for meeting host"
        tests:
          - relationships:
              to: ref('go_dim_user')
              field: user_dim_id
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
      - name: meeting_quality_score
        description: "Calculated meeting quality score (1-5)"

  - name: go_fact_revenue_events
    description: "Revenue events fact table with financial metrics and analytics"
    columns:
      - name: revenue_event_id
        description: "Unique identifier for each revenue event"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_id
      - name: user_dim_id
        description: "Foreign key to user dimension"
        tests:
          - relationships:
              to: ref('go_dim_user')
              field: user_dim_id
      - name: gross_amount
        description: "Gross revenue amount"
        tests:
          - not_null
      - name: mrr_impact
        description: "Monthly recurring revenue impact"
      - name: arr_impact
        description: "Annual recurring revenue impact"

  - name: go_fact_support_metrics
    description: "Support metrics fact table with SLA tracking and resolution analytics"
    columns:
      - name: support_metrics_id
        description: "Unique identifier for each support metrics record"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_id
      - name: support_category_id
        description: "Foreign key to support category dimension"
        tests:
          - relationships:
              to: ref('go_dim_support_category')
              field: support_category_id
      - name: user_dim_id
        description: "Foreign key to user dimension"
        tests:
          - relationships:
              to: ref('go_dim_user')
              field: user_dim_id
      - name: sla_met
        description: "Boolean flag indicating if SLA was met"
      - name: customer_satisfaction_score
        description: "Customer satisfaction score (1-5)"
