version: 2

models:
  - name: go_audit_log
    description: "Audit log for Gold layer process tracking and monitoring"
    
  - name: go_dim_date
    description: "Date dimension for time-based analysis"
    
  - name: go_dim_user
    description: "User dimension with profile and subscription information"
    
  - name: go_dim_feature
    description: "Feature dimension with categorization and characteristics"
    
  - name: go_dim_license
    description: "License dimension with pricing and entitlements"
    
  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    
  - name: go_dim_support_category
    description: "Support category dimension with SLA information"
    
  - name: go_fact_meeting_activity
    description: "Meeting activity fact with comprehensive metrics"
    
  - name: go_fact_feature_usage
    description: "Feature usage fact with adoption metrics"
    
  - name: go_fact_revenue_events
    description: "Revenue events fact with financial metrics"
    
  - name: go_fact_support_metrics
    description: "Support metrics fact with SLA tracking"
