version: 2

models:
  - name: go_process_audit
    description: "Process audit log for Gold layer pipeline executions"
    
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    
  - name: go_dim_user
    description: "User dimension with profile and subscription information"
    
  - name: go_dim_feature
    description: "Feature dimension with platform features and characteristics"
    
  - name: go_dim_license
    description: "License dimension with types and entitlements"
    
  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    
  - name: go_dim_support_category
    description: "Support category dimension with characteristics"
    
  - name: go_fact_meeting_activity
    description: "Central fact table for meeting activities and engagement metrics"
    
  - name: go_fact_feature_usage
    description: "Fact table for feature usage metrics and patterns"
    
  - name: go_fact_revenue_events
    description: "Fact table for billing events and revenue metrics"
    
  - name: go_fact_support_metrics
    description: "Fact table for support ticket metrics and resolution performance"
