version: 2

models:
  - name: go_audit_log
    description: "Gold layer process audit log for tracking pipeline execution"
    columns:
      - name: audit_id
        description: "Unique identifier for each audit record"
      - name: process_name
        description: "Name of the process being audited"
      - name: source_table
        description: "Source table name"
      - name: target_table
        description: "Target table name"
      - name: process_start_time
        description: "Process start timestamp"
      - name: process_end_time
        description: "Process end timestamp"
      - name: process_status
        description: "Status of the process"

  - name: go_dim_date
    description: "Gold layer date dimension for time-based analysis"
    columns:
      - name: date_id
        description: "Unique identifier for each date"
      - name: date_value
        description: "The actual date value"
      - name: year
        description: "Year component"
      - name: quarter
        description: "Quarter component"
      - name: month
        description: "Month component"
      - name: day_of_month
        description: "Day of month component"

  - name: go_dim_user
    description: "Gold layer user dimension with enriched user attributes"
    columns:
      - name: user_dim_id
        description: "Surrogate key for user dimension"
      - name: user_name
        description: "Cleaned and standardized user name"
      - name: email_domain
        description: "Extracted email domain"
      - name: company
        description: "Cleaned company name"
      - name: plan_type
        description: "Standardized plan type"
      - name: plan_category
        description: "Derived plan category"

  - name: go_dim_feature
    description: "Gold layer feature dimension with feature characteristics"
    columns:
      - name: feature_id
        description: "Unique identifier for each feature"
      - name: feature_name
        description: "Name of the feature"
      - name: feature_category
        description: "Category classification of the feature"
      - name: feature_type
        description: "Type classification (Core/Advanced)"
      - name: feature_complexity
        description: "Complexity level of the feature"

  - name: go_dim_license
    description: "Gold layer license dimension with entitlements and pricing"
    columns:
      - name: license_id
        description: "Unique identifier for each license type"
      - name: license_type
        description: "Type of license"
      - name: license_category
        description: "Category of license"
      - name: license_tier
        description: "Tier classification"
      - name: max_participants
        description: "Maximum participants allowed"

  - name: go_dim_meeting_type
    description: "Gold layer meeting type dimension"
    columns:
      - name: meeting_type_id
        description: "Unique identifier for meeting type"
      - name: meeting_type
        description: "Type of meeting"
      - name: meeting_category
        description: "Category of meeting"
      - name: duration_category
        description: "Duration classification"

  - name: go_dim_support_category
    description: "Gold layer support category dimension"
    columns:
      - name: support_category_id
        description: "Unique identifier for support category"
      - name: support_category
        description: "Category of support ticket"
      - name: priority_level
        description: "Priority level classification"
      - name: expected_resolution_hours
        description: "Expected resolution time in hours"

  - name: go_fact_feature_usage
    description: "Gold layer fact table for feature usage metrics"
    columns:
      - name: feature_usage_id
        description: "Unique identifier for each usage record"
      - name: usage_date
        description: "Date of feature usage"
      - name: feature_name
        description: "Name of the feature used"
      - name: usage_count
        description: "Number of times feature was used"
      - name: usage_intensity
        description: "Intensity classification of usage"
      - name: user_experience_score
        description: "Calculated user experience score"

  - name: go_fact_meeting_activity
    description: "Gold layer fact table for meeting activities and engagement"
    columns:
      - name: meeting_activity_id
        description: "Unique identifier for each meeting activity record"
      - name: meeting_date
        description: "Date of the meeting"
      - name: participant_count
        description: "Number of participants"
      - name: actual_duration_minutes
        description: "Actual meeting duration in minutes"
      - name: participant_engagement_score
        description: "Calculated engagement score"
      - name: meeting_quality_score
        description: "Overall meeting quality score"

  - name: go_fact_revenue_events
    description: "Gold layer fact table for revenue events and financial transactions"
    columns:
      - name: revenue_event_id
        description: "Unique identifier for each revenue event"
      - name: transaction_date
        description: "Date of the transaction"
      - name: revenue_type
        description: "Type of revenue (Recurring, One-time, etc.)"
      - name: gross_amount
        description: "Gross transaction amount"
      - name: net_amount
        description: "Net amount after taxes and discounts"
      - name: mrr_impact
        description: "Monthly recurring revenue impact"
      - name: arr_impact
        description: "Annual recurring revenue impact"

  - name: go_fact_support_metrics
    description: "Gold layer fact table for support metrics and performance"
    columns:
      - name: support_metrics_id
        description: "Unique identifier for each support metrics record"
      - name: ticket_open_date
        description: "Date when ticket was opened"
      - name: ticket_type
        description: "Type of support ticket"
      - name: resolution_status
        description: "Current resolution status"
      - name: resolution_time_hours
        description: "Time taken to resolve in hours"
      - name: customer_satisfaction_score
        description: "Customer satisfaction score"
      - name: sla_met_flag
        description: "Flag indicating if SLA was met"
