version: 2

models:
  - name: go_audit_log
    description: "Gold layer process audit log for tracking ETL execution"
    columns:
      - name: audit_log_id
        description: "Unique identifier for each audit log entry"
        tests:
          - not_null
          - unique
      - name: process_name
        description: "Name of the process being audited"
        tests:
          - not_null
      - name: execution_status
        description: "Status of process execution"
        tests:
          - accepted_values:
              values: ['RUNNING', 'SUCCESS', 'FAILED', 'COMPLETED_WITH_ERRORS']
              
  - name: go_dim_user
    description: "User dimension table with enhanced attributes for analytics"
    columns:
      - name: user_key
        description: "Surrogate key for user dimension"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Business key - unique identifier for each user"
        tests:
          - not_null
      - name: user_name
        description: "Display name of the user (cleaned and standardized)"
      - name: email_domain
        description: "Email domain extracted from user email"
      - name: plan_type
        description: "Standardized subscription plan type"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Unknown']
      - name: is_current_record
        description: "Flag indicating if this is the current active record"
        tests:
          - not_null
          
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: date_key
        description: "Primary key - date value"
        tests:
          - not_null
          - unique
      - name: year
        description: "Calendar year"
        tests:
          - not_null
      - name: quarter
        description: "Calendar quarter (1-4)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
      - name: month
        description: "Calendar month (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
              
  - name: go_dim_feature
    description: "Feature dimension containing platform features and characteristics"
    columns:
      - name: feature_key
        description: "Surrogate key for feature dimension"
        tests:
          - not_null
          - unique
      - name: feature_name
        description: "Name of the platform feature"
        tests:
          - not_null
      - name: feature_category
        description: "Category classification of the feature"
        tests:
          - accepted_values:
              values: ['Collaboration', 'Recording', 'Communication', 'Advanced Meeting', 'Engagement', 'General']
              
  - name: go_dim_license
    description: "License dimension containing license types and entitlements"
    columns:
      - name: license_key
        description: "Surrogate key for license dimension"
        tests:
          - not_null
          - unique
      - name: license_type
        description: "Type of license"
        tests:
          - not_null
      - name: license_category
        description: "High-level license category"
        tests:
          - accepted_values:
              values: ['Standard', 'Professional', 'Enterprise', 'Other']
              
  - name: go_dim_meeting
    description: "Meeting dimension containing meeting characteristics and metadata"
    columns:
      - name: meeting_key
        description: "Surrogate key for meeting dimension"
        tests:
          - not_null
          - unique
      - name: duration_category
        description: "Categorization based on meeting duration"
        tests:
          - accepted_values:
              values: ['Brief', 'Standard', 'Extended', 'Long']
              
  - name: go_dim_support_category
    description: "Support category dimension for ticket categorization"
    columns:
      - name: support_category_key
        description: "Surrogate key for support category dimension"
        tests:
          - not_null
          - unique
      - name: support_category
        description: "Support ticket category"
        tests:
          - not_null
      - name: priority_level
        description: "Priority level for support tickets"
        tests:
          - accepted_values:
              values: ['Critical', 'High', 'Medium', 'Low']
              
  - name: go_fact_meeting_activity
    description: "Central fact table capturing meeting activities and usage metrics"
    columns:
      - name: user_key
        description: "Foreign key to user dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_user')
              field: user_key
      - name: date_key
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_key
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440
              
  - name: go_fact_support_activity
    description: "Fact table capturing support ticket activities and resolution metrics"
    columns:
      - name: user_key
        description: "Foreign key to user dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_user')
              field: user_key
      - name: date_key
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_key
      - name: support_category_key
        description: "Foreign key to support category dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_support_category')
              field: support_category_key
              
  - name: go_fact_revenue_activity
    description: "Fact table capturing billing events and revenue metrics"
    columns:
      - name: user_key
        description: "Foreign key to user dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_user')
              field: user_key
      - name: license_key
        description: "Foreign key to license dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_license')
              field: license_key
      - name: date_key
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_key
      - name: amount
        description: "Transaction amount"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              
  - name: go_fact_feature_usage
    description: "Fact table capturing detailed feature usage metrics and patterns"
    columns:
      - name: date_key
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_date')
              field: date_key
      - name: feature_key
        description: "Foreign key to feature dimension"
        tests:
          - not_null
          - relationships:
              to: ref('go_dim_feature')
              field: feature_key
      - name: user_key
        description: "Foreign key to user dimension"
        tests:
          - relationships:
              to: ref('go_dim_user')
              field: user_key
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
