version: 2

models:
  - name: go_audit_log
    description: "Gold layer process audit log for tracking ETL execution"
    
  - name: go_dim_user
    description: "User dimension table with enhanced attributes for analytics"
    
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    
  - name: go_dim_feature
    description: "Feature dimension containing platform features and characteristics"
    
  - name: go_dim_license
    description: "License dimension containing license types and entitlements"
    
  - name: go_dim_meeting
    description: "Meeting dimension containing meeting characteristics and metadata"
    
  - name: go_dim_support_category
    description: "Support category dimension for ticket categorization"
    
  - name: go_fact_meeting_activity
    description: "Central fact table capturing meeting activities and usage metrics"
    
  - name: go_fact_support_activity
    description: "Fact table capturing support ticket activities and resolution metrics"
    
  - name: go_fact_revenue_activity
    description: "Fact table capturing billing events and revenue metrics"
    
  - name: go_fact_feature_usage
    description: "Fact table capturing detailed feature usage metrics and patterns"
