version: 2

models:
  - name: go_process_audit
    description: "Process audit log for Gold layer pipeline executions"
    columns:
      - name: audit_log_id
        description: "Unique identifier for each audit log entry"
      - name: process_name
        description: "Name of the process being audited"
      - name: process_type
        description: "Type of process (DBT_MODEL, STORED_PROC, etc.)"
      - name: execution_start_timestamp
        description: "Timestamp when process execution started"
      - name: execution_end_timestamp
        description: "Timestamp when process execution ended"
      - name: execution_status
        description: "Status of process execution (RUNNING, SUCCESS, FAILED)"
      - name: source_table_name
        description: "Name of source table being processed"
      - name: target_table_name
        description: "Name of target table being created/updated"
      - name: records_processed
        description: "Number of records processed"
      - name: load_date
        description: "Date when audit record was created"
      - name: source_system
        description: "System that created the audit record"
        
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: date_id
        description: "Unique identifier for each date"
      - name: date_value
        description: "The actual date value"
      - name: year
        description: "Year component of the date"
      - name: quarter
        description: "Quarter component of the date"
      - name: month
        description: "Month component of the date"
      - name: month_name
        description: "Name of the month"
      - name: day_of_month
        description: "Day of the month"
      - name: day_of_week
        description: "Day of the week (1-7)"
      - name: day_name
        description: "Name of the day"
      - name: is_weekend
        description: "Flag indicating if date is a weekend"
      - name: is_holiday
        description: "Flag indicating if date is a holiday"
      - name: fiscal_year
        description: "Fiscal year (starting April 1st)"
      - name: fiscal_quarter
        description: "Fiscal quarter"
      - name: week_of_year
        description: "Week number of the year"
        
  - name: go_dim_user
    description: "User dimension with profile and subscription information"
    columns:
      - name: user_dim_id
        description: "Unique dimensional identifier for each user"
      - name: user_id
        description: "Business key - original user identifier"
      - name: user_name
        description: "Display name of the user"
      - name: email_domain
        description: "Domain extracted from user email"
      - name: company
        description: "Company or organization name"
      - name: plan_type
        description: "Standardized subscription plan type"
      - name: plan_category
        description: "High-level plan categorization (Free/Paid)"
      - name: registration_date
        description: "Date when user registered"
      - name: user_status
        description: "Current status of the user account"
      - name: geographic_region
        description: "Geographic region derived from email domain"
      - name: industry_sector
        description: "Industry sector classification"
      - name: user_role
        description: "Role of the user in the system"
      - name: account_type
        description: "Type of account (Individual/Business)"
      - name: language_preference
        description: "Preferred language setting"
      - name: effective_start_date
        description: "Start date for SCD Type 2 tracking"
      - name: effective_end_date
        description: "End date for SCD Type 2 tracking"
      - name: is_current_record
        description: "Flag indicating current active record"
        
  - name: go_dim_feature
    description: "Feature dimension with platform features and characteristics"
    columns:
      - name: feature_id
        description: "Unique identifier for each feature"
      - name: feature_name
        description: "Name of the platform feature"
      - name: feature_category
        description: "Category classification of the feature"
      - name: feature_type
        description: "Type of feature (Core/Standard/Advanced)"
      - name: feature_complexity
        description: "Complexity level of the feature"
      - name: is_premium_feature
        description: "Flag indicating if feature requires premium license"
      - name: feature_release_date
        description: "Date when feature was released"
      - name: feature_status
        description: "Current status of the feature"
      - name: usage_frequency_category
        description: "Expected usage frequency category"
      - name: feature_description
        description: "Description of the feature"
      - name: target_user_segment
        description: "Target user segment for the feature"
        
  - name: go_dim_license
    description: "License dimension with types and entitlements"
    columns:
      - name: license_id
        description: "Unique identifier for each license type"
      - name: license_type
        description: "Type of license"
      - name: license_category
        description: "Category of license (Standard/Professional/Enterprise)"
      - name: license_tier
        description: "Tier level of the license"
      - name: max_participants
        description: "Maximum number of participants allowed"
      - name: storage_limit_gb
        description: "Storage limit in gigabytes"
      - name: recording_limit_hours
        description: "Recording limit in hours"
      - name: admin_features_included
        description: "Flag indicating if admin features are included"
      - name: api_access_included
        description: "Flag indicating if API access is included"
      - name: sso_support_included
        description: "Flag indicating if SSO support is included"
      - name: monthly_price
        description: "Monthly price for the license"
      - name: annual_price
        description: "Annual price for the license"
      - name: license_benefits
        description: "Description of license benefits"
      - name: effective_start_date
        description: "Start date for license validity"
      - name: effective_end_date
        description: "End date for license validity"
      - name: is_current_record
        description: "Flag indicating current active record"
        
  - name: go_dim_meeting_type
    description: "Meeting type dimension with characteristics"
    columns:
      - name: meeting_type_id
        description: "Unique identifier for each meeting type"
      - name: meeting_type
        description: "Type of meeting"
      - name: meeting_category
        description: "Category based on duration and characteristics"
      - name: duration_category
        description: "Duration-based categorization"
      - name: participant_size_category
        description: "Category based on typical participant count"
      - name: time_of_day_category
        description: "Time of day when meeting typically occurs"
      - name: day_of_week
        description: "Day of week for the meeting"
      - name: is_weekend_meeting
        description: "Flag indicating if meeting is on weekend"
      - name: is_recurring_type
        description: "Flag indicating if meeting type is recurring"
      - name: meeting_quality_threshold
        description: "Quality threshold for this meeting type"
      - name: typical_features_used
        description: "Features typically used in this meeting type"
      - name: business_purpose
        description: "Business purpose of the meeting type"
        
  - name: go_dim_support_category
    description: "Support category dimension with characteristics"
    columns:
      - name: support_category_id
        description: "Unique identifier for each support category"
      - name: support_category
        description: "Main support category"
      - name: support_subcategory
        description: "Subcategory of support ticket"
      - name: priority_level
        description: "Priority level for this category"
      - name: expected_resolution_time_hours
        description: "Expected time to resolve tickets in this category"
      - name: requires_escalation
        description: "Flag indicating if category typically requires escalation"
      - name: self_service_available
        description: "Flag indicating if self-service options are available"
      - name: knowledge_base_articles
        description: "Number of knowledge base articles for this category"
      - name: common_resolution_steps
        description: "Common steps to resolve tickets in this category"
      - name: customer_impact_level
        description: "Typical customer impact level"
      - name: department_responsible
        description: "Department responsible for handling this category"
      - name: sla_target_hours
        description: "SLA target resolution time in hours"
        
  - name: go_fact_meeting_activity
    description: "Central fact table for meeting activities and engagement metrics"
    columns:
      - name: meeting_activity_id
        description: "Unique identifier for each meeting activity record"
      - name: date_id
        description: "Foreign key to date dimension"
      - name: meeting_type_id
        description: "Foreign key to meeting type dimension"
      - name: host_user_dim_id
        description: "Foreign key to user dimension for meeting host"
      - name: meeting_id
        description: "Business key - original meeting identifier"
      - name: meeting_date
        description: "Date when meeting occurred"
      - name: meeting_start_time
        description: "Start time of the meeting"
      - name: meeting_end_time
        description: "End time of the meeting"
      - name: scheduled_duration_minutes
        description: "Scheduled duration in minutes"
      - name: actual_duration_minutes
        description: "Actual duration in minutes"
      - name: participant_count
        description: "Number of participants in the meeting"
      - name: unique_participants
        description: "Number of unique participants"
      - name: host_duration_minutes
        description: "Duration host was in the meeting"
      - name: total_participant_minutes
        description: "Total minutes across all participants"
      - name: average_participation_minutes
        description: "Average participation time per participant"
      - name: peak_concurrent_participants
        description: "Maximum concurrent participants"
      - name: late_joiners_count
        description: "Number of participants who joined late"
      - name: early_leavers_count
        description: "Number of participants who left early"
      - name: features_used_count
        description: "Number of different features used"
      - name: screen_share_duration_minutes
        description: "Duration of screen sharing"
      - name: recording_duration_minutes
        description: "Duration of recording"
      - name: chat_messages_count
        description: "Number of chat messages"
      - name: file_shares_count
        description: "Number of files shared"
      - name: breakout_rooms_used
        description: "Number of breakout rooms used"
      - name: polls_conducted
        description: "Number of polls conducted"
      - name: meeting_quality_score
        description: "Overall meeting quality score"
      - name: audio_quality_score
        description: "Audio quality score"
      - name: video_quality_score
        description: "Video quality score"
      - name: connection_issues_count
        description: "Number of connection issues"
      - name: meeting_satisfaction_score
        description: "Meeting satisfaction score"
        
  - name: go_fact_feature_usage
    description: "Fact table for feature usage metrics and patterns"
    columns:
      - name: feature_usage_id
        description: "Unique identifier for each feature usage record"
      - name: date_id
        description: "Foreign key to date dimension"
      - name: feature_id
        description: "Foreign key to feature dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension"
      - name: meeting_id
        description: "Meeting where feature was used"
      - name: usage_date
        description: "Date when feature was used"
      - name: usage_timestamp
        description: "Timestamp when feature was used"
      - name: feature_name
        description: "Name of the feature used"
      - name: usage_count
        description: "Number of times feature was used"
      - name: usage_duration_minutes
        description: "Duration of feature usage"
      - name: session_duration_minutes
        description: "Total session duration"
      - name: feature_adoption_score
        description: "Score indicating feature adoption level"
      - name: user_experience_rating
        description: "User experience rating for feature usage"
      - name: feature_performance_score
        description: "Performance score of the feature"
      - name: concurrent_features_count
        description: "Number of features used concurrently"
      - name: usage_context
        description: "Context of feature usage"
      - name: device_type
        description: "Type of device used"
      - name: platform_version
        description: "Version of platform used"
      - name: error_count
        description: "Number of errors encountered"
      - name: success_rate
        description: "Success rate of feature usage"
        
  - name: go_fact_revenue_events
    description: "Fact table for billing events and revenue metrics"
    columns:
      - name: revenue_event_id
        description: "Unique identifier for each revenue event"
      - name: date_id
        description: "Foreign key to date dimension"
      - name: license_id
        description: "Foreign key to license dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension"
      - name: billing_event_id
        description: "Business key - original billing event identifier"
      - name: transaction_date
        description: "Date of the transaction"
      - name: transaction_timestamp
        description: "Timestamp of the transaction"
      - name: event_type
        description: "Type of billing event"
      - name: revenue_type
        description: "Type of revenue (Recurring/One-time/Refund)"
      - name: gross_amount
        description: "Gross amount of the transaction"
      - name: tax_amount
        description: "Tax amount"
      - name: discount_amount
        description: "Discount amount applied"
      - name: net_amount
        description: "Net amount after taxes and discounts"
      - name: currency_code
        description: "Currency code for the transaction"
      - name: exchange_rate
        description: "Exchange rate used"
      - name: usd_amount
        description: "Amount in USD"
      - name: payment_method
        description: "Method of payment"
      - name: subscription_period_months
        description: "Subscription period in months"
      - name: license_quantity
        description: "Number of licenses"
      - name: proration_amount
        description: "Prorated amount"
      - name: commission_amount
        description: "Commission amount"
      - name: mrr_impact
        description: "Monthly Recurring Revenue impact"
      - name: arr_impact
        description: "Annual Recurring Revenue impact"
      - name: customer_lifetime_value
        description: "Customer lifetime value"
      - name: churn_risk_score
        description: "Risk score for customer churn"
      - name: payment_status
        description: "Status of the payment"
      - name: refund_reason
        description: "Reason for refund if applicable"
      - name: sales_channel
        description: "Channel through which sale was made"
      - name: promotion_code
        description: "Promotion code used if any"
        
  - name: go_fact_support_metrics
    description: "Fact table for support ticket metrics and resolution performance"
    columns:
      - name: support_metrics_id
        description: "Unique identifier for each support metrics record"
      - name: date_id
        description: "Foreign key to date dimension"
      - name: support_category_id
        description: "Foreign key to support category dimension"
      - name: user_dim_id
        description: "Foreign key to user dimension"
      - name: ticket_id
        description: "Business key - original ticket identifier"
      - name: ticket_created_date
        description: "Date when ticket was created"
      - name: ticket_created_timestamp
        description: "Timestamp when ticket was created"
      - name: ticket_closed_date
        description: "Date when ticket was closed"
      - name: ticket_closed_timestamp
        description: "Timestamp when ticket was closed"
      - name: first_response_timestamp
        description: "Timestamp of first response"
      - name: resolution_timestamp
        description: "Timestamp when ticket was resolved"
      - name: ticket_category
        description: "Category of the support ticket"
      - name: ticket_subcategory
        description: "Subcategory of the support ticket"
      - name: priority_level
        description: "Priority level of the ticket"
      - name: severity_level
        description: "Severity level of the ticket"
      - name: resolution_status
        description: "Current resolution status"
      - name: first_response_time_hours
        description: "Time to first response in hours"
      - name: resolution_time_hours
        description: "Total resolution time in hours"
      - name: active_work_time_hours
        description: "Active work time in hours"
      - name: customer_wait_time_hours
        description: "Customer wait time in hours"
      - name: escalation_count
        description: "Number of escalations"
      - name: reassignment_count
        description: "Number of reassignments"
      - name: reopened_count
        description: "Number of times ticket was reopened"
      - name: agent_interactions_count
        description: "Number of agent interactions"
      - name: customer_interactions_count
        description: "Number of customer interactions"
      - name: knowledge_base_articles_used
        description: "Number of knowledge base articles referenced"
      - name: customer_satisfaction_score
        description: "Customer satisfaction score"
      - name: first_contact_resolution
        description: "Flag indicating if resolved on first contact"
      - name: sla_met
        description: "Flag indicating if SLA was met"
      - name: sla_breach_hours
        description: "Hours by which SLA was breached"
      - name: resolution_method
        description: "Method used to resolve the ticket"
      - name: root_cause_category
        description: "Root cause category"
      - name: preventable_issue
        description: "Flag indicating if issue was preventable"
      - name: follow_up_required
        description: "Flag indicating if follow-up is required"
      - name: cost_to_resolve
        description: "Cost to resolve the ticket"
