version: 2

models:
  - name: go_audit_log
    description: "Comprehensive audit log for pipeline execution tracking"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
        tests:
          - not_null
      - name: pipeline_name
        description: "Name of the executed pipeline/model"
      - name: execution_status
        description: "Status of pipeline execution (STARTED, COMPLETED, FAILED)"
        tests:
          - accepted_values:
              values: ['STARTED', 'COMPLETED', 'FAILED', 'RUNNING']

  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: date_id
        description: "Unique identifier for each date"
        tests:
          - not_null
          - unique
      - name: date_value
        description: "The actual date value"
        tests:
          - not_null
          - unique
      - name: is_weekend
        description: "Boolean flag indicating if date is weekend"
        tests:
          - accepted_values:
              values: [true, false]
      - name: fiscal_year
        description: "Fiscal year (July 1 - June 30)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 2020
              max_value: 2031

  - name: go_dim_feature
    description: "Feature dimension with categorization and characteristics"
    columns:
      - name: feature_id
        description: "Unique identifier for each feature"
        tests:
          - not_null
          - unique
      - name: feature_name
        description: "Name of the platform feature"
        tests:
          - not_null
      - name: feature_category
        description: "Category classification of the feature"
        tests:
          - accepted_values:
              values: ['Collaboration', 'Recording', 'Communication', 'Meeting Management', 'Video', 'Audio', 'Engagement', 'Security', 'Annotation', 'Other']
      - name: is_premium_feature
        description: "Boolean flag indicating if feature requires premium subscription"
        tests:
          - accepted_values:
              values: [true, false]

  - name: go_dim_user
    description: "User dimension with SCD Type 2 implementation"
    columns:
      - name: user_dim_id
        description: "Unique surrogate key for user dimension"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Business key for user (can have multiple records due to SCD2)"
        tests:
          - not_null
      - name: plan_category
        description: "Standardized plan category"
        tests:
          - accepted_values:
              values: ['Basic', 'Professional', 'Enterprise', 'Other']
      - name: is_current_record
        description: "Boolean flag indicating current active record"
        tests:
          - accepted_values:
              values: [true, false]
      - name: effective_start_date
        description: "Start date for this version of the record"
        tests:
          - not_null
      - name: effective_end_date
        description: "End date for this version of the record"
        tests:
          - not_null

  - name: go_fact_meeting_activity
    description: "Central fact table for meeting activities and engagement metrics"
    columns:
      - name: meeting_activity_id
        description: "Unique identifier for each meeting activity record"
        tests:
          - not_null
          - unique
      - name: meeting_date
        description: "Date of the meeting"
        tests:
          - not_null
      - name: actual_duration_minutes
        description: "Actual meeting duration in minutes"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1440
      - name: participant_count
        description: "Total number of participants in the meeting"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10000
      - name: participant_engagement_score
        description: "Calculated engagement score (0-10)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10
      - name: meeting_quality_score
        description: "Overall meeting quality score (0-10)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10

tests:
  - name: test_audit_log_completeness
    description: "Ensure all models have corresponding audit log entries"
  - name: test_date_dimension_continuity
    description: "Ensure date dimension has no gaps"
  - name: test_scd2_user_integrity
    description: "Validate SCD Type 2 implementation for users"
