version: 2

models:
  - name: dim_user
    description: "User dimension table with standardized user attributes and SCD Type 2 support"
    columns:
      - name: user_dim_id
        description: "Surrogate key for user dimension"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Business key - original user identifier"
        tests:
          - not_null
      - name: user_name
        description: "Standardized user display name"
      - name: email_domain
        description: "Extracted email domain for analysis"
      - name: company
        description: "Standardized company name"
      - name: plan_type
        description: "Standardized plan type (Basic, Pro, Enterprise)"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Unknown']
      - name: plan_category
        description: "High-level plan category (Free, Paid)"
        tests:
          - accepted_values:
              values: ['Free', 'Paid']
      - name: user_status
        description: "Current user status (Active, Inactive)"
        tests:
          - accepted_values:
              values: ['Active', 'Inactive']
      - name: is_current_record
        description: "SCD Type 2 current record flag"
        tests:
          - not_null

  - name: dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: date_id
        description: "Surrogate key for date dimension"
        tests:
          - unique
          - not_null
      - name: date_value
        description: "Actual date value"
        tests:
          - unique
          - not_null
      - name: year
        description: "Calendar year"
        tests:
          - not_null
      - name: fiscal_year
        description: "Fiscal year (April 1st start)"
        tests:
          - not_null

  - name: dim_feature
    description: "Feature dimension with categorization and characteristics"
    columns:
      - name: feature_id
        description: "Surrogate key for feature dimension"
        tests:
          - unique
          - not_null
      - name: feature_name
        description: "Standardized feature name"
        tests:
          - unique
          - not_null
      - name: feature_category
        description: "Feature category classification"
        tests:
          - accepted_values:
              values: ['Collaboration', 'Recording', 'Communication', 'Advanced Meeting', 'Engagement', 'General']

  - name: dim_license
    description: "License dimension with pricing and entitlements"
    columns:
      - name: license_id
        description: "Surrogate key for license dimension"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Standardized license type"
        tests:
          - not_null
      - name: monthly_price
        description: "Monthly subscription price"
        tests:
          - not_null

  - name: dim_meeting_type
    description: "Meeting type dimension with categorization"
    columns:
      - name: meeting_type_id
        description: "Surrogate key for meeting type dimension"
        tests:
          - unique
          - not_null
      - name: duration_category
        description: "Meeting duration category"
        tests:
          - accepted_values:
              values: ['Brief', 'Standard', 'Extended', 'Long']

  - name: dim_support_category
    description: "Support category dimension with SLA and process information"
    columns:
      - name: support_category_id
        description: "Surrogate key for support category dimension"
        tests:
          - unique
          - not_null
      - name: support_category
        description: "Standardized support category"
        tests:
          - not_null
      - name: sla_target_hours
        description: "SLA target resolution time in hours"
        tests:
          - not_null

  - name: fact_meeting_activity
    description: "Meeting activity fact table with comprehensive meeting metrics"
    columns:
      - name: meeting_activity_id
        description: "Surrogate key for meeting activity fact"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
      - name: host_user_dim_id
        description: "Foreign key to user dimension for meeting host"
        tests:
          - not_null
          - relationships:
              to: ref('dim_user')
              field: user_dim_id
      - name: participant_count
        description: "Number of meeting participants"
        tests:
          - not_null

  - name: fact_feature_usage
    description: "Feature usage fact table with adoption and performance metrics"
    columns:
      - name: feature_usage_id
        description: "Surrogate key for feature usage fact"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
      - name: feature_id
        description: "Foreign key to feature dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_feature')
              field: feature_id
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null

  - name: fact_revenue_events
    description: "Revenue events fact table with financial metrics"
    columns:
      - name: revenue_event_id
        description: "Surrogate key for revenue event fact"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
      - name: user_dim_id
        description: "Foreign key to user dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_user')
              field: user_dim_id
      - name: gross_amount
        description: "Gross revenue amount"
        tests:
          - not_null

  - name: fact_support_metrics
    description: "Support metrics fact table with SLA and resolution tracking"
    columns:
      - name: support_metrics_id
        description: "Surrogate key for support metrics fact"
        tests:
          - unique
          - not_null
      - name: date_id
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
      - name: support_category_id
        description: "Foreign key to support category dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_support_category')
              field: support_category_id
      - name: user_dim_id
        description: "Foreign key to user dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_user')
              field: user_dim_id
