version: 2

models:
  - name: go_audit_log
    description: "Gold layer process audit log for tracking transformations"
  - name: go_dim_date
    description: "Date dimension table for time-based analysis"
  - name: go_dim_user
    description: "User dimension with SCD Type 2 implementation"
  - name: go_dim_feature
    description: "Feature dimension for usage analysis"
  - name: go_dim_license
    description: "License dimension with entitlements and pricing"
  - name: go_dim_meeting_type
    description: "Meeting type dimension for meeting analysis"
  - name: go_dim_support_category
    description: "Support category dimension for ticket analysis"
  - name: go_fact_feature_usage
    description: "Feature usage fact table with comprehensive metrics"
  - name: go_fact_meeting_activity
    description: "Meeting activity fact table with engagement metrics"
  - name: go_fact_revenue_events
    description: "Revenue events fact table with financial metrics"
  - name: go_fact_support_metrics
    description: "Support metrics fact table with performance indicators"
