version: 2

models:
  - name: go_audit_log
    description: "Comprehensive audit trail for all Gold layer transformations"
    columns:
      - name: process_id
        description: "Unique identifier for each process execution"
        tests:
          - not_null
      - name: process_name
        description: "Name of the DBT model being executed"
      - name: process_status
        description: "Status of the process (STARTED, COMPLETED, FAILED)"
      - name: records_processed
        description: "Number of records processed in the transformation"
        
  - name: go_dim_date
    description: "Standard date dimension for time-based analysis"
    columns:
      - name: date_id
        description: "Unique identifier for each date"
        tests:
          - not_null
          - unique
      - name: date_value
        description: "The actual date value"
        tests:
          - not_null
          - unique
      - name: is_weekend
        description: "Flag indicating if date falls on weekend"
      - name: fiscal_year
        description: "Fiscal year (April-March cycle)"
        
  - name: go_dim_user
    description: "User dimension with SCD Type 2 implementation"
    columns:
      - name: user_dim_id
        description: "Unique identifier for each user dimension record"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Display name of the user"
        tests:
          - not_null
      - name: plan_category
        description: "Standardized plan category"
        tests:
          - accepted_values:
              values: ['Basic', 'Professional', 'Business', 'Enterprise', 'Other']
      - name: is_current_record
        description: "Flag indicating if this is the current version of the user record"
        
  - name: go_fact_feature_usage
    description: "Feature usage metrics and patterns"
    columns:
      - name: feature_usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - not_null
          - unique
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: success_rate_percentage
        description: "Success rate percentage for feature usage"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
