version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    database: DB_POC_ZOOM
    schema: SILVER
    tables:
      - name: si_users
        description: "Silver layer user data with profile and subscription information"
        
      - name: si_meetings
        description: "Silver layer meeting data with session details"
        
      - name: si_participants
        description: "Silver layer participant data for meetings"
        
      - name: si_feature_usage
        description: "Silver layer feature usage data"
        
      - name: si_support_tickets
        description: "Silver layer support ticket data"
        
      - name: si_billing_events
        description: "Silver layer billing and revenue data"
        
      - name: si_licenses
        description: "Silver layer license assignment data"
