version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleansed and validated data"
    tables:
      - name: si_users
        description: "Silver layer user profile and subscription information"
      - name: si_meetings
        description: "Silver layer meeting information and session details"
      - name: si_participants
        description: "Silver layer meeting participants and their session details"
      - name: si_feature_usage
        description: "Silver layer platform feature usage during meetings"
      - name: si_support_tickets
        description: "Silver layer customer support requests and resolution tracking"
      - name: si_billing_events
        description: "Silver layer financial transactions and billing activities"
      - name: si_licenses
        description: "Silver layer license assignments and entitlements"
