version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    tables:
      - name: si_users
        description: "Silver layer user data"
        columns:
          - name: user_id
            description: "Unique user identifier"
          - name: user_name
            description: "User display name"
          - name: email
            description: "User email address"
          - name: company
            description: "User company"
          - name: plan_type
            description: "User subscription plan"
          - name: validation_status
            description: "Data validation status"
          - name: source_system
            description: "Source system identifier"

      - name: si_meetings
        description: "Silver layer meeting data"
        columns:
          - name: meeting_id
            description: "Unique meeting identifier"
          - name: host_id
            description: "Meeting host user ID"
          - name: meeting_topic
            description: "Meeting topic/title"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: validation_status
            description: "Data validation status"
          - name: source_system
            description: "Source system identifier"

      - name: si_participants
        description: "Silver layer meeting participants data"
        columns:
          - name: participant_id
            description: "Unique participant identifier"
          - name: meeting_id
            description: "Associated meeting ID"
          - name: user_id
            description: "Participant user ID"
          - name: join_time
            description: "Participant join timestamp"
          - name: leave_time
            description: "Participant leave timestamp"
          - name: validation_status
            description: "Data validation status"

      - name: si_feature_usage
        description: "Silver layer feature usage data"
        columns:
          - name: usage_id
            description: "Unique usage record identifier"
          - name: meeting_id
            description: "Associated meeting ID"
          - name: feature_name
            description: "Name of the feature used"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date of feature usage"
          - name: validation_status
            description: "Data validation status"
          - name: source_system
            description: "Source system identifier"

      - name: si_support_tickets
        description: "Silver layer support tickets data"
        columns:
          - name: ticket_id
            description: "Unique ticket identifier"
          - name: user_id
            description: "User who created the ticket"
          - name: ticket_type
            description: "Type/category of support ticket"
          - name: resolution_status
            description: "Current resolution status"
          - name: open_date
            description: "Date ticket was opened"
          - name: validation_status
            description: "Data validation status"
          - name: source_system
            description: "Source system identifier"

      - name: si_billing_events
        description: "Silver layer billing events data"
        columns:
          - name: event_id
            description: "Unique billing event identifier"
          - name: user_id
            description: "User associated with billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Billing amount"
          - name: event_date
            description: "Date of billing event"
          - name: validation_status
            description: "Data validation status"
          - name: source_system
            description: "Source system identifier"

      - name: si_licenses
        description: "Silver layer license data"
        columns:
          - name: license_id
            description: "Unique license identifier"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User assigned to license"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: validation_status
            description: "Data validation status"
          - name: source_system
            description: "Source system identifier"
