version: 2

sources:
  - name: silver
    tables:
      - name: si_users
      - name: si_meetings
      - name: si_participants
      - name: si_feature_usage
      - name: si_support_tickets
      - name: si_billing_events
      - name: si_licenses
