version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    tables:
      - name: si_billing_events
        description: "Silver layer billing events data"
        columns:
          - name: billing_event_id
            description: "Unique identifier for billing event"
          - name: user_id
            description: "User identifier"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Transaction amount"
          - name: event_date
            description: "Date of the event"
          - name: currency_code
            description: "Currency code"
          - name: payment_method
            description: "Payment method used"
          - name: transaction_status
            description: "Status of transaction"

      - name: si_feature_usage
        description: "Silver layer feature usage data"
        columns:
          - name: feature_usage_id
            description: "Unique identifier for feature usage"
          - name: meeting_id
            description: "Meeting identifier"
          - name: feature_name
            description: "Name of the feature"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date of usage"
          - name: usage_duration_minutes
            description: "Duration of feature usage"
          - name: feature_category
            description: "Category of the feature"
          - name: usage_pattern
            description: "Pattern of usage"

      - name: si_licenses
        description: "Silver layer license data"
        columns:
          - name: license_id
            description: "Unique identifier for license"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User assigned to license"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: license_status
            description: "Status of license"
          - name: license_duration_days
            description: "Duration of license in days"
          - name: renewal_flag
            description: "License renewal flag"

      - name: si_meetings
        description: "Silver layer meetings data"
        columns:
          - name: meeting_id
            description: "Unique identifier for meeting"
          - name: host_id
            description: "Host user identifier"
          - name: meeting_topic
            description: "Topic of the meeting"
          - name: start_time
            description: "Meeting start time"
          - name: end_time
            description: "Meeting end time"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: meeting_type
            description: "Type of meeting"
          - name: time_zone
            description: "Time zone of meeting"
          - name: meeting_size_category
            description: "Size category of meeting"
          - name: business_hours_flag
            description: "Flag indicating if meeting was during business hours"

      - name: si_participants
        description: "Silver layer participants data"
        columns:
          - name: participant_id
            description: "Unique identifier for participant"
          - name: meeting_id
            description: "Meeting identifier"
          - name: user_id
            description: "User identifier"
          - name: join_time
            description: "Time participant joined"
          - name: leave_time
            description: "Time participant left"
          - name: attendance_duration_minutes
            description: "Duration of attendance in minutes"
          - name: attendance_percentage
            description: "Percentage of meeting attended"
          - name: late_join_flag
            description: "Flag indicating late join"
          - name: early_leave_flag
            description: "Flag indicating early leave"
          - name: engagement_score
            description: "Engagement score of participant"

      - name: si_support_tickets
        description: "Silver layer support tickets data"
        columns:
          - name: support_ticket_id
            description: "Unique identifier for support ticket"
          - name: user_id
            description: "User identifier"
          - name: ticket_type
            description: "Type of support ticket"
          - name: issue_description
            description: "Description of the issue"
          - name: priority_level
            description: "Priority level of ticket"
          - name: resolution_status
            description: "Resolution status"
          - name: open_date
            description: "Date ticket was opened"
          - name: close_date
            description: "Date ticket was closed"
          - name: resolution_time_hours
            description: "Time to resolve in hours"
          - name: first_response_time_hours
            description: "First response time in hours"
          - name: escalation_flag
            description: "Escalation flag"
          - name: sla_breach_flag
            description: "SLA breach flag"

      - name: si_users
        description: "Silver layer users data"
        columns:
          - name: user_id
            description: "Unique identifier for user"
          - name: user_name
            description: "Name of the user"
          - name: email
            description: "Email address"
          - name: email_domain
            description: "Email domain"
          - name: company
            description: "Company name"
          - name: plan_type
            description: "Plan type"
          - name: registration_date
            description: "Registration date"
          - name: account_age_days
            description: "Account age in days"
          - name: user_segment
            description: "User segment"
          - name: geographic_region
            description: "Geographic region"

      - name: si_webinars
        description: "Silver layer webinars data"
        columns:
          - name: webinar_id
            description: "Unique identifier for webinar"
          - name: host_id
            description: "Host user identifier"
          - name: webinar_topic
            description: "Topic of the webinar"
          - name: start_time
            description: "Webinar start time"
          - name: end_time
            description: "Webinar end time"
          - name: duration_minutes
            description: "Webinar duration in minutes"
          - name: registrants
            description: "Number of registrants"
          - name: actual_attendees
            description: "Number of actual attendees"
          - name: attendance_rate
            description: "Attendance rate percentage"
          - name: webinar_category
            description: "Category of webinar"
