version: 2

sources:
  - name: silver
    database: DB_POC_ZOOM
    schema: SILVER
    description: "Silver layer tables containing cleaned and validated data"
    tables:
      - name: si_users
        description: "Silver layer user data with data quality validations"
      - name: si_meetings
        description: "Silver layer meeting data with calculated metrics"
      - name: si_participants
        description: "Silver layer participant attendance data"
      - name: si_feature_usage
        description: "Silver layer feature usage data"
      - name: si_support_tickets
        description: "Silver layer support ticket data"
      - name: si_billing_events
        description: "Silver layer billing and transaction data"
      - name: si_licenses
        description: "Silver layer license assignment data"
      - name: si_webinars
        description: "Silver layer webinar data"
