version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    schema: silver
    tables:
      - name: si_users
        description: "Silver layer user data"
        
      - name: si_meetings
        description: "Silver layer meeting data"
        
      - name: si_participants
        description: "Silver layer meeting participants data"
        
      - name: si_feature_usage
        description: "Silver layer feature usage data"
        
      - name: si_support_tickets
        description: "Silver layer support tickets data"
        
      - name: si_billing_events
        description: "Silver layer billing events data"
        
      - name: si_licenses
        description: "Silver layer license data"
