version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    database: DB_POC_ZOOM
    schema: SILVER
    tables:
      - name: si_users
        description: "Silver layer user profile and subscription information"
        columns:
          - name: USER_ID
            description: "Unique identifier for each user account"
          - name: USER_NAME
            description: "Display name of the user"
          - name: EMAIL
            description: "Email address of the user"
          - name: COMPANY
            description: "Company or organization name"
          - name: PLAN_TYPE
            description: "Subscription plan type"
          - name: VALIDATION_STATUS
            description: "Status of data validation"
          - name: SOURCE_SYSTEM
            description: "Source system from which data originated"

      - name: si_meetings
        description: "Silver layer meeting information and session details"
        columns:
          - name: MEETING_ID
            description: "Unique identifier for each meeting"
          - name: HOST_ID
            description: "User ID of the meeting host"
          - name: MEETING_TOPIC
            description: "Topic or title of the meeting"
          - name: START_TIME
            description: "Meeting start timestamp"
          - name: END_TIME
            description: "Meeting end timestamp"
          - name: DURATION_MINUTES
            description: "Meeting duration in minutes"
          - name: VALIDATION_STATUS
            description: "Status of data validation"
          - name: DATA_QUALITY_SCORE
            description: "Quality score from validation process"

      - name: si_participants
        description: "Silver layer meeting participants and their session details"
        columns:
          - name: PARTICIPANT_ID
            description: "Unique identifier for each meeting participant"
          - name: MEETING_ID
            description: "Reference to meeting"
          - name: USER_ID
            description: "Reference to user who participated"
          - name: JOIN_TIME
            description: "Timestamp when participant joined meeting"
          - name: LEAVE_TIME
            description: "Timestamp when participant left meeting"
          - name: VALIDATION_STATUS
            description: "Status of data validation"

      - name: si_feature_usage
        description: "Silver layer platform feature usage during meetings"
        columns:
          - name: USAGE_ID
            description: "Unique identifier for each feature usage record"
          - name: MEETING_ID
            description: "Reference to meeting where feature was used"
          - name: FEATURE_NAME
            description: "Name of the feature being tracked"
          - name: USAGE_COUNT
            description: "Number of times feature was used"
          - name: USAGE_DATE
            description: "Date when feature usage occurred"
          - name: VALIDATION_STATUS
            description: "Status of data validation"

      - name: si_support_tickets
        description: "Silver layer customer support requests and resolution tracking"
        columns:
          - name: TICKET_ID
            description: "Unique identifier for each support ticket"
          - name: USER_ID
            description: "Reference to user who created the ticket"
          - name: TICKET_TYPE
            description: "Type of support ticket"
          - name: RESOLUTION_STATUS
            description: "Current status of ticket resolution"
          - name: OPEN_DATE
            description: "Date when ticket was opened"
          - name: VALIDATION_STATUS
            description: "Status of data validation"

      - name: si_billing_events
        description: "Silver layer financial transactions and billing activities"
        columns:
          - name: EVENT_ID
            description: "Unique identifier for each billing event"
          - name: USER_ID
            description: "Reference to user associated with billing event"
          - name: EVENT_TYPE
            description: "Type of billing event"
          - name: AMOUNT
            description: "Monetary amount for the billing event"
          - name: EVENT_DATE
            description: "Date when the billing event occurred"
          - name: VALIDATION_STATUS
            description: "Status of data validation"

      - name: si_licenses
        description: "Silver layer license assignments and entitlements"
        columns:
          - name: LICENSE_ID
            description: "Unique identifier for each license"
          - name: LICENSE_TYPE
            description: "Type of license"
          - name: ASSIGNED_TO_USER_ID
            description: "User ID to whom license is assigned"
          - name: START_DATE
            description: "License validity start date"
          - name: END_DATE
            description: "License validity end date"
          - name: VALIDATION_STATUS
            description: "Status of data validation"
