version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    tables:
      - name: si_billing_events
        description: "Silver layer billing events data"
      - name: si_feature_usage
        description: "Silver layer feature usage data"
      - name: si_licenses
        description: "Silver layer license data"
      - name: si_meetings
        description: "Silver layer meetings data"
      - name: si_participants
        description: "Silver layer participants data"
      - name: si_support_tickets
        description: "Silver layer support tickets data"
      - name: si_users
        description: "Silver layer users data"
      - name: si_webinars
        description: "Silver layer webinars data"
