version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    tables:
      - name: si_users
        description: "Silver layer user data"
        columns:
          - name: user_id
            description: "Unique user identifier"
          - name: user_name
            description: "User display name"
          - name: email
            description: "User email address"
          - name: company
            description: "User company"
          - name: plan_type
            description: "User subscription plan"
          - name: load_timestamp
            description: "Record load timestamp"
          - name: update_timestamp
            description: "Record update timestamp"
          - name: source_system
            description: "Source system identifier"
          - name: load_date
            description: "Load date"
          - name: update_date
            description: "Update date"
          - name: data_quality_score
            description: "Data quality score"
          - name: validation_status
            description: "Validation status"
            
      - name: si_meetings
        description: "Silver layer meeting data"
        columns:
          - name: meeting_id
            description: "Unique meeting identifier"
          - name: host_id
            description: "Meeting host user ID"
          - name: meeting_topic
            description: "Meeting topic"
          - name: start_time
            description: "Meeting start time"
          - name: end_time
            description: "Meeting end time"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Record load timestamp"
          - name: update_timestamp
            description: "Record update timestamp"
          - name: source_system
            description: "Source system identifier"
          - name: load_date
            description: "Load date"
          - name: update_date
            description: "Update date"
          - name: data_quality_score
            description: "Data quality score"
          - name: validation_status
            description: "Validation status"
            
      - name: si_participants
        description: "Silver layer participant data"
        columns:
          - name: participant_id
            description: "Unique participant identifier"
          - name: meeting_id
            description: "Meeting identifier"
          - name: user_id
            description: "Participant user ID"
          - name: join_time
            description: "Participant join time"
          - name: leave_time
            description: "Participant leave time"
          - name: load_timestamp
            description: "Record load timestamp"
          - name: update_timestamp
            description: "Record update timestamp"
          - name: source_system
            description: "Source system identifier"
          - name: load_date
            description: "Load date"
          - name: update_date
            description: "Update date"
          - name: data_quality_score
            description: "Data quality score"
          - name: validation_status
            description: "Validation status"
            
      - name: si_feature_usage
        description: "Silver layer feature usage data"
        columns:
          - name: usage_id
            description: "Unique usage identifier"
          - name: meeting_id
            description: "Meeting identifier"
          - name: feature_name
            description: "Feature name"
          - name: usage_count
            description: "Usage count"
          - name: usage_date
            description: "Usage date"
          - name: load_timestamp
            description: "Record load timestamp"
          - name: update_timestamp
            description: "Record update timestamp"
          - name: source_system
            description: "Source system identifier"
          - name: load_date
            description: "Load date"
          - name: update_date
            description: "Update date"
          - name: data_quality_score
            description: "Data quality score"
          - name: validation_status
            description: "Validation status"
            
      - name: si_support_tickets
        description: "Silver layer support ticket data"
        columns:
          - name: ticket_id
            description: "Unique ticket identifier"
          - name: user_id
            description: "User identifier"
          - name: ticket_type
            description: "Ticket type"
          - name: resolution_status
            description: "Resolution status"
          - name: open_date
            description: "Ticket open date"
          - name: load_timestamp
            description: "Record load timestamp"
          - name: update_timestamp
            description: "Record update timestamp"
          - name: source_system
            description: "Source system identifier"
          - name: load_date
            description: "Load date"
          - name: update_date
            description: "Update date"
          - name: data_quality_score
            description: "Data quality score"
          - name: validation_status
            description: "Validation status"
            
      - name: si_billing_events
        description: "Silver layer billing event data"
        columns:
          - name: event_id
            description: "Unique event identifier"
          - name: user_id
            description: "User identifier"
          - name: event_type
            description: "Event type"
          - name: amount
            description: "Event amount"
          - name: event_date
            description: "Event date"
          - name: load_timestamp
            description: "Record load timestamp"
          - name: update_timestamp
            description: "Record update timestamp"
          - name: source_system
            description: "Source system identifier"
          - name: load_date
            description: "Load date"
          - name: update_date
            description: "Update date"
          - name: data_quality_score
            description: "Data quality score"
          - name: validation_status
            description: "Validation status"
            
      - name: si_licenses
        description: "Silver layer license data"
        columns:
          - name: license_id
            description: "Unique license identifier"
          - name: license_type
            description: "License type"
          - name: assigned_to_user_id
            description: "Assigned user ID"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: load_timestamp
            description: "Record load timestamp"
          - name: update_timestamp
            description: "Record update timestamp"
          - name: source_system
            description: "Source system identifier"
          - name: load_date
            description: "Load date"
          - name: update_date
            description: "Update date"
          - name: data_quality_score
            description: "Data quality score"
          - name: validation_status
            description: "Validation status"
