version: 2

sources:
  - name: silver
    description: "Silver layer tables containing cleaned and validated data"
    tables:
      - name: si_users
        description: "Silver layer user data with data quality validations"
        columns:
          - name: user_id
            description: "Unique identifier for each user"
          - name: user_name
            description: "Full name of the user"
          - name: email
            description: "User email address"
          - name: company
            description: "Company or organization name"
          - name: plan_type
            description: "Subscription plan type"
          - name: account_status
            description: "Current account status"
          - name: registration_date
            description: "Date when user registered"
          - name: data_quality_score
            description: "Data quality score for the record"
          - name: source_system
            description: "Source system identifier"
            
      - name: si_meetings
        description: "Silver layer meeting data with calculated metrics"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Meeting subject or title"
          - name: meeting_type
            description: "Type of meeting"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: meeting_status
            description: "Current meeting status"
          - name: recording_status
            description: "Whether meeting was recorded"
          - name: participant_count
            description: "Number of participants"
          - name: data_quality_score
            description: "Data quality score for the record"
          - name: source_system
            description: "Source system identifier"
            
      - name: si_participants
        description: "Silver layer participant attendance data"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user"
          - name: join_time
            description: "When participant joined"
          - name: leave_time
            description: "When participant left"
          - name: attendance_duration
            description: "Time spent in meeting"
          - name: data_quality_score
            description: "Data quality score for the record"
          - name: source_system
            description: "Source system identifier"
            
      - name: si_feature_usage
        description: "Silver layer feature usage data"
        columns:
          - name: usage_id
            description: "Unique identifier for each usage record"
          - name: meeting_id
            description: "Reference to meeting"
          - name: feature_name
            description: "Name of the feature used"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_duration
            description: "Duration feature was active"
          - name: feature_category
            description: "Category of the feature"
          - name: usage_date
            description: "Date when feature was used"
          - name: data_quality_score
            description: "Data quality score for the record"
          - name: source_system
            description: "Source system identifier"
            
      - name: si_support_tickets
        description: "Silver layer support ticket data"
        columns:
          - name: ticket_id
            description: "Unique identifier for each ticket"
          - name: user_id
            description: "Reference to user who created ticket"
          - name: ticket_type
            description: "Category of support ticket"
          - name: priority_level
            description: "Priority level of ticket"
          - name: open_date
            description: "Date when ticket was created"
          - name: close_date
            description: "Date when ticket was resolved"
          - name: resolution_status
            description: "Current resolution status"
          - name: resolution_time_hours
            description: "Time to resolve ticket"
          - name: data_quality_score
            description: "Data quality score for the record"
          - name: source_system
            description: "Source system identifier"
            
      - name: si_billing_events
        description: "Silver layer billing and transaction data"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
          - name: user_id
            description: "Reference to user"
          - name: event_type
            description: "Type of billing event"
          - name: transaction_amount
            description: "Monetary value of the event"
          - name: transaction_date
            description: "Date of the transaction"
          - name: payment_method
            description: "Payment method used"
          - name: currency_code
            description: "Currency code for transaction"
          - name: transaction_status
            description: "Status of transaction"
          - name: data_quality_score
            description: "Data quality score for the record"
          - name: source_system
            description: "Source system identifier"
            
      - name: si_licenses
        description: "Silver layer license assignment data"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
          - name: assigned_to_user_id
            description: "User ID to whom license is assigned"
          - name: license_type
            description: "Type of license"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: license_status
            description: "Current license status"
          - name: data_quality_score
            description: "Data quality score for the record"
          - name: source_system
            description: "Source system identifier"
            
      - name: si_webinars
        description: "Silver layer webinar data"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"
          - name: host_id
            description: "User ID of webinar host"
          - name: webinar_topic
            description: "Webinar topic or title"
          - name: start_time
            description: "Webinar start timestamp"
          - name: end_time
            description: "Webinar end timestamp"
          - name: duration_minutes
            description: "Webinar duration in minutes"
          - name: registrants
            description: "Number of registered participants"
          - name: attendees
            description: "Number of actual attendees"
          - name: data_quality_score
            description: "Data quality score for the record"
          - name: source_system
            description: "Source system identifier"
