name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns

vars:
  # Set the timezone for timestamp operations
  timezone: 'UTC'
  # Set the default schema for sources
  bronze_schema: 'BRONZE'
