name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/silver/
    silver:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'SI_Audit_Log' %}
          INSERT INTO {{ ref('SI_Audit_Log') }} (
            AUDIT_ID, 
            TABLE_NAME, 
            OPERATION_TYPE, 
            AUDIT_TIMESTAMP, 
            PROCESSED_BY,
            SOURCE_SYSTEM
          ) 
          SELECT 
            UUID_STRING(), 
            '{{ this.name }}', 
            'PIPELINE_START', 
            CURRENT_TIMESTAMP(), 
            'DBT_SILVER_PIPELINE',
            'SILVER_LAYER'
        {% endif %}
      +post-hook: |
        {% if this.name != 'SI_Audit_Log' %}
          INSERT INTO {{ ref('SI_Audit_Log') }} (
            AUDIT_ID, 
            TABLE_NAME, 
            OPERATION_TYPE, 
            AUDIT_TIMESTAMP, 
            PROCESSED_BY,
            SOURCE_SYSTEM
          ) 
          SELECT 
            UUID_STRING(), 
            '{{ this.name }}', 
            'PIPELINE_END', 
            CURRENT_TIMESTAMP(), 
            'DBT_SILVER_PIPELINE',
            'SILVER_LAYER'
        {% endif %}

# Model execution order configuration
model-ordering:
  - name: SI_Audit_Log
    depends_on: []
  - name: SI_Users
    depends_on: [SI_Audit_Log]
  - name: SI_Meetings
    depends_on: [SI_Audit_Log, SI_Users]
  - name: SI_Participants
    depends_on: [SI_Audit_Log, SI_Users, SI_Meetings]
  - name: SI_Feature_Usage
    depends_on: [SI_Audit_Log, SI_Meetings]
  - name: SI_Support_Tickets
    depends_on: [SI_Audit_Log, SI_Users]
  - name: SI_Billing_Events
    depends_on: [SI_Audit_Log, SI_Users]
  - name: SI_Licenses
    depends_on: [SI_Audit_Log, SI_Users]

# Snapshot configurations
snapshots:
  zoom_silver_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: update_timestamp

# Seed configurations
seeds:
  zoom_silver_pipeline:
    +enabled: true
    +schema: seeds

# Test configurations
tests:
  zoom_silver_pipeline:
    +enabled: true
    +severity: warn

# Documentation configurations
docs:
  generate: true
  
# Variables
vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2020-01-01'
  # The `end_date` variable will be accessible in all resources  
  end_date: '2030-12-31'
  # Data quality threshold
  dq_threshold: 70
  # Audit retention days
  audit_retention_days: 730
