name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_bronze_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_bronze_pipeline:
    bronze:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'bz_audit_log' %}
          INSERT INTO {{ ref('bz_audit_log') }} (source_table, load_timestamp, processed_by, processing_time, status)
          VALUES ('{{ this.name }}', CURRENT_TIMESTAMP(), 'DBT', 0, 'STARTED')
        {% endif %}
      +post-hook: |
        {% if this.name != 'bz_audit_log' %}
          UPDATE {{ ref('bz_audit_log') }}
          SET processing_time = DATEDIFF('second', load_timestamp, CURRENT_TIMESTAMP()),
              status = 'COMPLETED'
          WHERE source_table = '{{ this.name }}' 
            AND status = 'STARTED'
            AND load_timestamp = (SELECT MAX(load_timestamp) FROM {{ ref('bz_audit_log') }} WHERE source_table = '{{ this.name }}' AND status = 'STARTED')
        {% endif %}
