name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    silver:
      +materialized: table
      SI_Audit_Log:
        +pre-hook: []
        +post-hook: []

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'

on-run-start:
  - "{{ log('Starting Silver Layer Pipeline Execution', info=true) }}"

on-run-end:
  - "{{ log('Completed Silver Layer Pipeline Execution', info=true) }}"
