name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
      # Ensure audit log runs first
      SI_Audit_Log:
        +pre_hook: []
        +post_hook: []
        +materialized: table
        +tags: ["audit", "first"]
      # All other silver models
      SI_Users:
        +materialized: table
        +tags: ["silver", "users"]
      SI_Meetings:
        +materialized: table
        +tags: ["silver", "meetings"]
      SI_Participants:
        +materialized: table
        +tags: ["silver", "participants"]
      SI_Feature_Usage:
        +materialized: table
        +tags: ["silver", "feature_usage"]
      SI_Support_Tickets:
        +materialized: table
        +tags: ["silver", "support"]
      SI_Billing_Events:
        +materialized: table
        +tags: ["silver", "billing"]
      SI_Licenses:
        +materialized: table
        +tags: ["silver", "licenses"]

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['zoom_silver_pipeline', 'dbt_utils']
