name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_bronze_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_bronze_pipeline:
    bronze:
      +materialized: table

vars:
  start_date: '2024-01-01'
  end_date: '2024-12-31'
  source_schema: 'RAW'
  target_schema: 'BRONZE'
