name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    bronze:
      +materialized: table
    silver:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'SI_AUDIT_LOG' %}
          INSERT INTO {{ ref('SI_AUDIT_LOG') }} (
            SOURCE_TABLE, ERROR_TYPE, COLUMN_NAME, ERROR_VALUE, PROCESS_TIMESTAMP, PROCESS_STATUS, EXECUTION_ID, PIPELINE_NAME, RECORD_COUNT, ERROR_COUNT, WARNING_COUNT, PROCESSED_BY, SOURCE_SYSTEM
          )
          VALUES (
            '{{ this.name }}', 'PROCESS_START', 'N/A', 'N/A', CURRENT_TIMESTAMP(), 'STARTED', 
            '{{ invocation_id }}', 'BRONZE_TO_SILVER_{{ this.name }}', 0, 0, 0, 'DBT_SILVER_PIPELINE', 'BRONZE_LAYER'
          )
        {% endif %}
      +post-hook: |
        {% if this.name != 'SI_AUDIT_LOG' %}
          INSERT INTO {{ ref('SI_AUDIT_LOG') }} (
            SOURCE_TABLE, ERROR_TYPE, COLUMN_NAME, ERROR_VALUE, PROCESS_TIMESTAMP, PROCESS_STATUS, EXECUTION_ID, PIPELINE_NAME, RECORD_COUNT, ERROR_COUNT, WARNING_COUNT, PROCESSED_BY, SOURCE_SYSTEM
          )
          VALUES (
            '{{ this.name }}', 'PROCESS_END', 'N/A', 'N/A', CURRENT_TIMESTAMP(), 'COMPLETED', 
            '{{ invocation_id }}', 'BRONZE_TO_SILVER_{{ this.name }}', 
            (SELECT COUNT(*) FROM {{ this }}), 0, 0, 'DBT_SILVER_PIPELINE', 'BRONZE_LAYER'
          )
        {% endif %}
    gold:
      +materialized: table

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
