name: 'zoom_gold_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_gold_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  audit_schema: "GOLD"
  audit_table: "GO_AUDIT_LOG"
  source_system: "SILVER_TO_GOLD_ETL"

models:
  zoom_gold_pipeline:
    gold:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'go_audit_log' %}
          INSERT INTO {{ target.schema }}.GO_AUDIT_LOG (
            PROCESS_ID, PROCESS_NAME, SOURCE_TABLE, TARGET_TABLE, 
            PROCESS_START_TIME, PROCESS_STATUS, LOAD_DATE, SOURCE_SYSTEM
          ) VALUES (
            '{{ invocation_id }}', 
            '{{ this.name }}', 
            'SILVER', 
            '{{ this.name }}', 
            CURRENT_TIMESTAMP(), 
            'STARTED', 
            CURRENT_DATE(), 
            '{{ var('source_system') }}'
          )
        {% endif %}
      +post-hook: |
        {% if this.name != 'go_audit_log' %}
          UPDATE {{ target.schema }}.GO_AUDIT_LOG 
          SET PROCESS_END_TIME = CURRENT_TIMESTAMP(), 
              PROCESS_STATUS = 'COMPLETED',
              RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }})
          WHERE PROCESS_ID = '{{ invocation_id }}' 
            AND PROCESS_NAME = '{{ this.name }}'
        {% endif %}
