name: 'zoom_analytics_gold'
version: '1.0.0'
config-version: 2

profile: 'zoom_analytics_gold'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_analytics_gold:
    gold:
      +materialized: table
      dimension:
        +materialized: table
      fact:
        +materialized: table

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'

seeds:
  zoom_analytics_gold:
    +quote_columns: false

snapshots:
  zoom_analytics_gold:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

tests:
  zoom_analytics_gold:
    +store_failures: true
    +schema: test_failures
