name: 'zoom_gold_layer'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_layer'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_layer:
    # Config indicated by + and applies to all files under models/gold/
    gold:
      +materialized: table
      +tags: ["gold"]
      # Audit log must run first
      go_audit_log:
        +pre_hook: []
        +post_hook: []
      # Dimensions run after audit log
      dimension:
        +materialized: table
        +tags: ["dimension", "gold"]
      # Facts run after dimensions
      fact:
        +materialized: table
        +tags: ["fact", "gold"]

# Global configurations
vars:
  # Database and schema configurations
  source_database: 'DB_POC_ZOOM'
  source_schema: 'SILVER'
  target_database: 'DB_POC_ZOOM'
  target_schema: 'GOLD'
  
  # Data quality configurations
  data_quality_threshold: 70
  audit_retention_days: 365
  
  # Business rule configurations
  fiscal_year_start_month: 4
  default_currency: 'USD'
  sla_default_hours: 72

# Snapshot configurations
snapshots:
  zoom_gold_layer:
    +target_schema: GOLD_SNAPSHOTS
    +strategy: timestamp
    +updated_at: UPDATE_DATE

# Seeds configurations
seeds:
  zoom_gold_layer:
    +schema: GOLD_REFERENCE

# Test configurations
tests:
  +store_failures: true
  +schema: GOLD_TEST_RESULTS
