name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/silver/
    silver:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'SI_Audit_Log' %}
          INSERT INTO {{ ref('SI_Audit_Log') }} (TABLE_NAME, STATUS, PROCESS_START_TIME, PROCESSED_BY, CREATED_AT) 
          SELECT '{{ this.name }}', 'STARTED', CURRENT_TIMESTAMP(), 'DBT_SILVER_PIPELINE', CURRENT_TIMESTAMP()
        {% endif %}
      +post-hook: |
        {% if this.name != 'SI_Audit_Log' %}
          INSERT INTO {{ ref('SI_Audit_Log') }} (TABLE_NAME, STATUS, PROCESS_END_TIME, PROCESSED_BY, RECORDS_PROCESSED, UPDATED_AT) 
          SELECT '{{ this.name }}', 'COMPLETED', CURRENT_TIMESTAMP(), 'DBT_SILVER_PIPELINE', (SELECT COUNT(*) FROM {{ this }}), CURRENT_TIMESTAMP()
        {% endif %}

# Specify the order of model execution
model-ordering:
  - "SI_Audit_Log"  # Must run first
  - "SI_USERS"
  - "SI_MEETINGS"
  - "SI_PARTICIPANTS"
  - "SI_FEATURE_USAGE"
  - "SI_SUPPORT_TICKETS"
  - "SI_BILLING_EVENTS"
  - "SI_LICENSES"

# Configure tests
tests:
  +store_failures: true
  +severity: warn

# Configure snapshots
snapshots:
  zoom_silver_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Configure seeds
seeds:
  zoom_silver_pipeline:
    +schema: seeds

# Configure macros
macros:
  zoom_silver_pipeline:
    +schema: macros

# Configure variables
vars:
  # dbt Cloud environment variables
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
  # Data quality thresholds
  dq_score_threshold: 70
  max_processing_time_minutes: 60
  
  # Business rules
  max_meeting_duration_minutes: 1440
  valid_plan_types: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE']
  valid_resolution_statuses: ['OPEN', 'IN PROGRESS', 'RESOLVED', 'CLOSED']

# Configure on-run-start and on-run-end hooks
on-run-start:
  - "{{ log('Starting Silver Layer Pipeline Execution', info=True) }}"
  - "CREATE SCHEMA IF NOT EXISTS {{ target.schema }}"

on-run-end:
  - "{{ log('Silver Layer Pipeline Execution Completed', info=True) }}"
  - |
    {% if target.name == 'prod' %}
      INSERT INTO {{ ref('SI_Audit_Log') }} (TABLE_NAME, STATUS, PROCESS_END_TIME, PROCESSED_BY, CREATED_AT) 
      SELECT 'PIPELINE_COMPLETE', 'SUCCESS', CURRENT_TIMESTAMP(), 'DBT_SILVER_PIPELINE', CURRENT_TIMESTAMP()
    {% endif %}

# Configure dispatch
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['zoom_silver_pipeline', 'dbt_utils']
