name: 'zoom_gold_analytics'
version: '1.0.0'
config-version: 2

profile: 'zoom_gold_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_gold_analytics:
    +materialized: table
    gold:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'go_process_audit' %}
          INSERT INTO {{ ref('go_process_audit') }} (
            AUDIT_LOG_ID, PROCESS_NAME, EXECUTION_START_TIMESTAMP, 
            EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME,
            LOAD_DATE, UPDATE_DATE, SOURCE_SYSTEM
          )
          VALUES (
            '{{ invocation_id }}', '{{ this.name }}', CURRENT_TIMESTAMP(),
            'RUNNING', 'SILVER', '{{ this.name }}',
            CURRENT_DATE(), CURRENT_DATE(), 'DBT_GOLD_ETL'
          )
        {% endif %}
      +post-hook: |
        {% if this.name != 'go_process_audit' %}
          UPDATE {{ ref('go_process_audit') }}
          SET 
            EXECUTION_END_TIMESTAMP = CURRENT_TIMESTAMP(),
            EXECUTION_STATUS = 'SUCCESS',
            RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}),
            UPDATE_DATE = CURRENT_DATE()
          WHERE AUDIT_LOG_ID = '{{ invocation_id }}' AND PROCESS_NAME = '{{ this.name }}'
        {% endif %}
