name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'user'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    +materialized: table
    
    silver:
      +materialized: table
      SI_AUDIT_LOG:
        +materialized: table
      SI_USERS:
        +materialized: table
      SI_MEETINGS:
        +materialized: table
      SI_PARTICIPANTS:
        +materialized: table
      SI_FEATURE_USAGE:
        +materialized: table
      SI_SUPPORT_TICKETS:
        +materialized: table
      SI_BILLING_EVENTS:
        +materialized: table
      SI_LICENSES:
        +materialized: table

vars:
  dq_score_threshold: 70
  start_date: '2020-01-01'
  end_date: '2030-12-31'
