name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_bronze_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_bronze_pipeline:
    # Config indicated by + and applies to all files under models/bronze/
    bronze:
      +materialized: table
      +tags: ["bronze"]

# Global configurations
vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2020-01-01'
  
# Seeds configuration
seeds:
  zoom_bronze_pipeline:
    +quote_columns: false

# Tests configuration
tests:
  zoom_bronze_pipeline:
    +store_failures: true
