name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/silver/
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
      # Ensure audit log runs first
      SI_Audit_Log:
        +pre-hook: []
        +post-hook: []
      # All other models depend on audit log
      SI_Users:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_Meetings:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_Participants:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_Feature_Usage:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_Support_Tickets:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_Billing_Events:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_Licenses:
        +depends_on:
          - ref('SI_Audit_Log')

# Set the timezone for timestamp functions
quoting:
  database: false
  schema: false
  identifier: false

vars:
  # dbt version
  dbt_version: ">=1.0.0"
  # Timezone setting
  timezone: 'UTC'
  # Data quality threshold
  dq_threshold: 60
