name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/example/
    silver:
      +materialized: table
    bronze:
      +materialized: view

vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2024-01-01'
  
# Configure seeds
seeds:
  zoom_silver_pipeline:
    +quote_columns: false

# Configure snapshots
snapshots:
  zoom_silver_pipeline:
    +target_schema: snapshots
