name: 'zoom_gold_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_gold_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_gold_pipeline:
    gold:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'go_process_audit' %}
        INSERT INTO {{ target.database }}.{{ target.schema }}.go_process_audit (
          PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, 
          EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME,
          LOAD_DATE, SOURCE_SYSTEM
        )
        VALUES (
          '{{ this.name }}', 'DBT_MODEL', CURRENT_TIMESTAMP(),
          'RUNNING', 'SILVER_LAYER', '{{ this.name }}',
          CURRENT_DATE(), 'DBT_GOLD_PIPELINE'
        )
        {% endif %}
      +post-hook: |
        {% if this.name != 'go_process_audit' %}
        UPDATE {{ target.database }}.{{ target.schema }}.go_process_audit
        SET EXECUTION_END_TIMESTAMP = CURRENT_TIMESTAMP(),
            EXECUTION_STATUS = 'SUCCESS',
            RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}),
            UPDATE_DATE = CURRENT_DATE()
        WHERE PROCESS_NAME = '{{ this.name }}'
          AND EXECUTION_STATUS = 'RUNNING'
        {% endif %}
