name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Audit log model should run first
    SI_AUDIT_LOG:
      +materialized: table
      +pre-hook: []
      +post-hook: []
    
    # Silver layer models
    +materialized: table
    +on_schema_change: "sync_all_columns"
    
    # Model execution order
    silver:
      +materialized: table
      +tags: ["silver"]
      
      # Ensure audit log runs first
      SI_AUDIT_LOG:
        +pre-hook: []
        +post-hook: []
      
      # Core silver models
      SI_USERS:
        +tags: ["silver", "users"]
      
      SI_MEETINGS:
        +tags: ["silver", "meetings"]
      
      SI_PARTICIPANTS:
        +tags: ["silver", "participants"]
      
      SI_FEATURE_USAGE:
        +tags: ["silver", "features"]
      
      SI_SUPPORT_TICKETS:
        +tags: ["silver", "support"]
      
      SI_BILLING_EVENTS:
        +tags: ["silver", "billing"]
      
      SI_LICENSES:
        +tags: ["silver", "licenses"]

# Global configurations
vars:
  # Data quality thresholds
  dq_score_threshold: 70
  
  # Date range for processing
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
  # Audit settings
  enable_audit_logging: true
  audit_table_name: 'SI_AUDIT_LOG'
  
  # Error handling
  fail_on_dq_errors: false
  log_dq_errors: true

# Test configurations
tests:
  +store_failures: true
  +severity: warn

# Snapshot configurations
snapshots:
  zoom_silver_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_timestamp

# Seeds configurations
seeds:
  zoom_silver_pipeline:
    +schema: reference_data
