name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver_pipeline'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    +materialized: table
    +tags: ["silver"]

vars:
  dq_score_threshold_passed: 90
  dq_score_threshold_warning: 70
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  max_error_threshold: 100
  enable_audit_logging: true

on-run-start:
  - "{{ log('Starting Silver Layer Pipeline Execution', info=true) }}"

on-run-end:
  - "{{ log('Silver Layer Pipeline Execution Completed', info=true) }}"

quoting:
  database: false
  schema: false
  identifier: false
