name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_bronze_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_bronze_pipeline:
    +materialized: table
    bronze:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'bz_data_audit' %}
          INSERT INTO {{ ref('bz_data_audit') }} (SOURCE_TABLE, LOAD_TIMESTAMP, PROCESSED_BY, PROCESSING_TIME, STATUS)
          VALUES ('{{ this.name }}', CURRENT_TIMESTAMP(), 'DBT_{{ invocation_id }}', 0, 'STARTED')
        {% endif %}
      +post-hook: |
        {% if this.name != 'bz_data_audit' %}
          UPDATE {{ ref('bz_data_audit') }}
          SET PROCESSING_TIME = DATEDIFF('second', LOAD_TIMESTAMP, CURRENT_TIMESTAMP()),
              STATUS = 'SUCCESS'
          WHERE SOURCE_TABLE = '{{ this.name }}'
            AND PROCESSED_BY = 'DBT_{{ invocation_id }}'
            AND STATUS = 'STARTED'
        {% endif %}

vars:
  source_schema: 'RAW'
  target_schema: 'BRONZE'
