name: 'zoom_gold_layer'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_layer'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_layer:
    # Config indicated by + and applies to all files under models/gold/
    gold:
      +materialized: table
      +schema: gold
      # Audit log must run first
      go_audit_log:
        +pre_hook: ""
        +post_hook: ""
      # Dimension tables
      dimension:
        +materialized: table
        +schema: gold
      # Fact tables  
      fact:
        +materialized: table
        +schema: gold

# Global configurations
vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2020-01-01'
  # The `end_date` variable will be accessible in all resources  
  end_date: '2030-12-31'

# Snapshot configurations
snapshots:
  zoom_gold_layer:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Seeds configurations
seeds:
  zoom_gold_layer:
    +schema: seeds

# Test configurations
tests:
  zoom_gold_layer:
    +severity: warn
