name: 'zoom_analytics_silver'
version: '1.0.0'
config-version: 2

profile: 'zoom_analytics_silver'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_analytics_silver:
    bronze:
      +materialized: table
    silver:
      +materialized: incremental
      +on_schema_change: sync_all_columns
      +unique_key: "{{ var('unique_key', 'id') }}"

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
