name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_bronze_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_bronze_pipeline:
    # Config indicated by + and applies to all files under models/bronze/
    bronze:
      +materialized: table
      +on_schema_change: "fail"

# Set a custom schema for different environments
vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2024-01-01'
  # The `end_date` variable will be accessible in all resources  
  end_date: '2024-12-31'

# Configure seeds
seeds:
  zoom_bronze_pipeline:
    +column_types:
      id: varchar(50)
      created_at: timestamp

# Configure snapshots
snapshots:
  zoom_bronze_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
