name: 'zoom_analytics'
version: '1.0.0'
config-version: 2

profile: 'zoom_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_analytics:
    bronze:
      +materialized: table
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
    gold:
      +materialized: table

vars:
  current_timestamp: "{{ run_started_at }}"
  audit_user: "DBT_SILVER_PIPELINE"
