name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
      +pre_hook: |
        {% if this.name != 'si_audit_log' %}
        INSERT INTO {{ ref('si_audit_log') }} (
          AUDIT_ID, TABLE_NAME, COLUMN_NAME, RECORD_ID, ERROR_TYPE, 
          ERROR_DESCRIPTION, ORIGINAL_VALUE, AUDIT_TIMESTAMP, 
          OPERATION_TYPE, PROCESSED_BY, SOURCE_SYSTEM
        )
        VALUES (
          GENERATE_UUID(), '{{ this.name }}', 'PIPELINE_START', 'N/A', 'PIPELINE_EXECUTION',
          'Pipeline execution started for {{ this.name }}', 'N/A', CURRENT_TIMESTAMP(),
          'INSERT', 'DBT_SILVER_PIPELINE', 'ZOOM_SYSTEM'
        )
        {% endif %}
      +post_hook: |
        {% if this.name != 'si_audit_log' %}
        INSERT INTO {{ ref('si_audit_log') }} (
          AUDIT_ID, TABLE_NAME, COLUMN_NAME, RECORD_ID, ERROR_TYPE, 
          ERROR_DESCRIPTION, ORIGINAL_VALUE, AUDIT_TIMESTAMP, 
          OPERATION_TYPE, PROCESSED_BY, SOURCE_SYSTEM
        )
        VALUES (
          GENERATE_UUID(), '{{ this.name }}', 'PIPELINE_END', 'N/A', 'PIPELINE_EXECUTION',
          'Pipeline execution completed for {{ this.name }}', 'N/A', CURRENT_TIMESTAMP(),
          'INSERT', 'DBT_SILVER_PIPELINE', 'ZOOM_SYSTEM'
        )
        {% endif %}
