name: 'zoom_gold_layer'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_layer'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_layer:
    # Config indicated by + and applies to all files under models/gold/
    gold:
      +materialized: table
      +tags: ["gold"]
      dimensional:
        +materialized: table
        +tags: ["dimension", "gold"]
      fact:
        +materialized: table
        +tags: ["fact", "gold"]

# Global configurations
vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2020-01-01'
  end_date: '2030-12-31'

# Hooks that run before and after dbt operations
on-run-start:
  - "{{ log('Starting dbt run for Gold Layer transformation', info=True) }}"
  
on-run-end:
  - "{{ log('Completed dbt run for Gold Layer transformation', info=True) }}"

# Snapshot configurations
snapshots:
  zoom_gold_layer:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
