name: 'zoom_gold_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_pipeline:
    # Config indicated by + and applies to all files under models/gold/
    gold:
      +materialized: table
      +tags: ["gold"]
      # Audit log model runs first
      go_audit_log:
        +pre-hook: []
        +post-hook: []
      # Dimension models
      dimensional:
        +materialized: table
        +tags: ["dimension", "gold"]
      # Fact models  
      fact:
        +materialized: table
        +tags: ["fact", "gold"]

# Global configurations
vars:
  # DBT project variables
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
# Dependencies and run order
on-run-start:
  - "{{ log('Starting Gold Layer Pipeline Execution', info=True) }}"
  
on-run-end:
  - "{{ log('Gold Layer Pipeline Execution Completed', info=True) }}"
