name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_bronze_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_bronze_pipeline:
    # Config indicated by + and applies to all files under models/bronze/
    bronze:
      +materialized: table
      +tags: ["bronze"]

# Global configurations
vars:
  # DBT project variables
  start_date: '2020-01-01'
  end_date: '2030-12-31'

# Seeds configuration
seeds:
  zoom_bronze_pipeline:
    +quote_columns: false

# Snapshots configuration
snapshots:
  zoom_bronze_pipeline:
    +target_database: "{{ env_var('DBT_DATABASE', 'DB_POC_ZOOM_1') }}"
    +target_schema: "snapshots"

# Macros configuration
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['zoom_bronze_pipeline', 'dbt_utils']
