name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    silver:
      +materialized: table

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  dq_score_threshold: 70
  max_error_rate: 0.05
  enable_audit_logging: true
  audit_retention_days: 365

seeds:
  zoom_silver_pipeline:
    +materialized: table

tests:
  zoom_silver_pipeline:
    +severity: error
    +store_failures: true

docs:
  generate: true
  
log-level: info
partial_parse: true
static_parser: true
use_colors: true
send_anonymous_usage_stats: false
