name: 'silver_layer_project'
version: '1.0.0'
config-version: 2

profile: 'silver_layer_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  silver_layer_project:
    silver:
      +materialized: table
