name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    +materialized: table
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
      si_audit_log:
        +pre_hook: []
        +post_hook: []
      +pre_hook: |
        {% if this.name != 'si_audit_log' %}
          INSERT INTO {{ ref('si_audit_log') }} (
            AUDIT_ID, TABLE_NAME, COLUMN_NAME, RECORD_ID, ERROR_TYPE, 
            ERROR_DESCRIPTION, ORIGINAL_VALUE, AUDIT_TIMESTAMP, 
            OPERATION_TYPE, PROCESSED_BY, SOURCE_SYSTEM
          )
          SELECT 
            UUID_STRING() as AUDIT_ID,
            '{{ this.name }}' as TABLE_NAME,
            'PIPELINE_START' as COLUMN_NAME,
            'N/A' as RECORD_ID,
            'PIPELINE_EXECUTION' as ERROR_TYPE,
            'Pipeline execution started for {{ this.name }}' as ERROR_DESCRIPTION,
            'N/A' as ORIGINAL_VALUE,
            CURRENT_TIMESTAMP() as AUDIT_TIMESTAMP,
            'INSERT' as OPERATION_TYPE,
            'DBT_SILVER_PIPELINE' as PROCESSED_BY,
            'ZOOM_PLATFORM' as SOURCE_SYSTEM;
        {% endif %}
      +post_hook: |
        {% if this.name != 'si_audit_log' %}
          INSERT INTO {{ ref('si_audit_log') }} (
            AUDIT_ID, TABLE_NAME, COLUMN_NAME, RECORD_ID, ERROR_TYPE, 
            ERROR_DESCRIPTION, ORIGINAL_VALUE, AUDIT_TIMESTAMP, 
            OPERATION_TYPE, PROCESSED_BY, SOURCE_SYSTEM
          )
          SELECT 
            UUID_STRING() as AUDIT_ID,
            '{{ this.name }}' as TABLE_NAME,
            'PIPELINE_END' as COLUMN_NAME,
            COUNT(*)::STRING as RECORD_ID,
            'PIPELINE_EXECUTION' as ERROR_TYPE,
            'Pipeline execution completed for {{ this.name }} with ' || COUNT(*) || ' records processed' as ERROR_DESCRIPTION,
            'N/A' as ORIGINAL_VALUE,
            CURRENT_TIMESTAMP() as AUDIT_TIMESTAMP,
            'INSERT' as OPERATION_TYPE,
            'DBT_SILVER_PIPELINE' as PROCESSED_BY,
            'ZOOM_PLATFORM' as SOURCE_SYSTEM
          FROM {{ this }};
        {% endif %}
