name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_bronze_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_bronze_pipeline:
    bronze:
      +materialized: table
      +tags: ["bronze"]
      
vars:
  # DBT Variables for Bronze Layer
  source_schema: "RAW"
  target_schema: "BRONZE"
  audit_enabled: true
  
# Model ordering to ensure audit table is created first
model-dependencies:
  bz_data_audit: []
  bz_users: ["bz_data_audit"]
  bz_meetings: ["bz_data_audit"]
  bz_participants: ["bz_data_audit"]
  bz_feature_usage: ["bz_data_audit"]
  bz_support_tickets: ["bz_data_audit"]
  bz_billing_events: ["bz_data_audit"]
  bz_licenses: ["bz_data_audit"]
