name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/example/
    silver:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'SI_Audit_Log' %}
          INSERT INTO {{ ref('SI_Audit_Log') }} (
            AUDIT_ID, 
            TABLE_NAME, 
            OPERATION_TYPE, 
            AUDIT_TIMESTAMP, 
            PROCESSED_BY
          ) 
          SELECT 
            UUID_STRING(), 
            '{{ this.name }}', 
            'PIPELINE_START', 
            CURRENT_TIMESTAMP(), 
            'DBT_SILVER_PIPELINE'
        {% endif %}
      +post-hook: |
        {% if this.name != 'SI_Audit_Log' %}
          INSERT INTO {{ ref('SI_Audit_Log') }} (
            AUDIT_ID, 
            TABLE_NAME, 
            OPERATION_TYPE, 
            AUDIT_TIMESTAMP, 
            PROCESSED_BY
          ) 
          SELECT 
            UUID_STRING(), 
            '{{ this.name }}', 
            'PIPELINE_END', 
            CURRENT_TIMESTAMP(), 
            'DBT_SILVER_PIPELINE'
        {% endif %}

# Model execution order
model-ordering:
  - "SI_Audit_Log"
  - "SI_Users"
  - "SI_Meetings"
  - "SI_Participants"
  - "SI_Feature_Usage"
  - "SI_Support_Tickets"
  - "SI_Billing_Events"
  - "SI_Licenses"

vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2023-01-01'
  # The `end_date` variable will be accessible in all resources  
  end_date: '2024-12-31'
