name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/silver/
    silver:
      +materialized: table

# Snowflake-specific configurations
vars:
  # Set timezone for timestamp conversions
  default_timezone: 'UTC'
  # Data quality score thresholds
  min_quality_score: 70
  # Audit retention period in days
  audit_retention_days: 90

# Seeds configuration
seeds:
  zoom_silver_pipeline:
    +quote_columns: false

# Snapshots configuration
snapshots:
  zoom_silver_pipeline:
    +target_schema: snapshots
