name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    silver:
      +materialized: table

vars:
  source_database: 'DB_POC_ZOOM'
  source_schema: 'BRONZE'
  target_schema: 'SILVER'
  dq_score_threshold: 70
  max_duration_minutes: 1440
  audit_enabled: true
  error_logging_enabled: true
