name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    +materialized: table
    silver:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'SI_AUDIT_LOG' %}
        INSERT INTO {{ ref('SI_AUDIT_LOG') }} (
          AUDIT_ID, TABLE_NAME, COLUMN_NAME, RECORD_ID, ERROR_TYPE, 
          ERROR_DESCRIPTION, ORIGINAL_VALUE, AUDIT_TIMESTAMP, 
          OPERATION_TYPE, PROCESSED_BY, SOURCE_SYSTEM
        )
        SELECT 
          UUID_STRING() as AUDIT_ID,
          '{{ this.name }}' as TABLE_NAME,
          'PIPELINE_START' as COLUMN_NAME,
          'N/A' as RECORD_ID,
          'PIPELINE_EXECUTION' as ERROR_TYPE,
          'Starting transformation from Bronze to Silver' as ERROR_DESCRIPTION,
          'N/A' as ORIGINAL_VALUE,
          CURRENT_TIMESTAMP() as AUDIT_TIMESTAMP,
          'INSERT' as OPERATION_TYPE,
          'DBT_SILVER_PIPELINE' as PROCESSED_BY,
          'BRONZE_LAYER' as SOURCE_SYSTEM
        WHERE '{{ this.name }}' != 'SI_AUDIT_LOG';
        {% endif %}
      +post-hook: |
        {% if this.name != 'SI_AUDIT_LOG' %}
        INSERT INTO {{ ref('SI_AUDIT_LOG') }} (
          AUDIT_ID, TABLE_NAME, COLUMN_NAME, RECORD_ID, ERROR_TYPE, 
          ERROR_DESCRIPTION, ORIGINAL_VALUE, AUDIT_TIMESTAMP, 
          OPERATION_TYPE, PROCESSED_BY, SOURCE_SYSTEM
        )
        SELECT 
          UUID_STRING() as AUDIT_ID,
          '{{ this.name }}' as TABLE_NAME,
          'PIPELINE_END' as COLUMN_NAME,
          'N/A' as RECORD_ID,
          'PIPELINE_EXECUTION' as ERROR_TYPE,
          'Completed transformation from Bronze to Silver' as ERROR_DESCRIPTION,
          'N/A' as ORIGINAL_VALUE,
          CURRENT_TIMESTAMP() as AUDIT_TIMESTAMP,
          'INSERT' as OPERATION_TYPE,
          'DBT_SILVER_PIPELINE' as PROCESSED_BY,
          'BRONZE_LAYER' as SOURCE_SYSTEM
        WHERE '{{ this.name }}' != 'SI_AUDIT_LOG';
        {% endif %}

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
