name: 'zoom_gold_analytics'
version: '1.0.0'
config-version: 2

profile: 'zoom_gold_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_gold_analytics:
    gold:
      +materialized: table
      dimension:
        +materialized: table
      fact:
        +materialized: table

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
