name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/silver/
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
      # Ensure audit log runs first
      SI_Audit_Log:
        +pre_hook: []
        +post_hook: []
      # All other models depend on audit log
      SI_USERS:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_MEETINGS:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_PARTICIPANTS:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_FEATURE_USAGE:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_SUPPORT_TICKETS:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_BILLING_EVENTS:
        +depends_on:
          - ref('SI_Audit_Log')
      SI_LICENSES:
        +depends_on:
          - ref('SI_Audit_Log')

# Global configurations
vars:
  # Data quality thresholds
  dq_threshold_passed: 90
  dq_threshold_warning: 70
  
  # Timezone settings
  default_timezone: 'UTC'
  source_timezone_est: 'America/New_York'
  
  # Business rule configurations
  valid_plan_types: ['Free', 'Basic', 'Pro', 'Enterprise']
  valid_resolution_statuses: ['Open', 'In Progress', 'Resolved', 'Closed']
  max_meeting_duration_minutes: 1440
  
  # Error handling configurations
  enable_error_logging: true
  enable_audit_logging: true
