name: 'zoom_analytics'
version: '1.0.0'
config-version: 2

profile: 'zoom_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_analytics:
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
      audit_log:
        +pre_hook: []
        +post_hook: []
      +pre_hook: |
        {% if this.name != 'audit_log' %}
          INSERT INTO {{ ref('audit_log') }} (execution_id, pipeline_name, start_time, status, source_tables_processed, target_tables_updated, executed_by, execution_environment, load_date, update_date, source_system)
          VALUES (
            '{{ invocation_id }}',
            '{{ this.name }}',
            CURRENT_TIMESTAMP(),
            'STARTED',
            'BRONZE.BZ_{{ this.name | upper | replace("SI_", "") }}',
            'SILVER.{{ this.name | upper }}',
            'DBT_CLOUD',
            'PRODUCTION',
            CURRENT_DATE(),
            CURRENT_DATE(),
            'ZOOM_PLATFORM'
          )
        {% endif %}
      +post_hook: |
        {% if this.name != 'audit_log' %}
          UPDATE {{ ref('audit_log') }}
          SET 
            end_time = CURRENT_TIMESTAMP(),
            status = 'SUCCESS',
            execution_duration_seconds = DATEDIFF('second', start_time, CURRENT_TIMESTAMP()),
            records_processed = (SELECT COUNT(*) FROM {{ this }}),
            records_inserted = (SELECT COUNT(*) FROM {{ this }}),
            update_date = CURRENT_DATE()
          WHERE execution_id = '{{ invocation_id }}' 
            AND pipeline_name = '{{ this.name }}'
            AND status = 'STARTED'
        {% endif %}
