name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    +materialized: table

vars:
  # Set timezone for timestamp conversions
  default_timezone: 'UTC'
  # Data quality thresholds
  dq_score_threshold: 70
  # Enable/disable specific validations
  enable_email_validation: true
  enable_referential_integrity: true
  enable_format_conversion: true
