name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/example/
    silver:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'si_audit_log' %}
          INSERT INTO {{ ref('si_audit_log') }} (TABLE_NAME, STATUS, AUDIT_TIMESTAMP, LOAD_TIMESTAMP) 
          SELECT '{{ this.name | upper }}', 'PROCESSING_STARTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        {% endif %}
      +post-hook: |
        {% if this.name != 'si_audit_log' %}
          INSERT INTO {{ ref('si_audit_log') }} (TABLE_NAME, STATUS, AUDIT_TIMESTAMP, LOAD_TIMESTAMP) 
          SELECT '{{ this.name | upper }}', 'PROCESSING_COMPLETED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        {% endif %}

# Model execution order - audit log must run first
model-ordering:
  - si_audit_log
  - si_users
  - si_meetings
  - si_participants
  - si_feature_usage
  - si_support_tickets
  - si_billing_events
  - si_licenses

# Snowflake-specific configurations
vars:
  # Data quality thresholds
  min_data_quality_score: 70
  
  # Date format patterns for conversion
  date_formats:
    - 'DD/MM/YYYY'
    - 'MM/DD/YYYY'
    - 'YYYY-MM-DD'
  
  # Timestamp format patterns
  timestamp_formats:
    - 'DD/MM/YYYY HH24:MI:SS'
    - 'MM/DD/YYYY HH24:MI'
    - 'YYYY-MM-DD HH24:MI:SS'

# Test configurations
tests:
  +store_failures: true
  +severity: warn

# Snapshot configurations
snapshots:
  zoom_silver_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_timestamp
