name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
      +pre_hook: |
        {% if this.name != 'SI_Audit_Log' %}
        INSERT INTO {{ ref('SI_Audit_Log') }} (
          EXECUTION_ID, PIPELINE_NAME, EXECUTION_START_TIME, EXECUTION_STATUS, 
          SOURCE_TABLE, TARGET_TABLE, EXECUTED_BY, LOAD_TIMESTAMP
        ) VALUES (
          '{{ invocation_id }}', 
          '{{ this.name }}', 
          CURRENT_TIMESTAMP(), 
          'RUNNING', 
          'BRONZE.BZ_{{ this.name[3:] }}', 
          '{{ this }}', 
          'DBT_PIPELINE', 
          CURRENT_TIMESTAMP()
        )
        {% endif %}
      +post_hook: |
        {% if this.name != 'SI_Audit_Log' %}
        UPDATE {{ ref('SI_Audit_Log') }} 
        SET EXECUTION_END_TIME = CURRENT_TIMESTAMP(),
            EXECUTION_STATUS = 'SUCCESS',
            RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}),
            RECORDS_SUCCESS = (SELECT COUNT(*) FROM {{ this }})
        WHERE EXECUTION_ID = '{{ invocation_id }}' 
        AND TARGET_TABLE = '{{ this }}'
        {% endif %}

vars:
  start_date: '2020-01-01'
  end_date: '2030-12-31'
