name: 'zoom_gold_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_pipeline:
    # Config indicated by + and applies to all files under models/gold/
    gold:
      +materialized: table
      +cluster_by: ["load_date"]
      dimensional:
        +materialized: table
        +cluster_by: ["load_date"]
      fact:
        +materialized: table
        +cluster_by: ["date_key"]

# Global configurations
vars:
  # Data quality threshold
  data_quality_threshold: 0.8
  # Date range for incremental loads
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
# Snapshot configurations
snapshots:
  zoom_gold_pipeline:
    +target_database: "{{ env_var('DBT_DATABASE', 'DB_POC_ZOOM') }}"
    +target_schema: "gold_snapshots"
    +strategy: timestamp
    +updated_at: updated_at

# Seeds configurations
seeds:
  zoom_gold_pipeline:
    +enabled: true
    +quote_columns: false

# Test configurations
tests:
  zoom_gold_pipeline:
    +store_failures: true
    +severity: warn

# Documentation
docs:
  zoom_gold_pipeline:
    +enabled: true
