name: 'zoom_analytics_bronze'
version: '1.0.0'
config-version: 2

profile: 'zoom_analytics_bronze'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_analytics_bronze:
    bronze:
      +materialized: table
      +on_schema_change: "fail"
