name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/silver/
    silver:
      +materialized: table

vars:
  # dbt Cloud environment variables
  start_date: '2020-01-01'
  end_date: '2030-12-31'

# Snapshot configurations
snapshots:
  zoom_silver_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: update_timestamp

# Seeds configurations
seeds:
  zoom_silver_pipeline:
    +schema: seeds

# Test configurations
tests:
  zoom_silver_pipeline:
    +store_failures: true
    +schema: test_failures

# Documentation
docs:
  zoom_silver_pipeline:
    +generate: true
