name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/silver/
    silver:
      +materialized: table
      +on_schema_change: sync_all_columns
      +pre-hook: |
        {% if this.name != 'SI_Audit_Log' %}
          INSERT INTO {{ ref('SI_Audit_Log') }} (
            EXECUTION_ID, 
            PIPELINE_NAME, 
            EXECUTION_START_TIME, 
            EXECUTION_STATUS, 
            SOURCE_TABLE, 
            TARGET_TABLE, 
            EXECUTED_BY, 
            LOAD_TIMESTAMP
          ) 
          SELECT 
            UUID_STRING(), 
            'BRONZE_TO_SILVER_{{ this.name }}', 
            CURRENT_TIMESTAMP(), 
            'STARTED', 
            'BZ_{{ this.name | replace("SI_", "") }}', 
            '{{ this.name }}', 
            'DBT_PIPELINE', 
            CURRENT_TIMESTAMP()
        {% endif %}
      +post-hook: |
        {% if this.name != 'SI_Audit_Log' %}
          INSERT INTO {{ ref('SI_Audit_Log') }} (
            EXECUTION_ID, 
            PIPELINE_NAME, 
            EXECUTION_END_TIME, 
            EXECUTION_STATUS, 
            SOURCE_TABLE, 
            TARGET_TABLE, 
            RECORDS_SUCCESS, 
            EXECUTED_BY, 
            LOAD_TIMESTAMP
          ) 
          SELECT 
            UUID_STRING(), 
            'BRONZE_TO_SILVER_{{ this.name }}', 
            CURRENT_TIMESTAMP(), 
            'COMPLETED', 
            'BZ_{{ this.name | replace("SI_", "") }}', 
            '{{ this.name }}', 
            (SELECT COUNT(*) FROM {{ this }}), 
            'DBT_PIPELINE', 
            CURRENT_TIMESTAMP()
        {% endif %}

# Specify the order of model execution
model-ordering:
  - "SI_Audit_Log"  # Must run first
  - "SI_USERS"
  - "SI_MEETINGS"
  - "SI_PARTICIPANTS"
  - "SI_FEATURE_USAGE"
  - "SI_SUPPORT_TICKETS"
  - "SI_BILLING_EVENTS"
  - "SI_LICENSES"

vars:
  # dbt Cloud environment variables
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
# Specify dbt version
require-dbt-version: [">=1.0.0", "<2.0.0"]
