name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_silver_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_silver_pipeline:
    # Config indicated by + and applies to all files under models/silver/
    silver:
      +materialized: table

# Configure tests
tests:
  +store_failures: true
  +severity: warn

# Configure variables
vars:
  # dbt Cloud environment variables
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
  # Data quality thresholds
  dq_score_threshold: 70
  max_processing_time_minutes: 60
  
  # Business rules
  max_meeting_duration_minutes: 1440
  valid_plan_types: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE']
  valid_resolution_statuses: ['OPEN', 'IN PROGRESS', 'RESOLVED', 'CLOSED']

# Configure on-run-start and on-run-end hooks
on-run-start:
  - "{{ log('Starting Silver Layer Pipeline Execution', info=True) }}"

on-run-end:
  - "{{ log('Silver Layer Pipeline Execution Completed', info=True) }}"
