name: 'zoom_silver_pipeline'
version: '1.0.0'
config-version: 2

profile: 'zoom_silver_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zoom_silver_pipeline:
    silver:
      +materialized: table
      si_pipeline_audit:
        +pre-hook: []
        +post-hook: []
      si_users:
        +depends_on:
          - ref('si_pipeline_audit')
      si_meetings:
        +depends_on:
          - ref('si_pipeline_audit')
          - ref('si_users')
      si_participants:
        +depends_on:
          - ref('si_pipeline_audit')
          - ref('si_meetings')
          - ref('si_users')
      si_feature_usage:
        +depends_on:
          - ref('si_pipeline_audit')
          - ref('si_meetings')
      si_support_tickets:
        +depends_on:
          - ref('si_pipeline_audit')
          - ref('si_users')
      si_billing_events:
        +depends_on:
          - ref('si_pipeline_audit')
          - ref('si_users')
      si_licenses:
        +depends_on:
          - ref('si_pipeline_audit')
          - ref('si_users')

vars:
  # Data quality thresholds
  max_meeting_duration_minutes: 1440
  min_meeting_duration_minutes: 1
  valid_plan_types: ['FREE', 'BASIC', 'PRO', 'BUSINESS', 'ENTERPRISE', 'EDUCATION']
  valid_feature_names: ['SCREEN_SHARE', 'CHAT', 'RECORDING', 'BREAKOUT_ROOMS', 'WHITEBOARD']
  valid_ticket_types: ['TECHNICAL', 'BILLING', 'FEATURE_REQUEST', 'ACCOUNT', 'GENERAL']
  valid_resolution_statuses: ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']
  valid_event_types: ['SUBSCRIPTION', 'UPGRADE', 'DOWNGRADE', 'REFUND', 'CHARGEBACK', 'PAYMENT']
  valid_license_statuses: ['EXPIRED', 'EXPIRING_SOON', 'FUTURE', 'ACTIVE']
  
  # Date range validations
  min_valid_date: '2020-01-01'
  max_future_billing_days: 30
  
  # Default values
  default_currency: 'USD'
  default_plan_type: 'UNKNOWN'
  default_feature_name: 'OTHER'
  default_ticket_type: 'GENERAL'
  default_resolution_status: 'OPEN'
  default_event_type: 'PAYMENT'
