version: 2

sources:
  - name: bronze
    description: Bronze layer tables from Zoom Platform Analytics System
    tables:
      - name: BZ_USERS
        description: Raw user profile and subscription information
      - name: BZ_MEETINGS
        description: Raw meeting information and session details
      - name: BZ_PARTICIPANTS
        description: Raw meeting participants and their session details
      - name: BZ_FEATURE_USAGE
        description: Raw usage of platform features during meetings
      - name: BZ_SUPPORT_TICKETS
        description: Raw customer support requests and resolution tracking
      - name: BZ_BILLING_EVENTS
        description: Raw financial transactions and billing activities
      - name: BZ_LICENSES
        description: Raw license assignments and entitlements

models:
  - name: SI_AUDIT_LOG
    description: Silver layer audit log table for tracking all operations
    columns:
      - name: AUDIT_ID
        description: Unique identifier for each audit record
      - name: TABLE_NAME
        description: Name of the table where operation occurred
      - name: ERROR_TYPE
        description: Type of error or operation
      - name: AUDIT_TIMESTAMP
        description: Timestamp when audit record was created

  - name: SI_USERS
    description: Silver layer table storing cleaned and standardized user information
    columns:
      - name: USER_ID
        description: Unique identifier for each user account
        tests:
          - not_null
          - unique
      - name: EMAIL
        description: Email address of the user (validated and standardized)
        tests:
          - not_null
      - name: PLAN_TYPE
        description: Subscription plan type (standardized values)
        tests:
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE']
      - name: DATA_QUALITY_SCORE
        description: Quality score from validation process (0-100)
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: Status of data validation
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']

  - name: SI_MEETINGS
    description: Silver layer table storing cleaned and standardized meeting information
    columns:
      - name: MEETING_ID
        description: Unique identifier for each meeting
        tests:
          - not_null
          - unique
      - name: HOST_ID
        description: User ID of the meeting host
        tests:
          - not_null
      - name: START_TIME
        description: Meeting start timestamp (standardized timezone)
        tests:
          - not_null
      - name: END_TIME
        description: Meeting end timestamp (standardized timezone)
        tests:
          - not_null
      - name: DURATION_MINUTES
        description: Meeting duration in minutes (validated and calculated)
      - name: DATA_QUALITY_SCORE
        description: Quality score from validation process (0-100)
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: Status of data validation
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']

  - name: SI_PARTICIPANTS
    description: Silver layer table storing cleaned participant session details
    columns:
      - name: PARTICIPANT_ID
        description: Unique identifier for each meeting participant
        tests:
          - not_null
          - unique
      - name: MEETING_ID
        description: Reference to meeting
        tests:
          - not_null
      - name: USER_ID
        description: Reference to user who participated
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: Quality score from validation process (0-100)
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: Status of data validation
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']

  - name: SI_FEATURE_USAGE
    description: Silver layer table storing cleaned platform feature usage
    columns:
      - name: USAGE_ID
        description: Unique identifier for each feature usage record
        tests:
          - not_null
          - unique
      - name: MEETING_ID
        description: Reference to meeting where feature was used
        tests:
          - not_null
      - name: FEATURE_NAME
        description: Name of the feature being tracked (standardized)
        tests:
          - not_null
      - name: USAGE_COUNT
        description: Number of times feature was used (validated)
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: Quality score from validation process (0-100)
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: Status of data validation
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']

  - name: SI_SUPPORT_TICKETS
    description: Silver layer table storing cleaned support requests
    columns:
      - name: TICKET_ID
        description: Unique identifier for each support ticket
        tests:
          - not_null
          - unique
      - name: USER_ID
        description: Reference to user who created the ticket
        tests:
          - not_null
      - name: TICKET_TYPE
        description: Type of support ticket (standardized)
        tests:
          - not_null
      - name: RESOLUTION_STATUS
        description: Current status of ticket resolution (standardized)
        tests:
          - accepted_values:
              values: ['OPEN', 'IN PROGRESS', 'RESOLVED', 'CLOSED']
      - name: DATA_QUALITY_SCORE
        description: Quality score from validation process (0-100)
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: Status of data validation
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']

  - name: SI_BILLING_EVENTS
    description: Silver layer table storing cleaned financial transactions
    columns:
      - name: EVENT_ID
        description: Unique identifier for each billing event
        tests:
          - not_null
          - unique
      - name: USER_ID
        description: Reference to user associated with billing event
        tests:
          - not_null
      - name: EVENT_TYPE
        description: Type of billing event (standardized)
        tests:
          - not_null
      - name: AMOUNT
        description: Monetary amount for the billing event (validated)
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: Quality score from validation process (0-100)
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: Status of data validation
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']

  - name: SI_LICENSES
    description: Silver layer table storing cleaned license assignments
    columns:
      - name: LICENSE_ID
        description: Unique identifier for each license
        tests:
          - not_null
          - unique
      - name: LICENSE_TYPE
        description: Type of license (standardized)
        tests:
          - not_null
      - name: ASSIGNED_TO_USER_ID
        description: User ID to whom license is assigned
        tests:
          - not_null
      - name: START_DATE
        description: License validity start date (standardized format)
      - name: END_DATE
        description: License validity end date (standardized format)
      - name: DATA_QUALITY_SCORE
        description: Quality score from validation process (0-100)
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: Status of data validation
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
