{{ config(
    materialized='table',
    tags=['silver', 'meetings']
) }}

WITH bronze_meetings AS (
    SELECT 
        MEETING_ID,
        HOST_ID,
        MEETING_TOPIC,
        START_TIME,
        END_TIME,
        DURATION_MINUTES,
        LOAD_TIMESTAMP,
        UPDATE_TIMESTAMP,
        SOURCE_SYSTEM
    FROM {{ ref('bz_meetings') }}
),

numeric_cleaning AS (
    SELECT 
        MEETING_ID,
        HOST_ID,
        TRIM(COALESCE(MEETING_TOPIC, 'UNKNOWN')) AS MEETING_TOPIC,
        CASE 
            WHEN START_TIME::STRING LIKE '%EST%' THEN 
                TRY_TO_TIMESTAMP(REPLACE(START_TIME::STRING, ' EST', ''), 'YYYY-MM-DD HH24:MI:SS')
            ELSE START_TIME
        END AS START_TIME,
        CASE 
            WHEN END_TIME::STRING LIKE '%EST%' THEN 
                TRY_TO_TIMESTAMP(REPLACE(END_TIME::STRING, ' EST', ''), 'YYYY-MM-DD HH24:MI:SS')
            ELSE END_TIME
        END AS END_TIME,
        /* Critical P1 DQ Check: Numeric Field Text Unit Cleaning */
        CASE 
            WHEN TRY_TO_NUMBER(REGEXP_REPLACE(DURATION_MINUTES::STRING, '[^0-9.]', '')) IS NOT NULL THEN
                TRY_TO_NUMBER(REGEXP_REPLACE(DURATION_MINUTES::STRING, '[^0-9.]', ''))
            ELSE TRY_TO_NUMBER(DURATION_MINUTES::STRING)
        END AS CLEAN_DURATION_MINUTES,
        DURATION_MINUTES AS ORIGINAL_DURATION_MINUTES,
        LOAD_TIMESTAMP,
        UPDATE_TIMESTAMP,
        SOURCE_SYSTEM
    FROM bronze_meetings
),

data_quality_checks AS (
    SELECT 
        MEETING_ID,
        HOST_ID,
        MEETING_TOPIC,
        START_TIME,
        END_TIME,
        CLEAN_DURATION_MINUTES AS DURATION_MINUTES,
        ORIGINAL_DURATION_MINUTES,
        LOAD_TIMESTAMP,
        UPDATE_TIMESTAMP,
        SOURCE_SYSTEM,
        CASE 
            WHEN MEETING_ID IS NULL THEN 0
            WHEN HOST_ID IS NULL THEN 20
            WHEN START_TIME IS NULL THEN 30
            WHEN END_TIME IS NULL THEN 30
            WHEN CLEAN_DURATION_MINUTES IS NULL THEN 40
            WHEN CLEAN_DURATION_MINUTES < 0 OR CLEAN_DURATION_MINUTES > 1440 THEN 50
            WHEN END_TIME <= START_TIME THEN 60
            ELSE 100
        END AS DATA_QUALITY_SCORE,
        CASE 
            WHEN MEETING_ID IS NULL THEN 'FAILED'
            WHEN HOST_ID IS NULL THEN 'FAILED'
            WHEN START_TIME IS NULL OR END_TIME IS NULL THEN 'FAILED'
            WHEN CLEAN_DURATION_MINUTES IS NULL THEN 'FAILED'
            WHEN CLEAN_DURATION_MINUTES < 0 OR CLEAN_DURATION_MINUTES > 1440 THEN 'WARNING'
            WHEN END_TIME <= START_TIME THEN 'WARNING'
            ELSE 'PASSED'
        END AS VALIDATION_STATUS,
        ROW_NUMBER() OVER (PARTITION BY MEETING_ID ORDER BY LOAD_TIMESTAMP DESC) AS rn
    FROM numeric_cleaning
    WHERE MEETING_ID IS NOT NULL
)

SELECT 
    MEETING_ID,
    HOST_ID,
    MEETING_TOPIC,
    START_TIME,
    END_TIME,
    DURATION_MINUTES,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    DATE(LOAD_TIMESTAMP) AS LOAD_DATE,
    DATE(UPDATE_TIMESTAMP) AS UPDATE_DATE,
    DATA_QUALITY_SCORE,
    VALIDATION_STATUS
FROM data_quality_checks
WHERE rn = 1
