{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_LOG_ID, PROCESS_NAME, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, LOAD_DATE, UPDATE_DATE, SOURCE_SYSTEM) VALUES ('{{ invocation_id }}_license', 'go_dim_license', CURRENT_TIMESTAMP(), 'RUNNING', 'si_licenses', 'go_dim_license', CURRENT_DATE(), CURRENT_DATE(), 'DBT_GOLD_ETL')",
    post_hook="UPDATE {{ ref('go_process_audit') }} SET EXECUTION_END_TIMESTAMP = CURRENT_TIMESTAMP(), EXECUTION_STATUS = 'SUCCESS', RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}), UPDATE_DATE = CURRENT_DATE() WHERE AUDIT_LOG_ID = '{{ invocation_id }}_license'"
) }}

-- License dimension with enhanced attributes

WITH license_data AS (
    SELECT DISTINCT
        LICENSE_TYPE,
        START_DATE,
        END_DATE,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_licenses') }}
    WHERE VALIDATION_STATUS = 'PASSED'
)

SELECT 
    ROW_NUMBER() OVER (ORDER BY LICENSE_TYPE) AS LICENSE_ID,
    INITCAP(TRIM(LICENSE_TYPE)) AS LICENSE_TYPE,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 'Standard'
        WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 'Professional'
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 'Enterprise'
        ELSE 'Other'
    END AS LICENSE_CATEGORY,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 'Tier 1'
        WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 'Tier 2'
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 'Tier 3'
        ELSE 'Tier 0'
    END AS LICENSE_TIER,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 100
        WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 500
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 1000
        ELSE 50
    END AS MAX_PARTICIPANTS,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 5
        WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 100
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 1000
        ELSE 1
    END AS STORAGE_LIMIT_GB,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 40
        WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 100
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 500
        ELSE 0
    END AS RECORDING_LIMIT_HOURS,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
        ELSE FALSE
    END AS ADMIN_FEATURES_INCLUDED,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' OR UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
        ELSE FALSE
    END AS API_ACCESS_INCLUDED,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
        ELSE FALSE
    END AS SSO_SUPPORT_INCLUDED,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 14.99
        WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 19.99
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 39.99
        ELSE 0.00
    END AS MONTHLY_PRICE,
    CASE 
        WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 149.90
        WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 199.90
        WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 399.90
        ELSE 0.00
    END AS ANNUAL_PRICE,
    'Standard license benefits for ' || LICENSE_TYPE AS LICENSE_BENEFITS,
    START_DATE AS EFFECTIVE_START_DATE,
    END_DATE AS EFFECTIVE_END_DATE,
    TRUE AS IS_CURRENT_RECORD,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    SOURCE_SYSTEM
FROM license_data
