{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (PROCESS_ID, PROCESS_NAME, SOURCE_TABLE, TARGET_TABLE, PROCESS_START_TIME, PROCESS_STATUS, CREATED_AT, UPDATED_AT) VALUES (GENERATE_UUID(), 'go_dim_support_category_transformation', 'SI_SUPPORT_TICKETS', 'GO_DIM_SUPPORT_CATEGORY', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())",
    post_hook="UPDATE {{ ref('go_audit_log') }} SET PROCESS_END_TIME = CURRENT_TIMESTAMP(), PROCESS_STATUS = 'COMPLETED', RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}), RECORDS_SUCCESS = (SELECT COUNT(*) FROM {{ this }}), UPDATED_AT = CURRENT_TIMESTAMP() WHERE PROCESS_NAME = 'go_dim_support_category_transformation' AND PROCESS_STATUS = 'STARTED'"
) }}

-- Support Category Dimension Table
WITH support_base AS (
    SELECT DISTINCT 
        TICKET_TYPE
    FROM {{ source('silver', 'si_support_tickets') }}
    WHERE TICKET_TYPE IS NOT NULL
        AND VALIDATION_STATUS = 'PASSED'
),

support_enriched AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY TICKET_TYPE) AS SUPPORT_CATEGORY_ID,
        TICKET_TYPE AS SUPPORT_CATEGORY,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%TECHNICAL%' THEN 'Technical'
            WHEN UPPER(TICKET_TYPE) LIKE '%BILLING%' THEN 'Billing'
            WHEN UPPER(TICKET_TYPE) LIKE '%FEATURE%' THEN 'Feature Request'
            WHEN UPPER(TICKET_TYPE) LIKE '%ACCOUNT%' THEN 'Account'
            WHEN UPPER(TICKET_TYPE) LIKE '%CRITICAL%' THEN 'Critical Issue'
            WHEN UPPER(TICKET_TYPE) LIKE '%HIGH%' THEN 'High Priority'
            WHEN UPPER(TICKET_TYPE) LIKE '%MEDIUM%' THEN 'Medium Priority'
            WHEN UPPER(TICKET_TYPE) LIKE '%LOW%' THEN 'Low Priority'
            ELSE 'General'
        END AS SUPPORT_SUBCATEGORY,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%CRITICAL%' THEN 'Critical'
            WHEN UPPER(TICKET_TYPE) LIKE '%HIGH%' THEN 'High'
            WHEN UPPER(TICKET_TYPE) LIKE '%MEDIUM%' THEN 'Medium'
            ELSE 'Low'
        END AS PRIORITY_LEVEL,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%CRITICAL%' THEN 4
            WHEN UPPER(TICKET_TYPE) LIKE '%HIGH%' THEN 24
            WHEN UPPER(TICKET_TYPE) LIKE '%MEDIUM%' THEN 72
            ELSE 168
        END AS EXPECTED_RESOLUTION_HOURS,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%CRITICAL%' OR UPPER(TICKET_TYPE) LIKE '%HIGH%' THEN TRUE
            ELSE FALSE
        END AS REQUIRES_ESCALATION,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%LOW%' OR UPPER(TICKET_TYPE) LIKE '%MEDIUM%' THEN TRUE
            ELSE FALSE
        END AS SELF_SERVICE_AVAILABLE,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%CRITICAL%' OR UPPER(TICKET_TYPE) LIKE '%TECHNICAL%' THEN TRUE
            ELSE FALSE
        END AS SPECIALIST_REQUIRED,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%CRITICAL%' THEN 'High'
            WHEN UPPER(TICKET_TYPE) LIKE '%HIGH%' OR UPPER(TICKET_TYPE) LIKE '%TECHNICAL%' THEN 'Medium'
            ELSE 'Low'
        END AS CATEGORY_COMPLEXITY,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%CRITICAL%' THEN 'Critical'
            WHEN UPPER(TICKET_TYPE) LIKE '%HIGH%' THEN 'High'
            WHEN UPPER(TICKET_TYPE) LIKE '%MEDIUM%' THEN 'Medium'
            ELSE 'Low'
        END AS CUSTOMER_IMPACT_LEVEL,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%TECHNICAL%' THEN 'Technical Support'
            WHEN UPPER(TICKET_TYPE) LIKE '%BILLING%' THEN 'Account Management'
            ELSE 'Standard Support'
        END AS RESOLUTION_METHOD,
        CASE 
            WHEN UPPER(TICKET_TYPE) LIKE '%TECHNICAL%' THEN 25
            WHEN UPPER(TICKET_TYPE) LIKE '%FEATURE%' THEN 15
            WHEN UPPER(TICKET_TYPE) LIKE '%BILLING%' THEN 10
            ELSE 5
        END AS KNOWLEDGE_BASE_ARTICLES,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        'SI_SUPPORT_TICKETS' AS SOURCE_SYSTEM
    FROM support_base
)

SELECT * FROM support_enriched
