{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (PROCESS_ID, PROCESS_NAME, SOURCE_TABLE, TARGET_TABLE, PROCESS_START_TIME, PROCESS_STATUS, CREATED_AT, UPDATED_AT) VALUES (GENERATE_UUID(), 'go_dim_license_transformation', 'SI_LICENSES', 'GO_DIM_LICENSE', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP())",
    post_hook="UPDATE {{ ref('go_audit_log') }} SET PROCESS_END_TIME = CURRENT_TIMESTAMP(), PROCESS_STATUS = 'COMPLETED', RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}), RECORDS_SUCCESS = (SELECT COUNT(*) FROM {{ this }}), UPDATED_AT = CURRENT_TIMESTAMP() WHERE PROCESS_NAME = 'go_dim_license_transformation' AND PROCESS_STATUS = 'STARTED'"
) }}

-- License Dimension Table
WITH license_base AS (
    SELECT DISTINCT 
        LICENSE_TYPE
    FROM {{ source('silver', 'si_licenses') }}
    WHERE LICENSE_TYPE IS NOT NULL
        AND VALIDATION_STATUS = 'PASSED'
),

license_enriched AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY LICENSE_TYPE) AS LICENSE_ID,
        LICENSE_TYPE,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 'Basic'
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 'Professional'
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 'Business'
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 'Enterprise'
            ELSE 'Other'
        END AS LICENSE_CATEGORY,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 'Tier 1'
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 'Tier 2'
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 'Tier 3'
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 'Tier 4'
            ELSE 'Tier 0'
        END AS LICENSE_TIER,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 100
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 500
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 1000
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 5000
            ELSE 50
        END AS MAX_PARTICIPANTS,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 5
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 25
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 100
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 1000
            ELSE 1
        END AS STORAGE_LIMIT_GB,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 40
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 100
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 500
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 1000
            ELSE 0
        END AS RECORDING_LIMIT_HOURS,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' OR UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS ADMIN_FEATURES_INCLUDED,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS API_ACCESS_INCLUDED,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS SSO_SUPPORT_INCLUDED,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 14.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 19.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 39.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 79.99
            ELSE 0.00
        END AS MONTHLY_PRICE,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 149.90
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 199.90
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 399.90
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 799.90
            ELSE 0.00
        END AS ANNUAL_PRICE,
        12 AS LICENSE_DURATION_MONTHS,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 5
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 10
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 25
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 100
            ELSE 1
        END AS CONCURRENT_MEETINGS_LIMIT,
        '2020-01-01'::DATE AS EFFECTIVE_START_DATE,
        '9999-12-31'::DATE AS EFFECTIVE_END_DATE,
        TRUE AS IS_CURRENT_RECORD,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        'SI_LICENSES' AS SOURCE_SYSTEM
    FROM license_base
)

SELECT * FROM license_enriched
