{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_DIM_USER_LOAD', 'DIMENSION_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_USERS', 'GO_DIM_USER', 'DBT_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_LAYER')",
    post_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_END_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, RECORDS_PROCESSED, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_DIM_USER_LOAD', 'DIMENSION_LOAD', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SUCCESS', 'SI_USERS', 'GO_DIM_USER', (SELECT COUNT(*) FROM {{ this }}), 'DBT_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_LAYER')"
) }}

-- User Dimension Transformation
-- Transforms Silver layer user data into Gold dimension with SCD Type 2 logic

WITH source_users AS (
    SELECT 
        USER_ID,
        USER_NAME,
        EMAIL,
        COMPANY,
        PLAN_TYPE,
        LOAD_TIMESTAMP,
        UPDATE_TIMESTAMP,
        SOURCE_SYSTEM,
        VALIDATION_STATUS
    FROM {{ source('silver', 'si_users') }}
    WHERE VALIDATION_STATUS = 'PASSED'
      AND USER_ID IS NOT NULL
      AND TRIM(USER_ID) != ''
),

user_transformations AS (
    SELECT 
        CONCAT('USR_', USER_ID) AS USER_KEY,
        USER_ID,
        UPPER(TRIM(COALESCE(USER_NAME, 'UNKNOWN'))) AS USER_NAME,
        CASE 
            WHEN EMAIL IS NOT NULL AND CONTAINS(EMAIL, '@') 
            THEN UPPER(SPLIT_PART(EMAIL, '@', 2))
            ELSE 'UNKNOWN_DOMAIN'
        END AS EMAIL_DOMAIN,
        UPPER(TRIM(COALESCE(COMPANY, 'UNKNOWN'))) AS COMPANY,
        CASE 
            WHEN UPPER(PLAN_TYPE) IN ('FREE', 'BASIC') THEN 'BASIC'
            WHEN UPPER(PLAN_TYPE) IN ('PRO', 'PROFESSIONAL') THEN 'PRO'
            WHEN UPPER(PLAN_TYPE) IN ('BUSINESS', 'ENTERPRISE') THEN 'ENTERPRISE'
            ELSE 'OTHER'
        END AS PLAN_TYPE,
        CASE 
            WHEN UPPER(PLAN_TYPE) IN ('FREE') THEN 'FREE_TIER'
            WHEN UPPER(PLAN_TYPE) IN ('BASIC', 'PRO', 'PROFESSIONAL') THEN 'PAID_INDIVIDUAL'
            WHEN UPPER(PLAN_TYPE) IN ('BUSINESS', 'ENTERPRISE') THEN 'PAID_ORGANIZATION'
            ELSE 'UNKNOWN'
        END AS PLAN_CATEGORY,
        DATE(LOAD_TIMESTAMP) AS REGISTRATION_DATE,
        'ACTIVE' AS USER_STATUS,
        'UNKNOWN' AS GEOGRAPHIC_REGION,
        'UNKNOWN' AS INDUSTRY_SECTOR,
        'STANDARD_USER' AS USER_ROLE,
        'INDIVIDUAL' AS ACCOUNT_TYPE,
        'ENGLISH' AS LANGUAGE_PREFERENCE,
        DATE(LOAD_TIMESTAMP) AS EFFECTIVE_START_DATE,
        DATE('9999-12-31') AS EFFECTIVE_END_DATE,
        TRUE AS IS_CURRENT_RECORD,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        SOURCE_SYSTEM,
        ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY LOAD_TIMESTAMP DESC) AS rn
    FROM source_users
)

SELECT 
    USER_KEY,
    USER_ID,
    USER_NAME,
    EMAIL_DOMAIN,
    COMPANY,
    PLAN_TYPE,
    PLAN_CATEGORY,
    REGISTRATION_DATE,
    USER_STATUS,
    GEOGRAPHIC_REGION,
    INDUSTRY_SECTOR,
    USER_ROLE,
    ACCOUNT_TYPE,
    LANGUAGE_PREFERENCE,
    EFFECTIVE_START_DATE,
    EFFECTIVE_END_DATE,
    IS_CURRENT_RECORD,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM user_transformations
WHERE rn = 1
