{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_DIM_MEETING_LOAD', 'DIMENSION_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_MEETINGS', 'GO_DIM_MEETING', 'DBT_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_LAYER')",
    post_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_END_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, RECORDS_PROCESSED, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_DIM_MEETING_LOAD', 'DIMENSION_LOAD', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SUCCESS', 'SI_MEETINGS', 'GO_DIM_MEETING', (SELECT COUNT(*) FROM {{ this }}), 'DBT_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_LAYER')"
) }}

-- Meeting Dimension Transformation
-- Creates meeting dimension based on meeting characteristics

WITH source_meetings AS (
    SELECT 
        MEETING_ID,
        START_TIME,
        DURATION_MINUTES,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_meetings') }}
    WHERE VALIDATION_STATUS = 'PASSED'
      AND DURATION_MINUTES > 0
      AND START_TIME IS NOT NULL
),

meeting_characteristics AS (
    SELECT DISTINCT
        'STANDARD' AS MEETING_TYPE,
        'BUSINESS' AS MEETING_CATEGORY,
        CASE 
            WHEN DURATION_MINUTES <= 15 THEN 'SHORT'
            WHEN DURATION_MINUTES <= 60 THEN 'MEDIUM'
            WHEN DURATION_MINUTES <= 180 THEN 'LONG'
            ELSE 'EXTENDED'
        END AS DURATION_CATEGORY,
        'SMALL' AS PARTICIPANT_SIZE_CATEGORY,
        CASE 
            WHEN HOUR(START_TIME) BETWEEN 6 AND 11 THEN 'MORNING'
            WHEN HOUR(START_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
            WHEN HOUR(START_TIME) BETWEEN 18 AND 22 THEN 'EVENING'
            ELSE 'NIGHT'
        END AS TIME_OF_DAY_CATEGORY,
        DAYNAME(START_TIME) AS DAY_OF_WEEK,
        CASE WHEN DAYOFWEEK(START_TIME) IN (1, 7) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
        FALSE AS IS_RECURRING,
        8.5 AS MEETING_QUALITY_SCORE,
        'SCREEN_SHARE,CHAT' AS TYPICAL_FEATURES_USED,
        'GENERAL_MEETING' AS BUSINESS_PURPOSE,
        SOURCE_SYSTEM
    FROM source_meetings
),

meeting_dimension AS (
    SELECT 
        CONCAT('MTG_', 
               REPLACE(MEETING_TYPE, ' ', '_'), '_',
               REPLACE(MEETING_CATEGORY, ' ', '_'), '_',
               DURATION_CATEGORY, '_',
               PARTICIPANT_SIZE_CATEGORY, '_',
               TIME_OF_DAY_CATEGORY
        ) AS MEETING_KEY,
        MEETING_TYPE,
        MEETING_CATEGORY,
        DURATION_CATEGORY,
        PARTICIPANT_SIZE_CATEGORY,
        TIME_OF_DAY_CATEGORY,
        DAY_OF_WEEK,
        IS_WEEKEND,
        IS_RECURRING,
        MEETING_QUALITY_SCORE,
        TYPICAL_FEATURES_USED,
        BUSINESS_PURPOSE,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        SOURCE_SYSTEM
    FROM meeting_characteristics
)

SELECT 
    MEETING_KEY,
    MEETING_TYPE,
    MEETING_CATEGORY,
    DURATION_CATEGORY,
    PARTICIPANT_SIZE_CATEGORY,
    TIME_OF_DAY_CATEGORY,
    DAY_OF_WEEK,
    IS_WEEKEND,
    IS_RECURRING,
    MEETING_QUALITY_SCORE,
    TYPICAL_FEATURES_USED,
    BUSINESS_PURPOSE,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM meeting_dimension
