{{ config(
    materialized='table',
    tags=['dimension', 'gold'],
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, RECORDS_READ, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, UPDATE_DATE, SOURCE_SYSTEM) SELECT '{{ dbt_utils.generate_surrogate_key([\"'GO_DIM_MEETING_TYPE'\", 'CURRENT_TIMESTAMP()']) }}', 'GO_DIM_MEETING_TYPE_LOAD', 'DIMENSION_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_MEETINGS', 'GO_DIM_MEETING_TYPE', (SELECT COUNT(*) FROM {{ source('silver', 'si_meetings') }}), 'DBT_PIPELINE', 'DBT_SYSTEM', CURRENT_DATE, CURRENT_DATE, 'DBT_GOLD_PIPELINE'",
    post_hook="UPDATE {{ ref('go_audit_log') }} SET EXECUTION_END_TIMESTAMP = CURRENT_TIMESTAMP(), EXECUTION_STATUS = 'SUCCESS', RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}), RECORDS_INSERTED = (SELECT COUNT(*) FROM {{ this }}) WHERE PROCESS_NAME = 'GO_DIM_MEETING_TYPE_LOAD' AND EXECUTION_STATUS = 'RUNNING'"
) }}

-- Gold Dimension: Meeting Type Dimension
-- Meeting types and characteristics for analysis

SELECT 
    ROW_NUMBER() OVER (ORDER BY MEETING_ID) AS MEETING_TYPE_ID,
    'Standard Meeting' AS MEETING_TYPE,
    CASE 
        WHEN DURATION_MINUTES <= 15 THEN 'Quick Sync'
        WHEN DURATION_MINUTES <= 60 THEN 'Standard Meeting'
        WHEN DURATION_MINUTES <= 120 THEN 'Extended Meeting'
        ELSE 'Long Session'
    END AS MEETING_CATEGORY,
    CASE 
        WHEN DURATION_MINUTES <= 15 THEN 'Brief'
        WHEN DURATION_MINUTES <= 60 THEN 'Standard'
        WHEN DURATION_MINUTES <= 120 THEN 'Extended'
        ELSE 'Long'
    END AS DURATION_CATEGORY,
    'Unknown' AS PARTICIPANT_SIZE_CATEGORY,
    CASE 
        WHEN HOUR(START_TIME) BETWEEN 6 AND 11 THEN 'Morning'
        WHEN HOUR(START_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
        WHEN HOUR(START_TIME) BETWEEN 18 AND 21 THEN 'Evening'
        ELSE 'Night'
    END AS TIME_OF_DAY_CATEGORY,
    DAYNAME(START_TIME) AS DAY_OF_WEEK,
    CASE WHEN DAYOFWEEK(START_TIME) IN (1, 7) THEN TRUE ELSE FALSE END AS IS_WEEKEND_MEETING,
    FALSE AS IS_RECURRING_TYPE,
    CASE 
        WHEN DATA_QUALITY_SCORE >= 90 THEN 9.0
        WHEN DATA_QUALITY_SCORE >= 80 THEN 8.0
        WHEN DATA_QUALITY_SCORE >= 70 THEN 7.0
        ELSE 6.0
    END AS MEETING_QUALITY_THRESHOLD,
    'Standard meeting features' AS TYPICAL_FEATURES_USED,
    'Business Meeting' AS BUSINESS_PURPOSE,
    CURRENT_DATE AS LOAD_DATE,
    CURRENT_DATE AS UPDATE_DATE,
    SOURCE_SYSTEM
FROM {{ source('silver', 'si_meetings') }}
WHERE VALIDATION_STATUS = 'PASSED'
