{{ config(
    materialized='table'
) }}

-- Feature Dimension Table
WITH feature_data AS (
    SELECT 'Screen Share' AS FEATURE_NAME
    UNION ALL SELECT 'Video'
    UNION ALL SELECT 'Audio'
    UNION ALL SELECT 'Chat'
    UNION ALL SELECT 'Recording'
    UNION ALL SELECT 'Breakout Rooms'
    UNION ALL SELECT 'Whiteboard'
    UNION ALL SELECT 'File Share'
)
SELECT 
    ROW_NUMBER() OVER (ORDER BY FEATURE_NAME) AS FEATURE_ID,
    FEATURE_NAME,
    CASE 
        WHEN UPPER(FEATURE_NAME) LIKE '%SCREEN%SHARE%' THEN 'Collaboration'
        WHEN UPPER(FEATURE_NAME) LIKE '%RECORD%' THEN 'Recording'
        WHEN UPPER(FEATURE_NAME) LIKE '%CHAT%' THEN 'Communication'
        WHEN UPPER(FEATURE_NAME) LIKE '%BREAKOUT%' THEN 'Meeting Management'
        WHEN UPPER(FEATURE_NAME) LIKE '%WHITEBOARD%' THEN 'Collaboration'
        WHEN UPPER(FEATURE_NAME) LIKE '%VIDEO%' THEN 'Media'
        WHEN UPPER(FEATURE_NAME) LIKE '%AUDIO%' THEN 'Media'
        ELSE 'Other'
    END AS FEATURE_CATEGORY,
    CASE 
        WHEN UPPER(FEATURE_NAME) IN ('SCREEN SHARE', 'CHAT', 'AUDIO', 'VIDEO') THEN 'Core'
        ELSE 'Advanced'
    END AS FEATURE_TYPE,
    CASE 
        WHEN UPPER(FEATURE_NAME) IN ('CHAT', 'AUDIO', 'VIDEO') THEN 'Low'
        WHEN UPPER(FEATURE_NAME) LIKE '%SCREEN%' THEN 'Medium'
        WHEN UPPER(FEATURE_NAME) LIKE '%RECORD%' THEN 'High'
        WHEN UPPER(FEATURE_NAME) LIKE '%BREAKOUT%' THEN 'High'
        ELSE 'Medium'
    END AS FEATURE_COMPLEXITY,
    CASE 
        WHEN UPPER(FEATURE_NAME) NOT IN ('CHAT', 'AUDIO', 'VIDEO') THEN TRUE
        ELSE FALSE
    END AS IS_PREMIUM_FEATURE,
    '2020-01-01'::DATE AS FEATURE_RELEASE_DATE,
    'Active' AS FEATURE_STATUS,
    'High' AS USAGE_FREQUENCY_CATEGORY,
    'Platform feature for enhanced meeting experience' AS FEATURE_DESCRIPTION,
    'All Users' AS TARGET_USER_TYPE,
    'Desktop, Mobile, Web' AS PLATFORM_AVAILABILITY,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    'SYSTEM' AS SOURCE_SYSTEM
FROM feature_data
