{{
  config(
    materialized='table',
    cluster_by=['DATE_KEY', 'USER_KEY'],
    tags=['fact', 'gold'],
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, LOAD_DATE, SOURCE_SYSTEM) SELECT '{{ invocation_id }}', 'FACT_MEETING_ACTIVITY_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_MEETINGS', 'GO_FACT_MEETING_ACTIVITY', CURRENT_DATE(), 'DBT_GOLD_PIPELINE' WHERE '{{ this.name }}' != 'go_audit_log'",
    post_hook="UPDATE {{ ref('go_audit_log') }} SET EXECUTION_END_TIMESTAMP = CURRENT_TIMESTAMP(), EXECUTION_STATUS = 'SUCCESS', RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}), EXECUTION_DURATION_SECONDS = DATEDIFF('second', EXECUTION_START_TIMESTAMP, CURRENT_TIMESTAMP()) WHERE AUDIT_LOG_ID = '{{ invocation_id }}' AND '{{ this.name }}' != 'go_audit_log'"
  )
}}

-- Meeting Activity Fact Table
WITH meeting_base AS (
    SELECT 
        sm.MEETING_ID,
        sm.HOST_ID,
        sm.MEETING_TOPIC,
        sm.START_TIME,
        sm.END_TIME,
        sm.DURATION_MINUTES,
        DATE(sm.START_TIME) AS MEETING_DATE,
        sm.DATA_QUALITY_SCORE,
        sm.SOURCE_SYSTEM
    FROM {{ source('silver', 'si_meetings') }} sm
    WHERE COALESCE(sm.VALIDATION_STATUS, '') = 'PASSED'
      AND sm.MEETING_ID IS NOT NULL
      AND sm.HOST_ID IS NOT NULL
),

participant_metrics AS (
    SELECT 
        sp.MEETING_ID,
        COUNT(DISTINCT sp.USER_ID) AS PARTICIPANT_COUNT,
        SUM(CASE 
            WHEN sp.LEAVE_TIME IS NOT NULL AND sp.JOIN_TIME IS NOT NULL 
            THEN DATEDIFF('minute', sp.JOIN_TIME, sp.LEAVE_TIME)
            ELSE 0 
        END) AS TOTAL_JOIN_TIME_MINUTES,
        AVG(CASE 
            WHEN sp.LEAVE_TIME IS NOT NULL AND sp.JOIN_TIME IS NOT NULL 
            THEN DATEDIFF('minute', sp.JOIN_TIME, sp.LEAVE_TIME)
            ELSE NULL 
        END) AS AVERAGE_PARTICIPATION_MINUTES
    FROM {{ source('silver', 'si_participants') }} sp
    WHERE COALESCE(sp.VALIDATION_STATUS, '') = 'PASSED'
    GROUP BY sp.MEETING_ID
),

feature_metrics AS (
    SELECT 
        sf.MEETING_ID,
        COUNT(DISTINCT sf.FEATURE_NAME) AS FEATURES_USED_COUNT,
        SUM(CASE WHEN UPPER(sf.FEATURE_NAME) LIKE '%SCREEN%SHARE%' THEN COALESCE(sf.USAGE_COUNT, 0) ELSE 0 END) AS SCREEN_SHARE_USAGE_COUNT,
        SUM(CASE WHEN UPPER(sf.FEATURE_NAME) LIKE '%RECORD%' THEN COALESCE(sf.USAGE_COUNT, 0) ELSE 0 END) AS RECORDING_USAGE_COUNT,
        SUM(CASE WHEN UPPER(sf.FEATURE_NAME) LIKE '%CHAT%' THEN COALESCE(sf.USAGE_COUNT, 0) ELSE 0 END) AS CHAT_USAGE_COUNT
    FROM {{ source('silver', 'si_feature_usage') }} sf
    WHERE COALESCE(sf.VALIDATION_STATUS, '') = 'PASSED'
      AND sf.MEETING_ID IS NOT NULL
    GROUP BY sf.MEETING_ID
),

fact_data AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY mb.MEETING_ID) AS MEETING_ACTIVITY_ID,
        -- Foreign Keys
        du.USER_KEY,
        dm.MEETING_KEY,
        dd.DATE_KEY,
        COALESCE(df.FEATURE_KEY, 'UNKNOWN') AS FEATURE_KEY,
        -- Fact Measures
        mb.MEETING_DATE,
        COALESCE(mb.MEETING_TOPIC, 'Unknown Topic') AS MEETING_TOPIC,
        mb.START_TIME,
        mb.END_TIME,
        COALESCE(mb.DURATION_MINUTES, 0) AS DURATION_MINUTES,
        COALESCE(pm.PARTICIPANT_COUNT, 0) AS PARTICIPANT_COUNT,
        COALESCE(pm.TOTAL_JOIN_TIME_MINUTES, 0) AS TOTAL_JOIN_TIME_MINUTES,
        COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) AS AVERAGE_PARTICIPATION_MINUTES,
        COALESCE(fm.FEATURES_USED_COUNT, 0) AS FEATURES_USED_COUNT,
        COALESCE(fm.SCREEN_SHARE_USAGE_COUNT, 0) AS SCREEN_SHARE_USAGE_COUNT,
        COALESCE(fm.RECORDING_USAGE_COUNT, 0) AS RECORDING_USAGE_COUNT,
        COALESCE(fm.CHAT_USAGE_COUNT, 0) AS CHAT_USAGE_COUNT,
        -- Calculated Quality Scores
        CASE 
            WHEN COALESCE(pm.PARTICIPANT_COUNT, 0) >= 5 AND COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) >= (COALESCE(mb.DURATION_MINUTES, 0) * 0.8) THEN 5.0
            WHEN COALESCE(pm.PARTICIPANT_COUNT, 0) >= 3 AND COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) >= (COALESCE(mb.DURATION_MINUTES, 0) * 0.6) THEN 4.0
            WHEN COALESCE(pm.PARTICIPANT_COUNT, 0) >= 2 AND COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) >= (COALESCE(mb.DURATION_MINUTES, 0) * 0.4) THEN 3.0
            WHEN COALESCE(pm.PARTICIPANT_COUNT, 0) >= 1 AND COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) >= (COALESCE(mb.DURATION_MINUTES, 0) * 0.2) THEN 2.0
            ELSE 1.0
        END AS MEETING_QUALITY_SCORE,
        5.0 AS AUDIO_QUALITY_SCORE, -- Default value
        5.0 AS VIDEO_QUALITY_SCORE, -- Default value
        0 AS CONNECTION_ISSUES_COUNT, -- Default value
        CASE 
            WHEN COALESCE(mb.DURATION_MINUTES, 0) >= 60 AND COALESCE(pm.PARTICIPANT_COUNT, 0) >= 3 THEN 5.0
            WHEN COALESCE(mb.DURATION_MINUTES, 0) >= 30 AND COALESCE(pm.PARTICIPANT_COUNT, 0) >= 2 THEN 4.0
            WHEN COALESCE(mb.DURATION_MINUTES, 0) >= 15 THEN 3.0
            ELSE 2.0
        END AS MEETING_SATISFACTION_SCORE,
        COALESCE(pm.PARTICIPANT_COUNT, 0) AS PEAK_CONCURRENT_PARTICIPANTS,
        0 AS LATE_JOINERS_COUNT, -- Default value
        0 AS EARLY_LEAVERS_COUNT, -- Default value
        0 AS BREAKOUT_ROOMS_USED, -- Default value
        0 AS POLLS_CONDUCTED, -- Default value
        0 AS FILE_SHARES_COUNT, -- Default value
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        COALESCE(mb.SOURCE_SYSTEM, 'SILVER_TO_GOLD_ETL') AS SOURCE_SYSTEM
    FROM meeting_base mb
    LEFT JOIN {{ ref('dim_user') }} du ON mb.HOST_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
    LEFT JOIN {{ ref('dim_date') }} dd ON mb.MEETING_DATE = dd.DATE_KEY
    LEFT JOIN {{ ref('dim_meeting') }} dm ON {{ dbt_utils.generate_surrogate_key(['mb.MEETING_ID']) }} = dm.MEETING_KEY
    LEFT JOIN participant_metrics pm ON mb.MEETING_ID = pm.MEETING_ID
    LEFT JOIN feature_metrics fm ON mb.MEETING_ID = fm.MEETING_ID
    LEFT JOIN {{ ref('dim_feature') }} df ON df.FEATURE_NAME = 'General' -- Default feature mapping
    WHERE du.USER_KEY IS NOT NULL
      AND dd.DATE_KEY IS NOT NULL
      AND dm.MEETING_KEY IS NOT NULL
)

SELECT * FROM fact_data
