{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'DAILY_AGG_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_AGG_DAILY_USAGE_SUMMARY_TRANSFORM', CURRENT_TIMESTAMP(), 'MULTIPLE_SOURCES', 'GO_AGG_DAILY_USAGE_SUMMARY', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, RECORDS_PROCESSED, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'DAILY_AGG_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_AGG_DAILY_USAGE_SUMMARY_TRANSFORM', CURRENT_TIMESTAMP(), 'MULTIPLE_SOURCES', 'GO_AGG_DAILY_USAGE_SUMMARY', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, (SELECT COUNT(*) FROM {{ this }}), 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
) }}

-- Gold Layer Daily Usage Summary Aggregated Table
-- Pre-aggregated daily metrics for improved query performance
-- Combines meeting, participant, and feature usage data

WITH daily_meetings AS (
    SELECT 
        DATE(START_TIME) AS SUMMARY_DATE,
        HOST_ID,
        COUNT(DISTINCT MEETING_ID) AS MEETING_COUNT,
        SUM(DURATION_MINUTES) AS TOTAL_MEETING_MINUTES,
        AVG(DURATION_MINUTES) AS AVERAGE_MEETING_DURATION,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_meetings') }}
    WHERE START_TIME IS NOT NULL
      AND DURATION_MINUTES > 0
    GROUP BY DATE(START_TIME), HOST_ID, SOURCE_SYSTEM
),

user_plans AS (
    SELECT 
        USER_ID,
        PLAN_TYPE
    FROM {{ source('silver', 'si_users') }}
),

daily_participants AS (
    SELECT 
        DATE(p.JOIN_TIME) AS SUMMARY_DATE,
        COUNT(DISTINCT p.PARTICIPANT_ID) AS TOTAL_PARTICIPANTS,
        COUNT(DISTINCT p.USER_ID) AS UNIQUE_ATTENDEES
    FROM {{ source('silver', 'si_participants') }} p
    WHERE p.JOIN_TIME IS NOT NULL
    GROUP BY DATE(p.JOIN_TIME)
),

-- Fixed feature aggregation without window functions in GROUP BY
daily_features_base AS (
    SELECT 
        f.USAGE_DATE AS SUMMARY_DATE,
        f.FEATURE_NAME,
        COUNT(f.USAGE_ID) AS FEATURE_COUNT
    FROM {{ source('silver', 'si_feature_usage') }} f
    WHERE f.USAGE_DATE IS NOT NULL
    GROUP BY f.USAGE_DATE, f.FEATURE_NAME
),

daily_features AS (
    SELECT 
        SUMMARY_DATE,
        SUM(FEATURE_COUNT) AS FEATURE_USAGE_EVENTS,
        -- Get most used feature by selecting the one with max count
        MAX(CASE WHEN rn = 1 THEN FEATURE_NAME ELSE NULL END) AS MOST_USED_FEATURE
    FROM (
        SELECT 
            SUMMARY_DATE,
            FEATURE_NAME,
            FEATURE_COUNT,
            ROW_NUMBER() OVER (PARTITION BY SUMMARY_DATE ORDER BY FEATURE_COUNT DESC) AS rn
        FROM daily_features_base
    ) ranked_features
    GROUP BY SUMMARY_DATE
),

daily_aggregation AS (
    SELECT 
        dm.SUMMARY_DATE,
        COALESCE(up.PLAN_TYPE, 'UNKNOWN') AS PLAN_TYPE,
        SUM(dm.MEETING_COUNT) AS TOTAL_MEETINGS,
        COALESCE(dp.TOTAL_PARTICIPANTS, 0) AS TOTAL_PARTICIPANTS,
        SUM(dm.TOTAL_MEETING_MINUTES) AS TOTAL_MEETING_MINUTES,
        AVG(dm.AVERAGE_MEETING_DURATION) AS AVERAGE_MEETING_DURATION,
        COUNT(DISTINCT dm.HOST_ID) AS UNIQUE_HOSTS,
        COALESCE(dp.UNIQUE_ATTENDEES, 0) AS UNIQUE_ATTENDEES,
        COALESCE(df.FEATURE_USAGE_EVENTS, 0) AS FEATURE_USAGE_EVENTS,
        COALESCE(df.MOST_USED_FEATURE, 'NONE') AS MOST_USED_FEATURE,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        dm.SOURCE_SYSTEM
    FROM daily_meetings dm
    LEFT JOIN user_plans up ON dm.HOST_ID = up.USER_ID
    LEFT JOIN daily_participants dp ON dm.SUMMARY_DATE = dp.SUMMARY_DATE
    LEFT JOIN daily_features df ON dm.SUMMARY_DATE = df.SUMMARY_DATE
    GROUP BY 
        dm.SUMMARY_DATE, 
        COALESCE(up.PLAN_TYPE, 'UNKNOWN'),
        dp.TOTAL_PARTICIPANTS,
        dp.UNIQUE_ATTENDEES,
        df.FEATURE_USAGE_EVENTS,
        df.MOST_USED_FEATURE,
        dm.SOURCE_SYSTEM
)

SELECT 
    SUMMARY_DATE::DATE AS SUMMARY_DATE,
    PLAN_TYPE::VARCHAR(16777216) AS PLAN_TYPE,
    TOTAL_MEETINGS::NUMBER(38,0) AS TOTAL_MEETINGS,
    TOTAL_PARTICIPANTS::NUMBER(38,0) AS TOTAL_PARTICIPANTS,
    TOTAL_MEETING_MINUTES::NUMBER(38,0) AS TOTAL_MEETING_MINUTES,
    AVERAGE_MEETING_DURATION::NUMBER(10,2) AS AVERAGE_MEETING_DURATION,
    UNIQUE_HOSTS::NUMBER(38,0) AS UNIQUE_HOSTS,
    UNIQUE_ATTENDEES::NUMBER(38,0) AS UNIQUE_ATTENDEES,
    FEATURE_USAGE_EVENTS::NUMBER(38,0) AS FEATURE_USAGE_EVENTS,
    MOST_USED_FEATURE::VARCHAR(16777216) AS MOST_USED_FEATURE,
    LOAD_DATE::DATE AS LOAD_DATE,
    UPDATE_DATE::DATE AS UPDATE_DATE,
    SOURCE_SYSTEM::VARCHAR(16777216) AS SOURCE_SYSTEM
FROM daily_aggregation
