{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'MONTHLY_REV_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_AGG_MONTHLY_REVENUE_SUMMARY_TRANSFORM', CURRENT_TIMESTAMP(), 'SI_BILLING_EVENTS', 'GO_AGG_MONTHLY_REVENUE_SUMMARY', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, RECORDS_PROCESSED, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'MONTHLY_REV_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_AGG_MONTHLY_REVENUE_SUMMARY_TRANSFORM', CURRENT_TIMESTAMP(), 'SI_BILLING_EVENTS', 'GO_AGG_MONTHLY_REVENUE_SUMMARY', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, (SELECT COUNT(*) FROM {{ this }}), 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
) }}

-- Gold Layer Monthly Revenue Summary Aggregated Table
-- Pre-aggregated monthly revenue metrics for financial reporting
-- Includes MRR, churn, and subscriber metrics

WITH monthly_billing AS (
    SELECT 
        DATE_TRUNC('month', EVENT_DATE) AS SUMMARY_MONTH,
        USER_ID,
        EVENT_TYPE,
        AMOUNT,
        CURRENCY_CODE,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_billing_events') }}
    WHERE EVENT_DATE IS NOT NULL
      AND AMOUNT IS NOT NULL
),

user_plans AS (
    SELECT 
        USER_ID,
        PLAN_TYPE
    FROM {{ source('silver', 'si_users') }}
),

monthly_revenue_metrics AS (
    SELECT 
        mb.SUMMARY_MONTH,
        COALESCE(up.PLAN_TYPE, 'UNKNOWN') AS PLAN_TYPE,
        -- Total Revenue
        SUM(CASE WHEN mb.EVENT_TYPE NOT IN ('REFUND', 'CHARGEBACK') THEN mb.AMOUNT ELSE 0 END) AS TOTAL_REVENUE,
        -- Recurring Revenue
        SUM(CASE WHEN mb.EVENT_TYPE IN ('SUBSCRIPTION', 'RENEWAL') THEN mb.AMOUNT ELSE 0 END) AS RECURRING_REVENUE,
        -- One-time Revenue
        SUM(CASE WHEN mb.EVENT_TYPE IN ('PAYMENT', 'UPGRADE') AND mb.EVENT_TYPE NOT IN ('SUBSCRIPTION', 'RENEWAL') THEN mb.AMOUNT ELSE 0 END) AS ONE_TIME_REVENUE,
        -- Refunds
        SUM(CASE WHEN mb.EVENT_TYPE IN ('REFUND', 'CHARGEBACK') THEN mb.AMOUNT ELSE 0 END) AS REFUNDS_AMOUNT,
        -- Active Subscribers (users with any billing event)
        COUNT(DISTINCT mb.USER_ID) AS ACTIVE_SUBSCRIBERS,
        -- New Subscribers (users with subscription events)
        COUNT(DISTINCT CASE WHEN mb.EVENT_TYPE = 'SUBSCRIPTION' THEN mb.USER_ID END) AS NEW_SUBSCRIBERS,
        -- Churned Subscribers (users with only refund/chargeback events)
        COUNT(DISTINCT CASE WHEN mb.EVENT_TYPE IN ('REFUND', 'CHARGEBACK') THEN mb.USER_ID END) AS CHURNED_SUBSCRIBERS,
        mb.SOURCE_SYSTEM
    FROM monthly_billing mb
    LEFT JOIN user_plans up ON mb.USER_ID = up.USER_ID
    GROUP BY 
        mb.SUMMARY_MONTH, 
        COALESCE(up.PLAN_TYPE, 'UNKNOWN'),
        mb.SOURCE_SYSTEM
),

final_metrics AS (
    SELECT 
        SUMMARY_MONTH,
        PLAN_TYPE,
        TOTAL_REVENUE,
        RECURRING_REVENUE,
        ONE_TIME_REVENUE,
        REFUNDS_AMOUNT,
        -- Net Revenue
        (TOTAL_REVENUE - REFUNDS_AMOUNT) AS NET_REVENUE,
        ACTIVE_SUBSCRIBERS,
        NEW_SUBSCRIBERS,
        CHURNED_SUBSCRIBERS,
        -- Average Revenue Per User
        CASE 
            WHEN ACTIVE_SUBSCRIBERS > 0 
            THEN (TOTAL_REVENUE - REFUNDS_AMOUNT) / ACTIVE_SUBSCRIBERS 
            ELSE 0 
        END AS AVERAGE_REVENUE_PER_USER,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        SOURCE_SYSTEM
    FROM monthly_revenue_metrics
)

SELECT 
    SUMMARY_MONTH::DATE AS SUMMARY_MONTH,
    PLAN_TYPE::VARCHAR(16777216) AS PLAN_TYPE,
    TOTAL_REVENUE::NUMBER(12,2) AS TOTAL_REVENUE,
    RECURRING_REVENUE::NUMBER(12,2) AS RECURRING_REVENUE,
    ONE_TIME_REVENUE::NUMBER(12,2) AS ONE_TIME_REVENUE,
    REFUNDS_AMOUNT::NUMBER(12,2) AS REFUNDS_AMOUNT,
    NET_REVENUE::NUMBER(12,2) AS NET_REVENUE,
    ACTIVE_SUBSCRIBERS::NUMBER(38,0) AS ACTIVE_SUBSCRIBERS,
    NEW_SUBSCRIBERS::NUMBER(38,0) AS NEW_SUBSCRIBERS,
    CHURNED_SUBSCRIBERS::NUMBER(38,0) AS CHURNED_SUBSCRIBERS,
    AVERAGE_REVENUE_PER_USER::NUMBER(10,2) AS AVERAGE_REVENUE_PER_USER,
    LOAD_DATE::DATE AS LOAD_DATE,
    UPDATE_DATE::DATE AS UPDATE_DATE,
    SOURCE_SYSTEM::VARCHAR(16777216) AS SOURCE_SYSTEM
FROM final_metrics
