{{ config(
    materialized='table'
) }}

-- Revenue Events Fact Table
WITH billing_base AS (
    SELECT 
        be.EVENT_ID,
        be.USER_ID,
        be.EVENT_TYPE,
        be.TRANSACTION_AMOUNT,
        be.TRANSACTION_DATE,
        be.PAYMENT_METHOD,
        be.CURRENCY_CODE,
        be.INVOICE_NUMBER,
        be.TRANSACTION_STATUS,
        COALESCE(be.DATA_QUALITY_SCORE, 1.0) AS DATA_QUALITY_SCORE,
        be.SOURCE_SYSTEM
    FROM DB_POC_ZOOM.SILVER.SI_BILLING_EVENTS be
    WHERE COALESCE(be.DATA_QUALITY_SCORE, 1.0) >= 0.8
      AND COALESCE(be.TRANSACTION_STATUS, 'Unknown') = 'Completed'
),

user_info AS (
    SELECT 
        USER_ID,
        PLAN_TYPE
    FROM DB_POC_ZOOM.SILVER.SI_USERS
    WHERE COALESCE(DATA_QUALITY_SCORE, 1.0) >= 0.8
),

license_info AS (
    SELECT 
        ASSIGNED_TO_USER_ID,
        LICENSE_TYPE
    FROM DB_POC_ZOOM.SILVER.SI_LICENSES
    WHERE COALESCE(DATA_QUALITY_SCORE, 1.0) >= 0.8
),

fact_revenue_events AS (
    SELECT 
        CONCAT('FACT_REV_', be.EVENT_ID, '_', TO_CHAR(be.TRANSACTION_DATE, 'YYYYMMDD')) AS FACT_REVENUE_EVENTS_ID,
        be.TRANSACTION_DATE AS DATE_KEY,
        be.USER_ID AS USER_KEY,
        COALESCE(l.LICENSE_TYPE, 'UNKNOWN') AS LICENSE_KEY,
        be.TRANSACTION_DATE,
        CASE 
            WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'USD' THEN COALESCE(be.TRANSACTION_AMOUNT, 0)
            WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'EUR' THEN COALESCE(be.TRANSACTION_AMOUNT, 0) * 1.1
            WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'GBP' THEN COALESCE(be.TRANSACTION_AMOUNT, 0) * 1.25
            ELSE COALESCE(be.TRANSACTION_AMOUNT, 0)
        END AS TRANSACTION_AMOUNT_USD,
        COALESCE(be.TRANSACTION_AMOUNT, 0) AS ORIGINAL_AMOUNT,
        COALESCE(be.CURRENCY_CODE, 'USD') AS CURRENCY_CODE,
        COALESCE(be.EVENT_TYPE, 'Unknown') AS EVENT_TYPE,
        COALESCE(be.PAYMENT_METHOD, 'Unknown') AS PAYMENT_METHOD,
        COALESCE(l.LICENSE_TYPE, 'UNKNOWN') AS LICENSE_TYPE,
        COALESCE(u.PLAN_TYPE, 'Unknown') AS CUSTOMER_PLAN_TYPE,
        COALESCE(be.TRANSACTION_STATUS, 'Unknown') AS TRANSACTION_STATUS,
        CASE 
            WHEN COALESCE(be.EVENT_TYPE, 'Unknown') IN ('Subscription', 'Upgrade') THEN 
                CASE 
                    WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'USD' THEN COALESCE(be.TRANSACTION_AMOUNT, 0)
                    WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'EUR' THEN COALESCE(be.TRANSACTION_AMOUNT, 0) * 1.1
                    WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'GBP' THEN COALESCE(be.TRANSACTION_AMOUNT, 0) * 1.25
                    ELSE COALESCE(be.TRANSACTION_AMOUNT, 0)
                END
            WHEN COALESCE(be.EVENT_TYPE, 'Unknown') IN ('Downgrade', 'Refund') THEN 
                -1 * CASE 
                    WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'USD' THEN COALESCE(be.TRANSACTION_AMOUNT, 0)
                    WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'EUR' THEN COALESCE(be.TRANSACTION_AMOUNT, 0) * 1.1
                    WHEN COALESCE(be.CURRENCY_CODE, 'USD') = 'GBP' THEN COALESCE(be.TRANSACTION_AMOUNT, 0) * 1.25
                    ELSE COALESCE(be.TRANSACTION_AMOUNT, 0)
                END
            ELSE 0
        END AS MRR_IMPACT,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        'SILVER_LAYER' AS SOURCE_SYSTEM
    FROM billing_base be
    LEFT JOIN user_info u ON be.USER_ID = u.USER_ID
    LEFT JOIN license_info l ON be.USER_ID = l.ASSIGNED_TO_USER_ID
)

SELECT * FROM fact_revenue_events
