{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_FACT_REVENUE_ACTIVITY_LOAD', 'FACT_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_BILLING_EVENTS', 'GO_FACT_REVENUE_ACTIVITY', 'DBT_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_LAYER')",
    post_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_END_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, RECORDS_PROCESSED, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_FACT_REVENUE_ACTIVITY_LOAD', 'FACT_LOAD', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SUCCESS', 'SI_BILLING_EVENTS', 'GO_FACT_REVENUE_ACTIVITY', (SELECT COUNT(*) FROM {{ this }}), 'DBT_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_LAYER')"
) }}

-- Revenue Activity Fact Table
-- Captures billing events and revenue metrics

WITH billing_base AS (
    SELECT 
        be.EVENT_ID,
        be.USER_ID,
        be.EVENT_TYPE,
        be.AMOUNT,
        be.EVENT_DATE,
        be.SOURCE_SYSTEM
    FROM {{ source('silver', 'si_billing_events') }} be
    WHERE be.VALIDATION_STATUS = 'PASSED'
      AND be.USER_ID IS NOT NULL
      AND be.EVENT_ID IS NOT NULL
      AND be.EVENT_DATE IS NOT NULL
      AND be.AMOUNT IS NOT NULL
),

user_licenses AS (
    SELECT 
        sl.ASSIGNED_TO_USER_ID AS USER_ID,
        sl.LICENSE_TYPE,
        ROW_NUMBER() OVER (PARTITION BY sl.ASSIGNED_TO_USER_ID ORDER BY sl.START_DATE DESC) AS rn
    FROM {{ source('silver', 'si_licenses') }} sl
    WHERE sl.VALIDATION_STATUS = 'PASSED'
),

revenue_facts AS (
    SELECT 
        du.USER_KEY,
        COALESCE(dl.LICENSE_KEY, 'NO_LICENSE') AS LICENSE_KEY,
        dd.DATE_KEY,
        bb.EVENT_DATE AS TRANSACTION_DATE,
        TRIM(UPPER(bb.EVENT_TYPE)) AS EVENT_TYPE,
        ROUND(bb.AMOUNT, 2) AS AMOUNT,
        'USD' AS CURRENCY,
        'CREDIT_CARD' AS PAYMENT_METHOD,
        CASE 
            WHEN UPPER(bb.EVENT_TYPE) IN ('SUBSCRIPTION', 'RENEWAL', 'UPGRADE') 
            THEN bb.AMOUNT 
            ELSE 0 
        END AS SUBSCRIPTION_REVENUE_AMOUNT,
        CASE 
            WHEN UPPER(bb.EVENT_TYPE) IN ('ONE-TIME PURCHASE', 'SETUP FEE') 
            THEN bb.AMOUNT 
            ELSE 0 
        END AS ONE_TIME_REVENUE_AMOUNT,
        CASE 
            WHEN UPPER(bb.EVENT_TYPE) = 'REFUND' 
            THEN bb.AMOUNT 
            ELSE 0 
        END AS REFUND_AMOUNT,
        bb.AMOUNT * 0.08 AS TAX_AMOUNT,
        CASE 
            WHEN UPPER(bb.EVENT_TYPE) = 'REFUND' 
            THEN -bb.AMOUNT 
            ELSE bb.AMOUNT 
        END AS NET_REVENUE_AMOUNT,
        0 AS DISCOUNT_AMOUNT,
        1.0 AS EXCHANGE_RATE,
        bb.AMOUNT AS USD_AMOUNT,
        CASE 
            WHEN UPPER(bb.EVENT_TYPE) IN ('SUBSCRIPTION', 'RENEWAL') 
            THEN 12 
            ELSE 1 
        END AS SUBSCRIPTION_PERIOD_MONTHS,
        1 AS LICENSE_QUANTITY,
        0 AS PRORATION_AMOUNT,
        bb.AMOUNT * 0.05 AS COMMISSION_AMOUNT,
        CASE 
            WHEN UPPER(bb.EVENT_TYPE) IN ('SUBSCRIPTION', 'RENEWAL', 'UPGRADE') 
            THEN bb.AMOUNT / 12 
            ELSE 0 
        END AS MRR_IMPACT,
        CASE 
            WHEN UPPER(bb.EVENT_TYPE) IN ('SUBSCRIPTION', 'RENEWAL', 'UPGRADE') 
            THEN bb.AMOUNT 
            ELSE 0 
        END AS ARR_IMPACT,
        bb.AMOUNT * 24 AS CUSTOMER_LIFETIME_VALUE,
        2.5 AS CHURN_RISK_SCORE,
        'COMPLETED' AS PAYMENT_STATUS,
        CASE 
            WHEN UPPER(bb.EVENT_TYPE) = 'REFUND' 
            THEN 'CUSTOMER_REQUEST' 
            ELSE NULL 
        END AS REFUND_REASON,
        'ONLINE' AS SALES_CHANNEL,
        NULL AS PROMOTION_CODE,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        bb.SOURCE_SYSTEM,
        ROW_NUMBER() OVER (
            PARTITION BY du.USER_KEY, COALESCE(dl.LICENSE_KEY, 'NO_LICENSE'), dd.DATE_KEY, bb.EVENT_DATE, bb.EVENT_TYPE
            ORDER BY bb.EVENT_ID DESC
        ) AS rn
    FROM billing_base bb
    INNER JOIN {{ ref('go_dim_user') }} du ON bb.USER_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
    INNER JOIN {{ ref('go_dim_date') }} dd ON bb.EVENT_DATE = dd.DATE_KEY
    LEFT JOIN user_licenses ul ON bb.USER_ID = ul.USER_ID AND ul.rn = 1
    LEFT JOIN {{ ref('go_dim_license') }} dl ON ul.LICENSE_TYPE = dl.LICENSE_TYPE AND dl.IS_CURRENT_RECORD = TRUE
)

SELECT 
    USER_KEY,
    LICENSE_KEY,
    DATE_KEY,
    TRANSACTION_DATE,
    EVENT_TYPE,
    AMOUNT,
    CURRENCY,
    PAYMENT_METHOD,
    SUBSCRIPTION_REVENUE_AMOUNT,
    ONE_TIME_REVENUE_AMOUNT,
    REFUND_AMOUNT,
    TAX_AMOUNT,
    NET_REVENUE_AMOUNT,
    DISCOUNT_AMOUNT,
    EXCHANGE_RATE,
    USD_AMOUNT,
    SUBSCRIPTION_PERIOD_MONTHS,
    LICENSE_QUANTITY,
    PRORATION_AMOUNT,
    COMMISSION_AMOUNT,
    MRR_IMPACT,
    ARR_IMPACT,
    CUSTOMER_LIFETIME_VALUE,
    CHURN_RISK_SCORE,
    PAYMENT_STATUS,
    REFUND_REASON,
    SALES_CHANNEL,
    PROMOTION_CODE,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM revenue_facts
WHERE rn = 1
