{{ config(materialized='table') }}

-- Revenue Events Fact Table
SELECT 
    ROW_NUMBER() OVER (ORDER BY be.EVENT_ID) AS REVENUE_EVENT_ID,
    be.EVENT_DATE AS TRANSACTION_DATE,
    CURRENT_TIMESTAMP() AS TRANSACTION_TIMESTAMP,
    be.EVENT_TYPE,
    CASE 
        WHEN UPPER(be.EVENT_TYPE) LIKE '%SUBSCRIPTION%' THEN 'Recurring'
        WHEN UPPER(be.EVENT_TYPE) LIKE '%UPGRADE%' THEN 'Expansion'
        WHEN UPPER(be.EVENT_TYPE) LIKE '%ADDON%' THEN 'Add-on'
        ELSE 'One-time'
    END AS REVENUE_TYPE,
    be.AMOUNT AS GROSS_AMOUNT,
    be.AMOUNT * 0.08 AS TAX_AMOUNT,
    CASE 
        WHEN u.PLAN_TYPE = 'Enterprise' THEN be.AMOUNT * 0.15
        WHEN u.PLAN_TYPE = 'Pro' THEN be.AMOUNT * 0.10
        ELSE 0
    END AS DISCOUNT_AMOUNT,
    be.AMOUNT - (be.AMOUNT * 0.08) - 
    CASE 
        WHEN u.PLAN_TYPE = 'Enterprise' THEN be.AMOUNT * 0.15
        WHEN u.PLAN_TYPE = 'Pro' THEN be.AMOUNT * 0.10
        ELSE 0
    END AS NET_AMOUNT,
    'USD' AS CURRENCY_CODE,
    1.0 AS EXCHANGE_RATE,
    be.AMOUNT AS USD_AMOUNT,
    CASE 
        WHEN be.AMOUNT > 1000 THEN 'Bank Transfer'
        WHEN be.AMOUNT > 100 THEN 'Credit Card'
        ELSE 'PayPal'
    END AS PAYMENT_METHOD,
    'Completed' AS PAYMENT_STATUS,
    12 AS SUBSCRIPTION_PERIOD_MONTHS,
    CASE 
        WHEN UPPER(be.EVENT_TYPE) LIKE '%SUBSCRIPTION%' THEN TRUE
        ELSE FALSE
    END AS IS_RECURRING_REVENUE,
    CASE 
        WHEN u.PLAN_TYPE = 'Enterprise' THEN be.AMOUNT * 24
        WHEN u.PLAN_TYPE = 'Pro' THEN be.AMOUNT * 18
        WHEN u.PLAN_TYPE = 'Basic' THEN be.AMOUNT * 12
        ELSE be.AMOUNT * 6
    END AS CUSTOMER_LIFETIME_VALUE,
    CASE 
        WHEN UPPER(be.EVENT_TYPE) LIKE '%SUBSCRIPTION%' THEN be.AMOUNT
        ELSE 0
    END AS MRR_IMPACT,
    CASE 
        WHEN UPPER(be.EVENT_TYPE) LIKE '%SUBSCRIPTION%' THEN be.AMOUNT * 12
        ELSE 0
    END AS ARR_IMPACT,
    be.AMOUNT * 0.05 AS COMMISSION_AMOUNT,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    be.SOURCE_SYSTEM
FROM SILVER.SI_BILLING_EVENTS be
LEFT JOIN SILVER.SI_USERS u ON be.USER_ID = u.USER_ID
WHERE be.VALIDATION_STATUS = 'PASSED'
    AND be.DATA_QUALITY_SCORE >= 80
    AND be.AMOUNT > 0
