{{ config(
    materialized='table'
) }}

-- Revenue Events Fact Table
-- Fact table capturing detailed billing events and revenue metrics

WITH billing_base AS (
    SELECT 
        be.EVENT_ID,
        be.USER_ID,
        be.EVENT_TYPE,
        COALESCE(be.AMOUNT, 0) AS AMOUNT,
        COALESCE(be.EVENT_DATE, CURRENT_DATE()) AS EVENT_DATE,
        be.SOURCE_SYSTEM
    FROM {{ source('silver', 'si_billing_events') }} be
    WHERE be.VALIDATION_STATUS = 'PASSED'
      AND be.EVENT_ID IS NOT NULL
)

SELECT 
    ROW_NUMBER() OVER (ORDER BY bb.EVENT_ID) AS REVENUE_EVENT_ID,
    COALESCE(dd.DATE_ID, 1) AS DATE_ID,
    1 AS LICENSE_ID, -- Default license
    COALESCE(du.USER_DIM_ID, 1) AS USER_DIM_ID,
    bb.EVENT_ID AS BILLING_EVENT_ID,
    bb.EVENT_DATE AS TRANSACTION_DATE,
    bb.EVENT_DATE::TIMESTAMP_NTZ AS TRANSACTION_TIMESTAMP,
    COALESCE(bb.EVENT_TYPE, 'Unknown') AS EVENT_TYPE,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) IN ('SUBSCRIPTION', 'RENEWAL', 'UPGRADE') THEN 'Recurring'
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) IN ('ONE-TIME PURCHASE', 'SETUP FEE') THEN 'One-time'
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) = 'REFUND' THEN 'Refund'
        ELSE 'Other'
    END AS REVENUE_TYPE,
    bb.AMOUNT AS GROSS_AMOUNT,
    bb.AMOUNT * 0.08 AS TAX_AMOUNT,
    0.00 AS DISCOUNT_AMOUNT,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) = 'REFUND' THEN -bb.AMOUNT
        ELSE bb.AMOUNT
    END AS NET_AMOUNT,
    'USD' AS CURRENCY_CODE,
    1.0 AS EXCHANGE_RATE,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) = 'REFUND' THEN -bb.AMOUNT
        ELSE bb.AMOUNT
    END AS USD_AMOUNT,
    'Credit Card' AS PAYMENT_METHOD,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) IN ('SUBSCRIPTION', 'RENEWAL') THEN 12
        ELSE 0
    END AS SUBSCRIPTION_PERIOD_MONTHS,
    1 AS LICENSE_QUANTITY,
    0.00 AS PRORATION_AMOUNT,
    bb.AMOUNT * 0.05 AS COMMISSION_AMOUNT,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) IN ('SUBSCRIPTION', 'RENEWAL', 'UPGRADE') THEN bb.AMOUNT / 12
        ELSE 0
    END AS MRR_IMPACT,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) IN ('SUBSCRIPTION', 'RENEWAL', 'UPGRADE') THEN bb.AMOUNT
        ELSE 0
    END AS ARR_IMPACT,
    bb.AMOUNT * 5 AS CUSTOMER_LIFETIME_VALUE,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) = 'REFUND' THEN 3.5
        WHEN bb.AMOUNT < 0 THEN 2.5
        ELSE 1.0
    END AS CHURN_RISK_SCORE,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) = 'REFUND' THEN 'Refunded'
        WHEN bb.AMOUNT > 0 THEN 'Successful'
        WHEN bb.AMOUNT = 0 THEN 'Pending'
        ELSE 'Failed'
    END AS PAYMENT_STATUS,
    CASE 
        WHEN UPPER(COALESCE(bb.EVENT_TYPE, '')) = 'REFUND' THEN 'Customer Request'
        ELSE NULL
    END AS REFUND_REASON,
    'Online' AS SALES_CHANNEL,
    NULL AS PROMOTION_CODE,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    bb.SOURCE_SYSTEM
FROM billing_base bb
LEFT JOIN {{ ref('go_dim_date') }} dd ON bb.EVENT_DATE = dd.DATE_VALUE
LEFT JOIN {{ ref('go_dim_user') }} du ON bb.USER_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
