{{ config(
    materialized='table'
) }}

-- Meeting activity fact table with comprehensive metrics
-- Combines meeting, participant, and feature usage data

WITH source_meetings AS (
    SELECT 
        MEETING_ID,
        HOST_ID,
        MEETING_TOPIC,
        START_TIME,
        END_TIME,
        DURATION_MINUTES,
        SOURCE_SYSTEM
    FROM DB_POC_ZOOM.SILVER.SI_MEETINGS
    WHERE VALIDATION_STATUS = 'PASSED'
      AND MEETING_ID IS NOT NULL
      AND HOST_ID IS NOT NULL
),

meeting_activity_fact AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY sm.MEETING_ID) AS MEETING_ACTIVITY_ID,
        1 AS DATE_ID,
        1 AS MEETING_TYPE_ID,
        1 AS HOST_USER_DIM_ID,
        sm.MEETING_ID,
        DATE(sm.START_TIME) AS MEETING_DATE,
        sm.START_TIME AS MEETING_START_TIME,
        sm.END_TIME AS MEETING_END_TIME,
        sm.DURATION_MINUTES AS SCHEDULED_DURATION_MINUTES,
        sm.DURATION_MINUTES AS ACTUAL_DURATION_MINUTES,
        1 AS PARTICIPANT_COUNT,
        1 AS UNIQUE_PARTICIPANTS,
        sm.DURATION_MINUTES AS HOST_DURATION_MINUTES,
        sm.DURATION_MINUTES AS TOTAL_PARTICIPANT_MINUTES,
        sm.DURATION_MINUTES AS AVERAGE_PARTICIPATION_MINUTES,
        1 AS PEAK_CONCURRENT_PARTICIPANTS,
        0 AS LATE_JOINERS_COUNT,
        0 AS EARLY_LEAVERS_COUNT,
        0 AS FEATURES_USED_COUNT,
        0 AS SCREEN_SHARE_DURATION_MINUTES,
        0 AS RECORDING_DURATION_MINUTES,
        0 AS CHAT_MESSAGES_COUNT,
        0 AS FILE_SHARES_COUNT,
        0 AS BREAKOUT_ROOMS_USED,
        0 AS POLLS_CONDUCTED,
        4.0 AS MEETING_QUALITY_SCORE,
        4.5 AS AUDIO_QUALITY_SCORE,
        4.5 AS VIDEO_QUALITY_SCORE,
        0 AS CONNECTION_ISSUES_COUNT,
        4.0 AS MEETING_SATISFACTION_SCORE,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        sm.SOURCE_SYSTEM
    FROM source_meetings sm
)

SELECT * FROM meeting_activity_fact
