{{ config(
    materialized='table'
) }}

-- Feature Usage Fact Table
-- Captures detailed feature usage metrics and patterns

WITH source_features AS (
    SELECT 
        COALESCE(USAGE_ID, 'UNKNOWN_USAGE') AS USAGE_ID,
        COALESCE(MEETING_ID, 'UNKNOWN_MEETING') AS MEETING_ID,
        COALESCE(FEATURE_NAME, 'Unknown Feature') AS FEATURE_NAME,
        COALESCE(USAGE_COUNT, 0) AS USAGE_COUNT,
        COALESCE(USAGE_DATE, CURRENT_DATE()) AS USAGE_DATE,
        COALESCE(SOURCE_SYSTEM, 'UNKNOWN') AS SOURCE_SYSTEM
    FROM {{ source('silver', 'si_feature_usage') }}
    WHERE COALESCE(VALIDATION_STATUS, 'PASSED') = 'PASSED'
),

source_meetings AS (
    SELECT 
        COALESCE(MEETING_ID, 'UNKNOWN_MEETING') AS MEETING_ID,
        COALESCE(HOST_ID, 'UNKNOWN_HOST') AS HOST_ID,
        COALESCE(DURATION_MINUTES, 30) AS DURATION_MINUTES
    FROM {{ source('silver', 'si_meetings') }}
    WHERE COALESCE(VALIDATION_STATUS, 'PASSED') = 'PASSED'
),

feature_usage_transformations AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY fu.USAGE_ID) AS FEATURE_USAGE_ID,
        -- Foreign Key Columns for BI Integration
        COALESCE(dd.DATE_KEY, CURRENT_DATE()) AS DATE_KEY,
        COALESCE(df.FEATURE_KEY, 'UNKNOWN_FEATURE') AS FEATURE_KEY,
        COALESCE(du.USER_KEY, 'UNKNOWN_USER') AS USER_KEY,
        COALESCE(dm.MEETING_KEY, fu.MEETING_ID) AS MEETING_KEY,
        -- Fact Measures
        fu.USAGE_DATE,
        fu.USAGE_DATE::TIMESTAMP_NTZ AS USAGE_TIMESTAMP,
        fu.FEATURE_NAME,
        fu.USAGE_COUNT,
        sm.DURATION_MINUTES AS USAGE_DURATION_MINUTES,
        sm.DURATION_MINUTES AS SESSION_DURATION_MINUTES,
        CASE 
            WHEN fu.USAGE_COUNT >= 10 THEN 5.0
            WHEN fu.USAGE_COUNT >= 5 THEN 4.0
            WHEN fu.USAGE_COUNT >= 3 THEN 3.0
            WHEN fu.USAGE_COUNT >= 1 THEN 2.0
            ELSE 1.0
        END AS FEATURE_ADOPTION_SCORE,
        8.5 AS USER_EXPERIENCE_RATING,
        9.0 AS FEATURE_PERFORMANCE_SCORE,
        1 AS CONCURRENT_FEATURES_COUNT,
        'Meeting' AS USAGE_CONTEXT,
        'Desktop' AS DEVICE_TYPE,
        '5.12.0' AS PLATFORM_VERSION,
        0 AS ERROR_COUNT,
        CASE 
            WHEN fu.USAGE_COUNT > 0 THEN 100.0
            ELSE 0.0
        END AS SUCCESS_RATE,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        'SILVER_TO_GOLD_ETL' AS SOURCE_SYSTEM
    FROM source_features fu
    LEFT JOIN {{ ref('go_dim_date') }} dd ON fu.USAGE_DATE = dd.DATE_KEY
    LEFT JOIN {{ ref('go_dim_feature') }} df ON fu.FEATURE_NAME = df.FEATURE_NAME
    LEFT JOIN source_meetings sm ON fu.MEETING_ID = sm.MEETING_ID
    LEFT JOIN {{ ref('go_dim_user') }} du ON sm.HOST_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
    LEFT JOIN {{ ref('go_dim_meeting') }} dm ON fu.MEETING_ID = dm.MEETING_KEY
)

SELECT 
    FEATURE_USAGE_ID,
    DATE_KEY,
    FEATURE_KEY,
    USER_KEY,
    MEETING_KEY,
    USAGE_DATE,
    USAGE_TIMESTAMP,
    FEATURE_NAME,
    USAGE_COUNT,
    USAGE_DURATION_MINUTES,
    SESSION_DURATION_MINUTES,
    FEATURE_ADOPTION_SCORE,
    USER_EXPERIENCE_RATING,
    FEATURE_PERFORMANCE_SCORE,
    CONCURRENT_FEATURES_COUNT,
    USAGE_CONTEXT,
    DEVICE_TYPE,
    PLATFORM_VERSION,
    ERROR_COUNT,
    SUCCESS_RATE,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM feature_usage_transformations
