{{ config(
    materialized='table',
    cluster_by=['TICKET_CREATED_DATE', 'SUPPORT_CATEGORY_ID']
) }}

WITH support_tickets_base AS (
    SELECT 
        st.TICKET_ID,
        st.USER_ID,
        st.TICKET_TYPE,
        st.RESOLUTION_STATUS,
        st.OPEN_DATE,
        st.OPEN_DATE::TIMESTAMP_NTZ AS TICKET_CREATED_TIMESTAMP,
        CASE 
            WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') 
            THEN st.OPEN_DATE + INTERVAL '1 DAY'
            ELSE NULL 
        END AS TICKET_CLOSED_DATE,
        CASE 
            WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') 
            THEN (st.OPEN_DATE + INTERVAL '1 DAY')::TIMESTAMP_NTZ
            ELSE NULL 
        END AS TICKET_CLOSED_TIMESTAMP,
        st.SOURCE_SYSTEM
    FROM {{ ref('si_support_tickets') }} st
    WHERE st.VALIDATION_STATUS = 'PASSED'
)

SELECT 
    dd.DATE_ID,
    dsc.SUPPORT_CATEGORY_ID,
    du.USER_DIM_ID,
    stb.TICKET_ID,
    stb.OPEN_DATE AS TICKET_CREATED_DATE,
    stb.TICKET_CREATED_TIMESTAMP,
    stb.TICKET_CLOSED_DATE,
    stb.TICKET_CLOSED_TIMESTAMP,
    DATEADD('hour', 1, stb.TICKET_CREATED_TIMESTAMP) AS FIRST_RESPONSE_TIMESTAMP,
    stb.TICKET_CLOSED_TIMESTAMP AS RESOLUTION_TIMESTAMP,
    stb.TICKET_TYPE AS TICKET_CATEGORY,
    CASE 
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%TECHNICAL%' THEN 'Technical Issue'
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%BILLING%' THEN 'Billing Inquiry'
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%FEATURE%' THEN 'Feature Request'
        ELSE 'General Support'
    END AS TICKET_SUBCATEGORY,
    CASE 
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%CRITICAL%' THEN 'Critical'
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%URGENT%' THEN 'High'
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%BILLING%' THEN 'Medium'
        ELSE 'Low'
    END AS PRIORITY_LEVEL,
    CASE 
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%CRITICAL%' THEN 'Critical'
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%URGENT%' THEN 'High'
        ELSE 'Medium'
    END AS SEVERITY_LEVEL,
    stb.RESOLUTION_STATUS,
    1.0 AS FIRST_RESPONSE_TIME_HOURS,
    CASE 
        WHEN stb.TICKET_CLOSED_TIMESTAMP IS NOT NULL 
        THEN DATEDIFF('hour', stb.TICKET_CREATED_TIMESTAMP, stb.TICKET_CLOSED_TIMESTAMP)
        ELSE NULL
    END AS RESOLUTION_TIME_HOURS,
    CASE 
        WHEN stb.TICKET_CLOSED_TIMESTAMP IS NOT NULL 
        THEN DATEDIFF('hour', stb.TICKET_CREATED_TIMESTAMP, stb.TICKET_CLOSED_TIMESTAMP)
        ELSE NULL
    END AS ACTIVE_WORK_TIME_HOURS,
    0.0 AS CUSTOMER_WAIT_TIME_HOURS,
    0 AS ESCALATION_COUNT,
    0 AS REASSIGNMENT_COUNT,
    0 AS REOPENED_COUNT,
    1 AS AGENT_INTERACTIONS_COUNT,
    1 AS CUSTOMER_INTERACTIONS_COUNT,
    CASE 
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%TECHNICAL%' THEN 15
        WHEN UPPER(stb.TICKET_TYPE) LIKE '%BILLING%' THEN 10
        ELSE 5
    END AS KNOWLEDGE_BASE_ARTICLES_USED,
    CASE 
        WHEN stb.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN 4.0
        ELSE 2.0
    END AS CUSTOMER_SATISFACTION_SCORE,
    TRUE AS FIRST_CONTACT_RESOLUTION,
    CASE 
        WHEN stb.TICKET_CLOSED_TIMESTAMP IS NOT NULL 
        THEN CASE 
            WHEN DATEDIFF('hour', stb.TICKET_CREATED_TIMESTAMP, stb.TICKET_CLOSED_TIMESTAMP) <= dsc.SLA_TARGET_HOURS 
            THEN TRUE 
            ELSE FALSE 
        END
        ELSE NULL
    END AS SLA_MET,
    CASE 
        WHEN stb.TICKET_CLOSED_TIMESTAMP IS NOT NULL 
        THEN GREATEST(0, DATEDIFF('hour', stb.TICKET_CREATED_TIMESTAMP, stb.TICKET_CLOSED_TIMESTAMP) - dsc.SLA_TARGET_HOURS)
        ELSE NULL
    END AS SLA_BREACH_HOURS,
    'Online Support' AS RESOLUTION_METHOD,
    'User Error' AS ROOT_CAUSE_CATEGORY,
    TRUE AS PREVENTABLE_ISSUE,
    FALSE AS FOLLOW_UP_REQUIRED,
    25.00 AS COST_TO_RESOLVE,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP() AS UPDATE_TIMESTAMP,
    stb.SOURCE_SYSTEM
FROM support_tickets_base stb
LEFT JOIN {{ ref('go_dim_date') }} dd ON stb.OPEN_DATE = dd.DATE_VALUE
LEFT JOIN {{ ref('go_dim_user') }} du ON stb.USER_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
LEFT JOIN {{ ref('go_dim_support_category') }} dsc ON stb.TICKET_TYPE = dsc.SUPPORT_CATEGORY
