{{ config(
    materialized='table'
) }}

-- Feature Usage Fact Table
WITH sample_data AS (
    SELECT 
        'MEETING_001' AS MEETING_ID,
        'Screen Share' AS FEATURE_NAME,
        5 AS USAGE_COUNT,
        '2024-01-15'::DATE AS USAGE_DATE,
        60 AS DURATION_MINUTES
    UNION ALL
    SELECT 
        'MEETING_002' AS MEETING_ID,
        'Video' AS FEATURE_NAME,
        10 AS USAGE_COUNT,
        '2024-01-16'::DATE AS USAGE_DATE,
        45 AS DURATION_MINUTES
    UNION ALL
    SELECT 
        'MEETING_003' AS MEETING_ID,
        'Chat' AS FEATURE_NAME,
        15 AS USAGE_COUNT,
        '2024-01-17'::DATE AS USAGE_DATE,
        30 AS DURATION_MINUTES
)
SELECT 
    USAGE_DATE,
    CURRENT_TIMESTAMP() as USAGE_TIMESTAMP,
    FEATURE_NAME,
    USAGE_COUNT,
    CASE 
        WHEN DURATION_MINUTES > 0 THEN 
            (USAGE_COUNT * 1.0 / 3) * DURATION_MINUTES
        ELSE 0
    END as USAGE_DURATION_MINUTES,
    COALESCE(DURATION_MINUTES, 0) as SESSION_DURATION_MINUTES,
    CASE 
        WHEN USAGE_COUNT >= 10 THEN 'High'
        WHEN USAGE_COUNT >= 5 THEN 'Medium'
        ELSE 'Low'
    END as USAGE_INTENSITY,
    CASE 
        WHEN USAGE_COUNT > 0 AND DURATION_MINUTES > 0 THEN 
            LEAST(10.0, (USAGE_COUNT * 2.0) + (DURATION_MINUTES / 10.0))
        ELSE 0
    END as USER_EXPERIENCE_SCORE,
    8.5 as FEATURE_PERFORMANCE_SCORE,
    3 as CONCURRENT_FEATURES_COUNT,
    0 as ERROR_COUNT,
    100.0 as SUCCESS_RATE_PERCENTAGE,
    CASE 
        WHEN FEATURE_NAME ILIKE '%video%' THEN USAGE_COUNT * 50.0
        WHEN FEATURE_NAME ILIKE '%screen%' THEN USAGE_COUNT * 30.0
        WHEN FEATURE_NAME ILIKE '%audio%' THEN USAGE_COUNT * 5.0
        ELSE USAGE_COUNT * 2.0
    END as BANDWIDTH_CONSUMED_MB,
    CURRENT_DATE() as LOAD_DATE,
    CURRENT_DATE() as UPDATE_DATE,
    'SYSTEM' AS SOURCE_SYSTEM
FROM sample_data
