{{ config(
    materialized='table',
    tags=['fact', 'gold'],
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, UPDATE_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_FACT_FEATURE_USAGE_LOAD', 'FACT_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_FEATURE_USAGE', 'GO_FACT_FEATURE_USAGE', 'DBT_MODEL', 'DBT_SYSTEM', CURRENT_DATE, CURRENT_DATE, 'DBT_GOLD_LAYER')",
    post_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_END_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, RECORDS_PROCESSED, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, UPDATE_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_FACT_FEATURE_USAGE_LOAD', 'FACT_LOAD', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SUCCESS', 'SI_FEATURE_USAGE', 'GO_FACT_FEATURE_USAGE', (SELECT COUNT(*) FROM {{ this }}), 'DBT_MODEL', 'DBT_SYSTEM', CURRENT_DATE, CURRENT_DATE, 'DBT_GOLD_LAYER')"
) }}

-- Feature Usage Fact Table
WITH source_feature_usage AS (
    SELECT 
        fu.USAGE_ID,
        fu.MEETING_ID,
        fu.FEATURE_NAME,
        fu.USAGE_COUNT,
        fu.USAGE_DATE,
        fu.SOURCE_SYSTEM
    FROM {{ source('silver', 'SI_FEATURE_USAGE') }} fu
    WHERE fu.VALIDATION_STATUS = 'PASSED'
),

meeting_context AS (
    SELECT 
        sm.MEETING_ID,
        sm.HOST_ID,
        sm.DURATION_MINUTES
    FROM {{ source('silver', 'SI_MEETINGS') }} sm
    WHERE sm.VALIDATION_STATUS = 'PASSED'
),

fact_feature_usage AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY sfu.USAGE_ID) AS FEATURE_USAGE_ID,
        dd.DATE_ID AS DATE_ID,
        df.FEATURE_ID AS FEATURE_ID,
        du.USER_DIM_ID AS USER_DIM_ID,
        sfu.MEETING_ID,
        sfu.USAGE_DATE,
        sfu.USAGE_DATE::TIMESTAMP_NTZ AS USAGE_TIMESTAMP,
        sfu.FEATURE_NAME,
        sfu.USAGE_COUNT,
        COALESCE(mc.DURATION_MINUTES, 0) AS USAGE_DURATION_MINUTES,
        COALESCE(mc.DURATION_MINUTES, 0) AS SESSION_DURATION_MINUTES,
        CASE 
            WHEN sfu.USAGE_COUNT >= 10 THEN 5.0
            WHEN sfu.USAGE_COUNT >= 5 THEN 4.0
            WHEN sfu.USAGE_COUNT >= 3 THEN 3.0
            WHEN sfu.USAGE_COUNT >= 1 THEN 2.0
            ELSE 1.0
        END AS FEATURE_ADOPTION_SCORE,
        4.5 AS USER_EXPERIENCE_RATING,
        4.8 AS FEATURE_PERFORMANCE_SCORE,
        1 AS CONCURRENT_FEATURES_COUNT,
        CASE 
            WHEN COALESCE(mc.DURATION_MINUTES, 0) >= 60 THEN 'Extended Session'
            WHEN COALESCE(mc.DURATION_MINUTES, 0) >= 30 THEN 'Standard Session'
            WHEN COALESCE(mc.DURATION_MINUTES, 0) >= 15 THEN 'Short Session'
            WHEN COALESCE(mc.DURATION_MINUTES, 0) >= 5 THEN 'Brief Session'
            ELSE 'Quick Access'
        END AS USAGE_CONTEXT,
        'Desktop' AS DEVICE_TYPE,
        '1.0' AS PLATFORM_VERSION,
        0 AS ERROR_COUNT,
        100.0 AS SUCCESS_RATE,
        CURRENT_DATE AS LOAD_DATE,
        CURRENT_DATE AS UPDATE_DATE,
        sfu.SOURCE_SYSTEM
    FROM source_feature_usage sfu
    LEFT JOIN {{ ref('go_dim_date') }} dd ON sfu.USAGE_DATE = dd.DATE_VALUE
    LEFT JOIN {{ ref('go_dim_feature') }} df ON sfu.FEATURE_NAME = df.FEATURE_NAME
    LEFT JOIN meeting_context mc ON sfu.MEETING_ID = mc.MEETING_ID
    LEFT JOIN {{ ref('go_dim_user') }} du ON mc.HOST_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
)

SELECT * FROM fact_feature_usage
