{{ config(
    materialized='table'
) }}

-- Gold Fact: Support Metrics Fact
-- Description: Support ticket activities and resolution performance metrics

WITH source_tickets AS (
    SELECT 
        st.TICKET_ID,
        st.USER_ID,
        st.TICKET_TYPE,
        st.RESOLUTION_STATUS,
        st.OPEN_DATE,
        st.SOURCE_SYSTEM,
        st.VALIDATION_STATUS
    FROM {{ source('silver', 'si_support_tickets') }} st
    WHERE (st.VALIDATION_STATUS = 'PASSED' OR st.VALIDATION_STATUS IS NULL)
      AND st.TICKET_ID IS NOT NULL
),

support_metrics AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY TICKET_ID) AS SUPPORT_METRICS_ID,
        COALESCE(OPEN_DATE, CURRENT_DATE) AS TICKET_OPEN_DATE,
        CASE 
            WHEN UPPER(COALESCE(RESOLUTION_STATUS, '')) = 'RESOLVED' THEN 
                DATEADD('day', 3, COALESCE(OPEN_DATE, CURRENT_DATE))
            ELSE NULL
        END AS TICKET_CLOSE_DATE,
        DATEADD('hour', 2, COALESCE(OPEN_DATE, CURRENT_DATE)) AS TICKET_CREATED_TIMESTAMP,
        CASE 
            WHEN UPPER(COALESCE(RESOLUTION_STATUS, '')) = 'RESOLVED' THEN 
                DATEADD('hour', 72, COALESCE(OPEN_DATE, CURRENT_DATE))
            ELSE NULL
        END AS TICKET_RESOLVED_TIMESTAMP,
        DATEADD('hour', 2, COALESCE(OPEN_DATE, CURRENT_DATE)) AS FIRST_RESPONSE_TIMESTAMP,
        COALESCE(TICKET_TYPE, 'General') AS TICKET_TYPE,
        COALESCE(RESOLUTION_STATUS, 'Open') AS RESOLUTION_STATUS,
        CASE 
            WHEN UPPER(COALESCE(TICKET_TYPE, '')) LIKE '%CRITICAL%' THEN 'Critical'
            WHEN UPPER(COALESCE(TICKET_TYPE, '')) LIKE '%HIGH%' THEN 'High'
            WHEN UPPER(COALESCE(TICKET_TYPE, '')) LIKE '%MEDIUM%' THEN 'Medium'
            ELSE 'Low'
        END AS PRIORITY_LEVEL,
        CASE 
            WHEN UPPER(COALESCE(TICKET_TYPE, '')) LIKE '%CRITICAL%' THEN 'Critical'
            WHEN UPPER(COALESCE(TICKET_TYPE, '')) LIKE '%HIGH%' THEN 'High'
            ELSE 'Medium'
        END AS SEVERITY_LEVEL,
        CASE 
            WHEN UPPER(COALESCE(RESOLUTION_STATUS, '')) = 'RESOLVED' THEN 72.0
            ELSE NULL
        END AS RESOLUTION_TIME_HOURS,
        2.0 AS FIRST_RESPONSE_TIME_HOURS,
        0 AS ESCALATION_COUNT,
        0 AS REASSIGNMENT_COUNT,
        CASE 
            WHEN UPPER(COALESCE(RESOLUTION_STATUS, '')) = 'RESOLVED' THEN 8.5
            ELSE NULL
        END AS CUSTOMER_SATISFACTION_SCORE,
        9.2 AS AGENT_PERFORMANCE_SCORE,
        TRUE AS FIRST_CONTACT_RESOLUTION_FLAG,
        CASE 
            WHEN UPPER(COALESCE(RESOLUTION_STATUS, '')) = 'RESOLVED' THEN TRUE
            ELSE FALSE
        END AS SLA_MET_FLAG,
        0.0 AS SLA_BREACH_HOURS,
        5 AS COMMUNICATION_COUNT,
        TRUE AS KNOWLEDGE_BASE_USED_FLAG,
        CASE 
            WHEN UPPER(COALESCE(TICKET_TYPE, '')) LIKE '%TECHNICAL%' THEN TRUE
            ELSE FALSE
        END AS REMOTE_ASSISTANCE_USED_FLAG,
        FALSE AS FOLLOW_UP_REQUIRED_FLAG,
        CURRENT_DATE AS LOAD_DATE,
        CURRENT_DATE AS UPDATE_DATE,
        COALESCE(SOURCE_SYSTEM, 'UNKNOWN') AS SOURCE_SYSTEM
    FROM source_tickets
)

SELECT * FROM support_metrics
