{{
  config(
    materialized='table',
    cluster_by=['DATE_ID', 'HOST_USER_DIM_ID'],
    tags=['fact', 'gold'],
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, UPDATE_DATE, SOURCE_SYSTEM) SELECT '{{ dbt_utils.generate_surrogate_key(['go_fact_meeting_activity', run_started_at]) }}', 'go_fact_meeting_activity', 'FACT_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_MEETINGS', 'GO_FACT_MEETING_ACTIVITY', 'DBT_RUN', 'DBT_SYSTEM', CURRENT_DATE(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_END_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, RECORDS_PROCESSED, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, UPDATE_DATE, SOURCE_SYSTEM) SELECT '{{ dbt_utils.generate_surrogate_key(['go_fact_meeting_activity_complete', run_started_at]) }}', 'go_fact_meeting_activity', 'FACT_LOAD', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SUCCESS', 'SI_MEETINGS', 'GO_FACT_MEETING_ACTIVITY', (SELECT COUNT(*) FROM {{ this }}), 'DBT_RUN', 'DBT_SYSTEM', CURRENT_DATE(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
  )
}}

-- Meeting Activity Fact Table
-- Central fact table capturing comprehensive meeting activities and engagement metrics

WITH meeting_base AS (
    SELECT 
        MEETING_ID,
        HOST_ID,
        MEETING_TOPIC,
        START_TIME,
        END_TIME,
        DURATION_MINUTES,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_meetings') }}
    WHERE VALIDATION_STATUS = 'PASSED'
),

participant_metrics AS (
    SELECT 
        MEETING_ID,
        COUNT(DISTINCT USER_ID) AS PARTICIPANT_COUNT,
        COUNT(DISTINCT PARTICIPANT_ID) AS UNIQUE_PARTICIPANTS,
        SUM(DATEDIFF('minute', JOIN_TIME, LEAVE_TIME)) AS TOTAL_PARTICIPANT_MINUTES,
        AVG(DATEDIFF('minute', JOIN_TIME, LEAVE_TIME)) AS AVERAGE_PARTICIPATION_MINUTES,
        MAX(PARTICIPANT_COUNT_AT_TIME) AS PEAK_CONCURRENT_PARTICIPANTS,
        COUNT(CASE WHEN JOIN_TIME > DATEADD('minute', 5, (SELECT START_TIME FROM meeting_base mb WHERE mb.MEETING_ID = sp.MEETING_ID)) THEN 1 END) AS LATE_JOINERS_COUNT,
        COUNT(CASE WHEN LEAVE_TIME < DATEADD('minute', -5, (SELECT END_TIME FROM meeting_base mb WHERE mb.MEETING_ID = sp.MEETING_ID)) THEN 1 END) AS EARLY_LEAVERS_COUNT
    FROM {{ source('silver', 'si_participants') }} sp
    WHERE VALIDATION_STATUS = 'PASSED'
    GROUP BY MEETING_ID
),

feature_usage_metrics AS (
    SELECT 
        MEETING_ID,
        COUNT(DISTINCT FEATURE_NAME) AS FEATURES_USED_COUNT,
        SUM(CASE WHEN UPPER(FEATURE_NAME) LIKE '%SCREEN%SHARE%' THEN USAGE_COUNT ELSE 0 END) AS SCREEN_SHARE_DURATION_MINUTES,
        SUM(CASE WHEN UPPER(FEATURE_NAME) LIKE '%RECORD%' THEN USAGE_COUNT ELSE 0 END) AS RECORDING_DURATION_MINUTES,
        SUM(CASE WHEN UPPER(FEATURE_NAME) LIKE '%CHAT%' THEN USAGE_COUNT ELSE 0 END) AS CHAT_MESSAGES_COUNT,
        SUM(CASE WHEN UPPER(FEATURE_NAME) LIKE '%FILE%' THEN USAGE_COUNT ELSE 0 END) AS FILE_SHARES_COUNT,
        SUM(CASE WHEN UPPER(FEATURE_NAME) LIKE '%BREAKOUT%' THEN USAGE_COUNT ELSE 0 END) AS BREAKOUT_ROOMS_USED,
        SUM(CASE WHEN UPPER(FEATURE_NAME) LIKE '%POLL%' THEN USAGE_COUNT ELSE 0 END) AS POLLS_CONDUCTED
    FROM {{ source('silver', 'si_feature_usage') }}
    WHERE VALIDATION_STATUS = 'PASSED'
    GROUP BY MEETING_ID
),

meeting_facts AS (
    SELECT 
        -- Surrogate Key
        {{ dbt_utils.generate_surrogate_key(['mb.MEETING_ID']) }} AS MEETING_ACTIVITY_ID,
        
        -- Foreign Keys
        dd.DATE_ID,
        COALESCE(dmt.MEETING_TYPE_ID, 1) AS MEETING_TYPE_ID,
        COALESCE(du.USER_DIM_ID, 1) AS HOST_USER_DIM_ID,
        
        -- Meeting Identifiers
        mb.MEETING_ID,
        DATE(mb.START_TIME) AS MEETING_DATE,
        mb.START_TIME AS MEETING_START_TIME,
        mb.END_TIME AS MEETING_END_TIME,
        
        -- Meeting Metrics
        mb.DURATION_MINUTES AS SCHEDULED_DURATION_MINUTES,
        mb.DURATION_MINUTES AS ACTUAL_DURATION_MINUTES,
        COALESCE(pm.PARTICIPANT_COUNT, 0) AS PARTICIPANT_COUNT,
        COALESCE(pm.UNIQUE_PARTICIPANTS, 0) AS UNIQUE_PARTICIPANTS,
        mb.DURATION_MINUTES AS HOST_DURATION_MINUTES,
        COALESCE(pm.TOTAL_PARTICIPANT_MINUTES, 0) AS TOTAL_PARTICIPANT_MINUTES,
        COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) AS AVERAGE_PARTICIPATION_MINUTES,
        COALESCE(pm.PEAK_CONCURRENT_PARTICIPANTS, 0) AS PEAK_CONCURRENT_PARTICIPANTS,
        COALESCE(pm.LATE_JOINERS_COUNT, 0) AS LATE_JOINERS_COUNT,
        COALESCE(pm.EARLY_LEAVERS_COUNT, 0) AS EARLY_LEAVERS_COUNT,
        
        -- Feature Usage Metrics
        COALESCE(fum.FEATURES_USED_COUNT, 0) AS FEATURES_USED_COUNT,
        COALESCE(fum.SCREEN_SHARE_DURATION_MINUTES, 0) AS SCREEN_SHARE_DURATION_MINUTES,
        COALESCE(fum.RECORDING_DURATION_MINUTES, 0) AS RECORDING_DURATION_MINUTES,
        COALESCE(fum.CHAT_MESSAGES_COUNT, 0) AS CHAT_MESSAGES_COUNT,
        COALESCE(fum.FILE_SHARES_COUNT, 0) AS FILE_SHARES_COUNT,
        COALESCE(fum.BREAKOUT_ROOMS_USED, 0) AS BREAKOUT_ROOMS_USED,
        COALESCE(fum.POLLS_CONDUCTED, 0) AS POLLS_CONDUCTED,
        
        -- Quality Scores
        CASE 
            WHEN COALESCE(pm.PARTICIPANT_COUNT, 0) >= 5 AND COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) >= (mb.DURATION_MINUTES * 0.8) THEN 5.0
            WHEN COALESCE(pm.PARTICIPANT_COUNT, 0) >= 3 AND COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) >= (mb.DURATION_MINUTES * 0.6) THEN 4.0
            WHEN COALESCE(pm.PARTICIPANT_COUNT, 0) >= 2 AND COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) >= (mb.DURATION_MINUTES * 0.4) THEN 3.0
            WHEN COALESCE(pm.PARTICIPANT_COUNT, 0) >= 1 AND COALESCE(pm.AVERAGE_PARTICIPATION_MINUTES, 0) >= (mb.DURATION_MINUTES * 0.2) THEN 2.0
            ELSE 1.0
        END AS MEETING_QUALITY_SCORE,
        
        4.5 AS AUDIO_QUALITY_SCORE, -- Default value
        4.5 AS VIDEO_QUALITY_SCORE, -- Default value
        0 AS CONNECTION_ISSUES_COUNT, -- Default value
        4.0 AS MEETING_SATISFACTION_SCORE, -- Default value
        
        -- Metadata
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        mb.SOURCE_SYSTEM
    FROM meeting_base mb
    LEFT JOIN {{ ref('go_dim_date') }} dd ON DATE(mb.START_TIME) = dd.DATE_VALUE
    LEFT JOIN {{ ref('go_dim_user') }} du ON mb.HOST_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
    LEFT JOIN {{ ref('go_dim_meeting_type') }} dmt ON (
        CASE 
            WHEN mb.DURATION_MINUTES <= 15 THEN 'Quick Sync'
            WHEN mb.DURATION_MINUTES <= 60 THEN 'Standard Meeting'
            WHEN mb.DURATION_MINUTES <= 120 THEN 'Extended Meeting'
            ELSE 'Long Session'
        END = dmt.MEETING_CATEGORY
    )
    LEFT JOIN participant_metrics pm ON mb.MEETING_ID = pm.MEETING_ID
    LEFT JOIN feature_usage_metrics fum ON mb.MEETING_ID = fum.MEETING_ID
)

SELECT * FROM meeting_facts
