{{ config(
    materialized='table'
) }}

-- Support Activity Fact Table
-- Captures support ticket activities and resolution metrics

WITH source_tickets AS (
    SELECT 
        COALESCE(TICKET_ID, 'UNKNOWN_TICKET') AS TICKET_ID,
        COALESCE(USER_ID, 'UNKNOWN_USER') AS USER_ID,
        COALESCE(TICKET_TYPE, 'General Support') AS TICKET_TYPE,
        COALESCE(RESOLUTION_STATUS, 'Open') AS RESOLUTION_STATUS,
        COALESCE(OPEN_DATE, CURRENT_DATE()) AS OPEN_DATE,
        COALESCE(SOURCE_SYSTEM, 'UNKNOWN') AS SOURCE_SYSTEM
    FROM {{ source('silver', 'si_support_tickets') }}
    WHERE COALESCE(VALIDATION_STATUS, 'PASSED') = 'PASSED'
),

support_transformations AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY st.TICKET_ID) AS SUPPORT_ACTIVITY_ID,
        -- Foreign Key Columns for BI Integration
        COALESCE(du.USER_KEY, 'UNKNOWN_USER') AS USER_KEY,
        COALESCE(dd.DATE_KEY, CURRENT_DATE()) AS DATE_KEY,
        COALESCE(dsc.SUPPORT_CATEGORY_KEY, 'UNKNOWN_CATEGORY') AS SUPPORT_CATEGORY_KEY,
        -- Fact Measures
        st.OPEN_DATE AS TICKET_OPEN_DATE,
        CASE 
            WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') 
            THEN st.OPEN_DATE + INTERVAL '2 DAYS' 
            ELSE NULL 
        END AS TICKET_CLOSE_DATE,
        st.TICKET_TYPE,
        st.RESOLUTION_STATUS,
        COALESCE(dsc.PRIORITY_LEVEL, 'Medium') AS PRIORITY_LEVEL,
        CASE 
            WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed')
            THEN 48.0
            ELSE NULL 
        END AS RESOLUTION_TIME_HOURS,
        0 AS ESCALATION_COUNT,
        8.0 AS CUSTOMER_SATISFACTION_SCORE,
        CASE 
            WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN TRUE 
            ELSE FALSE 
        END AS FIRST_CONTACT_RESOLUTION_FLAG,
        4.0 AS FIRST_RESPONSE_TIME_HOURS,
        24.0 AS ACTIVE_WORK_TIME_HOURS,
        24.0 AS CUSTOMER_WAIT_TIME_HOURS,
        0 AS REASSIGNMENT_COUNT,
        0 AS REOPENED_COUNT,
        3 AS AGENT_INTERACTIONS_COUNT,
        2 AS CUSTOMER_INTERACTIONS_COUNT,
        1 AS KNOWLEDGE_BASE_ARTICLES_USED,
        CASE 
            WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') AND 
                 48.0 <= COALESCE(dsc.SLA_TARGET_HOURS, 72.0)
            THEN TRUE 
            ELSE FALSE 
        END AS SLA_MET,
        CASE 
            WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') AND 
                 48.0 > COALESCE(dsc.SLA_TARGET_HOURS, 72.0)
            THEN 48.0 - COALESCE(dsc.SLA_TARGET_HOURS, 72.0)
            ELSE 0 
        END AS SLA_BREACH_HOURS,
        'Email Support' AS RESOLUTION_METHOD,
        'User Error' AS ROOT_CAUSE_CATEGORY,
        TRUE AS PREVENTABLE_ISSUE,
        FALSE AS FOLLOW_UP_REQUIRED,
        25.00 AS COST_TO_RESOLVE,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        'SILVER_TO_GOLD_ETL' AS SOURCE_SYSTEM
    FROM source_tickets st
    LEFT JOIN {{ ref('go_dim_user') }} du ON st.USER_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
    LEFT JOIN {{ ref('go_dim_date') }} dd ON st.OPEN_DATE = dd.DATE_KEY
    LEFT JOIN {{ ref('go_dim_support_category') }} dsc ON st.TICKET_TYPE = dsc.SUPPORT_CATEGORY
)

SELECT 
    SUPPORT_ACTIVITY_ID,
    USER_KEY,
    DATE_KEY,
    SUPPORT_CATEGORY_KEY,
    TICKET_OPEN_DATE,
    TICKET_CLOSE_DATE,
    TICKET_TYPE,
    RESOLUTION_STATUS,
    PRIORITY_LEVEL,
    RESOLUTION_TIME_HOURS,
    ESCALATION_COUNT,
    CUSTOMER_SATISFACTION_SCORE,
    FIRST_CONTACT_RESOLUTION_FLAG,
    FIRST_RESPONSE_TIME_HOURS,
    ACTIVE_WORK_TIME_HOURS,
    CUSTOMER_WAIT_TIME_HOURS,
    REASSIGNMENT_COUNT,
    REOPENED_COUNT,
    AGENT_INTERACTIONS_COUNT,
    CUSTOMER_INTERACTIONS_COUNT,
    KNOWLEDGE_BASE_ARTICLES_USED,
    SLA_MET,
    SLA_BREACH_HOURS,
    RESOLUTION_METHOD,
    ROOT_CAUSE_CATEGORY,
    PREVENTABLE_ISSUE,
    FOLLOW_UP_REQUIRED,
    COST_TO_RESOLVE,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM support_transformations
