{{ config(
    materialized='table',
    tags=['fact', 'gold'],
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (PROCESS_ID, PROCESS_NAME, PROCESS_TYPE, PROCESS_START_TIME, PROCESS_STATUS, SOURCE_TABLE, TARGET_TABLE, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_FACT_SUPPORT_ACTIVITY_LOAD', 'FACT_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_SUPPORT_TICKETS', 'GO_FACT_SUPPORT_ACTIVITY', 'DBT_MODEL_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_PIPELINE')",
    post_hook="INSERT INTO {{ ref('go_audit_log') }} (PROCESS_ID, PROCESS_NAME, PROCESS_TYPE, PROCESS_START_TIME, PROCESS_END_TIME, PROCESS_STATUS, SOURCE_TABLE, TARGET_TABLE, RECORDS_PROCESSED, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT UUID_STRING(), 'GO_FACT_SUPPORT_ACTIVITY_LOAD', 'FACT_LOAD', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SUCCESS', 'SI_SUPPORT_TICKETS', 'GO_FACT_SUPPORT_ACTIVITY', (SELECT COUNT(*) FROM {{ this }}), 'DBT_MODEL_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_PIPELINE'"
) }}

-- Support activity fact table transformation
WITH support_base AS (
    SELECT 
        st.TICKET_ID,
        st.USER_ID,
        st.TICKET_TYPE,
        st.RESOLUTION_STATUS,
        st.OPEN_DATE,
        st.SOURCE_SYSTEM
    FROM {{ source('silver', 'si_support_tickets') }} st
    WHERE st.VALIDATION_STATUS = 'PASSED'
),

support_metrics AS (
    SELECT 
        sb.*,
        CASE WHEN sb.RESOLUTION_STATUS IN ('Resolved', 'Closed') 
             THEN sb.OPEN_DATE + INTERVAL '1 DAY' -- Placeholder for actual close date
             ELSE NULL END AS TICKET_CLOSE_DATE,
        CASE WHEN sb.RESOLUTION_STATUS IN ('Resolved', 'Closed')
             THEN DATEDIFF('hour', sb.OPEN_DATE, sb.OPEN_DATE + INTERVAL '1 DAY')
             ELSE NULL END AS RESOLUTION_TIME_HOURS
    FROM support_base sb
)

SELECT 
    ROW_NUMBER() OVER (ORDER BY sm.TICKET_ID) AS SUPPORT_ACTIVITY_ID,
    -- Foreign Key Columns for BI Integration
    du.USER_KEY,
    dd.DATE_KEY,
    dsc.SUPPORT_CATEGORY_KEY,
    -- Fact Measures
    sm.OPEN_DATE AS TICKET_OPEN_DATE,
    sm.TICKET_CLOSE_DATE,
    sm.TICKET_TYPE,
    sm.RESOLUTION_STATUS,
    COALESCE(dsc.PRIORITY_LEVEL, 'Medium') AS PRIORITY_LEVEL,
    sm.RESOLUTION_TIME_HOURS,
    0 AS ESCALATION_COUNT, -- Default value
    CASE 
        WHEN sm.RESOLUTION_TIME_HOURS <= 4 THEN 5.0
        WHEN sm.RESOLUTION_TIME_HOURS <= 24 THEN 4.0
        WHEN sm.RESOLUTION_TIME_HOURS <= 72 THEN 3.0
        WHEN sm.RESOLUTION_TIME_HOURS <= 168 THEN 2.0
        ELSE 1.0
    END AS CUSTOMER_SATISFACTION_SCORE,
    FALSE AS FIRST_CONTACT_RESOLUTION_FLAG, -- Default value
    4.0 AS FIRST_RESPONSE_TIME_HOURS, -- Default value
    COALESCE(sm.RESOLUTION_TIME_HOURS, 0) AS ACTIVE_WORK_TIME_HOURS,
    0 AS CUSTOMER_WAIT_TIME_HOURS, -- Default value
    0 AS REASSIGNMENT_COUNT, -- Default value
    0 AS REOPENED_COUNT, -- Default value
    1 AS AGENT_INTERACTIONS_COUNT, -- Default value
    1 AS CUSTOMER_INTERACTIONS_COUNT, -- Default value
    0 AS KNOWLEDGE_BASE_ARTICLES_USED, -- Default value
    CASE WHEN sm.RESOLUTION_TIME_HOURS <= COALESCE(dsc.SLA_TARGET_HOURS, 72)
         THEN TRUE ELSE FALSE END AS SLA_MET,
    CASE WHEN sm.RESOLUTION_TIME_HOURS > COALESCE(dsc.SLA_TARGET_HOURS, 72)
         THEN sm.RESOLUTION_TIME_HOURS - COALESCE(dsc.SLA_TARGET_HOURS, 72)
         ELSE 0 END AS SLA_BREACH_HOURS,
    'Standard Resolution' AS RESOLUTION_METHOD,
    'User Error' AS ROOT_CAUSE_CATEGORY,
    CASE 
        WHEN sm.TICKET_TYPE IN ('Password Reset', 'Account Lockout', 'Basic Setup') THEN TRUE
        ELSE FALSE
    END AS PREVENTABLE_ISSUE,
    FALSE AS FOLLOW_UP_REQUIRED, -- Default value
    50.0 AS COST_TO_RESOLVE, -- Default value
    -- Metadata
    CURRENT_DATE AS LOAD_DATE,
    CURRENT_DATE AS UPDATE_DATE,
    sm.SOURCE_SYSTEM
FROM support_metrics sm
JOIN {{ ref('go_dim_user') }} du ON sm.USER_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
JOIN {{ ref('go_dim_date') }} dd ON sm.OPEN_DATE = dd.DATE_KEY
JOIN {{ ref('go_dim_support_category') }} dsc ON MD5(UPPER(TRIM(sm.TICKET_TYPE))) = dsc.SUPPORT_CATEGORY_KEY
