{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'SUPPORT_FACT_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_FACT_SUPPORT_ACTIVITY_TRANSFORM', CURRENT_TIMESTAMP(), 'SI_SUPPORT_TICKETS', 'GO_FACT_SUPPORT_ACTIVITY', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, RECORDS_PROCESSED, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'SUPPORT_FACT_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_FACT_SUPPORT_ACTIVITY_TRANSFORM', CURRENT_TIMESTAMP(), 'SI_SUPPORT_TICKETS', 'GO_FACT_SUPPORT_ACTIVITY', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, (SELECT COUNT(*) FROM {{ this }}), 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
) }}

-- Gold Layer Support Activity Fact Table
-- Transforms support ticket data with performance metrics and SLA tracking
-- Enables comprehensive support analytics and performance monitoring

WITH source_tickets AS (
    SELECT 
        TICKET_ID,
        USER_ID,
        TICKET_TYPE,
        RESOLUTION_STATUS,
        OPEN_DATE,
        RESOLUTION_TIME_HOURS,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_support_tickets') }}
    WHERE TICKET_TYPE IS NOT NULL
      AND OPEN_DATE IS NOT NULL
      AND USER_ID IS NOT NULL
),

user_context AS (
    SELECT 
        USER_ID,
        PLAN_TYPE
    FROM {{ source('silver', 'si_users') }}
),

support_enrichment AS (
    SELECT 
        st.OPEN_DATE AS TICKET_DATE,
        st.USER_ID AS USER_KEY,
        UPPER(TRIM(st.TICKET_TYPE)) AS TICKET_TYPE,
        CASE 
            WHEN UPPER(TRIM(st.RESOLUTION_STATUS)) IN ('RESOLVED', 'CLOSED', 'PENDING', 'OPEN', 'IN_PROGRESS') 
            THEN UPPER(TRIM(st.RESOLUTION_STATUS))
            ELSE 'UNKNOWN'
        END AS RESOLUTION_STATUS,
        st.OPEN_DATE,
        COALESCE(st.RESOLUTION_TIME_HOURS, 0) AS RESOLUTION_TIME_HOURS,
        CASE 
            WHEN u.PLAN_TYPE IN ('ENTERPRISE', 'BUSINESS') THEN 'HIGH'
            WHEN u.PLAN_TYPE = 'PRO' THEN 'MEDIUM'
            ELSE 'STANDARD'
        END AS PRIORITY_LEVEL,
        CASE 
            WHEN st.RESOLUTION_TIME_HOURS <= 24 AND UPPER(st.RESOLUTION_STATUS) IN ('RESOLVED', 'CLOSED') 
            THEN TRUE 
            ELSE FALSE 
        END AS FIRST_CONTACT_RESOLUTION_FLAG,
        CASE 
            WHEN st.RESOLUTION_TIME_HOURS > 72 
            THEN TRUE 
            ELSE FALSE 
        END AS ESCALATION_FLAG,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        st.SOURCE_SYSTEM
    FROM source_tickets st
    LEFT JOIN user_context u ON st.USER_ID = u.USER_ID
)

SELECT 
    TICKET_DATE::DATE,
    USER_KEY::VARCHAR(16777216),
    TICKET_TYPE::VARCHAR(16777216),
    RESOLUTION_STATUS::VARCHAR(16777216),
    OPEN_DATE::DATE,
    RESOLUTION_TIME_HOURS::NUMBER(10,2),
    PRIORITY_LEVEL::VARCHAR(50),
    FIRST_CONTACT_RESOLUTION_FLAG::BOOLEAN,
    ESCALATION_FLAG::BOOLEAN,
    LOAD_DATE::DATE,
    UPDATE_DATE::DATE,
    SOURCE_SYSTEM::VARCHAR(16777216)
FROM support_enrichment
