{{ config(
    materialized='table',
    tags=['fact', 'gold'],
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, PROCESS_TYPE, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, RECORDS_READ, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, UPDATE_DATE, SOURCE_SYSTEM) SELECT '{{ dbt_utils.generate_surrogate_key([\"'GO_FACT_SUPPORT_METRICS'\", 'CURRENT_TIMESTAMP()']) }}', 'GO_FACT_SUPPORT_METRICS_LOAD', 'FACT_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_SUPPORT_TICKETS', 'GO_FACT_SUPPORT_METRICS', (SELECT COUNT(*) FROM {{ source('silver', 'si_support_tickets') }}), 'DBT_PIPELINE', 'DBT_SYSTEM', CURRENT_DATE, CURRENT_DATE, 'DBT_GOLD_PIPELINE'",
    post_hook="UPDATE {{ ref('go_audit_log') }} SET EXECUTION_END_TIMESTAMP = CURRENT_TIMESTAMP(), EXECUTION_STATUS = 'SUCCESS', RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}), RECORDS_INSERTED = (SELECT COUNT(*) FROM {{ this }}) WHERE PROCESS_NAME = 'GO_FACT_SUPPORT_METRICS_LOAD' AND EXECUTION_STATUS = 'RUNNING'"
) }}

-- Gold Fact: Support Metrics Fact Table
-- Detailed support ticket metrics and resolution performance

SELECT 
    ROW_NUMBER() OVER (ORDER BY st.TICKET_ID) AS SUPPORT_METRICS_ID,
    dd.DATE_ID,
    dsc.SUPPORT_CATEGORY_ID,
    du.USER_DIM_ID,
    st.TICKET_ID,
    st.OPEN_DATE AS TICKET_CREATED_DATE,
    st.OPEN_DATE::TIMESTAMP_NTZ AS TICKET_CREATED_TIMESTAMP,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN st.OPEN_DATE + INTERVAL '1 DAY'
        ELSE NULL
    END AS TICKET_CLOSED_DATE,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN (st.OPEN_DATE + INTERVAL '1 DAY')::TIMESTAMP_NTZ
        ELSE NULL
    END AS TICKET_CLOSED_TIMESTAMP,
    st.OPEN_DATE::TIMESTAMP_NTZ + INTERVAL '2 HOURS' AS FIRST_RESPONSE_TIMESTAMP,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN (st.OPEN_DATE + INTERVAL '1 DAY')::TIMESTAMP_NTZ
        ELSE NULL
    END AS RESOLUTION_TIMESTAMP,
    st.TICKET_TYPE AS TICKET_CATEGORY,
    CASE 
        WHEN UPPER(st.TICKET_TYPE) LIKE '%TECHNICAL%' THEN 'Technical Issue'
        WHEN UPPER(st.TICKET_TYPE) LIKE '%BILLING%' THEN 'Billing Inquiry'
        WHEN UPPER(st.TICKET_TYPE) LIKE '%FEATURE%' THEN 'Feature Request'
        ELSE 'General Support'
    END AS TICKET_SUBCATEGORY,
    CASE 
        WHEN UPPER(st.TICKET_TYPE) LIKE '%CRITICAL%' THEN 'Critical'
        WHEN UPPER(st.TICKET_TYPE) LIKE '%URGENT%' THEN 'High'
        WHEN UPPER(st.TICKET_TYPE) LIKE '%BILLING%' THEN 'Medium'
        ELSE 'Low'
    END AS PRIORITY_LEVEL,
    CASE 
        WHEN UPPER(st.TICKET_TYPE) LIKE '%CRITICAL%' THEN 'Critical'
        WHEN UPPER(st.TICKET_TYPE) LIKE '%URGENT%' THEN 'High'
        WHEN UPPER(st.TICKET_TYPE) LIKE '%BILLING%' THEN 'Medium'
        ELSE 'Low'
    END AS SEVERITY_LEVEL,
    st.RESOLUTION_STATUS,
    2.0 AS FIRST_RESPONSE_TIME_HOURS,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN 24.0
        ELSE NULL
    END AS RESOLUTION_TIME_HOURS,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN 20.0
        ELSE NULL
    END AS ACTIVE_WORK_TIME_HOURS,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN 4.0
        ELSE NULL
    END AS CUSTOMER_WAIT_TIME_HOURS,
    CASE 
        WHEN UPPER(st.TICKET_TYPE) LIKE '%CRITICAL%' THEN 1
        ELSE 0
    END AS ESCALATION_COUNT,
    0 AS REASSIGNMENT_COUNT,
    0 AS REOPENED_COUNT,
    3 AS AGENT_INTERACTIONS_COUNT,
    2 AS CUSTOMER_INTERACTIONS_COUNT,
    CASE 
        WHEN UPPER(st.TICKET_TYPE) LIKE '%TECHNICAL%' THEN 2
        WHEN UPPER(st.TICKET_TYPE) LIKE '%BILLING%' THEN 1
        ELSE 0
    END AS KNOWLEDGE_BASE_ARTICLES_USED,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') AND 24.0 <= 48.0 THEN 4.0
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') AND 24.0 <= 72.0 THEN 3.0
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') THEN 2.0
        ELSE 1.0
    END AS CUSTOMER_SATISFACTION_SCORE,
    FALSE AS FIRST_CONTACT_RESOLUTION,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') AND 24.0 <= dsc.SLA_TARGET_HOURS THEN TRUE
        ELSE FALSE
    END AS SLA_MET,
    CASE 
        WHEN st.RESOLUTION_STATUS IN ('Resolved', 'Closed') AND 24.0 > dsc.SLA_TARGET_HOURS THEN 24.0 - dsc.SLA_TARGET_HOURS
        ELSE 0
    END AS SLA_BREACH_HOURS,
    'Agent Resolution' AS RESOLUTION_METHOD,
    'User Error' AS ROOT_CAUSE_CATEGORY,
    CASE 
        WHEN st.TICKET_TYPE IN ('Password Reset', 'Account Lockout', 'Basic Setup') THEN TRUE
        ELSE FALSE
    END AS PREVENTABLE_ISSUE,
    FALSE AS FOLLOW_UP_REQUIRED,
    50.0 AS COST_TO_RESOLVE,
    CURRENT_DATE AS LOAD_DATE,
    CURRENT_DATE AS UPDATE_DATE,
    st.SOURCE_SYSTEM
FROM {{ source('silver', 'si_support_tickets') }} st
LEFT JOIN {{ ref('go_dim_user') }} du ON st.USER_ID = du.USER_ID AND du.IS_CURRENT_RECORD = TRUE
LEFT JOIN {{ ref('go_dim_date') }} dd ON st.OPEN_DATE = dd.DATE_VALUE
LEFT JOIN {{ ref('go_dim_support_category') }} dsc ON st.TICKET_TYPE = dsc.SUPPORT_CATEGORY
WHERE st.VALIDATION_STATUS = 'PASSED'
