{{ config(
    materialized='table',
    on_schema_change='sync_all_columns'
) }}

-- Silver Layer Audit Log Table
-- This table tracks all Silver layer pipeline execution details
-- No pre-hook or post-hook logic included as per requirements

SELECT 
    CAST(NULL AS STRING) AS EXECUTION_ID,
    CAST(NULL AS VARCHAR(255)) AS PIPELINE_NAME,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS START_TIME,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS END_TIME,
    CAST(NULL AS VARCHAR(255)) AS STATUS,
    CAST(NULL AS VARCHAR(16777216)) AS ERROR_MESSAGE,
    CAST(NULL AS NUMBER) AS EXECUTION_DURATION_SECONDS,
    CAST(NULL AS VARCHAR(16777216)) AS SOURCE_TABLES_PROCESSED,
    CAST(NULL AS VARCHAR(16777216)) AS TARGET_TABLES_UPDATED,
    CAST(NULL AS NUMBER) AS RECORDS_PROCESSED,
    CAST(NULL AS NUMBER) AS RECORDS_INSERTED,
    CAST(NULL AS NUMBER) AS RECORDS_UPDATED,
    CAST(NULL AS NUMBER) AS RECORDS_REJECTED,
    CAST(NULL AS VARCHAR(255)) AS EXECUTED_BY,
    CAST(NULL AS VARCHAR(255)) AS EXECUTION_ENVIRONMENT,
    CAST(NULL AS VARCHAR(16777216)) AS DATA_LINEAGE_INFO,
    CAST(NULL AS DATE) AS LOAD_DATE,
    CAST(NULL AS DATE) AS UPDATE_DATE,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_SYSTEM
WHERE FALSE
