{{ config(
    materialized='table',
    on_schema_change='sync_all_columns'
) }}

-- Silver Layer Audit Log Table
-- This table tracks all pipeline executions and data quality metrics

SELECT
    {{ dbt_utils.generate_surrogate_key(['CURRENT_TIMESTAMP()', "'INITIAL_LOAD'", "'AUDIT_LOG'"]) }} AS EXECUTION_ID,
    'AUDIT_LOG_INITIALIZATION' AS PIPELINE_NAME,
    CURRENT_TIMESTAMP() AS START_TIME,
    CURRENT_TIMESTAMP() AS END_TIME,
    'SUCCESS' AS STATUS,
    NULL AS ERROR_MESSAGE,
    0 AS EXECUTION_DURATION_SECONDS,
    'SYSTEM_INITIALIZATION' AS SOURCE_TABLES_PROCESSED,
    'SI_PIPELINE_AUDIT' AS TARGET_TABLES_UPDATED,
    1 AS RECORDS_PROCESSED,
    1 AS RECORDS_INSERTED,
    0 AS RECORDS_UPDATED,
    0 AS RECORDS_REJECTED,
    'DBT_SYSTEM' AS EXECUTED_BY,
    'PROD' AS EXECUTION_ENVIRONMENT,
    'Initial audit log setup for Silver layer pipeline' AS DATA_LINEAGE_INFO,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    'Silver Layer Pipeline' AS SOURCE_SYSTEM

WHERE FALSE -- This ensures no actual records are inserted during initialization

UNION ALL

-- This will be populated by post-hooks from other models
SELECT
    NULL AS EXECUTION_ID,
    NULL AS PIPELINE_NAME,
    NULL AS START_TIME,
    NULL AS END_TIME,
    NULL AS STATUS,
    NULL AS ERROR_MESSAGE,
    NULL AS EXECUTION_DURATION_SECONDS,
    NULL AS SOURCE_TABLES_PROCESSED,
    NULL AS TARGET_TABLES_UPDATED,
    NULL AS RECORDS_PROCESSED,
    NULL AS RECORDS_INSERTED,
    NULL AS RECORDS_UPDATED,
    NULL AS RECORDS_REJECTED,
    NULL AS EXECUTED_BY,
    NULL AS EXECUTION_ENVIRONMENT,
    NULL AS DATA_LINEAGE_INFO,
    NULL AS LOAD_DATE,
    NULL AS UPDATE_DATE,
    NULL AS SOURCE_SYSTEM
WHERE FALSE
