version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: BZ_USERS
        description: "Raw user profile and subscription information"
        columns:
          - name: USER_ID
            description: "Unique identifier for each user account"
          - name: USER_NAME
            description: "Display name of the user"
          - name: EMAIL
            description: "Email address of the user"
          - name: COMPANY
            description: "Company or organization name"
          - name: PLAN_TYPE
            description: "Subscription plan type"
      
      - name: BZ_MEETINGS
        description: "Raw meeting information and session details"
        columns:
          - name: MEETING_ID
            description: "Unique identifier for each meeting"
          - name: HOST_ID
            description: "User ID of the meeting host"
          - name: DURATION_MINUTES
            description: "Meeting duration in minutes (may contain text units)"
      
      - name: BZ_PARTICIPANTS
        description: "Raw meeting participants and their session details"
        columns:
          - name: PARTICIPANT_ID
            description: "Unique identifier for each meeting participant"
          - name: JOIN_TIME
            description: "Timestamp when participant joined (various formats)"
          - name: LEAVE_TIME
            description: "Timestamp when participant left (various formats)"
      
      - name: BZ_FEATURE_USAGE
        description: "Raw platform feature usage during meetings"
      
      - name: BZ_SUPPORT_TICKETS
        description: "Raw customer support requests and resolution tracking"
      
      - name: BZ_BILLING_EVENTS
        description: "Raw financial transactions and billing activities"
      
      - name: BZ_LICENSES
        description: "Raw license assignments and entitlements"
        columns:
          - name: START_DATE
            description: "License validity start date (may be DD/MM/YYYY format)"
          - name: END_DATE
            description: "License validity end date (may be DD/MM/YYYY format)"

models:
  - name: SI_Audit_Log
    description: "Audit log table for Silver layer pipeline execution tracking"
    columns:
      - name: TABLE_NAME
        description: "Name of the table being processed"
      - name: PROCESS_STATUS
        description: "Status of the process (STARTED, COMPLETED, FAILED)"
      - name: AUDIT_TIMESTAMP
        description: "Timestamp of the audit entry"
  
  - name: SI_USERS
    description: "Cleaned and standardized user profile and subscription information"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user account"
      - name: EMAIL
        description: "Validated and standardized email address"
      - name: PLAN_TYPE
        description: "Standardized subscription plan type"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
  
  - name: SI_MEETINGS
    description: "Cleaned and standardized meeting information with duration text cleaning"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes (cleaned from text units)"
      - name: START_TIME
        description: "Meeting start timestamp (EST format converted)"
      - name: END_TIME
        description: "Meeting end timestamp (EST format converted)"
  
  - name: SI_PARTICIPANTS
    description: "Cleaned and standardized meeting participants with timestamp format handling"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each meeting participant"
      - name: JOIN_TIME
        description: "Participant join timestamp (MM/DD/YYYY format converted)"
      - name: LEAVE_TIME
        description: "Participant leave timestamp (MM/DD/YYYY format converted)"
  
  - name: SI_FEATURE_USAGE
    description: "Cleaned and standardized platform feature usage"
  
  - name: SI_SUPPORT_TICKETS
    description: "Cleaned and standardized customer support requests"
  
  - name: SI_BILLING_EVENTS
    description: "Cleaned and standardized financial transactions"
  
  - name: SI_LICENSES
    description: "Cleaned and standardized license assignments with DD/MM/YYYY date conversion"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
      - name: START_DATE
        description: "License validity start date (DD/MM/YYYY format converted)"
      - name: END_DATE
        description: "License validity end date (DD/MM/YYYY format converted)"
