version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: BZ_USERS
        description: "Raw user profile and subscription information"
      - name: BZ_MEETINGS
        description: "Raw meeting information and session details"
      - name: BZ_PARTICIPANTS
        description: "Raw meeting participants and their session details"
      - name: BZ_FEATURE_USAGE
        description: "Raw usage of platform features during meetings"
      - name: BZ_SUPPORT_TICKETS
        description: "Raw customer support requests and resolution tracking"
      - name: BZ_BILLING_EVENTS
        description: "Raw financial transactions and billing activities"
      - name: BZ_LICENSES
        description: "Raw license assignments and entitlements"

models:
  - name: SI_Audit_Log
    description: "Silver layer audit log for tracking pipeline operations and errors"
  - name: SI_Users
    description: "Silver layer table storing cleaned and standardized user profile and subscription information"
  - name: SI_Meetings
    description: "Silver layer table storing cleaned and standardized meeting information with critical format fixes"
  - name: SI_Participants
    description: "Silver layer table storing cleaned and standardized meeting participants with multi-format timestamp support"
  - name: SI_Feature_Usage
    description: "Silver layer table storing cleaned and standardized platform feature usage"
  - name: SI_Support_Tickets
    description: "Silver layer table storing cleaned and standardized customer support requests"
  - name: SI_Billing_Events
    description: "Silver layer table storing cleaned and standardized financial transactions"
  - name: SI_Licenses
    description: "Silver layer table storing cleaned and standardized license assignments with critical DD/MM/YYYY date format conversion"
