version: 2

sources:
  - name: bronze
    description: Bronze layer tables containing raw data
    tables:
      - name: bz_users
        description: Raw user data from source systems
      - name: bz_meetings
        description: Raw meeting data from source systems
      - name: bz_participants
        description: Raw participant data from source systems
      - name: bz_feature_usage
        description: Raw feature usage data from source systems
      - name: bz_support_tickets
        description: Raw support ticket data from source systems
      - name: bz_billing_events
        description: Raw billing event data from source systems
      - name: bz_licenses
        description: Raw license data from source systems
      - name: bz_webinars
        description: Raw webinar data from source systems
      - name: bz_audit_records
        description: Raw audit records from bronze layer

models:
  - name: audit_log
    description: Audit log for tracking pipeline execution
    columns:
      - name: audit_id
        description: Unique identifier for audit records
        tests:
          - not_null
          - unique
      - name: source_table
        description: Name of the source table being processed
        tests:
          - not_null
  
  - name: si_users
    description: Cleaned and standardized user data
    columns:
      - name: user_id
        description: Unique identifier for users
        tests:
          - not_null
          - unique
      - name: email
        description: Validated email address
        tests:
          - not_null
      - name: plan_type
        description: Standardized subscription plan
        tests:
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE', 'UNKNOWN']
      - name: account_status
        description: Current account status
        tests:
          - accepted_values:
              values: ['ACTIVE', 'INACTIVE', 'SUSPENDED']
  
  - name: si_meetings
    description: Cleaned and enriched meeting data
    columns:
      - name: meeting_id
        description: Unique identifier for meetings
        tests:
          - not_null
          - unique
      - name: host_id
        description: Reference to user who hosted the meeting
        tests:
          - not_null
      - name: meeting_type
        description: Categorized meeting type
        tests:
          - accepted_values:
              values: ['SCHEDULED', 'INSTANT', 'WEBINAR']
      - name: meeting_status
        description: Current meeting status
        tests:
          - accepted_values:
              values: ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED']
  
  - name: si_participants
    description: Cleaned participant attendance data
    columns:
      - name: participant_id
        description: Unique identifier for participants
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: Reference to meeting
        tests:
          - not_null
      - name: user_id
        description: Reference to participating user
        tests:
          - not_null
      - name: participant_role
        description: Role of the participant
        tests:
          - accepted_values:
              values: ['HOST', 'PARTICIPANT']
  
  - name: si_feature_usage
    description: Standardized feature usage data
    columns:
      - name: usage_id
        description: Unique identifier for feature usage
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: Reference to meeting where feature was used
        tests:
          - not_null
      - name: feature_category
        description: Categorized feature type
        tests:
          - accepted_values:
              values: ['AUDIO', 'VIDEO', 'COLLABORATION', 'SECURITY', 'OTHER']
  
  - name: si_support_tickets
    description: Standardized support ticket data
    columns:
      - name: ticket_id
        description: Unique identifier for support tickets
        tests:
          - not_null
          - unique
      - name: user_id
        description: Reference to user who created the ticket
        tests:
          - not_null
      - name: ticket_type
        description: Standardized ticket category
        tests:
          - accepted_values:
              values: ['TECHNICAL', 'BILLING', 'FEATURE REQUEST', 'BUG REPORT', 'OTHER']
      - name: priority_level
        description: Ticket priority level
        tests:
          - accepted_values:
              values: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
      - name: resolution_status
        description: Current resolution status
        tests:
          - accepted_values:
              values: ['OPEN', 'IN PROGRESS', 'RESOLVED', 'CLOSED']
  
  - name: si_billing_events
    description: Validated billing transaction data
    columns:
      - name: event_id
        description: Unique identifier for billing events
        tests:
          - not_null
          - unique
      - name: user_id
        description: Reference to user associated with billing event
        tests:
          - not_null
      - name: event_type
        description: Standardized billing event type
        tests:
          - accepted_values:
              values: ['SUBSCRIPTION', 'UPGRADE', 'DOWNGRADE', 'REFUND', 'OTHER']
      - name: currency_code
        description: ISO currency code
        tests:
          - accepted_values:
              values: ['USD', 'EUR', 'GBP']
  
  - name: si_licenses
    description: Validated license management data
    columns:
      - name: license_id
        description: Unique identifier for licenses
        tests:
          - not_null
          - unique
      - name: license_type
        description: Standardized license category
        tests:
          - accepted_values:
              values: ['BASIC', 'PRO', 'ENTERPRISE', 'ADD-ON']
      - name: license_status
        description: Current license status
        tests:
          - accepted_values:
              values: ['ACTIVE', 'EXPIRED', 'SUSPENDED']
  
  - name: si_webinars
    description: Cleaned webinar data with engagement metrics
    columns:
      - name: webinar_id
        description: Unique identifier for webinars
        tests:
          - not_null
          - unique
      - name: host_id
        description: Reference to user who hosted the webinar
        tests:
          - not_null
