version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: bz_users
        description: "Bronze users table with raw user data"
      - name: bz_meetings
        description: "Bronze meetings table with raw meeting data"
      - name: bz_participants
        description: "Bronze participants table with raw participant data"
      - name: bz_billing_events
        description: "Bronze billing events table with raw billing data"
      - name: bz_licenses
        description: "Bronze licenses table with raw license data"
      - name: bz_feature_usage
        description: "Bronze feature usage table with raw feature usage data"
      - name: bz_support_tickets
        description: "Bronze support tickets table with raw support ticket data"
      - name: bz_webinars
        description: "Bronze webinars table with raw webinar data"

models:
  - name: audit_log
    description: "Silver layer audit log for tracking pipeline executions"
    columns:
      - name: audit_id
        description: "Unique identifier for audit record"
        tests:
          - unique
          - not_null
      - name: pipeline_name
        description: "Name of the pipeline being executed"
        tests:
          - not_null
      - name: execution_status
        description: "Status of pipeline execution"
        tests:
          - accepted_values:
              values: ['INITIALIZED', 'STARTED', 'RUNNING', 'COMPLETED', 'FAILED']
              
  - name: si_users
    description: "Silver layer users table with cleansed and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for user"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "User display name"
        tests:
          - not_null
      - name: email
        description: "User email address (validated and standardized)"
        tests:
          - not_null
          - unique
      - name: plan_type
        description: "User subscription plan type"
        tests:
          - accepted_values:
              values: ['Free', 'Basic', 'Pro', 'Enterprise']
      - name: data_quality_score
        description: "Data quality score (0.00-1.00)"
        tests:
          - not_null
              
  - name: si_meetings
    description: "Silver layer meetings table with validated meeting data and derived attributes"
    columns:
      - name: meeting_id
        description: "Unique identifier for meeting"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "Meeting host user identifier"
        tests:
          - not_null
      - name: duration_minutes
        description: "Meeting duration in minutes"
      - name: data_quality_score
        description: "Data quality score (0.00-1.00)"
        tests:
          - not_null
              
  - name: si_participants
    description: "Silver layer participants table with attendance metrics and engagement scores"
    columns:
      - name: participant_id
        description: "Unique identifier for participant record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier"
        tests:
          - not_null
      - name: user_id
        description: "Participant user identifier"
        tests:
          - not_null
      - name: engagement_score
        description: "Engagement score (0.00-1.00)"
              
  - name: si_billing_events
    description: "Silver layer billing events table with validated and standardized billing data"
    columns:
      - name: billing_event_id
        description: "Unique identifier for billing event"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "User identifier for billing event"
        tests:
          - not_null
      - name: event_type
        description: "Standardized billing event type"
        tests:
          - accepted_values:
              values: ['Payment', 'Refund', 'Subscription', 'Upgrade', 'Downgrade']
      - name: amount
        description: "Billing amount (validated)"
        tests:
          - not_null
      - name: currency_code
        description: "Currency code (ISO standard)"
        tests:
          - not_null
          - accepted_values:
              values: ['USD']
              
  - name: si_licenses
    description: "Silver layer licenses table with license management and lifecycle tracking"
    columns:
      - name: license_id
        description: "Unique identifier for license"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Type of license"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Add-on']
      - name: license_status
        description: "Current status of license"
        tests:
          - accepted_values:
              values: ['Active', 'Expired', 'Suspended']
              
  - name: si_feature_usage
    description: "Silver layer feature usage table with usage analytics and categorization"
    columns:
      - name: feature_usage_id
        description: "Unique identifier for feature usage record"
        tests:
          - unique
          - not_null
      - name: feature_category
        description: "Category of feature used"
        tests:
          - accepted_values:
              values: ['Audio', 'Video', 'Screen Share', 'Chat', 'Recording', 'Other']
      - name: usage_pattern
        description: "Usage intensity pattern"
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High']
              
  - name: si_support_tickets
    description: "Silver layer support tickets table with SLA tracking and resolution analytics"
    columns:
      - name: support_ticket_id
        description: "Unique identifier for support ticket"
        tests:
          - unique
          - not_null
      - name: ticket_type
        description: "Standardized ticket type"
        tests:
          - accepted_values:
              values: ['Technical', 'Billing', 'Feature Request', 'General']
      - name: resolution_status
        description: "Current resolution status"
        tests:
          - accepted_values:
              values: ['Open', 'In Progress', 'Resolved', 'Closed']
      - name: priority_level
        description: "Priority level of ticket"
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High', 'Critical']
              
  - name: si_webinars
    description: "Silver layer webinars table with attendance analytics and performance metrics"
    columns:
      - name: webinar_id
        description: "Unique identifier for webinar"
        tests:
          - unique
          - not_null
      - name: webinar_category
        description: "Category of webinar"
        tests:
          - accepted_values:
              values: ['Training', 'Product Demo', 'Marketing', 'General']
      - name: attendance_rate
        description: "Percentage attendance rate"
