version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user data from Zoom platform"
      - name: bz_meetings
        description: "Raw meeting data from Zoom platform"
      - name: bz_participants
        description: "Raw participant data from Zoom platform"
      - name: bz_feature_usage
        description: "Raw feature usage data from Zoom platform"
      - name: bz_support_tickets
        description: "Raw support ticket data from Zoom platform"
      - name: bz_billing_events
        description: "Raw billing event data from Zoom platform"
      - name: bz_licenses
        description: "Raw license data from Zoom platform"

models:
  - name: si_pipeline_audit
    description: "Audit table for tracking pipeline execution and data quality metrics"
  
  - name: si_users
    description: "Cleansed and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - unique
          - not_null
      - name: email
        description: "Validated and standardized email address"
        tests:
          - not_null
  
  - name: si_meetings
    description: "Cleansed and standardized meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for meetings"
        tests:
          - unique
          - not_null
  
  - name: si_participants
    description: "Cleansed participant data with calculated attendance duration"
    columns:
      - name: participant_id
        description: "Unique identifier for participants"
        tests:
          - unique
          - not_null
  
  - name: si_feature_usage
    description: "Cleansed feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for usage records"
        tests:
          - unique
          - not_null
  
  - name: si_support_tickets
    description: "Cleansed support ticket data with calculated resolution metrics"
    columns:
      - name: ticket_id
        description: "Unique identifier for support tickets"
        tests:
          - unique
          - not_null
  
  - name: si_billing_events
    description: "Cleansed billing event data with currency standardization"
    columns:
      - name: event_id
        description: "Unique identifier for billing events"
        tests:
          - unique
          - not_null
  
  - name: si_licenses
    description: "Cleansed license data with calculated status and expiry metrics"
    columns:
      - name: license_id
        description: "Unique identifier for licenses"
        tests:
          - unique
          - not_null
