version: 2

models:
  - name: SI_AUDIT_LOG
    description: "Independent Silver audit table for comprehensive tracking of all Silver layer operations"
    
  - name: SI_USERS
    description: "Silver layer table storing cleaned and standardized user profile and subscription information"
    
  - name: SI_MEETINGS
    description: "Silver layer table storing cleaned and standardized meeting information with numeric field cleaning"
    
  - name: SI_PARTICIPANTS
    description: "Silver layer table storing cleaned and standardized meeting participants with timestamp format handling"
    
  - name: SI_FEATURE_USAGE
    description: "Silver layer table storing cleaned and standardized platform feature usage during meetings"
    
  - name: SI_SUPPORT_TICKETS
    description: "Silver layer table storing cleaned and standardized customer support requests"
    
  - name: SI_BILLING_EVENTS
    description: "Silver layer table storing cleaned and standardized financial transactions and billing activities"
    
  - name: SI_LICENSES
    description: "Silver layer table storing cleaned and standardized license assignments with date format conversion"
