version: 2

sources:
  - name: bronze
    description: Bronze layer tables containing raw data
    tables:
      - name: bz_users
        description: Raw user data from bronze layer
        columns:
          - name: user_id
            description: Unique identifier for users
          - name: user_name
            description: User display name
          - name: email
            description: User email address
          - name: company
            description: User company
          - name: plan_type
            description: Subscription plan type
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
      
      - name: bz_meetings
        description: Raw meeting data from bronze layer
        columns:
          - name: meeting_id
            description: Unique identifier for meetings
          - name: host_id
            description: Meeting host user ID
          - name: meeting_topic
            description: Meeting topic or title
          - name: start_time
            description: Meeting start time
          - name: end_time
            description: Meeting end time
          - name: duration_minutes
            description: Meeting duration in minutes
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
      
      - name: bz_participants
        description: Raw participant data from bronze layer
        columns:
          - name: participant_id
            description: Unique identifier for participants
          - name: meeting_id
            description: Associated meeting ID
          - name: user_id
            description: Participant user ID
          - name: join_time
            description: Time participant joined
          - name: leave_time
            description: Time participant left
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
      
      - name: bz_feature_usage
        description: Raw feature usage data from bronze layer
        columns:
          - name: usage_id
            description: Unique identifier for usage records
          - name: meeting_id
            description: Associated meeting ID
          - name: feature_name
            description: Name of the feature used
          - name: usage_count
            description: Number of times feature was used
          - name: usage_date
            description: Date of feature usage
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
      
      - name: bz_support_tickets
        description: Raw support ticket data from bronze layer
        columns:
          - name: ticket_id
            description: Unique identifier for support tickets
          - name: user_id
            description: User who created the ticket
          - name: ticket_type
            description: Type of support ticket
          - name: resolution_status
            description: Current resolution status
          - name: open_date
            description: Date ticket was opened
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
      
      - name: bz_billing_events
        description: Raw billing event data from bronze layer
        columns:
          - name: event_id
            description: Unique identifier for billing events
          - name: user_id
            description: Associated user ID
          - name: event_type
            description: Type of billing event
          - name: amount
            description: Transaction amount
          - name: event_date
            description: Date of billing event
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
      
      - name: bz_licenses
        description: Raw license data from bronze layer
        columns:
          - name: license_id
            description: Unique identifier for licenses
          - name: license_type
            description: Type of license
          - name: assigned_to_user_id
            description: User assigned to license
          - name: start_date
            description: License start date
          - name: end_date
            description: License end date
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
      
      - name: bz_webinars
        description: Raw webinar data from bronze layer
        columns:
          - name: webinar_id
            description: Unique identifier for webinars
          - name: host_id
            description: Webinar host user ID
          - name: webinar_topic
            description: Webinar topic or title
          - name: start_time
            description: Webinar start time
          - name: end_time
            description: Webinar end time
          - name: registrants
            description: Number of registrants
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier

models:
  - name: audit_log
    description: Audit log for tracking Silver layer processing
    columns:
      - name: audit_id
        description: Unique identifier for audit records
        tests:
          - unique
          - not_null
      - name: table_name
        description: Name of the table being processed
        tests:
          - not_null
      - name: process_start_time
        description: Process start timestamp
        tests:
          - not_null
      - name: process_end_time
        description: Process end timestamp
      - name: status
        description: Process status
        tests:
          - accepted_values:
              values: ['STARTED', 'COMPLETED', 'FAILED']
      - name: records_processed
        description: Number of records processed
      - name: created_at
        description: Record creation timestamp
      - name: updated_at
        description: Record update timestamp

  - name: si_users
    description: Silver layer users table with cleaned and validated data
    columns:
      - name: user_id
        description: Unique identifier for users
        tests:
          - unique
          - not_null
      - name: user_name
        description: Standardized user name
        tests:
          - not_null
      - name: email
        description: Validated email address
        tests:
          - not_null
      - name: company
        description: Standardized company name
      - name: plan_type
        description: Validated plan type
        tests:
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE', 'UNKNOWN']
      - name: registration_date
        description: User registration date
      - name: last_login_date
        description: Last login date
      - name: account_status
        description: Account status
        tests:
          - accepted_values:
              values: ['Active', 'Inactive']
      - name: data_quality_score
        description: Data quality score (0.00 to 1.00)
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1

  - name: si_meetings
    description: Silver layer meetings table with cleaned and enriched data
    columns:
      - name: meeting_id
        description: Unique identifier for meetings
        tests:
          - unique
          - not_null
      - name: host_id
        description: Meeting host user ID
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: meeting_topic
        description: Meeting topic
      - name: meeting_type
        description: Meeting type
        tests:
          - accepted_values:
              values: ['Webinar', 'Instant', 'Personal', 'Scheduled']
      - name: start_time
        description: Meeting start time
        tests:
          - not_null
      - name: end_time
        description: Meeting end time
        tests:
          - not_null
      - name: duration_minutes
        description: Meeting duration in minutes
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1440
      - name: participant_count
        description: Number of participants
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10000
      - name: data_quality_score
        description: Data quality score (0.00 to 1.00)
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1
