version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: BZ_USERS
        description: "Raw user profile and subscription information"
      - name: BZ_MEETINGS
        description: "Raw meeting information and session details"
      - name: BZ_PARTICIPANTS
        description: "Raw meeting participants and their session details"
      - name: BZ_FEATURE_USAGE
        description: "Raw usage of platform features during meetings"
      - name: BZ_SUPPORT_TICKETS
        description: "Raw customer support requests and resolution tracking"
      - name: BZ_BILLING_EVENTS
        description: "Raw financial transactions and billing activities"
      - name: BZ_LICENSES
        description: "Raw license assignments and entitlements"

models:
  - name: SI_Audit_Log
    description: "Audit table for comprehensive tracking of all Silver layer pipeline executions"
    
  - name: SI_USERS
    description: "Silver layer table storing cleaned and standardized user profile and subscription information"
    
  - name: SI_MEETINGS
    description: "Silver layer table storing cleaned and standardized meeting information and session details"
    
  - name: SI_PARTICIPANTS
    description: "Silver layer table storing cleaned and standardized meeting participants and their session details"
    
  - name: SI_FEATURE_USAGE
    description: "Silver layer table storing cleaned and standardized platform feature usage during meetings"
    
  - name: SI_SUPPORT_TICKETS
    description: "Silver layer table storing cleaned and standardized customer support requests and resolution tracking"
    
  - name: SI_BILLING_EVENTS
    description: "Silver layer table storing cleaned and standardized financial transactions and billing activities"
    
  - name: SI_LICENSES
    description: "Silver layer table storing cleaned and standardized license assignments and entitlements"
