version: 2

sources:
  - name: bronze
    database: DB_POC_ZOOM
    schema: BRONZE
    tables:
      - name: bz_users
      - name: bz_meetings
      - name: bz_participants
      - name: bz_feature_usage
      - name: bz_support_tickets
      - name: bz_billing_events
      - name: bz_licenses
      - name: bz_webinars

models:
  - name: si_pipeline_audit
    description: "Audit log table for tracking Silver layer pipeline execution"
    columns:
      - name: EXECUTION_ID
        description: "Unique identifier for each pipeline execution"
      - name: PIPELINE_NAME
        description: "Name of the data pipeline or process"
      - name: START_TIME
        description: "When the pipeline execution started"
      - name: END_TIME
        description: "When the pipeline execution completed"
      - name: STATUS
        description: "Status (Success, Failed, Partial Success, Cancelled)"

  - name: si_users
    description: "Silver layer table containing cleaned and standardized user data"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user account"
      - name: USER_NAME
        description: "Standardized full name of the registered user"
      - name: EMAIL
        description: "Validated and standardized email address"
      - name: PLAN_TYPE
        description: "Standardized subscription tier"
      - name: DATA_QUALITY_SCORE
        description: "Overall data quality score for the record (0.00 to 1.00)"

  - name: si_meetings
    description: "Silver layer table containing cleaned and enriched meeting data"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
      - name: HOST_ID
        description: "User ID of the meeting host"
      - name: MEETING_TOPIC
        description: "Cleaned and standardized meeting subject"
      - name: DURATION_MINUTES
        description: "Calculated meeting duration in minutes"

  - name: si_participants
    description: "Silver layer table containing cleaned participant attendance data"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each participant record"
      - name: MEETING_ID
        description: "Reference to meeting"
      - name: USER_ID
        description: "Reference to user who participated"

  - name: si_feature_usage
    description: "Silver layer table containing standardized feature usage data"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for each feature usage record"
      - name: FEATURE_NAME
        description: "Standardized name of the platform feature"

  - name: si_support_tickets
    description: "Silver layer table containing standardized support ticket data"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for each support ticket"
      - name: TICKET_TYPE
        description: "Standardized category"

  - name: si_billing_events
    description: "Silver layer table containing validated billing transaction data"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for each billing event"
      - name: TRANSACTION_AMOUNT
        description: "Validated monetary value"

  - name: si_licenses
    description: "Silver layer table containing validated license data"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
      - name: LICENSE_TYPE
        description: "Standardized category"

  - name: si_webinars
    description: "Silver layer table containing cleaned webinar data"
    columns:
      - name: WEBINAR_ID
        description: "Unique identifier for each webinar"
      - name: ATTENDANCE_RATE
        description: "Percentage of registrants who attended"
