version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: BZ_USERS
        description: "Raw user profile and subscription information"
        columns:
          - name: USER_ID
            description: "Unique identifier for each user account"
          - name: USER_NAME
            description: "Display name of the user (PII)"
          - name: EMAIL
            description: "Email address of the user (PII)"
          - name: COMPANY
            description: "Company or organization name"
          - name: PLAN_TYPE
            description: "Subscription plan type"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded into Bronze layer"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system from which data originated"
            
      - name: BZ_MEETINGS
        description: "Raw meeting information and session details"
        columns:
          - name: MEETING_ID
            description: "Unique identifier for each meeting"
          - name: HOST_ID
            description: "User ID of the meeting host"
          - name: MEETING_TOPIC
            description: "Topic or title of the meeting"
          - name: START_TIME
            description: "Meeting start timestamp (may include EST timezone)"
          - name: END_TIME
            description: "Meeting end timestamp (may include EST timezone)"
          - name: DURATION_MINUTES
            description: "Meeting duration in minutes"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded into Bronze layer"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system from which data originated"
            
      - name: BZ_PARTICIPANTS
        description: "Raw meeting participants and their session details"
        columns:
          - name: PARTICIPANT_ID
            description: "Unique identifier for each meeting participant"
          - name: MEETING_ID
            description: "Reference to meeting"
          - name: USER_ID
            description: "Reference to user who participated"
          - name: JOIN_TIME
            description: "Timestamp when participant joined (may be MM/DD/YYYY HH:MM format)"
          - name: LEAVE_TIME
            description: "Timestamp when participant left (may be MM/DD/YYYY HH:MM format)"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded into Bronze layer"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system from which data originated"
            
      - name: BZ_FEATURE_USAGE
        description: "Raw usage of platform features during meetings"
      - name: BZ_SUPPORT_TICKETS
        description: "Raw customer support requests and resolution tracking"
      - name: BZ_BILLING_EVENTS
        description: "Raw financial transactions and billing activities"
      - name: BZ_LICENSES
        description: "Raw license assignments and entitlements"

models:
  - name: SI_Audit_Log
    description: "Silver layer audit log for tracking pipeline executions and data quality metrics"
    columns:
      - name: EXECUTION_ID
        description: "Unique identifier for each pipeline execution"
      - name: PIPELINE_NAME
        description: "Name of the pipeline being executed"
      - name: EXECUTION_STATUS
        description: "Status of pipeline execution (RUNNING, SUCCESS, FAILED)"
      - name: SOURCE_TABLE
        description: "Bronze table being processed"
      - name: TARGET_TABLE
        description: "Silver table being populated"
      - name: RECORDS_PROCESSED
        description: "Number of records processed"
      - name: RECORDS_SUCCESS
        description: "Number of records successfully loaded"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when audit record was created"
        
  - name: SI_USERS
    description: "Silver layer users table with cleaned and standardized user data"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user account"
        tests:
          - unique
          - not_null
      - name: USER_NAME
        description: "Standardized display name of the user"
      - name: EMAIL
        description: "Validated and standardized email address"
      - name: COMPANY
        description: "Standardized company or organization name"
      - name: PLAN_TYPE
        description: "Standardized subscription plan type (FREE, BASIC, PRO, ENTERPRISE)"
        tests:
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE']
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_MEETINGS
    description: "Silver layer meetings table with timezone-converted and validated meeting data"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
        tests:
          - unique
          - not_null
      - name: HOST_ID
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: START_TIME
        description: "Meeting start timestamp (converted from EST to UTC if needed)"
        tests:
          - not_null
      - name: END_TIME
        description: "Meeting end timestamp (converted from EST to UTC if needed)"
        tests:
          - not_null
      - name: DURATION_MINUTES
        description: "Validated meeting duration in minutes"
      - name: DATA_QUALITY_SCORE
        description: "Quality score including timestamp format validation (0-100)"
      - name: VALIDATION_STATUS
        description: "Status including timestamp format validation (PASSED, FAILED, WARNING)"
        
  - name: SI_PARTICIPANTS
    description: "Silver layer participants table with format-converted timestamps"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each meeting participant"
        tests:
          - unique
          - not_null
      - name: MEETING_ID
        description: "Reference to meeting"
        tests:
          - not_null
      - name: USER_ID
        description: "Reference to user who participated"
        tests:
          - not_null
      - name: JOIN_TIME
        description: "Participant join timestamp (converted from MM/DD/YYYY HH:MM if needed)"
        tests:
          - not_null
      - name: LEAVE_TIME
        description: "Participant leave timestamp (converted from MM/DD/YYYY HH:MM if needed)"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Quality score including timestamp format validation (0-100)"
      - name: VALIDATION_STATUS
        description: "Status including timestamp format validation (PASSED, FAILED, WARNING)"
        
  - name: SI_FEATURE_USAGE
    description: "Silver layer feature usage table with standardized feature names"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for each feature usage record"
        tests:
          - unique
          - not_null
      - name: MEETING_ID
        description: "Reference to meeting where feature was used"
        tests:
          - not_null
      - name: FEATURE_NAME
        description: "Standardized name of the feature being tracked"
      - name: USAGE_COUNT
        description: "Validated number of times feature was used"
        
  - name: SI_SUPPORT_TICKETS
    description: "Silver layer support tickets table with standardized status values"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for each support ticket"
        tests:
          - unique
          - not_null
      - name: USER_ID
        description: "Reference to user who created the ticket"
        tests:
          - not_null
      - name: RESOLUTION_STATUS
        description: "Standardized current status of ticket resolution"
        tests:
          - accepted_values:
              values: ['OPEN', 'IN PROGRESS', 'RESOLVED', 'CLOSED']
              
  - name: SI_BILLING_EVENTS
    description: "Silver layer billing events table with validated amounts"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for each billing event"
        tests:
          - unique
          - not_null
      - name: USER_ID
        description: "Reference to user associated with billing event"
        tests:
          - not_null
      - name: AMOUNT
        description: "Validated and standardized monetary amount"
        
  - name: SI_LICENSES
    description: "Silver layer licenses table with validated date ranges"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
        tests:
          - unique
          - not_null
      - name: ASSIGNED_TO_USER_ID
        description: "User ID to whom license is assigned"
        tests:
          - not_null
      - name: START_DATE
        description: "Validated license validity start date"
        tests:
          - not_null
      - name: END_DATE
        description: "Validated license validity end date"
        tests:
          - not_null
