version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: BZ_USERS
        description: "Raw user profile and subscription information"
      - name: BZ_MEETINGS
        description: "Raw meeting information and session details"
      - name: BZ_PARTICIPANTS
        description: "Raw meeting participants and their session details"
      - name: BZ_FEATURE_USAGE
        description: "Raw usage of platform features during meetings"
      - name: BZ_SUPPORT_TICKETS
        description: "Raw customer support requests and resolution tracking"
      - name: BZ_BILLING_EVENTS
        description: "Raw financial transactions and billing activities"
      - name: BZ_LICENSES
        description: "Raw license assignments and entitlements"

models:
  - name: SI_AUDIT_LOG
    description: "Audit log table for Silver layer pipeline execution tracking"
    columns:
      - name: MODEL_NAME
        description: "Name of the dbt model being executed"
      - name: SOURCE_TABLE
        description: "Name of the source Bronze table"
      - name: TARGET_TABLE
        description: "Name of the target Silver table"
      - name: PROCESS_START_TIME
        description: "Timestamp when the process started"
      - name: PROCESS_END_TIME
        description: "Timestamp when the process ended"
      - name: DURATION_SECONDS
        description: "Duration of the process in seconds"
      - name: STATUS
        description: "Status of the process (STARTED, COMPLETED, FAILED)"
      - name: RECORDS_PROCESSED
        description: "Number of records processed"
      - name: RECORDS_SUCCESS
        description: "Number of records successfully processed"
      - name: RECORDS_FAILED
        description: "Number of records that failed processing"
      - name: ERROR_DETAILS
        description: "Details of any errors encountered"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when the audit record was created"
        
  - name: SI_USERS
    description: "Silver layer table storing cleaned and standardized user profile and subscription information"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user account"
        tests:
          - unique
          - not_null
      - name: USER_NAME
        description: "Display name of the user (cleaned and standardized format)"
      - name: EMAIL
        description: "Email address of the user (validated and standardized)"
        tests:
          - not_null
      - name: COMPANY
        description: "Company or organization name (cleaned and standardized)"
      - name: PLAN_TYPE
        description: "Subscription plan type (standardized values: Free, Basic, Pro, Enterprise)"
        tests:
          - accepted_values:
              values: ['Free', 'Basic', 'Pro', 'Enterprise']
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
        tests:
          - not_null
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
        tests:
          - not_null
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_MEETINGS
    description: "Silver layer table storing cleaned and standardized meeting information and session details"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
        tests:
          - unique
          - not_null
      - name: HOST_ID
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: MEETING_TOPIC
        description: "Topic or title of the meeting (cleaned and standardized)"
      - name: START_TIME
        description: "Meeting start timestamp (standardized timezone)"
        tests:
          - not_null
      - name: END_TIME
        description: "Meeting end timestamp (standardized timezone)"
        tests:
          - not_null
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes (validated and calculated)"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
        tests:
          - not_null
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
        tests:
          - not_null
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_PARTICIPANTS
    description: "Silver layer table storing cleaned and standardized meeting participants and their session details"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each meeting participant"
        tests:
          - unique
          - not_null
      - name: MEETING_ID
        description: "Reference to meeting"
        tests:
          - not_null
      - name: USER_ID
        description: "Reference to user who participated"
        tests:
          - not_null
      - name: JOIN_TIME
        description: "Timestamp when participant joined meeting (standardized timezone)"
        tests:
          - not_null
      - name: LEAVE_TIME
        description: "Timestamp when participant left meeting (standardized timezone)"
        tests:
          - not_null
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
        tests:
          - not_null
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
        tests:
          - not_null
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_FEATURE_USAGE
    description: "Silver layer table storing cleaned and standardized platform feature usage during meetings"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for each feature usage record"
        tests:
          - unique
          - not_null
      - name: MEETING_ID
        description: "Reference to meeting where feature was used"
        tests:
          - not_null
      - name: FEATURE_NAME
        description: "Name of the feature being tracked (standardized naming)"
        tests:
          - not_null
      - name: USAGE_COUNT
        description: "Number of times feature was used (validated)"
      - name: USAGE_DATE
        description: "Date when feature usage occurred (standardized format)"
        tests:
          - not_null
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
        tests:
          - not_null
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
        tests:
          - not_null
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_SUPPORT_TICKETS
    description: "Silver layer table storing cleaned and standardized customer support requests and resolution tracking"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for each support ticket"
        tests:
          - unique
          - not_null
      - name: USER_ID
        description: "Reference to user who created the ticket"
        tests:
          - not_null
      - name: TICKET_TYPE
        description: "Type of support ticket (standardized categories)"
        tests:
          - not_null
      - name: RESOLUTION_STATUS
        description: "Current status of ticket resolution (standardized values)"
        tests:
          - accepted_values:
              values: ['Open', 'In Progress', 'Resolved', 'Closed']
      - name: OPEN_DATE
        description: "Date when ticket was opened (standardized format)"
        tests:
          - not_null
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
        tests:
          - not_null
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
        tests:
          - not_null
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_BILLING_EVENTS
    description: "Silver layer table storing cleaned and standardized financial transactions and billing activities"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for each billing event"
        tests:
          - unique
          - not_null
      - name: USER_ID
        description: "Reference to user associated with billing event"
        tests:
          - not_null
      - name: EVENT_TYPE
        description: "Type of billing event (standardized categories)"
        tests:
          - not_null
      - name: AMOUNT
        description: "Monetary amount for the billing event (validated and standardized)"
      - name: EVENT_DATE
        description: "Date when the billing event occurred (standardized format)"
        tests:
          - not_null
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
        tests:
          - not_null
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
        tests:
          - not_null
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_LICENSES
    description: "Silver layer table storing cleaned and standardized license assignments and entitlements"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
        tests:
          - unique
          - not_null
      - name: LICENSE_TYPE
        description: "Type of license (standardized categories)"
        tests:
          - not_null
      - name: ASSIGNED_TO_USER_ID
        description: "User ID to whom license is assigned"
        tests:
          - not_null
      - name: START_DATE
        description: "License validity start date (standardized format)"
        tests:
          - not_null
      - name: END_DATE
        description: "License validity end date (standardized format)"
        tests:
          - not_null
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
        tests:
          - not_null
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
        tests:
          - not_null
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
