version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
            tests:
              - not_null
              - unique
          - name: email
            description: "Email address of the user"
            tests:
              - not_null
      
      - name: bz_meetings
        description: "Raw meeting session information"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of the meeting host"
            tests:
              - not_null
      
      - name: bz_participants
        description: "Raw meeting participant information"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to meeting"
            tests:
              - not_null
          - name: user_id
            description: "Reference to user who participated"
            tests:
              - not_null
      
      - name: bz_feature_usage
        description: "Raw platform feature usage tracking"
      - name: bz_support_tickets
        description: "Raw customer support ticket information"
      - name: bz_billing_events
        description: "Raw billing and financial transaction information"
      - name: bz_licenses
        description: "Raw license management information"
      - name: bz_webinars
        description: "Raw webinar session information"
      - name: bz_audit_records
        description: "Audit records from bronze layer processing"

models:
  - name: audit_log
    description: "Silver layer audit log for tracking pipeline execution"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
        tests:
          - not_null
          - unique
      - name: pipeline_name
        description: "Name of the data pipeline or process"
        tests:
          - not_null
      - name: status
        description: "Execution status"
        tests:
          - not_null
          - accepted_values:
              values: ['Success', 'Failed', 'Partial Success', 'In Progress']

  - name: si_users
    description: "Silver layer cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
      - name: email
        description: "Validated and standardized email address"
        tests:
          - not_null
      - name: plan_type
        description: "Standardized subscription tier"
        tests:
          - not_null
          - accepted_values:
              values: ['Free', 'Basic', 'Pro', 'Enterprise', 'Unknown']
      - name: account_status
        description: "Current status of user account"
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null

  - name: si_meetings
    description: "Silver layer cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: meeting_type
        description: "Standardized meeting category"
        tests:
          - not_null
          - accepted_values:
              values: ['Scheduled', 'Instant', 'Webinar', 'Personal']
      - name: meeting_status
        description: "Current state of the meeting"
        tests:
          - not_null
          - accepted_values:
              values: ['Scheduled', 'In Progress', 'Completed', 'Cancelled']
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null

  - name: si_participants
    description: "Silver layer cleaned participant attendance data"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting"
        tests:
          - not_null
          - relationships:
              to: ref('si_meetings')
              field: meeting_id
      - name: user_id
        description: "Reference to user who participated"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: attendance_duration
        description: "Time participant spent in meeting (minutes)"
        tests:
          - not_null
      - name: participant_role
        description: "Role of attendee"
        tests:
          - not_null
          - accepted_values:
              values: ['Host', 'Co-host', 'Participant', 'Observer']
      - name: connection_quality
        description: "Network connection quality during participation"
        tests:
          - not_null
          - accepted_values:
              values: ['Excellent', 'Good', 'Fair', 'Poor']
