version: 2

models:
  - name: SI_AUDIT_LOG
    description: "Independent Silver audit table for comprehensive tracking of all Silver layer operations"
    columns:
      - name: AUDIT_ID
        description: "Unique identifier for each audit record"
        tests:
          - not_null
      - name: TABLE_NAME
        description: "Name of the Silver layer table where operation occurred"
        tests:
          - not_null
      - name: COLUMN_NAME
        description: "Column name where operation occurred"
      - name: RECORD_ID
        description: "Primary key value of affected record"
      - name: ERROR_TYPE
        description: "Type of error or operation"
      - name: ERROR_DESCRIPTION
        description: "Detailed description of the operation or error"
      - name: ORIGINAL_VALUE
        description: "Original value before transformation"
      - name: AUDIT_TIMESTAMP
        description: "Timestamp when audit record was created"
        tests:
          - not_null
      - name: OPERATION_TYPE
        description: "Type of operation (INSERT, UPDATE, DELETE, VALIDATION)"
      - name: PROCESSED_BY
        description: "User or system that performed the operation"
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        
  - name: SI_USERS
    description: "Silver layer table storing cleaned and standardized user profile and subscription information"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
      - name: USER_NAME
        description: "Display name of the user (cleaned and standardized format)"
      - name: EMAIL
        description: "Email address of the user (validated and standardized)"
        tests:
          - not_null
      - name: COMPANY
        description: "Company or organization name (cleaned and standardized)"
      - name: PLAN_TYPE
        description: "Subscription plan type (standardized values)"
        tests:
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE']
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: VALIDATION_STATUS
        description: "Status of data validation"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_MEETINGS
    description: "Silver layer table storing cleaned and standardized meeting information and session details"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: HOST_ID
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: START_TIME
        description: "Meeting start timestamp (standardized timezone)"
        tests:
          - not_null
      - name: END_TIME
        description: "Meeting end timestamp (standardized timezone)"
        tests:
          - not_null
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes (validated and calculated)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: VALIDATION_STATUS
        description: "Status of data validation"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_PARTICIPANTS
    description: "Silver layer table storing cleaned and standardized meeting participants and their session details"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each meeting participant"
        tests:
          - not_null
          - unique
      - name: MEETING_ID
        description: "Reference to meeting"
        tests:
          - not_null
      - name: USER_ID
        description: "Reference to user who participated"
        tests:
          - not_null
      - name: JOIN_TIME
        description: "Timestamp when participant joined meeting (standardized timezone)"
        tests:
          - not_null
      - name: LEAVE_TIME
        description: "Timestamp when participant left meeting (standardized timezone)"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: VALIDATION_STATUS
        description: "Status of data validation"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_FEATURE_USAGE
    description: "Silver layer table storing cleaned and standardized platform feature usage during meetings"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for each feature usage record"
        tests:
          - not_null
          - unique
      - name: MEETING_ID
        description: "Reference to meeting where feature was used"
        tests:
          - not_null
      - name: FEATURE_NAME
        description: "Name of the feature being tracked (standardized naming)"
        tests:
          - not_null
      - name: USAGE_COUNT
        description: "Number of times feature was used (validated)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: VALIDATION_STATUS
        description: "Status of data validation"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_SUPPORT_TICKETS
    description: "Silver layer table storing cleaned and standardized customer support requests and resolution tracking"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for each support ticket"
        tests:
          - not_null
          - unique
      - name: USER_ID
        description: "Reference to user who created the ticket"
        tests:
          - not_null
      - name: RESOLUTION_STATUS
        description: "Current status of ticket resolution (standardized values)"
        tests:
          - accepted_values:
              values: ['OPEN', 'IN PROGRESS', 'RESOLVED', 'CLOSED']
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: VALIDATION_STATUS
        description: "Status of data validation"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_BILLING_EVENTS
    description: "Silver layer table storing cleaned and standardized financial transactions and billing activities"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique
      - name: USER_ID
        description: "Reference to user associated with billing event"
        tests:
          - not_null
      - name: AMOUNT
        description: "Monetary amount for the billing event (validated and standardized)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: VALIDATION_STATUS
        description: "Status of data validation"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
              
  - name: SI_LICENSES
    description: "Silver layer table storing cleaned and standardized license assignments and entitlements"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
        tests:
          - not_null
          - unique
      - name: ASSIGNED_TO_USER_ID
        description: "User ID to whom license is assigned"
        tests:
          - not_null
      - name: START_DATE
        description: "License validity start date (standardized format)"
        tests:
          - not_null
      - name: END_DATE
        description: "License validity end date (standardized format)"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: VALIDATION_STATUS
        description: "Status of data validation"
        tests:
          - accepted_values:
              values: ['PASSED', 'FAILED', 'WARNING']
