version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: BZ_USERS
        description: "Raw user profile and subscription information"
      - name: BZ_MEETINGS
        description: "Raw meeting information and session details"
      - name: BZ_PARTICIPANTS
        description: "Raw meeting participants and their session details"
      - name: BZ_FEATURE_USAGE
        description: "Raw usage of platform features during meetings"
      - name: BZ_SUPPORT_TICKETS
        description: "Raw customer support requests and resolution tracking"
      - name: BZ_BILLING_EVENTS
        description: "Raw financial transactions and billing activities"
      - name: BZ_LICENSES
        description: "Raw license assignments and entitlements"

models:
  - name: SI_Audit_Log
    description: "Silver layer audit log table for tracking pipeline operations and errors"
  - name: SI_Users
    description: "Silver layer users table with cleaned and standardized user data"
  - name: SI_Meetings
    description: "Silver layer meetings table with cleaned and validated meeting data"
  - name: SI_Participants
    description: "Silver layer participants table with cleaned participant session data"
  - name: SI_Feature_Usage
    description: "Silver layer feature usage table with standardized feature tracking data"
  - name: SI_Support_Tickets
    description: "Silver layer support tickets table with standardized ticket data"
  - name: SI_Billing_Events
    description: "Silver layer billing events table with validated financial transaction data"
  - name: SI_Licenses
    description: "Silver layer licenses table with validated license assignment data"
