version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user"
          - name: company
            description: "Company or organization name"
          - name: plan_type
            description: "Type of subscription plan"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
      
      - name: bz_meetings
        description: "Raw meeting session information"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
      
      - name: bz_participants
        description: "Raw meeting participant information"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user who participated"
          - name: join_time
            description: "Timestamp when participant joined"
          - name: leave_time
            description: "Timestamp when participant left"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
      
      - name: bz_feature_usage
        description: "Raw platform feature usage tracking"
      - name: bz_support_tickets
        description: "Raw customer support ticket information"
      - name: bz_billing_events
        description: "Raw billing and financial transaction information"
      - name: bz_licenses
        description: "Raw license management information"
      - name: bz_webinars
        description: "Raw webinar session information"

models:
  - name: si_pipeline_audit
    description: "Audit table for tracking Silver layer pipeline executions"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
        tests:
          - unique
          - not_null
      - name: pipeline_name
        description: "Name of the data pipeline or process"
        tests:
          - not_null
      - name: start_time
        description: "When the pipeline execution started"
        tests:
          - not_null
      - name: status
        description: "Status of pipeline execution"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'RUNNING', 'CANCELLED']
  
  - name: si_users
    description: "Silver layer table storing cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "Standardized full name of the registered user"
        tests:
          - not_null
      - name: email
        description: "Validated and standardized email address"
      - name: company
        description: "Standardized organization or company affiliation"
      - name: plan_type
        description: "Standardized subscription tier"
        tests:
          - accepted_values:
              values: ['Free', 'Basic', 'Pro', 'Enterprise', 'Unknown']
      - name: account_status
        description: "Current status of user account"
        tests:
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
  
  - name: si_meetings
    description: "Silver layer table storing cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: meeting_type
        description: "Standardized meeting category"
        tests:
          - accepted_values:
              values: ['Scheduled', 'Instant', 'Webinar', 'Personal']
      - name: meeting_status
        description: "Current state of the meeting"
        tests:
          - accepted_values:
              values: ['Scheduled', 'In Progress', 'Completed', 'Cancelled']
      - name: duration_minutes
        description: "Calculated and validated meeting duration"
        tests:
          - not_null
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
