version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: BZ_USERS
        description: "Raw user profile and subscription information"
      - name: BZ_MEETINGS
        description: "Raw meeting information and session details"
      - name: BZ_PARTICIPANTS
        description: "Raw meeting participants and their session details"
      - name: BZ_FEATURE_USAGE
        description: "Raw usage of platform features during meetings"
      - name: BZ_SUPPORT_TICKETS
        description: "Raw customer support requests and resolution tracking"
      - name: BZ_BILLING_EVENTS
        description: "Raw financial transactions and billing activities"
      - name: BZ_LICENSES
        description: "Raw license assignments and entitlements"

models:
  - name: SI_Audit_Log
    description: "Silver layer audit log for tracking all data operations and errors"
    columns:
      - name: AUDIT_ID
        description: "Unique identifier for each audit record"
      - name: TABLE_NAME
        description: "Name of the table where operation occurred"
      - name: COLUMN_NAME
        description: "Name of the column where operation occurred"
      - name: RECORD_ID
        description: "Primary key value of affected record"
      - name: ERROR_TYPE
        description: "Type of error or operation"
      - name: ERROR_DESCRIPTION
        description: "Detailed description of the operation or error"
      - name: ORIGINAL_VALUE
        description: "Original value before transformation"
      - name: AUDIT_TIMESTAMP
        description: "Timestamp when audit record was created"
      - name: OPERATION_TYPE
        description: "Type of operation performed"
      - name: PROCESSED_BY
        description: "User or system that performed the operation"
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        
  - name: SI_Users
    description: "Silver layer table storing cleaned and standardized user profile and subscription information"
    
  - name: SI_Meetings
    description: "Silver layer table storing cleaned and standardized meeting information and session details"
    
  - name: SI_Participants
    description: "Silver layer table storing cleaned and standardized meeting participants and their session details"
    
  - name: SI_Feature_Usage
    description: "Silver layer table storing cleaned and standardized platform feature usage during meetings"
    
  - name: SI_Support_Tickets
    description: "Silver layer table storing cleaned and standardized customer support requests and resolution tracking"
    
  - name: SI_Billing_Events
    description: "Silver layer table storing cleaned and standardized financial transactions and billing activities"
    
  - name: SI_Licenses
    description: "Silver layer table storing cleaned and standardized license assignments and entitlements"
