version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user data from Zoom platform"
        columns:
          - name: user_id
            description: "Unique identifier for users"
          - name: user_name
            description: "User display name"
          - name: email
            description: "User email address"
          - name: company
            description: "User company name"
          - name: plan_type
            description: "User subscription plan type"
          - name: load_timestamp
            description: "Timestamp when record was loaded into bronze"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
      
      - name: bz_meetings
        description: "Raw meeting data from Zoom platform"
        columns:
          - name: meeting_id
            description: "Unique identifier for meetings"
          - name: host_id
            description: "User ID of meeting host"
          - name: meeting_topic
            description: "Meeting topic or title"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Timestamp when record was loaded into bronze"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
      
      - name: bz_participants
        description: "Raw participant data from Zoom platform"
        columns:
          - name: participant_id
            description: "Unique identifier for participants"
          - name: meeting_id
            description: "Meeting identifier"
          - name: user_id
            description: "User identifier"
          - name: join_time
            description: "Participant join timestamp"
          - name: leave_time
            description: "Participant leave timestamp"
          - name: load_timestamp
            description: "Timestamp when record was loaded into bronze"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
      
      - name: bz_feature_usage
        description: "Raw feature usage data from Zoom platform"
        columns:
          - name: usage_id
            description: "Unique identifier for usage records"
          - name: meeting_id
            description: "Meeting identifier"
          - name: feature_name
            description: "Name of feature used"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date of feature usage"
          - name: load_timestamp
            description: "Timestamp when record was loaded into bronze"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
      
      - name: bz_support_tickets
        description: "Raw support ticket data from Zoom platform"
        columns:
          - name: ticket_id
            description: "Unique identifier for support tickets"
          - name: user_id
            description: "User identifier"
          - name: ticket_type
            description: "Type of support ticket"
          - name: resolution_status
            description: "Current status of ticket"
          - name: open_date
            description: "Date ticket was opened"
          - name: load_timestamp
            description: "Timestamp when record was loaded into bronze"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
      
      - name: bz_billing_events
        description: "Raw billing event data from Zoom platform"
        columns:
          - name: event_id
            description: "Unique identifier for billing events"
          - name: user_id
            description: "User identifier"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Billing amount"
          - name: event_date
            description: "Date of billing event"
          - name: load_timestamp
            description: "Timestamp when record was loaded into bronze"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
      
      - name: bz_licenses
        description: "Raw license data from Zoom platform"
        columns:
          - name: license_id
            description: "Unique identifier for licenses"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID license is assigned to"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: load_timestamp
            description: "Timestamp when record was loaded into bronze"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"

models:
  - name: si_pipeline_audit
    description: "Audit table for tracking pipeline execution and data quality metrics"
    columns:
      - name: audit_id
        description: "Unique identifier for audit records"
      - name: pipeline_name
        description: "Name of the executed pipeline"
      - name: source_table
        description: "Source table being processed"
      - name: target_table
        description: "Target table being populated"
      - name: execution_start_time
        description: "Pipeline execution start timestamp"
      - name: execution_end_time
        description: "Pipeline execution end timestamp"
      - name: execution_status
        description: "Pipeline execution status"
      - name: records_processed
        description: "Number of records processed"
      - name: processed_by
        description: "User or system that executed the pipeline"
  
  - name: si_users
    description: "Cleansed and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "Standardized user display name"
        tests:
          - not_null
      - name: email
        description: "Validated and standardized email address"
        tests:
          - not_null
      - name: plan_type
        description: "Standardized subscription plan type"
        tests:
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'BUSINESS', 'ENTERPRISE', 'UNKNOWN']
  
  - name: si_meetings
    description: "Cleansed and standardized meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for meetings"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "User ID of meeting host"
        tests:
          - not_null
      - name: start_time
        description: "Meeting start timestamp"
        tests:
          - not_null
      - name: end_time
        description: "Meeting end timestamp"
        tests:
          - not_null
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
  
  - name: si_participants
    description: "Cleansed participant data with calculated attendance duration"
    columns:
      - name: participant_id
        description: "Unique identifier for participants"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier"
        tests:
          - not_null
      - name: user_id
        description: "User identifier"
        tests:
          - not_null
      - name: attendance_duration
        description: "Calculated attendance duration in minutes"
  
  - name: si_feature_usage
    description: "Cleansed feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for usage records"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Meeting identifier"
        tests:
          - not_null
      - name: feature_name
        description: "Standardized feature name"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times feature was used"
        tests:
          - not_null
  
  - name: si_support_tickets
    description: "Cleansed support ticket data with calculated resolution metrics"
    columns:
      - name: ticket_id
        description: "Unique identifier for support tickets"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "User identifier"
        tests:
          - not_null
      - name: resolution_status
        description: "Standardized ticket status"
        tests:
          - accepted_values:
              values: ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']
  
  - name: si_billing_events
    description: "Cleansed billing event data with currency standardization"
    columns:
      - name: event_id
        description: "Unique identifier for billing events"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "User identifier"
        tests:
          - not_null
      - name: amount
        description: "Validated billing amount"
        tests:
          - not_null
      - name: currency_code
        description: "Standardized currency code"
        tests:
          - not_null
  
  - name: si_licenses
    description: "Cleansed license data with calculated status and expiry metrics"
    columns:
      - name: license_id
        description: "Unique identifier for licenses"
        tests:
          - unique
          - not_null
      - name: assigned_to_user_id
        description: "User ID license is assigned to"
        tests:
          - not_null
      - name: license_status
        description: "Calculated license status"
        tests:
          - accepted_values:
              values: ['ACTIVE', 'EXPIRED', 'EXPIRING_SOON', 'FUTURE']
      - name: days_to_expiry
        description: "Calculated days until license expiry"
        tests:
          - not_null
