version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    database: DB_POC_ZOOM
    schema: BRONZE
    tables:
      - name: bz_users
        description: "Raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
          - name: email
            description: "Email address of the user"
      
      - name: bz_meetings
        description: "Raw meeting session information"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: host_id
            description: "User ID of the meeting host"
      
      - name: bz_participants
        description: "Raw meeting participant information"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user who participated"
      
      - name: bz_feature_usage
        description: "Raw platform feature usage tracking"
      - name: bz_support_tickets
        description: "Raw customer support ticket information"
      - name: bz_billing_events
        description: "Raw billing and financial transaction information"
      - name: bz_licenses
        description: "Raw license management information"
      - name: bz_webinars
        description: "Raw webinar session information"
      - name: bz_audit_records
        description: "Audit records from bronze layer processing"

models:
  - name: audit_log
    description: "Silver layer audit log for tracking pipeline execution"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
      - name: pipeline_name
        description: "Name of the data pipeline or process"
      - name: status
        description: "Execution status"

  - name: si_users
    description: "Silver layer cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
      - name: email
        description: "Validated and standardized email address"
      - name: plan_type
        description: "Standardized subscription tier"
      - name: account_status
        description: "Current status of user account"
      - name: data_quality_score
        description: "Overall data quality score for the record"

  - name: si_meetings
    description: "Silver layer cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
      - name: host_id
        description: "User ID of the meeting host"
      - name: meeting_type
        description: "Standardized meeting category"
      - name: meeting_status
        description: "Current state of the meeting"
      - name: duration_minutes
        description: "Meeting duration in minutes"

  - name: si_participants
    description: "Silver layer cleaned participant attendance data"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
      - name: meeting_id
        description: "Reference to meeting"
      - name: user_id
        description: "Reference to user who participated"
      - name: attendance_duration
        description: "Time participant spent in meeting (minutes)"
      - name: participant_role
        description: "Role of attendee"
      - name: connection_quality
        description: "Network connection quality during participation"
