version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Bronze layer user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
            tests:
              - not_null
              - unique
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user - PII Data"
          - name: company
            description: "Company or organization name"
          - name: plan_type
            description: "Type of subscription plan"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
            tests:
              - not_null
          - name: update_timestamp
            description: "Timestamp when record was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Source system from which data originated"
            tests:
              - not_null

      - name: bz_meetings
        description: "Bronze layer meeting session information"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
            tests:
              - not_null
          - name: update_timestamp
            description: "Timestamp when record was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Source system from which data originated"
            tests:
              - not_null

      - name: bz_participants
        description: "Bronze layer meeting participant information"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user who participated"
          - name: join_time
            description: "Timestamp when participant joined"
          - name: leave_time
            description: "Timestamp when participant left"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
            tests:
              - not_null
          - name: update_timestamp
            description: "Timestamp when record was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Source system from which data originated"
            tests:
              - not_null

      - name: bz_feature_usage
        description: "Bronze layer platform feature usage tracking"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to meeting where feature was used"
          - name: feature_name
            description: "Name of the feature being tracked"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date when feature usage occurred"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
            tests:
              - not_null
          - name: update_timestamp
            description: "Timestamp when record was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Source system from which data originated"
            tests:
              - not_null

      - name: bz_support_tickets
        description: "Bronze layer customer support ticket information"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "Reference to user who created the ticket"
          - name: ticket_type
            description: "Type or category of support ticket"
          - name: resolution_status
            description: "Current status of ticket resolution"
          - name: open_date
            description: "Date when ticket was opened"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
            tests:
              - not_null
          - name: update_timestamp
            description: "Timestamp when record was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Source system from which data originated"
            tests:
              - not_null

      - name: bz_billing_events
        description: "Bronze layer billing and financial transaction information"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "Reference to user associated with billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Monetary amount for the billing event"
          - name: event_date
            description: "Date when the billing event occurred"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
            tests:
              - not_null
          - name: update_timestamp
            description: "Timestamp when record was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Source system from which data originated"
            tests:
              - not_null

      - name: bz_licenses
        description: "Bronze layer license management information"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
            tests:
              - not_null
              - unique
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID to whom license is assigned"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
            tests:
              - not_null
          - name: update_timestamp
            description: "Timestamp when record was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Source system from which data originated"
            tests:
              - not_null

      - name: bz_webinars
        description: "Bronze layer webinar session information"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of the webinar host"
          - name: webinar_topic
            description: "Topic or title of the webinar"
          - name: start_time
            description: "Webinar start timestamp"
          - name: end_time
            description: "Webinar end timestamp"
          - name: registrants
            description: "Number of registered participants"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
            tests:
              - not_null
          - name: update_timestamp
            description: "Timestamp when record was last updated"
            tests:
              - not_null
          - name: source_system
            description: "Source system from which data originated"
            tests:
              - not_null

models:
  - name: si_audit_log
    description: "Silver layer audit log for tracking pipeline executions"
    columns:
      - name: audit_id
        description: "Unique identifier for each audit record"
        tests:
          - not_null
          - unique
      - name: execution_id
        description: "Execution identifier for grouping related audit records"
      - name: pipeline_name
        description: "Name of the pipeline or process"
      - name: start_time
        description: "Pipeline execution start time"
      - name: end_time
        description: "Pipeline execution end time"
      - name: status
        description: "Execution status"
      - name: error_message
        description: "Error message if execution failed"
      - name: execution_duration_seconds
        description: "Total execution time in seconds"
      - name: source_tables_processed
        description: "List of source tables processed"
      - name: target_tables_updated
        description: "List of target tables updated"
      - name: records_processed
        description: "Total number of records processed"
      - name: records_inserted
        description: "Number of new records inserted"
      - name: records_updated
        description: "Number of existing records updated"
      - name: records_rejected
        description: "Number of records rejected due to quality issues"
      - name: executed_by
        description: "User or system that executed the pipeline"
      - name: execution_environment
        description: "Environment where pipeline was executed"
      - name: data_lineage_info
        description: "Information about data lineage and transformations"
      - name: load_date
        description: "Date when record was loaded"
      - name: update_date
        description: "Date when record was last updated"
      - name: source_system
        description: "Source system identifier"

  - name: si_users
    description: "Silver layer cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Standardized full name of the registered user"
      - name: email
        description: "Validated and standardized email address"
      - name: company
        description: "Standardized organization or company affiliation"
      - name: plan_type
        description: "Standardized subscription tier"
      - name: registration_date
        description: "Date when the user first registered"
      - name: last_login_date
        description: "Most recent date the user accessed the platform"
      - name: account_status
        description: "Current status of user account"
      - name: load_timestamp
        description: "Timestamp when record was loaded into silver layer"
      - name: update_timestamp
        description: "Timestamp when record was last updated in silver layer"
      - name: source_system
        description: "Source system from which data originated"
      - name: data_quality_score
        description: "Overall data quality score for the record (0.00 to 1.00)"
      - name: load_date
        description: "Date when record was loaded"
      - name: update_date
        description: "Date when record was last updated"
