version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user data from Zoom platform"
        columns:
          - name: user_id
            description: "Unique identifier for users"
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user"
          - name: company
            description: "Company name associated with the user"
          - name: plan_type
            description: "Subscription plan type"
          - name: load_timestamp
            description: "Timestamp when record was loaded into bronze"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system identifier"
      
      - name: bz_meetings
        description: "Raw meeting data from Zoom platform"
        columns:
          - name: meeting_id
            description: "Unique identifier for meetings"
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
      
      - name: bz_participants
        description: "Raw participant data from meetings"
        columns:
          - name: participant_id
            description: "Unique identifier for participants"
          - name: meeting_id
            description: "Meeting identifier"
          - name: user_id
            description: "User identifier for participant"
          - name: join_time
            description: "Timestamp when participant joined"
          - name: leave_time
            description: "Timestamp when participant left"
      
      - name: bz_feature_usage
        description: "Raw feature usage data"
        columns:
          - name: usage_id
            description: "Unique identifier for usage records"
          - name: meeting_id
            description: "Meeting identifier"
          - name: feature_name
            description: "Name of the feature used"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date when feature was used"
      
      - name: bz_support_tickets
        description: "Raw support ticket data"
        columns:
          - name: ticket_id
            description: "Unique identifier for support tickets"
          - name: user_id
            description: "User who created the ticket"
          - name: ticket_type
            description: "Type or category of the ticket"
          - name: resolution_status
            description: "Current status of the ticket"
          - name: open_date
            description: "Date when ticket was opened"
      
      - name: bz_billing_events
        description: "Raw billing event data"
        columns:
          - name: event_id
            description: "Unique identifier for billing events"
          - name: user_id
            description: "User associated with the billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Billing amount"
          - name: event_date
            description: "Date of the billing event"
      
      - name: bz_licenses
        description: "Raw license data"
        columns:
          - name: license_id
            description: "Unique identifier for licenses"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User assigned to the license"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"

models:
  - name: si_pipeline_audit
    description: "Audit table for tracking pipeline execution metrics and status"
    columns:
      - name: audit_id
        description: "Unique identifier for audit records"
      - name: pipeline_name
        description: "Name of the executed pipeline"
      - name: execution_status
        description: "Status of pipeline execution (SUCCESS, FAILED, RUNNING)"
      - name: execution_start_time
        description: "Timestamp when pipeline execution started"
      - name: execution_end_time
        description: "Timestamp when pipeline execution ended"
      - name: records_processed
        description: "Number of records processed in the pipeline"
  
  - name: si_users
    description: "Cleansed and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for users"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Standardized user display name"
        tests:
          - not_null
      - name: email
        description: "Validated and standardized email address"
        tests:
          - not_null
      - name: plan_type
        description: "Standardized subscription plan type"
        tests:
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'BUSINESS', 'ENTERPRISE', 'UNKNOWN']
  
  - name: si_meetings
    description: "Cleansed and validated meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for meetings"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of meeting host (validated against users)"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: duration_minutes
        description: "Validated meeting duration in minutes"
        tests:
          - not_null
  
  - name: si_participants
    description: "Cleansed participant data with calculated attendance duration"
    columns:
      - name: participant_id
        description: "Unique identifier for participants"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Meeting identifier (validated against meetings)"
        tests:
          - not_null
          - relationships:
              to: ref('si_meetings')
              field: meeting_id
      - name: user_id
        description: "User identifier (validated against users)"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: attendance_duration
        description: "Calculated attendance duration in minutes"
  
  - name: si_feature_usage
    description: "Cleansed feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for usage records"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Meeting identifier (validated against meetings)"
        tests:
          - not_null
          - relationships:
              to: ref('si_meetings')
              field: meeting_id
      - name: usage_count
        description: "Validated usage count (non-negative)"
        tests:
          - not_null
  
  - name: si_support_tickets
    description: "Cleansed support ticket data with calculated resolution times"
    columns:
      - name: ticket_id
        description: "Unique identifier for support tickets"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "User who created the ticket (validated against users)"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: resolution_status
        description: "Standardized resolution status"
        tests:
          - accepted_values:
              values: ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']
  
  - name: si_billing_events
    description: "Cleansed billing event data with currency standardization"
    columns:
      - name: event_id
        description: "Unique identifier for billing events"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "User associated with billing event (validated against users)"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: amount
        description: "Validated positive billing amount"
        tests:
          - not_null
      - name: currency_code
        description: "Standardized currency code"
        tests:
          - not_null
  
  - name: si_licenses
    description: "Cleansed license data with calculated status and expiry information"
    columns:
      - name: license_id
        description: "Unique identifier for licenses"
        tests:
          - not_null
          - unique
      - name: assigned_to_user_id
        description: "User assigned to license (validated against users)"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: license_status
        description: "Calculated license status based on dates"
        tests:
          - accepted_values:
              values: ['ACTIVE', 'EXPIRED', 'EXPIRING_SOON', 'FUTURE']
      - name: days_to_expiry
        description: "Calculated days until license expiry"
        tests:
          - not_null
