version: 2

sources:
  - name: bronze
    schema: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: bz_users
        description: "Raw user profile and subscription information"
      - name: bz_meetings
        description: "Raw meeting information and session details"
      - name: bz_participants
        description: "Raw meeting participants and their session details"
      - name: bz_feature_usage
        description: "Raw usage of platform features during meetings"
      - name: bz_support_tickets
        description: "Raw customer support requests and resolution tracking"
      - name: bz_billing_events
        description: "Raw financial transactions and billing activities"
      - name: bz_licenses
        description: "Raw license assignments and entitlements"

models:
  - name: si_audit_log
    description: "Audit log table for Silver layer pipeline execution tracking"
    
  - name: si_users
    description: "Silver layer table with cleaned and standardized user information"
    
  - name: si_meetings
    description: "Silver layer table with cleaned and standardized meeting information"
    
  - name: si_participants
    description: "Silver layer table with cleaned and standardized participant information"
    
  - name: si_feature_usage
    description: "Silver layer table with cleaned and standardized feature usage information"
    
  - name: si_support_tickets
    description: "Silver layer table with cleaned and standardized support ticket information"
    
  - name: si_billing_events
    description: "Silver layer table with cleaned and standardized billing event information"
    
  - name: si_licenses
    description: "Silver layer table with cleaned and standardized license information"
