version: 2

models:
  - name: SI_Audit_Log
    description: "Silver layer audit log for tracking pipeline executions"
    columns:
      - name: EXECUTION_ID
        description: "Unique identifier for each pipeline execution"
      - name: PIPELINE_NAME
        description: "Name of the pipeline being executed"
      - name: PIPELINE_TYPE
        description: "Type of pipeline (BRONZE_TO_SILVER)"
      - name: EXECUTION_START_TIME
        description: "Timestamp when pipeline execution started"
      - name: EXECUTION_END_TIME
        description: "Timestamp when pipeline execution completed"
      - name: EXECUTION_STATUS
        description: "Status of pipeline execution (SUCCESS, FAILED, WARNING)"
      - name: SOURCE_TABLE
        description: "Source table being processed"
      - name: TARGET_TABLE
        description: "Target table being populated"
      - name: RECORDS_SUCCESS
        description: "Number of records successfully processed"
      - name: EXECUTED_BY
        description: "User or system that executed the pipeline"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when audit record was created"
  
  - name: SI_Users
    description: "Silver layer users table with cleaned and validated data"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user account"
      - name: USER_NAME
        description: "Display name of the user (cleaned and standardized)"
      - name: EMAIL
        description: "Email address of the user (validated and standardized)"
      - name: COMPANY
        description: "Company or organization name (cleaned)"
      - name: PLAN_TYPE
        description: "Subscription plan type (standardized values)"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
  
  - name: SI_Meetings
    description: "Silver layer meetings table with cleaned and validated data"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
      - name: HOST_ID
        description: "User ID of the meeting host"
      - name: MEETING_TOPIC
        description: "Topic or title of the meeting (cleaned)"
      - name: START_TIME
        description: "Meeting start timestamp (standardized timezone)"
      - name: END_TIME
        description: "Meeting end timestamp (standardized timezone)"
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes (validated)"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
  
  - name: SI_Participants
    description: "Silver layer participants table with cleaned and validated data"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each meeting participant"
      - name: MEETING_ID
        description: "Reference to meeting"
      - name: USER_ID
        description: "Reference to user who participated"
      - name: JOIN_TIME
        description: "Timestamp when participant joined meeting (standardized)"
      - name: LEAVE_TIME
        description: "Timestamp when participant left meeting (standardized)"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
  
  - name: SI_Feature_Usage
    description: "Silver layer feature usage table with cleaned and validated data"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for each feature usage record"
      - name: MEETING_ID
        description: "Reference to meeting where feature was used"
      - name: FEATURE_NAME
        description: "Name of the feature being tracked (standardized)"
      - name: USAGE_COUNT
        description: "Number of times feature was used (validated)"
      - name: USAGE_DATE
        description: "Date when feature usage occurred (standardized)"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
  
  - name: SI_Support_Tickets
    description: "Silver layer support tickets table with cleaned and validated data"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for each support ticket"
      - name: USER_ID
        description: "Reference to user who created the ticket"
      - name: TICKET_TYPE
        description: "Type of support ticket (standardized)"
      - name: RESOLUTION_STATUS
        description: "Current status of ticket resolution (standardized)"
      - name: OPEN_DATE
        description: "Date when ticket was opened (validated)"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
  
  - name: SI_Billing_Events
    description: "Silver layer billing events table with cleaned and validated data"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for each billing event"
      - name: USER_ID
        description: "Reference to user associated with billing event"
      - name: EVENT_TYPE
        description: "Type of billing event (standardized)"
      - name: AMOUNT
        description: "Monetary amount for the billing event (validated)"
      - name: EVENT_DATE
        description: "Date when the billing event occurred (validated)"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
  
  - name: SI_Licenses
    description: "Silver layer licenses table with cleaned and validated data"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
      - name: LICENSE_TYPE
        description: "Type of license (standardized)"
      - name: ASSIGNED_TO_USER_ID
        description: "User ID to whom license is assigned"
      - name: START_DATE
        description: "License validity start date (validated)"
      - name: END_DATE
        description: "License validity end date (validated)"
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was processed into Silver layer"
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated"
      - name: SOURCE_SYSTEM
        description: "Source system from which data originated"
      - name: LOAD_DATE
        description: "Date when record was processed into Silver layer"
      - name: UPDATE_DATE
        description: "Date when record was last updated"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
