version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Bronze users table with raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user"
          - name: company
            description: "Company or organization name"
          - name: plan_type
            description: "Type of subscription plan"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: bz_meetings
        description: "Bronze meetings table with raw meeting session information"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: bz_participants
        description: "Bronze participants table with raw meeting participant information"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user who participated"
          - name: join_time
            description: "Timestamp when participant joined"
          - name: leave_time
            description: "Timestamp when participant left"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: bz_feature_usage
        description: "Bronze feature usage table"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
          - name: meeting_id
            description: "Reference to meeting where feature was used"
          - name: feature_name
            description: "Name of the feature being tracked"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date when feature usage occurred"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: bz_support_tickets
        description: "Bronze support tickets table"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
          - name: user_id
            description: "Reference to user who created the ticket"
          - name: ticket_type
            description: "Type or category of support ticket"
          - name: resolution_status
            description: "Current status of ticket resolution"
          - name: open_date
            description: "Date when ticket was opened"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: bz_billing_events
        description: "Bronze billing events table"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
          - name: user_id
            description: "Reference to user associated with billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Monetary amount for the billing event"
          - name: event_date
            description: "Date when the billing event occurred"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: bz_licenses
        description: "Bronze licenses table"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID to whom license is assigned"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: bz_webinars
        description: "Bronze webinars table"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"
          - name: host_id
            description: "User ID of the webinar host"
          - name: webinar_topic
            description: "Topic or title of the webinar"
          - name: start_time
            description: "Webinar start timestamp"
          - name: end_time
            description: "Webinar end timestamp"
          - name: registrants
            description: "Number of registered participants"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"

models:
  - name: si_pipeline_audit
    description: "Silver layer pipeline audit table for tracking execution details"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
        tests:
          - unique
          - not_null
      - name: pipeline_name
        description: "Name of the data pipeline or process"
        tests:
          - not_null
      - name: start_time
        description: "When the pipeline execution started"
      - name: end_time
        description: "When the pipeline execution completed"
      - name: status
        description: "Status of pipeline execution"
        tests:
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PARTIAL_SUCCESS', 'CANCELLED', 'STARTED', 'COMPLETED']
              
  - name: si_users
    description: "Silver layer users table with cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "Standardized full name of the registered user"
        tests:
          - not_null
      - name: email
        description: "Validated and standardized email address"
        tests:
          - not_null
          - unique
      - name: plan_type
        description: "Standardized subscription tier"
        tests:
          - accepted_values:
              values: ['Free', 'Basic', 'Pro', 'Enterprise']
      - name: account_status
        description: "Current status of user account"
        tests:
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
          
  - name: si_meetings
    description: "Silver layer meetings table with cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: meeting_type
        description: "Standardized meeting category"
        tests:
          - accepted_values:
              values: ['Scheduled', 'Instant', 'Webinar', 'Personal']
      - name: meeting_status
        description: "Current state of the meeting"
        tests:
          - accepted_values:
              values: ['Scheduled', 'In Progress', 'Completed', 'Cancelled']
      - name: duration_minutes
        description: "Calculated and validated meeting duration in minutes"
        tests:
          - not_null
          
  - name: si_participants
    description: "Silver layer participants table with cleaned participant attendance data"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Reference to meeting"
        tests:
          - not_null
          - relationships:
              to: ref('si_meetings')
              field: meeting_id
      - name: user_id
        description: "Reference to user who participated"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: participant_role
        description: "Role of attendee"
        tests:
          - accepted_values:
              values: ['Host', 'Co-host', 'Participant', 'Observer']
      - name: connection_quality
        description: "Network connection quality during participation"
        tests:
          - accepted_values:
              values: ['Excellent', 'Good', 'Fair', 'Poor']
              
  - name: si_feature_usage
    description: "Silver layer feature usage table with standardized feature data"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Reference to meeting where feature was used"
        tests:
          - not_null
      - name: feature_name
        description: "Standardized name of the platform feature"
        tests:
          - not_null
      - name: feature_category
        description: "Classification of feature type"
        tests:
          - accepted_values:
              values: ['Audio', 'Video', 'Collaboration', 'Security', 'General']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
          
  - name: si_support_tickets
    description: "Silver layer support tickets table with standardized ticket data"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Reference to user who created the ticket"
        tests:
          - not_null
      - name: ticket_type
        description: "Standardized category of support ticket"
        tests:
          - accepted_values:
              values: ['Technical', 'Billing', 'Feature Request', 'Bug Report', 'General']
      - name: priority_level
        description: "Urgency level of ticket"
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High', 'Critical']
      - name: resolution_status
        description: "Current status of ticket resolution"
        tests:
          - accepted_values:
              values: ['Open', 'In Progress', 'Resolved', 'Closed']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
          
  - name: si_billing_events
    description: "Silver layer billing events table with validated transaction data"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Reference to user associated with billing event"
        tests:
          - not_null
      - name: event_type
        description: "Standardized billing transaction type"
        tests:
          - accepted_values:
              values: ['Subscription', 'Upgrade', 'Downgrade', 'Refund', 'Other']
      - name: transaction_status
        description: "Status of transaction"
        tests:
          - accepted_values:
              values: ['Completed', 'Pending', 'Refunded']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
          
  - name: si_licenses
    description: "Silver layer licenses table with validated license data"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        tests:
          - unique
          - not_null
      - name: assigned_to_user_id
        description: "User ID to whom license is assigned"
        tests:
          - not_null
      - name: license_type
        description: "Standardized category of license"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Add-on']
      - name: license_status
        description: "Current state of license"
        tests:
          - accepted_values:
              values: ['Active', 'Expired', 'Pending']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
          
  - name: si_webinars
    description: "Silver layer webinars table with cleaned webinar data and engagement metrics"
    columns:
      - name: webinar_id
        description: "Unique identifier for each webinar"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "User ID of the webinar host"
        tests:
          - not_null
      - name: webinar_topic
        description: "Cleaned and standardized topic or title of the webinar"
        tests:
          - not_null
      - name: duration_minutes
        description: "Calculated webinar duration in minutes"
        tests:
          - not_null
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
