version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from source systems"
    tables:
      - name: BZ_USERS
        description: "Raw user profile and subscription information"
      - name: BZ_MEETINGS
        description: "Raw meeting information and session details"
      - name: BZ_PARTICIPANTS
        description: "Raw meeting participants and their session details"
      - name: BZ_FEATURE_USAGE
        description: "Raw platform feature usage during meetings"
      - name: BZ_SUPPORT_TICKETS
        description: "Raw customer support requests and resolution tracking"
      - name: BZ_BILLING_EVENTS
        description: "Raw financial transactions and billing activities"
      - name: BZ_LICENSES
        description: "Raw license assignments and entitlements"

models:
  - name: SI_Audit_Log
    description: "Audit log table for tracking Silver layer pipeline executions"
    columns:
      - name: EXECUTION_ID
        description: "Unique identifier for each pipeline execution"
      - name: PIPELINE_NAME
        description: "Name of the specific pipeline"
      - name: EXECUTION_STATUS
        description: "Status of pipeline execution (SUCCESS, FAILED, WARNING)"
  
  - name: SI_USERS
    description: "Silver layer table with cleaned and standardized user information"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user account"
      - name: EMAIL
        description: "Email address of the user (validated and standardized)"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"
  
  - name: SI_MEETINGS
    description: "Silver layer table with cleaned and standardized meeting information"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
      - name: HOST_ID
        description: "User ID of the meeting host"
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes (validated and calculated)"
  
  - name: SI_PARTICIPANTS
    description: "Silver layer table with cleaned and standardized participant information"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each meeting participant"
      - name: MEETING_ID
        description: "Reference to meeting"
      - name: USER_ID
        description: "Reference to user who participated"
  
  - name: SI_FEATURE_USAGE
    description: "Silver layer table with cleaned and standardized feature usage information"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for each feature usage record"
      - name: MEETING_ID
        description: "Reference to meeting where feature was used"
      - name: FEATURE_NAME
        description: "Name of the feature being tracked (standardized naming)"
  
  - name: SI_SUPPORT_TICKETS
    description: "Silver layer table with cleaned and standardized support ticket information"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for each support ticket"
      - name: USER_ID
        description: "Reference to user who created the ticket"
      - name: RESOLUTION_STATUS
        description: "Current status of ticket resolution (standardized values)"
  
  - name: SI_BILLING_EVENTS
    description: "Silver layer table with cleaned and standardized billing event information"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for each billing event"
      - name: USER_ID
        description: "Reference to user associated with billing event"
      - name: AMOUNT
        description: "Monetary amount for the billing event (validated and standardized)"
  
  - name: SI_LICENSES
    description: "Silver layer table with cleaned and standardized license information"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
      - name: ASSIGNED_TO_USER_ID
        description: "User ID to whom license is assigned"
      - name: START_DATE
        description: "License validity start date (standardized format)"
      - name: END_DATE
        description: "License validity end date (standardized format)"
