version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user"
          - name: company
            description: "Company or organization name"
          - name: plan_type
            description: "Type of subscription plan"
          - name: load_timestamp
            description: "Timestamp when record was loaded"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: bz_meetings
        description: "Raw meeting session information"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
            
      - name: bz_participants
        description: "Raw meeting participant information"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user who participated"
          - name: join_time
            description: "Timestamp when participant joined"
          - name: leave_time
            description: "Timestamp when participant left"
            
      - name: bz_feature_usage
        description: "Raw platform feature usage tracking"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
          - name: meeting_id
            description: "Reference to meeting where feature was used"
          - name: feature_name
            description: "Name of the feature being tracked"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date when feature usage occurred"
            
      - name: bz_support_tickets
        description: "Raw customer support ticket information"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
          - name: user_id
            description: "Reference to user who created the ticket"
          - name: ticket_type
            description: "Type or category of support ticket"
          - name: resolution_status
            description: "Current status of ticket resolution"
          - name: open_date
            description: "Date when ticket was opened"
            
      - name: bz_billing_events
        description: "Raw billing and financial transaction information"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
          - name: user_id
            description: "Reference to user associated with billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Monetary amount for the billing event"
          - name: event_date
            description: "Date when the billing event occurred"
            
      - name: bz_licenses
        description: "Raw license management information"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID to whom license is assigned"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
            
      - name: bz_webinars
        description: "Raw webinar session information"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"
          - name: host_id
            description: "User ID of the webinar host"
          - name: webinar_topic
            description: "Topic or title of the webinar"
          - name: start_time
            description: "Webinar start timestamp"
          - name: end_time
            description: "Webinar end timestamp"
          - name: registrants
            description: "Number of registered participants"

models:
  - name: audit_log
    description: "Audit log table for tracking all Silver layer pipeline executions"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
      - name: pipeline_name
        description: "Name of the data pipeline or process"
      - name: start_time
        description: "When the pipeline execution started"
      - name: end_time
        description: "When the pipeline execution completed"
      - name: status
        description: "Status (Success, Failed, Partial Success, Cancelled)"
        
  - name: si_users
    description: "Silver layer table storing cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "Standardized full name of the registered user"
      - name: email
        description: "Validated and standardized email address"
      - name: company
        description: "Standardized organization or company affiliation"
      - name: plan_type
        description: "Standardized subscription tier"
        tests:
          - accepted_values:
              values: ['Free', 'Basic', 'Pro', 'Enterprise']
      - name: account_status
        description: "Current status of user account"
        tests:
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended']
      - name: data_quality_score
        description: "Overall data quality score for the record (0.00 to 1.00)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.00
              max_value: 1.00
              
  - name: si_meetings
    description: "Silver layer table storing cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: meeting_type
        description: "Standardized meeting category"
        tests:
          - accepted_values:
              values: ['Scheduled', 'Instant', 'Webinar', 'Personal']
      - name: duration_minutes
        description: "Calculated and validated meeting duration in minutes"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1440
              
  - name: si_participants
    description: "Silver layer table storing cleaned participant attendance data"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "Reference to meeting"
        tests:
          - not_null
      - name: user_id
        description: "Reference to user who participated"
        tests:
          - not_null
      - name: participant_role
        description: "Role of attendee"
        tests:
          - accepted_values:
              values: ['Host', 'Co-host', 'Participant', 'Observer']
              
  - name: si_feature_usage
    description: "Silver layer table storing standardized feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - unique
          - not_null
      - name: feature_category
        description: "Classification of feature type"
        tests:
          - accepted_values:
              values: ['Audio', 'Video', 'Collaboration', 'Security']
              
  - name: si_support_tickets
    description: "Silver layer table storing standardized customer support ticket data"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        tests:
          - unique
          - not_null
      - name: ticket_type
        description: "Standardized category"
        tests:
          - accepted_values:
              values: ['Technical', 'Billing', 'Feature Request', 'Bug Report']
      - name: priority_level
        description: "Urgency level of ticket"
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High', 'Critical']
              
  - name: si_billing_events
    description: "Silver layer table storing validated billing and financial transaction data"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        tests:
          - unique
          - not_null
      - name: event_type
        description: "Standardized billing transaction type"
        tests:
          - accepted_values:
              values: ['Subscription', 'Upgrade', 'Downgrade', 'Refund']
      - name: transaction_amount
        description: "Validated monetary value of the billing event"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.01
              max_value: 10000.00
              
  - name: si_licenses
    description: "Silver layer table storing validated license assignment and management data"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Standardized category"
        tests:
          - accepted_values:
              values: ['Basic', 'Pro', 'Enterprise', 'Add-on']
      - name: license_status
        description: "Current state"
        tests:
          - accepted_values:
              values: ['Active', 'Expired', 'Suspended']
              
  - name: si_webinars
    description: "Silver layer table storing cleaned webinar data with engagement metrics"
    columns:
      - name: webinar_id
        description: "Unique identifier for each webinar"
        tests:
          - unique
          - not_null
      - name: attendance_rate
        description: "Percentage of registrants who attended"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.00
              max_value: 100.00
