version: 2

models:
  - name: SI_Audit_Log
    description: "Silver layer audit log for tracking pipeline operations"
    columns:
      - name: AUDIT_ID
        description: "Unique identifier for each audit record"
        tests:
          - not_null
      - name: TABLE_NAME
        description: "Name of the table where operation occurred"
      - name: OPERATION_TYPE
        description: "Type of operation performed"
      - name: AUDIT_TIMESTAMP
        description: "Timestamp when audit record was created"

  - name: SI_Users
    description: "Silver layer cleaned and standardized user information"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user"
        tests:
          - not_null
          - unique
      - name: EMAIL
        description: "Validated email address"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"
      - name: VALIDATION_STATUS
        description: "Status of data validation (PASSED, FAILED, WARNING)"

  - name: SI_Meetings
    description: "Silver layer cleaned and standardized meeting information"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: HOST_ID
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes (cleaned from text units)"
      - name: DATA_QUALITY_SCORE
        description: "Quality score from validation process (0-100)"

  - name: SI_Participants
    description: "Silver layer cleaned participant session details"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each participant"
        tests:
          - not_null
          - unique
      - name: MEETING_ID
        description: "Reference to meeting"
        tests:
          - not_null
      - name: USER_ID
        description: "Reference to user who participated"
        tests:
          - not_null

  - name: SI_Feature_Usage
    description: "Silver layer cleaned feature usage information"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for each usage record"
        tests:
          - not_null
          - unique
      - name: MEETING_ID
        description: "Reference to meeting where feature was used"
        tests:
          - not_null
      - name: USAGE_COUNT
        description: "Number of times feature was used"
        tests:
          - not_null

  - name: SI_Support_Tickets
    description: "Silver layer cleaned support ticket information"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for each support ticket"
        tests:
          - not_null
          - unique
      - name: USER_ID
        description: "Reference to user who created the ticket"
        tests:
          - not_null
      - name: RESOLUTION_STATUS
        description: "Current status of ticket resolution"

  - name: SI_Billing_Events
    description: "Silver layer cleaned billing event information"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique
      - name: USER_ID
        description: "Reference to user associated with billing event"
        tests:
          - not_null
      - name: AMOUNT
        description: "Monetary amount for the billing event"
        tests:
          - not_null

  - name: SI_Licenses
    description: "Silver layer cleaned license information"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
        tests:
          - not_null
          - unique
      - name: ASSIGNED_TO_USER_ID
        description: "User ID to whom license is assigned"
        tests:
          - not_null
      - name: START_DATE
        description: "License validity start date (converted from DD/MM/YYYY)"
      - name: END_DATE
        description: "License validity end date (converted from DD/MM/YYYY)"
