version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
          - name: email
            description: "Email address of the user"
      
      - name: bz_meetings
        description: "Raw meeting session information"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
      
      - name: bz_participants
        description: "Raw meeting participant information"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
      
      - name: bz_feature_usage
        description: "Raw platform feature usage tracking"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
      
      - name: bz_support_tickets
        description: "Raw customer support ticket information"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
      
      - name: bz_billing_events
        description: "Raw billing and financial transaction information"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
      
      - name: bz_licenses
        description: "Raw license management information"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
      
      - name: bz_webinars
        description: "Raw webinar session information"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"

models:
  - name: si_pipeline_audit
    description: "Audit table for tracking Silver layer pipeline execution details"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
      - name: pipeline_name
        description: "Name of the data pipeline or process"
      - name: status
        description: "Status (Success, Failed, Partial Success, Cancelled)"

  - name: si_users
    description: "Silver layer table storing cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
      - name: email
        description: "Validated and standardized email address"
      - name: data_quality_score
        description: "Overall data quality score for the record (0.00 to 1.00)"

  - name: si_meetings
    description: "Silver layer table storing cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
      - name: host_id
        description: "User ID of the meeting host"
      - name: data_quality_score
        description: "Overall data quality score for the record (0.00 to 1.00)"

  - name: si_participants
    description: "Silver layer table storing cleaned participant attendance data"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
      - name: meeting_id
        description: "Reference to meeting"
      - name: user_id
        description: "Reference to user who participated"
      - name: data_quality_score
        description: "Overall data quality score for the record (0.00 to 1.00)"
