version: 2

models:
  - name: SI_Audit_Log
    description: "Silver layer audit log table for tracking all data operations and errors"
  
  - name: SI_Users
    description: "Silver layer users table with cleaned and standardized user profile and subscription information"
  
  - name: SI_Meetings
    description: "Silver layer meetings table with cleaned and standardized meeting information"
  
  - name: SI_Participants
    description: "Silver layer participants table with cleaned and standardized participant information"
  
  - name: SI_Feature_Usage
    description: "Silver layer feature usage table with cleaned and standardized feature usage information"
  
  - name: SI_Support_Tickets
    description: "Silver layer support tickets table with cleaned and standardized ticket information"
  
  - name: SI_Billing_Events
    description: "Silver layer billing events table with cleaned and standardized billing information"
  
  - name: SI_Licenses
    description: "Silver layer licenses table with cleaned and standardized license information"
