version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data"
    tables:
      - name: BZ_USERS
        description: "Raw user data from source systems"
      - name: BZ_MEETINGS
        description: "Raw meeting data from source systems"
      - name: BZ_PARTICIPANTS
        description: "Raw participant data from source systems"
      - name: BZ_FEATURE_USAGE
        description: "Raw feature usage data from source systems"
      - name: BZ_SUPPORT_TICKETS
        description: "Raw support ticket data from source systems"
      - name: BZ_BILLING_EVENTS
        description: "Raw billing event data from source systems"
      - name: BZ_LICENSES
        description: "Raw license data from source systems"

models:
  - name: SI_AUDIT_LOG
    description: "Silver layer audit log for tracking all operations and errors"
    columns:
      - name: AUDIT_ID
        description: "Unique identifier for each audit record"
        tests:
          - not_null
      - name: TABLE_NAME
        description: "Name of the table where operation occurred"
      - name: OPERATION_TYPE
        description: "Type of operation performed"
      - name: AUDIT_TIMESTAMP
        description: "Timestamp when audit record was created"

  - name: SI_USERS
    description: "Silver layer users table with cleaned and validated data"
    columns:
      - name: USER_ID
        description: "Unique identifier for each user"
        tests:
          - not_null
          - unique
      - name: EMAIL
        description: "User email address (validated format)"
        tests:
          - not_null
      - name: PLAN_TYPE
        description: "Subscription plan type (standardized values)"
        tests:
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE']
      - name: DATA_QUALITY_SCORE
        description: "Data quality score (0-100)"
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: "Validation status of the record"
        tests:
          - accepted_values:
              values: ['PASSED', 'WARNING', 'FAILED']

  - name: SI_MEETINGS
    description: "Silver layer meetings table with cleaned and validated data"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: HOST_ID
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes (cleaned from text units)"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Data quality score (0-100)"
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: "Validation status of the record"
        tests:
          - accepted_values:
              values: ['PASSED', 'WARNING', 'FAILED']

  - name: SI_PARTICIPANTS
    description: "Silver layer participants table with cleaned and validated data"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for each participant"
        tests:
          - not_null
          - unique
      - name: MEETING_ID
        description: "Reference to meeting"
        tests:
          - not_null
      - name: USER_ID
        description: "Reference to user"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Data quality score (0-100)"
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: "Validation status of the record"
        tests:
          - accepted_values:
              values: ['PASSED', 'WARNING', 'FAILED']

  - name: SI_FEATURE_USAGE
    description: "Silver layer feature usage table with cleaned and validated data"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for each usage record"
        tests:
          - not_null
          - unique
      - name: MEETING_ID
        description: "Reference to meeting"
        tests:
          - not_null
      - name: FEATURE_NAME
        description: "Name of the feature (standardized)"
        tests:
          - not_null
      - name: USAGE_COUNT
        description: "Number of times feature was used"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Data quality score (0-100)"
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: "Validation status of the record"
        tests:
          - accepted_values:
              values: ['PASSED', 'WARNING', 'FAILED']

  - name: SI_SUPPORT_TICKETS
    description: "Silver layer support tickets table with cleaned and validated data"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for each ticket"
        tests:
          - not_null
          - unique
      - name: USER_ID
        description: "Reference to user who created the ticket"
        tests:
          - not_null
      - name: RESOLUTION_STATUS
        description: "Current status of ticket resolution"
        tests:
          - accepted_values:
              values: ['OPEN', 'IN PROGRESS', 'RESOLVED', 'CLOSED']
      - name: DATA_QUALITY_SCORE
        description: "Data quality score (0-100)"
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: "Validation status of the record"
        tests:
          - accepted_values:
              values: ['PASSED', 'WARNING', 'FAILED']

  - name: SI_BILLING_EVENTS
    description: "Silver layer billing events table with cleaned and validated data"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique
      - name: USER_ID
        description: "Reference to user associated with billing event"
        tests:
          - not_null
      - name: AMOUNT
        description: "Monetary amount for the billing event"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Data quality score (0-100)"
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: "Validation status of the record"
        tests:
          - accepted_values:
              values: ['PASSED', 'WARNING', 'FAILED']

  - name: SI_LICENSES
    description: "Silver layer licenses table with cleaned and validated data"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for each license"
        tests:
          - not_null
          - unique
      - name: ASSIGNED_TO_USER_ID
        description: "User ID to whom license is assigned"
        tests:
          - not_null
      - name: START_DATE
        description: "License validity start date (converted from DD/MM/YYYY)"
        tests:
          - not_null
      - name: END_DATE
        description: "License validity end date (converted from DD/MM/YYYY)"
        tests:
          - not_null
      - name: DATA_QUALITY_SCORE
        description: "Data quality score (0-100)"
        tests:
          - not_null
      - name: VALIDATION_STATUS
        description: "Validation status of the record"
        tests:
          - accepted_values:
              values: ['PASSED', 'WARNING', 'FAILED']
