version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
          - name: email
            description: "Email address of the user"
      
      - name: bz_meetings
        description: "Raw meeting session data"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: host_id
            description: "User ID of the meeting host"
      
      - name: bz_participants
        description: "Raw participant data for meeting attendance"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
          - name: meeting_id
            description: "Reference to meeting"
      
      - name: bz_feature_usage
        description: "Raw feature usage data"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
      
      - name: bz_support_tickets
        description: "Raw support ticket data"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
      
      - name: bz_billing_events
        description: "Raw billing event data"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
      
      - name: bz_licenses
        description: "Raw license data"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
      
      - name: bz_webinars
        description: "Raw webinar session data"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"

models:
  - name: si_pipeline_audit
    description: "Audit log for tracking pipeline execution details"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
        tests:
          - not_null
          - unique
      - name: pipeline_name
        description: "Name of the data pipeline or process"
        tests:
          - not_null
      - name: status
        description: "Status of pipeline execution"
        tests:
          - not_null
          - accepted_values:
              values: ['RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL']

  - name: si_users
    description: "Silver layer table storing cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
      - name: email
        description: "Validated and standardized email address"
        tests:
          - not_null
      - name: plan_type
        description: "Standardized subscription tier"
        tests:
          - not_null
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE']
      - name: account_status
        description: "Current status of user account"
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null

  - name: si_meetings
    description: "Silver layer table storing cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: duration_minutes
        description: "Calculated and validated meeting duration in minutes"
        tests:
          - not_null
      - name: meeting_status
        description: "Current state of the meeting"
        tests:
          - not_null
          - accepted_values:
              values: ['Scheduled', 'In Progress', 'Completed', 'Cancelled']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null

  - name: si_participants
    description: "Silver layer table storing cleaned participant attendance data"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting"
        tests:
          - not_null
      - name: user_id
        description: "Reference to user who participated"
        tests:
          - not_null
      - name: attendance_duration
        description: "Calculated time participant spent in meeting"
        tests:
          - not_null
      - name: participant_role
        description: "Role of attendee in the meeting"
        tests:
          - not_null
          - accepted_values:
              values: ['Host', 'Co-host', 'Participant', 'Observer']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null

  - name: si_feature_usage
    description: "Silver layer table storing standardized feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting where feature was used"
        tests:
          - not_null
      - name: feature_category
        description: "Classification of feature type"
        tests:
          - not_null
          - accepted_values:
              values: ['Audio', 'Video', 'Collaboration', 'Security']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null

  - name: si_data_quality_errors
    description: "Table to store data validation errors and quality issues"
    columns:
      - name: error_id
        description: "Unique identifier for each data quality error"
        tests:
          - not_null
          - unique
      - name: source_table
        description: "Name of the source table where error was detected"
        tests:
          - not_null
      - name: error_type
        description: "Type of error detected"
        tests:
          - not_null
          - accepted_values:
              values: ['Missing Value', 'Invalid Format', 'Constraint Violation', 'Duplicate']
