version: 2

sources:
  - name: raw_schema
    description: "Raw data tables from Zoom platform"
    database: DB_POC_ZOOM
    schema: RAW
    tables:
      - name: users
        description: "Raw users table with user account data"
        columns:
          - name: user_id
            description: "Unique identifier for each user"
          - name: email
            description: "User email address"
      
      - name: meetings
        description: "Raw meetings table with meeting data"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: host_id
            description: "User ID of meeting host"
      
      - name: participants
        description: "Raw participants table with attendance data"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user"
      
      - name: feature_usage
        description: "Raw feature usage table"
      - name: support_tickets
        description: "Raw support tickets table"
      - name: billing_events
        description: "Raw billing events table"
      - name: licenses
        description: "Raw licenses table"
      - name: webinars
        description: "Raw webinars table"

models:
  - name: si_pipeline_audit
    description: "Silver layer pipeline audit table for tracking execution details"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
        tests:
          - not_null
          - unique
      - name: pipeline_name
        description: "Name of the executed pipeline"
        tests:
          - not_null
      - name: status
        description: "Execution status"
        tests:
          - not_null
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'PARTIAL_SUCCESS', 'CANCELLED', 'STARTED', 'COMPLETED']
  
  - name: si_users
    description: "Silver layer users table with cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Standardized user name"
        tests:
          - not_null
      - name: email
        description: "Validated and standardized email address"
        tests:
          - not_null
      - name: plan_type
        description: "Standardized subscription plan type"
        tests:
          - not_null
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE', 'UNKNOWN_PLAN']
      - name: account_status
        description: "Current account status"
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended']
      - name: data_quality_score
        description: "Data quality score for the record"
        tests:
          - not_null
  
  - name: si_meetings
    description: "Silver layer meetings table with cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of meeting host"
        tests:
          - not_null
      - name: meeting_type
        description: "Standardized meeting category"
        tests:
          - not_null
          - accepted_values:
              values: ['Scheduled', 'Instant', 'Webinar', 'Personal']
      - name: meeting_status
        description: "Current meeting state"
        tests:
          - not_null
          - accepted_values:
              values: ['Scheduled', 'In Progress', 'Completed', 'Cancelled']
      - name: duration_minutes
        description: "Meeting duration in minutes"
        tests:
          - not_null
      - name: data_quality_score
        description: "Data quality score for the record"
        tests:
          - not_null
