version: 2

sources:
  - name: bronze
    description: Bronze layer tables containing raw data
    tables:
      - name: bz_users
        description: Raw user data from source systems
      - name: bz_meetings
        description: Raw meeting data from source systems
      - name: bz_participants
        description: Raw participant data from source systems
      - name: bz_feature_usage
        description: Raw feature usage data from source systems
      - name: bz_support_tickets
        description: Raw support ticket data from source systems
      - name: bz_billing_events
        description: Raw billing event data from source systems
      - name: bz_licenses
        description: Raw license data from source systems

models:
  - name: si_audit_log
    description: Audit log table for tracking data processing activities
    columns:
      - name: model_name
        description: Name of the dbt model being processed
      - name: table_name
        description: Name of the table being processed
      - name: process_status
        description: Status of the process (STARTED, COMPLETED, FAILED)
      - name: load_timestamp
        description: Timestamp when the audit record was loaded
  
  - name: si_users
    description: Cleansed and standardized user data
    columns:
      - name: user_id
        description: Unique identifier for users
        tests:
          - unique
          - not_null
      - name: data_quality_score
        description: Quality score from validation process (0-100)
      - name: validation_status
        description: Status of data validation (PASSED, FAILED, WARNING)
  
  - name: si_meetings
    description: Cleansed and standardized meeting data
    columns:
      - name: meeting_id
        description: Unique identifier for meetings
        tests:
          - unique
          - not_null
      - name: duration_minutes
        description: Validated meeting duration in minutes
      - name: data_quality_score
        description: Quality score from validation process (0-100)
      - name: validation_status
        description: Status of data validation (PASSED, FAILED, WARNING)
  
  - name: si_participants
    description: Cleansed and standardized participant data
    columns:
      - name: participant_id
        description: Unique identifier for participants
        tests:
          - unique
          - not_null
      - name: data_quality_score
        description: Quality score from validation process (0-100)
      - name: validation_status
        description: Status of data validation (PASSED, FAILED, WARNING)
  
  - name: si_feature_usage
    description: Cleansed and standardized feature usage data
    columns:
      - name: usage_id
        description: Unique identifier for feature usage records
        tests:
          - unique
          - not_null
      - name: data_quality_score
        description: Quality score from validation process (0-100)
      - name: validation_status
        description: Status of data validation (PASSED, FAILED, WARNING)
  
  - name: si_support_tickets
    description: Cleansed and standardized support ticket data
    columns:
      - name: ticket_id
        description: Unique identifier for support tickets
        tests:
          - unique
          - not_null
      - name: data_quality_score
        description: Quality score from validation process (0-100)
      - name: validation_status
        description: Status of data validation (PASSED, FAILED, WARNING)
  
  - name: si_billing_events
    description: Cleansed and standardized billing event data
    columns:
      - name: event_id
        description: Unique identifier for billing events
        tests:
          - unique
          - not_null
      - name: data_quality_score
        description: Quality score from validation process (0-100)
      - name: validation_status
        description: Status of data validation (PASSED, FAILED, WARNING)
  
  - name: si_licenses
    description: Cleansed and standardized license data
    columns:
      - name: license_id
        description: Unique identifier for licenses
        tests:
          - unique
          - not_null
      - name: data_quality_score
        description: Quality score from validation process (0-100)
      - name: validation_status
        description: Status of data validation (PASSED, FAILED, WARNING)
