version: 2

sources:
  - name: bronze
    description: Bronze layer tables containing raw data
    tables:
      - name: bz_users
        description: Raw user data from source systems
        columns:
          - name: user_id
            description: Unique identifier for users
          - name: user_name
            description: User display name
          - name: email
            description: User email address
          - name: company
            description: User company
          - name: plan_type
            description: Subscription plan type
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
            
      - name: bz_meetings
        description: Raw meeting data from source systems
        columns:
          - name: meeting_id
            description: Unique identifier for meetings
          - name: host_id
            description: Meeting host user ID
          - name: meeting_topic
            description: Meeting topic or title
          - name: start_time
            description: Meeting start timestamp
          - name: end_time
            description: Meeting end timestamp
          - name: duration_minutes
            description: Meeting duration in minutes
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
            
      - name: bz_participants
        description: Raw participant data from source systems
        columns:
          - name: participant_id
            description: Unique identifier for participants
          - name: meeting_id
            description: Associated meeting ID
          - name: user_id
            description: Participant user ID
          - name: join_time
            description: Participant join timestamp
          - name: leave_time
            description: Participant leave timestamp
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
            
      - name: bz_feature_usage
        description: Raw feature usage data from source systems
        columns:
          - name: usage_id
            description: Unique identifier for usage records
          - name: meeting_id
            description: Associated meeting ID
          - name: feature_name
            description: Name of the feature used
          - name: usage_count
            description: Number of times feature was used
          - name: usage_date
            description: Date of feature usage
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
            
      - name: bz_support_tickets
        description: Raw support ticket data from source systems
        columns:
          - name: ticket_id
            description: Unique identifier for support tickets
          - name: user_id
            description: User who created the ticket
          - name: ticket_type
            description: Type of support ticket
          - name: resolution_status
            description: Current resolution status
          - name: open_date
            description: Date ticket was opened
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
            
      - name: bz_billing_events
        description: Raw billing event data from source systems
        columns:
          - name: event_id
            description: Unique identifier for billing events
          - name: user_id
            description: User associated with billing event
          - name: event_type
            description: Type of billing event
          - name: amount
            description: Billing amount
          - name: event_date
            description: Date of billing event
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
            
      - name: bz_licenses
        description: Raw license data from source systems
        columns:
          - name: license_id
            description: Unique identifier for licenses
          - name: license_type
            description: Type of license
          - name: assigned_to_user_id
            description: User assigned to license
          - name: start_date
            description: License start date
          - name: end_date
            description: License end date
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier
            
      - name: bz_webinars
        description: Raw webinar data from source systems
        columns:
          - name: webinar_id
            description: Unique identifier for webinars
          - name: host_id
            description: Webinar host user ID
          - name: webinar_topic
            description: Webinar topic or title
          - name: start_time
            description: Webinar start timestamp
          - name: end_time
            description: Webinar end timestamp
          - name: registrants
            description: Number of registered participants
          - name: load_timestamp
            description: Data load timestamp
          - name: update_timestamp
            description: Data update timestamp
          - name: source_system
            description: Source system identifier

models:
  - name: audit_log
    description: Silver layer pipeline audit log
    columns:
      - name: execution_id
        description: Unique execution identifier
        tests:
          - unique
          - not_null
      - name: pipeline_name
        description: Name of the pipeline
      - name: start_time
        description: Pipeline start time
      - name: end_time
        description: Pipeline end time
      - name: status
        description: Pipeline execution status
      - name: records_processed
        description: Number of records processed
        
  - name: si_users
    description: Silver layer users table with cleaned and validated data
    columns:
      - name: user_id
        description: Unique identifier for users
        tests:
          - unique
          - not_null
      - name: user_name
        description: Standardized user name
        tests:
          - not_null
      - name: email
        description: Validated email address
        tests:
          - not_null
      - name: company
        description: User company
      - name: plan_type
        description: Standardized subscription plan type
      - name: registration_date
        description: User registration date
      - name: last_login_date
        description: Last login date
      - name: account_status
        description: Current account status
      - name: data_quality_score
        description: Data quality score (0.00 to 1.00)
        
  - name: si_meetings
    description: Silver layer meetings table with enriched data
    columns:
      - name: meeting_id
        description: Unique identifier for meetings
        tests:
          - unique
          - not_null
      - name: host_id
        description: Meeting host user ID
        tests:
          - not_null
      - name: meeting_topic
        description: Standardized meeting topic
      - name: meeting_type
        description: Derived meeting type
      - name: start_time
        description: Validated meeting start time
        tests:
          - not_null
      - name: end_time
        description: Validated meeting end time
        tests:
          - not_null
      - name: duration_minutes
        description: Calculated meeting duration
      - name: host_name
        description: Host user name
      - name: meeting_status
        description: Current meeting status
      - name: recording_status
        description: Recording availability status
      - name: participant_count
        description: Number of participants
      - name: data_quality_score
        description: Data quality score (0.00 to 1.00)
