version: 2

sources:
  - name: bronze
    description: "Bronze layer tables containing raw data from Zoom platform"
    tables:
      - name: bz_users
        description: "Raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
            tests:
              - not_null
              - unique
          - name: email
            description: "Email address of the user"
            tests:
              - not_null
      
      - name: bz_meetings
        description: "Raw meeting session data"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of the meeting host"
            tests:
              - not_null
      
      - name: bz_participants
        description: "Raw participant data for meeting attendance"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to meeting"
            tests:
              - not_null
      
      - name: bz_feature_usage
        description: "Raw feature usage data"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
            tests:
              - not_null
              - unique
      
      - name: bz_support_tickets
        description: "Raw support ticket data"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
            tests:
              - not_null
              - unique
      
      - name: bz_billing_events
        description: "Raw billing event data"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
            tests:
              - not_null
              - unique
      
      - name: bz_licenses
        description: "Raw license data"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
            tests:
              - not_null
              - unique
      
      - name: bz_webinars
        description: "Raw webinar session data"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"
            tests:
              - not_null
              - unique

models:
  - name: audit_log
    description: "Audit log for tracking pipeline execution details"
    columns:
      - name: execution_id
        description: "Unique identifier for each pipeline execution"
        tests:
          - not_null
          - unique
      - name: pipeline_name
        description: "Name of the data pipeline or process"
        tests:
          - not_null
      - name: status
        description: "Status of pipeline execution"
        tests:
          - not_null
          - accepted_values:
              values: ['RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL']

  - name: si_users
    description: "Silver layer table storing cleaned and standardized user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
      - name: email
        description: "Validated and standardized email address"
        tests:
          - not_null
      - name: plan_type
        description: "Standardized subscription tier"
        tests:
          - not_null
          - accepted_values:
              values: ['FREE', 'BASIC', 'PRO', 'ENTERPRISE']
      - name: account_status
        description: "Current status of user account"
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1

  - name: si_meetings
    description: "Silver layer table storing cleaned and enriched meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: duration_minutes
        description: "Calculated and validated meeting duration in minutes"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1440
      - name: meeting_status
        description: "Current state of the meeting"
        tests:
          - not_null
          - accepted_values:
              values: ['Scheduled', 'In Progress', 'Completed', 'Cancelled']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1

  - name: si_participants
    description: "Silver layer table storing cleaned participant attendance data"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting"
        tests:
          - not_null
          - relationships:
              to: ref('si_meetings')
              field: meeting_id
      - name: user_id
        description: "Reference to user who participated"
        tests:
          - not_null
          - relationships:
              to: ref('si_users')
              field: user_id
      - name: attendance_duration
        description: "Calculated time participant spent in meeting"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1440
      - name: participant_role
        description: "Role of attendee in the meeting"
        tests:
          - not_null
          - accepted_values:
              values: ['Host', 'Co-host', 'Participant', 'Observer']
      - name: data_quality_score
        description: "Overall data quality score for the record"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1
