{{ config(
    materialized='table',
    on_schema_change='sync_all_columns'
) }}

-- Silver Layer Audit Log Table
-- This table tracks all data processing activities and errors
SELECT 
    CAST(NULL AS VARCHAR(255)) AS MODEL_NAME,
    CAST(NULL AS VARCHAR(255)) AS TABLE_NAME,
    CAST(NULL AS VARCHAR(255)) AS COLUMN_NAME,
    CAST(NULL AS VARCHAR(16777216)) AS INVALID_VALUE,
    CAST(NULL AS VARCHAR(255)) AS ERROR_TYPE,
    CAST(NULL AS VARCHAR(16777216)) AS ERROR_DESCRIPTION,
    CAST(NULL AS VARCHAR(255)) AS RECORD_ID,
    CAST(NULL AS VARCHAR(16777216)) AS ORIGINAL_VALUE,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS AUDIT_TIMESTAMP,
    CAST(NULL AS VARCHAR(255)) AS PROCESS_STATUS,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS LOAD_TIMESTAMP
WHERE FALSE
