{{ config(
    materialized='table',
    unique_key='AUDIT_ID'
) }}

SELECT
    CAST(NULL AS VARCHAR(255)) AS AUDIT_ID,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_TABLE,
    CAST(NULL AS VARCHAR(255)) AS ERROR_TYPE,
    CAST(NULL AS VARCHAR(255)) AS COLUMN_NAME,
    CAST(NULL AS VARCHAR(MAX)) AS ERROR_VALUE,
    CAST(NULL AS TIMESTAMP) AS PROCESS_TIMESTAMP,
    CAST(NULL AS VARCHAR(255)) AS PROCESS_STATUS,
    CAST(NULL AS VARCHAR(255)) AS EXECUTION_ID,
    CAST(NULL AS VARCHAR(255)) AS PIPELINE_NAME,
    CAST(NULL AS NUMBER(38,0)) AS RECORD_COUNT,
    CAST(NULL AS NUMBER(38,0)) AS ERROR_COUNT,
    CAST(NULL AS NUMBER(38,0)) AS WARNING_COUNT,
    CAST(NULL AS VARCHAR(255)) AS PROCESSED_BY,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_SYSTEM,
    CAST(NULL AS TIMESTAMP) AS CREATED_AT,
    CAST(NULL AS TIMESTAMP) AS UPDATED_AT
WHERE FALSE
