{{ config(
    materialized='table',
    alias='SI_AUDIT_LOG'
) }}

/* 
 * SI_AUDIT_LOG - Independent Silver Audit Table
 * This table must be created first without hooks
 * Creates empty table structure for audit logging
 */

SELECT 
    CAST(NULL AS VARCHAR(255)) AS AUDIT_ID,
    CAST(NULL AS VARCHAR(255)) AS TABLE_NAME,
    CAST(NULL AS VARCHAR(255)) AS COLUMN_NAME,
    CAST(NULL AS VARCHAR(255)) AS RECORD_ID,
    CAST(NULL AS VARCHAR(255)) AS ERROR_TYPE,
    CAST(NULL AS VARCHAR(255)) AS ERROR_DESCRIPTION,
    CAST(NULL AS VARCHAR(255)) AS ORIGINAL_VALUE,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS AUDIT_TIMESTAMP,
    CAST(NULL AS VARCHAR(255)) AS OPERATION_TYPE,
    CAST(NULL AS VARCHAR(255)) AS PROCESSED_BY,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_SYSTEM
WHERE FALSE
