{{ config(
    materialized='table',
    on_schema_change='sync_all_columns'
) }}

-- Audit Log table for Silver layer pipeline execution tracking
-- This table must be created first before other models run

SELECT 
    CAST(NULL AS VARCHAR(255)) AS MODEL_NAME,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_TABLE,
    CAST(NULL AS VARCHAR(255)) AS TARGET_TABLE,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS PROCESS_START_TIME,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS PROCESS_END_TIME,
    CAST(NULL AS NUMBER(10,2)) AS DURATION_SECONDS,
    CAST(NULL AS VARCHAR(50)) AS STATUS,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_PROCESSED,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_SUCCESS,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_FAILED,
    CAST(NULL AS VARCHAR(16777216)) AS ERROR_DETAILS,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS LOAD_TIMESTAMP
WHERE FALSE
