{{ config(
    materialized='table',
    on_schema_change='sync_all_columns',
    pre_hook="INSERT INTO {{ ref('si_pipeline_audit') }} (EXECUTION_ID, PIPELINE_NAME, START_TIME, STATUS, EXECUTED_BY, EXECUTION_ENVIRONMENT, SOURCE_SYSTEM, LOAD_DATE, UPDATE_DATE) SELECT 'DQ_' || REPLACE(REPLACE(REPLACE(CURRENT_TIMESTAMP()::STRING, ' ', '_'), ':', ''), '.', '_'), 'Silver_Data_Quality_Errors_ETL', CURRENT_TIMESTAMP(), 'STARTED', 'DBT_SILVER_JOB', 'PRODUCTION', 'ZOOM_PLATFORM', CURRENT_DATE(), CURRENT_DATE()",
    post_hook="INSERT INTO {{ ref('si_pipeline_audit') }} (EXECUTION_ID, PIPELINE_NAME, START_TIME, END_TIME, STATUS, EXECUTION_DURATION_SECONDS, SOURCE_TABLES_PROCESSED, TARGET_TABLES_UPDATED, RECORDS_PROCESSED, RECORDS_INSERTED, RECORDS_UPDATED, RECORDS_REJECTED, EXECUTED_BY, EXECUTION_ENVIRONMENT, DATA_LINEAGE_INFO, SOURCE_SYSTEM, LOAD_DATE, UPDATE_DATE) SELECT 'DQ_' || REPLACE(REPLACE(REPLACE(CURRENT_TIMESTAMP()::STRING, ' ', '_'), ':', ''), '.', '_'), 'Silver_Data_Quality_Errors_ETL', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'COMPLETED', 0, 'SI_PIPELINE_AUDIT', 'SI_DATA_QUALITY_ERRORS', (SELECT COUNT(*) FROM {{ this }}), (SELECT COUNT(*) FROM {{ this }}), 0, 0, 'DBT_SILVER_JOB', 'PRODUCTION', 'Silver Data Quality Errors tracking', 'ZOOM_PLATFORM', CURRENT_DATE(), CURRENT_DATE()"
) }}

-- Silver Data Quality Errors Table
-- Tracks data validation errors and quality issues identified during Silver layer processing

WITH error_base AS (
    SELECT
        'DQ_ERROR_' || REPLACE(REPLACE(REPLACE(CURRENT_TIMESTAMP()::STRING, ' ', '_'), ':', ''), '.', '_') AS ERROR_ID,
        'SI_PIPELINE_AUDIT' AS SOURCE_TABLE,
        'AUDIT_INIT' AS SOURCE_RECORD_ID,
        'Missing Value' AS ERROR_TYPE,
        'EXECUTION_ID' AS ERROR_COLUMN,
        'Data Quality Error tracking initialization' AS ERROR_DESCRIPTION,
        'Low' AS ERROR_SEVERITY,
        CURRENT_TIMESTAMP() AS DETECTED_TIMESTAMP,
        'Open' AS RESOLUTION_STATUS,
        'System initialization' AS RESOLUTION_ACTION,
        NULL AS RESOLVED_TIMESTAMP,
        'DBT_SYSTEM' AS RESOLVED_BY,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        'ZOOM_PLATFORM' AS SOURCE_SYSTEM
    WHERE FALSE  -- This ensures no actual error records are created during initialization
    
    UNION ALL
    
    SELECT
        'DQ_INIT_001' AS ERROR_ID,
        'SYSTEM_INIT' AS SOURCE_TABLE,
        'INIT_001' AS SOURCE_RECORD_ID,
        'System Initialization' AS ERROR_TYPE,
        'N/A' AS ERROR_COLUMN,
        'Data Quality Error tracking system initialized successfully' AS ERROR_DESCRIPTION,
        'Low' AS ERROR_SEVERITY,
        CURRENT_TIMESTAMP() AS DETECTED_TIMESTAMP,
        'Resolved' AS RESOLUTION_STATUS,
        'System initialization completed' AS RESOLUTION_ACTION,
        CURRENT_TIMESTAMP() AS RESOLVED_TIMESTAMP,
        'DBT_SYSTEM' AS RESOLVED_BY,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        'ZOOM_PLATFORM' AS SOURCE_SYSTEM
)

SELECT
    ERROR_ID,
    SOURCE_TABLE,
    SOURCE_RECORD_ID,
    ERROR_TYPE,
    ERROR_COLUMN,
    ERROR_DESCRIPTION,
    ERROR_SEVERITY,
    DETECTED_TIMESTAMP,
    RESOLUTION_STATUS,
    RESOLUTION_ACTION,
    RESOLVED_TIMESTAMP,
    RESOLVED_BY,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM error_base
