{{ config(
    materialized='table',
    alias='SI_DATA_QUALITY_ERRORS'
) }}

/* Error Data Table - Empty structure for error logging */
SELECT 
    CAST(NULL AS VARCHAR(255)) AS ERROR_ID,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_TABLE,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_RECORD_KEY,
    CAST(NULL AS VARCHAR(255)) AS ERROR_TYPE,
    CAST(NULL AS VARCHAR(255)) AS ERROR_CATEGORY,
    CAST(NULL AS VARCHAR(255)) AS ERROR_DESCRIPTION,
    CAST(NULL AS VARCHAR(255)) AS ERROR_COLUMN,
    CAST(NULL AS VARCHAR(255)) AS ERROR_VALUE,
    CAST(NULL AS VARCHAR(255)) AS ERROR_SEVERITY,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS ERROR_TIMESTAMP,
    CAST(NULL AS VARCHAR(255)) AS RESOLUTION_STATUS,
    CAST(NULL AS VARCHAR(255)) AS RESOLUTION_NOTES,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS LOAD_TIMESTAMP,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS UPDATE_TIMESTAMP,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_SYSTEM
WHERE FALSE
