{{ config(materialized='table') }}

SELECT 
    USAGE_ID,
    MEETING_ID,
    FEATURE_NAME,
    USAGE_COUNT,
    USAGE_DATE,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    DATE(LOAD_TIMESTAMP) AS LOAD_DATE,
    DATE(COALESCE(UPDATE_TIMESTAMP, LOAD_TIMESTAMP)) AS UPDATE_DATE,
    100 AS DATA_QUALITY_SCORE,
    'PASSED' AS VALIDATION_STATUS
FROM BRONZE.BZ_FEATURE_USAGE
WHERE USAGE_ID IS NOT NULL
