{{ config(
    materialized='table'
) }}

/*
 * SI_FEATURE_USAGE - Silver Layer Feature Usage Table
 */

WITH bronze_feature_usage AS (
    SELECT 
        USAGE_ID,
        MEETING_ID,
        FEATURE_NAME,
        USAGE_COUNT,
        USAGE_DATE,
        LOAD_TIMESTAMP,
        UPDATE_TIMESTAMP,
        SOURCE_SYSTEM
    FROM BRONZE.BZ_FEATURE_USAGE
    WHERE USAGE_ID IS NOT NULL
      AND COALESCE(USAGE_COUNT, 0) >= 0
)

SELECT 
    USAGE_ID,
    MEETING_ID,
    UPPER(TRIM(FEATURE_NAME)) AS FEATURE_NAME,
    USAGE_COUNT,
    USAGE_DATE,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    DATE(LOAD_TIMESTAMP) AS LOAD_DATE,
    COALESCE(DATE(UPDATE_TIMESTAMP), DATE(LOAD_TIMESTAMP)) AS UPDATE_DATE,
    
    /* Data Quality Score Calculation */
    CASE 
        WHEN USAGE_ID IS NOT NULL 
            AND MEETING_ID IS NOT NULL 
            AND FEATURE_NAME IS NOT NULL 
            AND USAGE_COUNT IS NOT NULL 
            AND USAGE_COUNT >= 0
            AND USAGE_DATE IS NOT NULL
        THEN 100
        WHEN USAGE_ID IS NOT NULL AND MEETING_ID IS NOT NULL AND FEATURE_NAME IS NOT NULL 
        THEN 75
        WHEN USAGE_ID IS NOT NULL 
        THEN 50
        ELSE 25
    END AS DATA_QUALITY_SCORE,
    
    /* Validation Status */
    CASE 
        WHEN USAGE_ID IS NOT NULL 
            AND MEETING_ID IS NOT NULL 
            AND FEATURE_NAME IS NOT NULL 
            AND USAGE_COUNT IS NOT NULL 
            AND USAGE_COUNT >= 0
            AND USAGE_DATE IS NOT NULL
        THEN 'PASSED'
        WHEN USAGE_ID IS NOT NULL AND MEETING_ID IS NOT NULL 
        THEN 'WARNING'
        ELSE 'FAILED'
    END AS VALIDATION_STATUS
FROM bronze_feature_usage
