{{ config(
    materialized='table',
    pre_hook="INSERT INTO SILVER.SI_AUDIT_LOG (TABLE_NAME, PROCESS_STATUS, PROCESS_START_TIME, AUDIT_TIMESTAMP) SELECT 'SI_FEATURE_USAGE', 'STARTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()",
    post_hook="INSERT INTO SILVER.SI_AUDIT_LOG (TABLE_NAME, PROCESS_STATUS, PROCESS_END_TIME, RECORDS_PROCESSED, RECORDS_SUCCESS, AUDIT_TIMESTAMP) SELECT 'SI_FEATURE_USAGE', 'COMPLETED', CURRENT_TIMESTAMP(), (SELECT COUNT(*) FROM SILVER.SI_FEATURE_USAGE), (SELECT COUNT(*) FROM SILVER.SI_FEATURE_USAGE WHERE VALIDATION_STATUS = 'PASSED'), CURRENT_TIMESTAMP()"
) }}

-- Silver Layer Feature Usage Table
-- Transforms and cleanses feature usage data from Bronze layer

WITH bronze_feature_usage AS (
    SELECT 
        USAGE_ID,
        MEETING_ID,
        FEATURE_NAME,
        USAGE_COUNT,
        USAGE_DATE,
        LOAD_TIMESTAMP,
        UPDATE_TIMESTAMP,
        SOURCE_SYSTEM,
        ROW_NUMBER() OVER (PARTITION BY USAGE_ID ORDER BY UPDATE_TIMESTAMP DESC) AS rn
    FROM BRONZE.BZ_FEATURE_USAGE
    WHERE USAGE_ID IS NOT NULL
),

data_quality_checks AS (
    SELECT 
        *,
        -- Data quality scoring
        CASE 
            WHEN USAGE_ID IS NULL THEN 0
            WHEN MEETING_ID IS NULL THEN 20
            WHEN FEATURE_NAME IS NULL OR LENGTH(TRIM(FEATURE_NAME)) = 0 THEN 30
            WHEN USAGE_COUNT IS NULL OR USAGE_COUNT < 0 THEN 40
            WHEN USAGE_DATE IS NULL THEN 50
            WHEN USAGE_DATE > CURRENT_DATE() THEN 60
            ELSE 100
        END AS DATA_QUALITY_SCORE,
        
        CASE 
            WHEN USAGE_ID IS NULL OR MEETING_ID IS NULL THEN 'FAILED'
            WHEN FEATURE_NAME IS NULL OR LENGTH(TRIM(FEATURE_NAME)) = 0 THEN 'FAILED'
            WHEN USAGE_COUNT IS NULL OR USAGE_COUNT < 0 THEN 'FAILED'
            WHEN USAGE_DATE IS NULL OR USAGE_DATE > CURRENT_DATE() THEN 'WARNING'
            ELSE 'PASSED'
        END AS VALIDATION_STATUS
    FROM bronze_feature_usage
    WHERE rn = 1
)

SELECT 
    USAGE_ID,
    MEETING_ID,
    UPPER(TRIM(FEATURE_NAME)) AS FEATURE_NAME,
    COALESCE(USAGE_COUNT, 0) AS USAGE_COUNT,
    USAGE_DATE,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    DATA_QUALITY_SCORE,
    VALIDATION_STATUS
FROM data_quality_checks
WHERE VALIDATION_STATUS IN ('PASSED', 'WARNING')
