{{ config(materialized='table') }}

SELECT 
    LICENSE_ID,
    LICENSE_TYPE,
    ASSIGNED_TO_USER_ID,

    /* FIX: Always cast to STRING before applying formats */
    COALESCE(
        TRY_TO_DATE(START_DATE::STRING, 'DD/MM/YYYY'),
        TRY_TO_DATE(START_DATE::STRING, 'YYYY-MM-DD'),
        TRY_TO_DATE(START_DATE::STRING, 'MM/DD/YYYY'),
        TRY_TO_DATE(START_DATE::STRING)
    ) AS START_DATE,

    COALESCE(
        TRY_TO_DATE(END_DATE::STRING, 'DD/MM/YYYY'),
        TRY_TO_DATE(END_DATE::STRING, 'YYYY-MM-DD'),
        TRY_TO_DATE(END_DATE::STRING, 'MM/DD/YYYY'),
        TRY_TO_DATE(END_DATE::STRING)
    ) AS END_DATE,

    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    DATE(LOAD_TIMESTAMP) AS LOAD_DATE,
    DATE(COALESCE(UPDATE_TIMESTAMP, LOAD_TIMESTAMP)) AS UPDATE_DATE,

    100 AS DATA_QUALITY_SCORE,
    'PASSED' AS VALIDATION_STATUS

FROM BRONZE.BZ_LICENSES
WHERE LICENSE_ID IS NOT NULL;
