{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('SI_Audit_Log') }} (TABLE_NAME, PROCESS_STATUS, PROCESS_START_TIME, AUDIT_TIMESTAMP) SELECT 'SI_LICENSES', 'STARTED', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() WHERE '{{ this.name }}' != 'SI_Audit_Log'",
    post_hook="INSERT INTO {{ ref('SI_Audit_Log') }} (TABLE_NAME, PROCESS_STATUS, PROCESS_END_TIME, RECORDS_PROCESSED, RECORDS_SUCCESS, AUDIT_TIMESTAMP) SELECT 'SI_LICENSES', 'COMPLETED', CURRENT_TIMESTAMP(), (SELECT COUNT(*) FROM {{ this }}), (SELECT COUNT(*) FROM {{ this }} WHERE VALIDATION_STATUS = 'PASSED'), CURRENT_TIMESTAMP() WHERE '{{ this.name }}' != 'SI_Audit_Log'"
) }}

-- Silver Layer Licenses Table
-- Transforms and cleanses license data from Bronze layer with DD/MM/YYYY format handling

WITH bronze_licenses AS (
    SELECT 
        LICENSE_ID,
        LICENSE_TYPE,
        ASSIGNED_TO_USER_ID,
        START_DATE,
        END_DATE,
        LOAD_TIMESTAMP,
        UPDATE_TIMESTAMP,
        SOURCE_SYSTEM,
        ROW_NUMBER() OVER (PARTITION BY LICENSE_ID ORDER BY UPDATE_TIMESTAMP DESC) AS rn
    FROM {{ source('bronze', 'BZ_LICENSES') }}
    WHERE LICENSE_ID IS NOT NULL
),

cleaned_licenses AS (
    SELECT 
        *,
        -- Handle DD/MM/YYYY format in dates
        CASE 
            WHEN START_DATE::STRING REGEXP '^\\d{1,2}/\\d{1,2}/\\d{4}$' THEN 
                TRY_TO_DATE(START_DATE::STRING, 'DD/MM/YYYY')
            ELSE START_DATE
        END AS CLEAN_START_DATE,
        
        CASE 
            WHEN END_DATE::STRING REGEXP '^\\d{1,2}/\\d{1,2}/\\d{4}$' THEN 
                TRY_TO_DATE(END_DATE::STRING, 'DD/MM/YYYY')
            ELSE END_DATE
        END AS CLEAN_END_DATE
    FROM bronze_licenses
    WHERE rn = 1
),

data_quality_checks AS (
    SELECT 
        *,
        -- Data quality scoring
        CASE 
            WHEN LICENSE_ID IS NULL THEN 0
            WHEN LICENSE_TYPE IS NULL OR LENGTH(TRIM(LICENSE_TYPE)) = 0 THEN 20
            WHEN ASSIGNED_TO_USER_ID IS NULL THEN 30
            WHEN CLEAN_START_DATE IS NULL THEN 40
            WHEN CLEAN_END_DATE IS NULL THEN 50
            WHEN CLEAN_START_DATE >= CLEAN_END_DATE THEN 60
            ELSE 100
        END AS DATA_QUALITY_SCORE,
        
        CASE 
            WHEN LICENSE_ID IS NULL OR ASSIGNED_TO_USER_ID IS NULL THEN 'FAILED'
            WHEN LICENSE_TYPE IS NULL OR LENGTH(TRIM(LICENSE_TYPE)) = 0 THEN 'FAILED'
            WHEN CLEAN_START_DATE IS NULL OR CLEAN_END_DATE IS NULL THEN 'FAILED'
            WHEN CLEAN_START_DATE >= CLEAN_END_DATE THEN 'FAILED'
            ELSE 'PASSED'
        END AS VALIDATION_STATUS
    FROM cleaned_licenses
)

SELECT 
    LICENSE_ID,
    UPPER(TRIM(LICENSE_TYPE)) AS LICENSE_TYPE,
    ASSIGNED_TO_USER_ID,
    CLEAN_START_DATE AS START_DATE,
    CLEAN_END_DATE AS END_DATE,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    DATA_QUALITY_SCORE,
    VALIDATION_STATUS
FROM data_quality_checks
WHERE VALIDATION_STATUS IN ('PASSED', 'WARNING')
