{{ config(materialized='table') }}

SELECT 
    MEETING_ID,
    HOST_ID,
    MEETING_TOPIC,
    START_TIME,
    END_TIME,
    CASE 
        WHEN TRY_TO_NUMBER(REGEXP_REPLACE(DURATION_MINUTES::STRING, '[^0-9.]', '')) IS NOT NULL THEN
            TRY_TO_NUMBER(REGEXP_REPLACE(DURATION_MINUTES::STRING, '[^0-9.]', ''))
        ELSE TRY_TO_NUMBER(DURATION_MINUTES::STRING)
    END AS DURATION_MINUTES,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    DATE(LOAD_TIMESTAMP) AS LOAD_DATE,
    DATE(COALESCE(UPDATE_TIMESTAMP, LOAD_TIMESTAMP)) AS UPDATE_DATE,
    100 AS DATA_QUALITY_SCORE,
    'PASSED' AS VALIDATION_STATUS
FROM BRONZE.BZ_MEETINGS
WHERE MEETING_ID IS NOT NULL
