{{ config(
    materialized='table',
    on_schema_change='sync_all_columns',
    tags=['silver', 'audit']
) }}

SELECT
    CAST(NULL AS VARCHAR(255)) AS EXECUTION_ID,
    CAST(NULL AS VARCHAR(255)) AS PIPELINE_NAME,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS START_TIME,
    CAST(NULL AS TIMESTAMP_NTZ(9)) AS END_TIME,
    CAST(NULL AS VARCHAR(50)) AS STATUS,
    CAST(NULL AS VARCHAR(5000)) AS ERROR_MESSAGE,
    CAST(NULL AS NUMBER) AS EXECUTION_DURATION_SECONDS,
    CAST(NULL AS VARCHAR(1000)) AS SOURCE_TABLES_PROCESSED,
    CAST(NULL AS VARCHAR(1000)) AS TARGET_TABLES_UPDATED,
    CAST(NULL AS NUMBER) AS RECORDS_PROCESSED,
    CAST(NULL AS NUMBER) AS RECORDS_INSERTED,
    CAST(NULL AS NUMBER) AS RECORDS_UPDATED,
    CAST(NULL AS NUMBER) AS RECORDS_REJECTED,
    CAST(NULL AS VARCHAR(255)) AS EXECUTED_BY,
    CAST(NULL AS VARCHAR(50)) AS EXECUTION_ENVIRONMENT,
    CAST(NULL AS VARCHAR(5000)) AS DATA_LINEAGE_INFO,
    CAST(NULL AS DATE) AS LOAD_DATE,
    CAST(NULL AS DATE) AS UPDATE_DATE,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_SYSTEM
WHERE 1=0
