{{ config(materialized='table') }}

SELECT 
    PARTICIPANT_ID,
    MEETING_ID,
    USER_ID,
    COALESCE(
        TRY_TO_TIMESTAMP(JOIN_TIME, 'YYYY-MM-DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(JOIN_TIME, 'DD/MM/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(JOIN_TIME, 'MM/DD/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(JOIN_TIME)
    ) AS JOIN_TIME,
    COALESCE(
        TRY_TO_TIMESTAMP(LEAVE_TIME, 'YYYY-MM-DD HH24:MI:SS'),
        TRY_TO_TIMESTAMP(LEAVE_TIME, 'DD/MM/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(LEAVE_TIME, 'MM/DD/YYYY HH24:MI'),
        TRY_TO_TIMESTAMP(LEAVE_TIME)
    ) AS LEAVE_TIME,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    DATE(LOAD_TIMESTAMP) AS LOAD_DATE,
    DATE(COALESCE(UPDATE_TIMESTAMP, LOAD_TIMESTAMP)) AS UPDATE_DATE,
    100 AS DATA_QUALITY_SCORE,
    'PASSED' AS VALIDATION_STATUS
FROM BRONZE.BZ_PARTICIPANTS
WHERE PARTICIPANT_ID IS NOT NULL
