{{ config(
    materialized='table',
    on_schema_change='sync_all_columns'
) }}

SELECT 
    CAST(NULL AS VARCHAR(255)) AS AUDIT_ID,
    CAST(NULL AS VARCHAR(255)) AS PIPELINE_NAME,
    CAST(NULL AS VARCHAR(255)) AS PIPELINE_RUN_ID,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_TABLE,
    CAST(NULL AS VARCHAR(255)) AS TARGET_TABLE,
    CAST(NULL AS TIMESTAMP_NTZ) AS EXECUTION_START_TIME,
    CAST(NULL AS TIMESTAMP_NTZ) AS EXECUTION_END_TIME,
    CAST(NULL AS NUMBER(10,2)) AS EXECUTION_DURATION_SECONDS,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_READ,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_PROCESSED,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_INSERTED,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_UPDATED,
    CAST(NULL AS NUMBER(38,0)) AS RECORDS_REJECTED,
    CAST(NULL AS NUMBER(38,0)) AS ERROR_COUNT,
    CAST(NULL AS NUMBER(38,0)) AS WARNING_COUNT,
    CAST(NULL AS VARCHAR(255)) AS EXECUTION_STATUS,
    CAST(NULL AS VARCHAR(1000)) AS ERROR_MESSAGE,
    CAST(NULL AS VARCHAR(255)) AS PROCESSED_BY,
    CAST(NULL AS VARCHAR(255)) AS PROCESSING_MODE,
    CAST(NULL AS TIMESTAMP_NTZ) AS DATA_FRESHNESS_TIMESTAMP,
    CAST(NULL AS VARCHAR(1000)) AS RESOURCE_UTILIZATION,
    CAST(NULL AS DATE) AS LOAD_DATE,
    CAST(NULL AS DATE) AS UPDATE_DATE,
    CAST(NULL AS VARCHAR(255)) AS SOURCE_SYSTEM
WHERE FALSE
