{{ config(
    materialized='table',
    on_schema_change='sync_all_columns'
) }}

-- Silver Layer Pipeline Audit Table
-- This table tracks all Silver layer pipeline execution details independently

SELECT 
    CONCAT('EXEC_', TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS'), '_', ABS(HASH(RANDOM()))) AS EXECUTION_ID,
    'Silver_Pipeline_Initial_Load' AS PIPELINE_NAME,
    CURRENT_TIMESTAMP() AS START_TIME,
    CURRENT_TIMESTAMP() AS END_TIME,
    'Success' AS STATUS,
    NULL AS ERROR_MESSAGE,
    0 AS EXECUTION_DURATION_SECONDS,
    'BRONZE.BZ_USERS,BRONZE.BZ_MEETINGS,BRONZE.BZ_PARTICIPANTS,BRONZE.BZ_FEATURE_USAGE,BRONZE.BZ_SUPPORT_TICKETS,BRONZE.BZ_BILLING_EVENTS,BRONZE.BZ_LICENSES,BRONZE.BZ_WEBINARS' AS SOURCE_TABLES_PROCESSED,
    'SILVER.SI_USERS,SILVER.SI_MEETINGS,SILVER.SI_PARTICIPANTS,SILVER.SI_FEATURE_USAGE,SILVER.SI_SUPPORT_TICKETS,SILVER.SI_BILLING_EVENTS,SILVER.SI_LICENSES,SILVER.SI_WEBINARS' AS TARGET_TABLES_UPDATED,
    0 AS RECORDS_PROCESSED,
    0 AS RECORDS_INSERTED,
    0 AS RECORDS_UPDATED,
    0 AS RECORDS_REJECTED,
    'DBT_SILVER_PIPELINE' AS EXECUTED_BY,
    'PRODUCTION' AS EXECUTION_ENVIRONMENT,
    'Silver layer data transformation from Bronze to Silver with data quality validations' AS DATA_LINEAGE_INFO,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    'ZOOM_PLATFORM' AS SOURCE_SYSTEM
WHERE FALSE -- This creates the table structure without inserting initial data

UNION ALL

-- Insert initial audit record
SELECT 
    CONCAT('EXEC_', TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS'), '_', ABS(HASH(RANDOM()))) AS EXECUTION_ID,
    'Silver_Pipeline_Audit_Table_Creation' AS PIPELINE_NAME,
    CURRENT_TIMESTAMP() AS START_TIME,
    CURRENT_TIMESTAMP() AS END_TIME,
    'Success' AS STATUS,
    NULL AS ERROR_MESSAGE,
    1 AS EXECUTION_DURATION_SECONDS,
    'SILVER.SI_PIPELINE_AUDIT' AS SOURCE_TABLES_PROCESSED,
    'SILVER.SI_PIPELINE_AUDIT' AS TARGET_TABLES_UPDATED,
    1 AS RECORDS_PROCESSED,
    1 AS RECORDS_INSERTED,
    0 AS RECORDS_UPDATED,
    0 AS RECORDS_REJECTED,
    'DBT_SILVER_PIPELINE' AS EXECUTED_BY,
    'PRODUCTION' AS EXECUTION_ENVIRONMENT,
    'Initial audit table creation for Silver layer pipeline tracking' AS DATA_LINEAGE_INFO,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    'ZOOM_PLATFORM' AS SOURCE_SYSTEM
