{{ config(materialized='table') }}

SELECT 
    TICKET_ID,
    USER_ID,
    TICKET_TYPE,
    RESOLUTION_STATUS,
    OPEN_DATE,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    DATE(LOAD_TIMESTAMP) AS LOAD_DATE,
    DATE(COALESCE(UPDATE_TIMESTAMP, LOAD_TIMESTAMP)) AS UPDATE_DATE,
    100 AS DATA_QUALITY_SCORE,
    'PASSED' AS VALIDATION_STATUS
FROM BRONZE.BZ_SUPPORT_TICKETS
WHERE TICKET_ID IS NOT NULL
