{{ config(materialized='table') }}

SELECT 
    USER_ID,
    USER_NAME,
    EMAIL,
    COMPANY,
    PLAN_TYPE,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM,
    DATE(LOAD_TIMESTAMP) AS LOAD_DATE,
    DATE(COALESCE(UPDATE_TIMESTAMP, LOAD_TIMESTAMP)) AS UPDATE_DATE,
    100 AS DATA_QUALITY_SCORE,
    'PASSED' AS VALIDATION_STATUS
FROM BRONZE.BZ_USERS
WHERE USER_ID IS NOT NULL
