{{ config(materialized='table') }}

SELECT 
    USER_ID,
    USER_NAME,
    EMAIL,
    COMPANY,
    PLAN_TYPE,
    LOAD_TIMESTAMP,
    UPDATE_TIMESTAMP,
    SOURCE_SYSTEM
FROM BRONZE.BZ_USERS
WHERE USER_ID IS NOT NULL
LIMIT 100
