version: 2

sources:
  - name: raw
    description: "Raw data layer containing unprocessed data from various source systems"
    database: DB_POC_ZOOM
    schema: RAW
    tables:
      - name: users
        description: "Raw user profile and subscription information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
            tests:
              - not_null
              - unique
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user"
          - name: company
            description: "Company or organization name"
          - name: plan_type
            description: "Subscription plan type"
          - name: load_timestamp
            description: "Timestamp when record was loaded into system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: meetings
        description: "Raw meeting information and session details"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Timestamp when record was loaded into system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: participants
        description: "Raw meeting participants and their session details"
        columns:
          - name: participant_id
            description: "Unique identifier for each meeting participant"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user who participated"
          - name: join_time
            description: "Timestamp when participant joined meeting"
          - name: leave_time
            description: "Timestamp when participant left meeting"
          - name: load_timestamp
            description: "Timestamp when record was loaded into system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: feature_usage
        description: "Raw usage of platform features during meetings"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to meeting where feature was used"
          - name: feature_name
            description: "Name of the feature being tracked"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date when feature usage occurred"
          - name: load_timestamp
            description: "Timestamp when record was loaded into system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: support_tickets
        description: "Raw customer support requests and resolution tracking"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "Reference to user who created the ticket"
          - name: ticket_type
            description: "Type of support ticket"
          - name: resolution_status
            description: "Current status of ticket resolution"
          - name: open_date
            description: "Date when ticket was opened"
          - name: load_timestamp
            description: "Timestamp when record was loaded into system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: billing_events
        description: "Raw financial transactions and billing activities"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "Reference to user associated with billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Monetary amount for the billing event"
          - name: event_date
            description: "Date when the billing event occurred"
          - name: load_timestamp
            description: "Timestamp when record was loaded into system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: licenses
        description: "Raw license assignments and entitlements"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
            tests:
              - not_null
              - unique
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID to whom license is assigned"
          - name: start_date
            description: "License validity start date"
          - name: end_date
            description: "License validity end date"
          - name: load_timestamp
            description: "Timestamp when record was loaded into system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"

models:
  - name: bz_data_audit
    description: "Comprehensive audit trail for all Bronze layer data operations"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for each audit record"
        data_type: number
        tests:
          - not_null
          - unique
      - name: source_table
        description: "Name of the Bronze layer table being processed"
        data_type: varchar(255)
        tests:
          - not_null
      - name: load_timestamp
        description: "When the operation occurred"
        data_type: timestamp_ntz
        tests:
          - not_null
      - name: processed_by
        description: "User or process that performed the operation"
        data_type: varchar(255)
        tests:
          - not_null
      - name: processing_time
        description: "Time taken to process the operation in seconds"
        data_type: number(38,3)
      - name: status
        description: "Status of the operation (SUCCESS, FAILED, WARNING, STARTED)"
        data_type: varchar(255)
        tests:
          - not_null
          - accepted_values:
              values: ['SUCCESS', 'FAILED', 'WARNING', 'STARTED', 'INITIALIZED']
              
  - name: bz_users
    description: "Bronze layer table storing raw user profile and subscription information"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        data_type: varchar(16777216)
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Display name of the user (PII)"
        data_type: varchar(16777216)
      - name: email
        description: "Email address of the user (PII)"
        data_type: varchar(16777216)
      - name: company
        description: "Company or organization name"
        data_type: varchar(16777216)
      - name: plan_type
        description: "Subscription plan type"
        data_type: varchar(16777216)
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system from which data originated"
        data_type: varchar(16777216)
        
  - name: bz_meetings
    description: "Bronze layer table storing raw meeting information and session details"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        data_type: varchar(16777216)
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of the meeting host"
        data_type: varchar(16777216)
      - name: meeting_topic
        description: "Topic or title of the meeting (Potential PII)"
        data_type: varchar(16777216)
      - name: start_time
        description: "Meeting start timestamp"
        data_type: timestamp_ntz
      - name: end_time
        description: "Meeting end timestamp"
        data_type: timestamp_ntz
      - name: duration_minutes
        description: "Meeting duration in minutes"
        data_type: number(38,0)
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system from which data originated"
        data_type: varchar(16777216)
        
  - name: bz_participants
    description: "Bronze layer table tracking raw meeting participants and their session details"
    columns:
      - name: participant_id
        description: "Unique identifier for each meeting participant"
        data_type: varchar(16777216)
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting"
        data_type: varchar(16777216)
      - name: user_id
        description: "Reference to user who participated"
        data_type: varchar(16777216)
      - name: join_time
        description: "Timestamp when participant joined meeting"
        data_type: timestamp_ntz
      - name: leave_time
        description: "Timestamp when participant left meeting"
        data_type: timestamp_ntz
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system from which data originated"
        data_type: varchar(16777216)
        
  - name: bz_feature_usage
    description: "Bronze layer table recording raw usage of platform features during meetings"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        data_type: varchar(16777216)
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting where feature was used"
        data_type: varchar(16777216)
      - name: feature_name
        description: "Name of the feature being tracked"
        data_type: varchar(16777216)
      - name: usage_count
        description: "Number of times feature was used"
        data_type: number(38,0)
      - name: usage_date
        description: "Date when feature usage occurred"
        data_type: date
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system from which data originated"
        data_type: varchar(16777216)
        
  - name: bz_support_tickets
    description: "Bronze layer table managing raw customer support requests and resolution tracking"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        data_type: varchar(16777216)
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to user who created the ticket"
        data_type: varchar(16777216)
      - name: ticket_type
        description: "Type of support ticket"
        data_type: varchar(16777216)
      - name: resolution_status
        description: "Current status of ticket resolution"
        data_type: varchar(16777216)
      - name: open_date
        description: "Date when ticket was opened"
        data_type: date
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system from which data originated"
        data_type: varchar(16777216)
        
  - name: bz_billing_events
    description: "Bronze layer table tracking raw financial transactions and billing activities"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        data_type: varchar(16777216)
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to user associated with billing event"
        data_type: varchar(16777216)
      - name: event_type
        description: "Type of billing event"
        data_type: varchar(16777216)
      - name: amount
        description: "Monetary amount for the billing event"
        data_type: number(10,2)
      - name: event_date
        description: "Date when the billing event occurred"
        data_type: date
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system from which data originated"
        data_type: varchar(16777216)
        
  - name: bz_licenses
    description: "Bronze layer table managing raw license assignments and entitlements"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        data_type: varchar(16777216)
        tests:
          - not_null
          - unique
      - name: license_type
        description: "Type of license"
        data_type: varchar(16777216)
      - name: assigned_to_user_id
        description: "User ID to whom license is assigned"
        data_type: varchar(16777216)
      - name: start_date
        description: "License validity start date"
        data_type: date
      - name: end_date
        description: "License validity end date"
        data_type: date
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        data_type: timestamp_ntz
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        data_type: timestamp_ntz
      - name: source_system
        description: "Source system from which data originated"
        data_type: varchar(16777216)
