version: 2

sources:
  - name: raw_schema
    description: "Raw data source schema containing unprocessed data from Zoom platform"
    database: DB_POC_ZOOM
    schema: RAW
    tables:
      - name: users
        description: "Raw user account information from Zoom platform"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
            tests:
              - not_null
              - unique
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user - PII Data"
          - name: company
            description: "Company or organization name"
          - name: plan_type
            description: "Type of subscription plan"
          - name: load_timestamp
            description: "Timestamp when record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: meetings
        description: "Raw meeting session data from Zoom platform"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: start_time
            description: "Meeting start timestamp"
          - name: end_time
            description: "Meeting end timestamp"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: load_timestamp
            description: "Timestamp when record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: participants
        description: "Raw participant data for meeting attendance tracking"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user who participated"
          - name: join_time
            description: "Timestamp when participant joined"
          - name: leave_time
            description: "Timestamp when participant left"
          - name: load_timestamp
            description: "Timestamp when record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: feature_usage
        description: "Raw feature usage data for platform analytics"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to meeting where feature was used"
          - name: feature_name
            description: "Name of the feature being tracked"
          - name: usage_count
            description: "Number of times feature was used"
          - name: usage_date
            description: "Date when feature usage occurred"
          - name: load_timestamp
            description: "Timestamp when record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: support_tickets
        description: "Raw support ticket data for customer service analytics"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "Reference to user who created the ticket"
          - name: ticket_type
            description: "Type or category of support ticket"
          - name: resolution_status
            description: "Current status of ticket resolution"
          - name: open_date
            description: "Date when ticket was opened"
          - name: load_timestamp
            description: "Timestamp when record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: billing_events
        description: "Raw billing event data for revenue analytics"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "Reference to user associated with billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Monetary amount for the billing event"
          - name: event_date
            description: "Date when the billing event occurred"
          - name: load_timestamp
            description: "Timestamp when record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: licenses
        description: "Raw license data for license management analytics"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
            tests:
              - not_null
              - unique
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID to whom license is assigned"
          - name: start_date
            description: "License start date"
          - name: end_date
            description: "License end date"
          - name: load_timestamp
            description: "Timestamp when record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"
            
      - name: webinars
        description: "Raw webinar session data from Zoom platform"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "User ID of the webinar host"
          - name: webinar_topic
            description: "Topic or title of the webinar"
          - name: start_time
            description: "Webinar start timestamp"
          - name: end_time
            description: "Webinar end timestamp"
          - name: registrants
            description: "Number of registered participants"
          - name: load_timestamp
            description: "Timestamp when record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when record was last updated"
          - name: source_system
            description: "Source system from which data originated"

models:
  - name: bz_audit_log
    description: "Audit table for tracking data processing activities in Bronze layer"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for audit record"
        tests:
          - not_null
          - unique
      - name: source_table
        description: "Name of the source table being processed"
        tests:
          - not_null
      - name: process_start_time
        description: "Timestamp when data processing started"
      - name: process_end_time
        description: "Timestamp when data processing ended"
      - name: status
        description: "Status of the processing operation (STARTED, COMPLETED, FAILED)"
        tests:
          - not_null
      - name: created_by
        description: "User or system that processed the data"
        tests:
          - not_null
      - name: created_timestamp
        description: "Timestamp when audit record was created"
        tests:
          - not_null
          
  - name: bz_users
    description: "Bronze layer table storing raw user account data from Zoom platform"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Display name of the user"
      - name: email
        description: "Email address of the user - PII Data"
      - name: company
        description: "Company or organization name"
      - name: plan_type
        description: "Type of subscription plan"
      - name: load_timestamp
        description: "Timestamp when record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system from which data originated"
        tests:
          - not_null
          
  - name: bz_meetings
    description: "Bronze layer table storing raw meeting session data from Zoom platform"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of the meeting host"
      - name: meeting_topic
        description: "Topic or title of the meeting"
      - name: start_time
        description: "Meeting start timestamp"
      - name: end_time
        description: "Meeting end timestamp"
      - name: duration_minutes
        description: "Meeting duration in minutes"
      - name: load_timestamp
        description: "Timestamp when record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system from which data originated"
        tests:
          - not_null
          
  - name: bz_participants
    description: "Bronze layer table storing raw participant data for meeting attendance tracking"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting"
      - name: user_id
        description: "Reference to user who participated"
      - name: join_time
        description: "Timestamp when participant joined"
      - name: leave_time
        description: "Timestamp when participant left"
      - name: load_timestamp
        description: "Timestamp when record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system from which data originated"
        tests:
          - not_null
          
  - name: bz_feature_usage
    description: "Bronze layer table storing raw feature usage data for platform analytics"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to meeting where feature was used"
      - name: feature_name
        description: "Name of the feature being tracked"
      - name: usage_count
        description: "Number of times feature was used"
      - name: usage_date
        description: "Date when feature usage occurred"
      - name: load_timestamp
        description: "Timestamp when record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system from which data originated"
        tests:
          - not_null
          
  - name: bz_support_tickets
    description: "Bronze layer table storing raw support ticket data for customer service analytics"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to user who created the ticket"
      - name: ticket_type
        description: "Type or category of support ticket"
      - name: resolution_status
        description: "Current status of ticket resolution"
      - name: open_date
        description: "Date when ticket was opened"
      - name: load_timestamp
        description: "Timestamp when record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system from which data originated"
        tests:
          - not_null
          
  - name: bz_billing_events
    description: "Bronze layer table storing raw billing event data for revenue analytics"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to user associated with billing event"
      - name: event_type
        description: "Type of billing event"
      - name: amount
        description: "Monetary amount for the billing event"
      - name: event_date
        description: "Date when the billing event occurred"
      - name: load_timestamp
        description: "Timestamp when record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system from which data originated"
        tests:
          - not_null
          
  - name: bz_licenses
    description: "Bronze layer table storing raw license data for license management analytics"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        tests:
          - not_null
          - unique
      - name: license_type
        description: "Type of license"
      - name: assigned_to_user_id
        description: "User ID to whom license is assigned"
      - name: start_date
        description: "License start date"
      - name: end_date
        description: "License end date"
      - name: load_timestamp
        description: "Timestamp when record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system from which data originated"
        tests:
          - not_null
          
  - name: bz_webinars
    description: "Bronze layer table storing raw webinar session data from Zoom platform"
    columns:
      - name: webinar_id
        description: "Unique identifier for each webinar"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "User ID of the webinar host"
      - name: webinar_topic
        description: "Topic or title of the webinar"
      - name: start_time
        description: "Webinar start timestamp"
      - name: end_time
        description: "Webinar end timestamp"
      - name: registrants
        description: "Number of registered participants"
      - name: load_timestamp
        description: "Timestamp when record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system from which data originated"
        tests:
          - not_null
