version: 2

sources:
  - name: raw
    description: "Raw data layer containing unprocessed data from Zoom platform"
    tables:
      - name: users
        description: "Raw user account information"
      - name: meetings
        description: "Raw meeting session information"
      - name: participants
        description: "Raw meeting participant information"
      - name: feature_usage
        description: "Raw platform feature usage tracking"
      - name: support_tickets
        description: "Raw customer support ticket information"
      - name: billing_events
        description: "Raw billing and financial transaction information"
      - name: licenses
        description: "Raw license management information"
      - name: webinars
        description: "Raw webinar session information"

models:
  - name: bz_users
    description: "Bronze layer table storing raw user account data from Zoom platform"
  - name: bz_meetings
    description: "Bronze layer table storing raw meeting session data from Zoom platform"
  - name: bz_participants
    description: "Bronze layer table storing raw participant data for meeting attendance tracking"
  - name: bz_feature_usage
    description: "Bronze layer table storing raw feature usage data for platform analytics"
  - name: bz_support_tickets
    description: "Bronze layer table storing raw support ticket data for customer service analytics"
  - name: bz_billing_events
    description: "Bronze layer table storing raw billing event data for revenue analytics"
  - name: bz_licenses
    description: "Bronze layer table storing raw license data for license management analytics"
  - name: bz_webinars
    description: "Bronze layer table storing raw webinar session data from Zoom platform"
