version: 2

sources:
  - name: raw_zoom_data
    description: "Raw data from Zoom platform ingested into RAW schema"
    database: DB_POC_ZOOM
    schema: RAW
    tables:
      - name: users
        description: "Raw user account information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user account"
          - name: company
            description: "Company or organization the user is associated with"
          - name: plan_type
            description: "Subscription plan type for the user"
          - name: load_timestamp
            description: "Timestamp when the record was first loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "Source system from which the data originated"
      
      - name: meetings
        description: "Raw meeting information"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting session"
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Subject or topic of the meeting"
          - name: start_time
            description: "Timestamp when the meeting started"
          - name: end_time
            description: "Timestamp when the meeting ended"
          - name: duration_minutes
            description: "Total duration of the meeting in minutes"
          - name: load_timestamp
            description: "Timestamp when the record was first loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "Source system from which the data originated"
      
      - name: participants
        description: "Raw participant information"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant session"
          - name: meeting_id
            description: "Identifier linking to the meeting the participant joined"
          - name: user_id
            description: "Identifier of the user who participated in the meeting"
          - name: join_time
            description: "Timestamp when the participant joined the meeting"
          - name: leave_time
            description: "Timestamp when the participant left the meeting"
          - name: load_timestamp
            description: "Timestamp when the record was first loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "Source system from which the data originated"
      
      - name: feature_usage
        description: "Raw feature usage information"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
          - name: meeting_id
            description: "Identifier linking to the meeting where feature was used"
          - name: feature_name
            description: "Name of the Zoom feature that was used"
          - name: usage_count
            description: "Number of times the feature was used in the meeting"
          - name: usage_date
            description: "Date when the feature usage occurred"
          - name: load_timestamp
            description: "Timestamp when the record was first loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "Source system from which the data originated"
      
      - name: support_tickets
        description: "Raw support ticket information"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
          - name: user_id
            description: "Identifier of the user who created the support ticket"
          - name: ticket_type
            description: "Category or type of the support ticket"
          - name: resolution_status
            description: "Current status of the support ticket resolution"
          - name: open_date
            description: "Date when the support ticket was created"
          - name: load_timestamp
            description: "Timestamp when the record was first loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "Source system from which the data originated"
      
      - name: billing_events
        description: "Raw billing event information"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
          - name: user_id
            description: "Identifier linking to the user associated with the billing event"
          - name: event_type
            description: "Type of billing event (charge, credit, refund, etc.)"
          - name: amount
            description: "Monetary amount of the billing event"
          - name: event_date
            description: "Date when the billing event occurred"
          - name: load_timestamp
            description: "Timestamp when the record was first loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "Source system from which the data originated"
      
      - name: licenses
        description: "Raw license information"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
          - name: license_type
            description: "Type of Zoom license (Basic, Pro, Business, Enterprise)"
          - name: assigned_to_user_id
            description: "User ID to whom the license is assigned"
          - name: start_date
            description: "Date when the license becomes active"
          - name: end_date
            description: "Date when the license expires"
          - name: load_timestamp
            description: "Timestamp when the record was first loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "Source system from which the data originated"

models:
  - name: bz_audit_log
    description: "Bronze layer audit log for tracking data processing activities"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for each audit record"
      - name: source_table
        description: "Name of the source table being processed"
      - name: load_timestamp
        description: "Timestamp when the processing started"
      - name: processed_by
        description: "System or process that performed the operation"
      - name: processing_time
        description: "Time taken to process the data in seconds"
      - name: status
        description: "Status of the processing operation"
  
  - name: bz_users
    description: "Bronze layer users table with raw data from source"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
      - name: user_name
        description: "Display name of the user"
      - name: email
        description: "Email address of the user account"
      - name: company
        description: "Company or organization the user is associated with"
      - name: plan_type
        description: "Subscription plan type for the user"
      - name: load_timestamp
        description: "Timestamp when the record was first loaded into the system"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system from which the data originated"
  
  - name: bz_meetings
    description: "Bronze layer meetings table with raw data from source"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting session"
      - name: host_id
        description: "User ID of the meeting host"
      - name: meeting_topic
        description: "Subject or topic of the meeting"
      - name: start_time
        description: "Timestamp when the meeting started"
      - name: end_time
        description: "Timestamp when the meeting ended"
      - name: duration_minutes
        description: "Total duration of the meeting in minutes"
      - name: load_timestamp
        description: "Timestamp when the record was first loaded into the system"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system from which the data originated"
  
  - name: bz_participants
    description: "Bronze layer participants table with raw data from source"
    columns:
      - name: participant_id
        description: "Unique identifier for each participant session"
      - name: meeting_id
        description: "Identifier linking to the meeting the participant joined"
      - name: user_id
        description: "Identifier of the user who participated in the meeting"
      - name: join_time
        description: "Timestamp when the participant joined the meeting"
      - name: leave_time
        description: "Timestamp when the participant left the meeting"
      - name: load_timestamp
        description: "Timestamp when the record was first loaded into the system"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system from which the data originated"
  
  - name: bz_feature_usage
    description: "Bronze layer feature usage table with raw data from source"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
      - name: meeting_id
        description: "Identifier linking to the meeting where feature was used"
      - name: feature_name
        description: "Name of the Zoom feature that was used"
      - name: usage_count
        description: "Number of times the feature was used in the meeting"
      - name: usage_date
        description: "Date when the feature usage occurred"
      - name: load_timestamp
        description: "Timestamp when the record was first loaded into the system"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system from which the data originated"
  
  - name: bz_support_tickets
    description: "Bronze layer support tickets table with raw data from source"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
      - name: user_id
        description: "Identifier of the user who created the support ticket"
      - name: ticket_type
        description: "Category or type of the support ticket"
      - name: resolution_status
        description: "Current status of the support ticket resolution"
      - name: open_date
        description: "Date when the support ticket was created"
      - name: load_timestamp
        description: "Timestamp when the record was first loaded into the system"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system from which the data originated"
  
  - name: bz_billing_events
    description: "Bronze layer billing events table with raw data from source"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
      - name: user_id
        description: "Identifier linking to the user associated with the billing event"
      - name: event_type
        description: "Type of billing event (charge, credit, refund, etc.)"
      - name: amount
        description: "Monetary amount of the billing event"
      - name: event_date
        description: "Date when the billing event occurred"
      - name: load_timestamp
        description: "Timestamp when the record was first loaded into the system"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system from which the data originated"
  
  - name: bz_licenses
    description: "Bronze layer licenses table with raw data from source"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
      - name: license_type
        description: "Type of Zoom license (Basic, Pro, Business, Enterprise)"
      - name: assigned_to_user_id
        description: "User ID to whom the license is assigned"
      - name: start_date
        description: "Date when the license becomes active"
      - name: end_date
        description: "Date when the license expires"
      - name: load_timestamp
        description: "Timestamp when the record was first loaded into the system"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system from which the data originated"
