version: 2

sources:
  - name: raw
    description: "Raw data layer containing unprocessed data from various Zoom sources"
    database: DB_POC_ZOOM
    schema: RAW
    tables:
      - name: BILLING_EVENTS
        description: "Raw billing and payment event data"
      - name: FEATURE_USAGE
        description: "Raw feature usage tracking data"
      - name: LICENSES
        description: "Raw license management data"
      - name: MEETINGS
        description: "Raw meeting data"
      - name: PARTICIPANTS
        description: "Raw participant data"
      - name: SUPPORT_TICKETS
        description: "Raw support ticket data"
      - name: USERS
        description: "Raw user data"
      - name: WEBINARS
        description: "Raw webinar data"

models:
  - name: bz_audit_log
    description: "Bronze layer audit table for tracking data processing activities"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for each audit record"
      - name: source_table
        description: "Name of the source table being processed"
      - name: load_timestamp
        description: "Timestamp when the processing started"
      - name: processed_by
        description: "System or process that performed the transformation"
      - name: processing_time
        description: "Time taken to process the data in seconds"
      - name: status
        description: "Status of the processing (STARTED, COMPLETED, FAILED)"
  
  - name: bz_billing_events
    description: "Bronze layer table containing cleaned billing and payment event data"
  
  - name: bz_feature_usage
    description: "Bronze layer table tracking usage of various Zoom features during meetings"
  
  - name: bz_licenses
    description: "Bronze layer table managing license assignments and validity periods"
  
  - name: bz_meetings
    description: "Bronze layer table containing core meeting information and duration data"
  
  - name: bz_participants
    description: "Bronze layer table tracking participant join/leave times for meetings"
  
  - name: bz_support_tickets
    description: "Bronze layer table containing customer support ticket information"
  
  - name: bz_users
    description: "Bronze layer table containing user account and profile information"
  
  - name: bz_webinars
    description: "Bronze layer table containing webinar-specific data including registrant counts"
