version: 2

sources:
  - name: raw_layer
    description: "Raw data layer containing unprocessed data from various source systems"
    database: DB_POC_ZOOM
    schema: RAW
    tables:
      - name: users
        description: "Raw user profile and subscription information"
        
      - name: meetings
        description: "Raw meeting information and session details"
        
      - name: participants
        description: "Raw meeting participants and their session details"
        
      - name: feature_usage
        description: "Raw usage of platform features during meetings"
        
      - name: support_tickets
        description: "Raw customer support requests and resolution tracking"
        
      - name: billing_events
        description: "Raw financial transactions and billing activities"
        
      - name: licenses
        description: "Raw license assignments and entitlements"

models:
  - name: bz_data_audit
    description: "Audit table for comprehensive tracking of all Bronze layer data operations"
        
  - name: bz_users
    description: "Bronze layer table storing cleaned and validated user profile information"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
        
  - name: bz_meetings
    description: "Bronze layer table storing cleaned and validated meeting information"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
        
  - name: bz_participants
    description: "Bronze layer table tracking cleaned and validated meeting participants"
    columns:
      - name: participant_id
        description: "Unique identifier for each meeting participant"
        tests:
          - not_null
          - unique
        
  - name: bz_feature_usage
    description: "Bronze layer table recording cleaned and validated platform feature usage"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - not_null
          - unique
        
  - name: bz_support_tickets
    description: "Bronze layer table managing cleaned and validated customer support requests"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        tests:
          - not_null
          - unique
        
  - name: bz_billing_events
    description: "Bronze layer table tracking cleaned and validated financial transactions"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique
        
  - name: bz_licenses
    description: "Bronze layer table managing cleaned and validated license assignments"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        tests:
          - not_null
          - unique
