version: 2

sources:
- name: raw_data
description: "Raw data from Zoom platform"
tables:
- name: users
description: "Raw users data from Zoom platform"
columns:
- name: user_id
description: "Unique identifier for user"
- name: user_name
description: "Name of the user"
- name: email
description: "Email address of the user"
- name: company
description: "Company name"
- name: plan_type
description: "Zoom plan type"
- name: load_timestamp
description: "Timestamp when data was loaded"
- name: update_timestamp
description: "Timestamp when data was updated"
- name: source_system
description: "Source system identifier"

- name: meetings
description: "Raw meetings data from Zoom platform"
columns:
- name: meeting_id
description: "Unique identifier for meeting"
- name: host_id
description: "Host user identifier"
- name: meeting_topic
description: "Topic of the meeting"
- name: start_time
description: "Meeting start time"
- name: end_time
description: "Meeting end time"
- name: duration_minutes
description: "Meeting duration in minutes"
- name: load_timestamp
description: "Timestamp when data was loaded"
- name: update_timestamp
description: "Timestamp when data was updated"
- name: source_system
description: "Source system identifier"

- name: participants
description: "Raw participants data from Zoom platform"
columns:
- name: participant_id
description: "Unique identifier for participant"
- name: meeting_id
description: "Meeting identifier"
- name: user_id
description: "User identifier"
- name: join_time
description: "Time when participant joined"
- name: leave_time
description: "Time when participant left"
- name: load_timestamp
description: "Timestamp when data was loaded"
- name: update_timestamp
description: "Timestamp when data was updated"
- name: source_system
description: "Source system identifier"

- name: feature_usage
description: "Raw feature usage data from Zoom platform"
columns:
- name: usage_id
description: "Unique identifier for usage record"
- name: meeting_id
description: "Meeting identifier"
- name: feature_name
description: "Name of the feature used"
- name: usage_count
description: "Number of times feature was used"
- name: usage_date
description: "Date of feature usage"
- name: load_timestamp
description: "Timestamp when data was loaded"
- name: update_timestamp
description: "Timestamp when data was updated"
- name: source_system
description: "Source system identifier"

- name: webinars
description: "Raw webinars data from Zoom platform"
columns:
- name: webinar_id
description: "Unique identifier for webinar"
- name: host_id
description: "Host user identifier"
- name: webinar_topic
description: "Topic of the webinar"
- name: start_time
description: "Webinar start time"
- name: end_time
description: "Webinar end time"
- name: registrants
description: "Number of registrants"
- name: load_timestamp
description: "Timestamp when data was loaded"
- name: update_timestamp
description: "Timestamp when data was updated"
- name: source_system
description: "Source system identifier"

- name: support_tickets
description: "Raw support tickets data from Zoom platform"
columns:
- name: ticket_id
description: "Unique identifier for support ticket"
- name: user_id
description: "User identifier"
- name: ticket_type
description: "Type of support ticket"
- name: resolution_status
description: "Status of ticket resolution"
- name: open_date
description: "Date when ticket was opened"
- name: load_timestamp
description: "Timestamp when data was loaded"
- name: update_timestamp
description: "Timestamp when data was updated"
- name: source_system
description: "Source system identifier"

- name: licenses
description: "Raw licenses data from Zoom platform"
columns:
- name: license_id
description: "Unique identifier for license"
- name: license_type
description: "Type of license"
- name: assigned_to_user_id
description: "User ID to whom license is assigned"
- name: start_date
description: "License start date"
- name: end_date
description: "License end date"
- name: load_timestamp
description: "Timestamp when data was loaded"
- name: update_timestamp
description: "Timestamp when data was updated"
- name: source_system
description: "Source system identifier"

- name: billing_events
description: "Raw billing events data from Zoom platform"
columns:
- name: event_id
description: "Unique identifier for billing event"
- name: user_id
description: "User identifier"
- name: event_type
description: "Type of billing event"
- name: amount
description: "Billing amount"
- name: event_date
description: "Date of billing event"
- name: load_timestamp
description: "Timestamp when data was loaded"
- name: update_timestamp
description: "Timestamp when data was updated"
- name: source_system
description: "Source system identifier"

models:
- name: bz_audit_log
description: "Audit log table for tracking bronze layer processing"
columns:
- name: record_id
description: "Auto-incrementing record identifier"
data_type: number
- name: source_table
description: "Name of the source table being processed"
data_type: varchar(255)
- name: load_timestamp
description: "Timestamp when processing started"
data_type: timestamp_ntz
- name: processed_by
description: "System or user that processed the data"
data_type: string
- name: processing_time
description: "Time taken to process in seconds"
data_type: number
- name: status
description: "Processing status (STARTED, COMPLETED, FAILED)"
data_type: string

- name: bz_users
description: "Bronze layer users table with cleaned and validated data"
columns:
- name: user_id
description: "Unique identifier for user"
data_type: string
- name: user_name
description: "Name of the user"
data_type: string
- name: email
description: "Email address of the user"
data_type: string
- name: company
description: "Company name"
data_type: string
- name: plan_type
description: "Zoom plan type"
data_type: string
- name: load_timestamp
description: "Timestamp when data was loaded into bronze"
data_type: timestamp_ntz
- name: update_timestamp
description: "Timestamp when data was last updated"
data_type: timestamp_ntz
- name: source_system
description: "Source system identifier"
data_type: string

- name: bz_meetings
description: "Bronze layer meetings table with cleaned and validated data"
columns:
- name: meeting_id
description: "Unique identifier for meeting"
data_type: string
- name: host_id
description: "Host user identifier"
data_type: string
- name: meeting_topic
description: "Topic of the meeting"
data_type: string
- name: start_time
description: "Meeting start time"
data_type: timestamp_ntz
- name: end_time
description: "Meeting end time"
data_type: timestamp_ntz
- name: duration_minutes
description: "Meeting duration in minutes"
data_type: number
- name: load_timestamp
description: "Timestamp when data was loaded into bronze"
data_type: timestamp_ntz
- name: update_timestamp
description: "Timestamp when data was last updated"
data_type: timestamp_ntz
- name: source_system
description: "Source system identifier"
data_type: string

- name: bz_participants
description: "Bronze layer participants table with cleaned and validated data"
columns:
- name: participant_id
description: "Unique identifier for participant"
data_type: string
- name: meeting_id
description: "Meeting identifier"
data_type: string
- name: user_id
description: "User identifier"
data_type: string
- name: join_time
description: "Time when participant joined"
data_type: timestamp_ntz
- name: leave_time
description: "Time when participant left"
data_type: timestamp_ntz
- name: load_timestamp
description: "Timestamp when data was loaded into bronze"
data_type: timestamp_ntz
- name: update_timestamp
description: "Timestamp when data was last updated"
data_type: timestamp_ntz
- name: source_system
description: "Source system identifier"
data_type: string

- name: bz_feature_usage
description: "Bronze layer feature usage table with cleaned and validated data"
columns:
- name: usage_id
description: "Unique identifier for usage record"
data_type: string
- name: meeting_id
description: "Meeting identifier"
data_type: string
- name: feature_name
description: "Name of the feature used"
data_type: string
- name: usage_count
description: "Number of times feature was used"
data_type: number
- name: usage_date
description: "Date of feature usage"
data_type: date
- name: load_timestamp
description: "Timestamp when data was loaded into bronze"
data_type: timestamp_ntz
- name: update_timestamp
description: "Timestamp when data was last updated"
data_type: timestamp_ntz
- name: source_system
description: "Source system identifier"
data_type: string

- name: bz_webinars
description: "Bronze layer webinars table with cleaned and validated data"
columns:
- name: webinar_id
description: "Unique identifier for webinar"
data_type: string
- name: host_id
description: "Host user identifier"
data_type: string
- name: webinar_topic
description: "Topic of the webinar"
data_type: string
- name: start_time
description: "Webinar start time"
data_type: timestamp_ntz
- name: end_time
description: "Webinar end time"
data_type: timestamp_ntz
- name: registrants
description: "Number of registrants"
data_type: number
- name: load_timestamp
description: "Timestamp when data was loaded into bronze"
data_type: timestamp_ntz
- name: update_timestamp
description: "Timestamp when data was last updated"
data_type: timestamp_ntz
- name: source_system
description: "Source system identifier"
data_type: string

- name: bz_support_tickets
description: "Bronze layer support tickets table with cleaned and validated data"
columns:
- name: ticket_id
description: "Unique identifier for support ticket"
data_type: string
- name: user_id
description: "User identifier"
data_type: string
- name: ticket_type
description: "Type of support ticket"
data_type: string
- name: resolution_status
description: "Status of ticket resolution"
data_type: string
- name: open_date
description: "Date when ticket was opened"
data_type: date
- name: load_timestamp
description: "Timestamp when data was loaded into bronze"
data_type: timestamp_ntz
- name: update_timestamp
description: "Timestamp when data was last updated"
data_type: timestamp_ntz
- name: source_system
description: "Source system identifier"
data_type: string

- name: bz_licenses
description: "Bronze layer licenses table with cleaned and validated data"
columns:
- name: license_id
description: "Unique identifier for license"
data_type: string
- name: license_type
description: "Type of license"
data_type: string
- name: assigned_to_user_id
description: "User ID to whom license is assigned"
data_type: string
- name: start_date
description: "License start date"
data_type: date
- name: end_date
description: "License end date"
data_type: date
- name: load_timestamp
description: "Timestamp when data was loaded into bronze"
data_type: timestamp_ntz
- name: update_timestamp
description: "Timestamp when data was last updated"
data_type: timestamp_ntz
- name: source_system
description: "Source system identifier"
data_type: string

- name: bz_billing_events
description: "Bronze layer billing events table with cleaned and validated data"
columns:
- name: event_id
description: "Unique identifier for billing event"
data_type: string
- name: user_id
description: "User identifier"
data_type: string
- name: event_type
description: "Type of billing event"
data_type: string
- name: amount
description: "Billing amount"
data_type: number
- name: event_date
description: "Date of billing event"
data_type: date
- name: load_timestamp
description: "Timestamp when data was loaded into bronze"
data_type: timestamp_ntz
- name: update_timestamp
description: "Timestamp when data was last updated"
data_type: timestamp_ntz
- name: source_system
description: "Source system identifier"
data_type: string
