version: 2

sources:
  - name: raw_zoom
    description: "Raw data source from Zoom platform"
    tables:
      - name: BILLING_EVENTS
        description: "Raw billing events data"
        columns:
          - name: EVENT_ID
            description: "Unique identifier for each billing event"
          - name: USER_ID
            description: "Reference to the user associated with the billing event"
          - name: EVENT_TYPE
            description: "Type of billing event"
          - name: AMOUNT
            description: "Monetary amount associated with the billing event"
          - name: EVENT_DATE
            description: "Date when the billing event occurred"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when the record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when the record was last updated"
          - name: SOURCE_SYSTEM
            description: "System from which the data originated"
      
      - name: FEATURE_USAGE
        description: "Raw feature usage data"
        columns:
          - name: USAGE_ID
            description: "Unique identifier for each feature usage record"
          - name: MEETING_ID
            description: "Reference to the meeting where the feature was used"
          - name: FEATURE_NAME
            description: "Name of the feature that was used"
          - name: USAGE_COUNT
            description: "Number of times the feature was used"
          - name: USAGE_DATE
            description: "Date when the feature was used"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when the record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when the record was last updated"
          - name: SOURCE_SYSTEM
            description: "System from which the data originated"
      
      - name: LICENSES
        description: "Raw licenses data"
        columns:
          - name: LICENSE_ID
            description: "Unique identifier for each license"
          - name: LICENSE_TYPE
            description: "Type of license"
          - name: ASSIGNED_TO_USER_ID
            description: "User ID to whom the license is assigned"
          - name: START_DATE
            description: "Date when the license becomes active"
          - name: END_DATE
            description: "Date when the license expires"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when the record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when the record was last updated"
          - name: SOURCE_SYSTEM
            description: "System from which the data originated"
      
      - name: MEETINGS
        description: "Raw meetings data"
        columns:
          - name: MEETING_ID
            description: "Unique identifier for each meeting"
          - name: HOST_ID
            description: "User ID of the meeting host"
          - name: MEETING_TOPIC
            description: "Topic or title of the meeting"
          - name: START_TIME
            description: "Timestamp when the meeting started"
          - name: END_TIME
            description: "Timestamp when the meeting ended"
          - name: DURATION_MINUTES
            description: "Duration of the meeting in minutes"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when the record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when the record was last updated"
          - name: SOURCE_SYSTEM
            description: "System from which the data originated"
      
      - name: PARTICIPANTS
        description: "Raw participants data"
        columns:
          - name: PARTICIPANT_ID
            description: "Unique identifier for each participant record"
          - name: MEETING_ID
            description: "Reference to the meeting the participant joined"
          - name: USER_ID
            description: "User ID of the participant"
          - name: JOIN_TIME
            description: "Timestamp when the participant joined the meeting"
          - name: LEAVE_TIME
            description: "Timestamp when the participant left the meeting"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when the record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when the record was last updated"
          - name: SOURCE_SYSTEM
            description: "System from which the data originated"
      
      - name: SUPPORT_TICKETS
        description: "Raw support tickets data"
        columns:
          - name: TICKET_ID
            description: "Unique identifier for each support ticket"
          - name: USER_ID
            description: "User ID who created the support ticket"
          - name: TICKET_TYPE
            description: "Type or category of the support ticket"
          - name: RESOLUTION_STATUS
            description: "Current status of the ticket resolution"
          - name: OPEN_DATE
            description: "Date when the support ticket was opened"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when the record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when the record was last updated"
          - name: SOURCE_SYSTEM
            description: "System from which the data originated"
      
      - name: USERS
        description: "Raw users data"
        columns:
          - name: USER_ID
            description: "Unique identifier for each user account"
          - name: USER_NAME
            description: "Display name of the user"
          - name: EMAIL
            description: "Email address of the user"
          - name: COMPANY
            description: "Company or organization the user belongs to"
          - name: PLAN_TYPE
            description: "Type of subscription plan the user has"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when the record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when the record was last updated"
          - name: SOURCE_SYSTEM
            description: "System from which the data originated"
      
      - name: WEBINARS
        description: "Raw webinars data"
        columns:
          - name: WEBINAR_ID
            description: "Unique identifier for each webinar"
          - name: HOST_ID
            description: "User ID of the webinar host"
          - name: WEBINAR_TOPIC
            description: "Topic or title of the webinar"
          - name: START_TIME
            description: "Timestamp when the webinar started"
          - name: END_TIME
            description: "Timestamp when the webinar ended"
          - name: REGISTRANTS
            description: "Number of users registered for the webinar"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when the record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when the record was last updated"
          - name: SOURCE_SYSTEM
            description: "System from which the data originated"

models:
  - name: bz_audit_log
    description: "Bronze layer audit table for tracking data processing activities"
    columns:
      - name: record_id
        description: "Auto-incrementing record identifier"
        tests:
          - not_null
      - name: source_table
        description: "Name of the source table being processed"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the processing started"
        tests:
          - not_null
      - name: processed_by
        description: "User or system that processed the data"
        tests:
          - not_null
      - name: processing_time
        description: "Time taken to process the data in seconds"
      - name: status
        description: "Status of the processing (STARTED, COMPLETED, FAILED)"
        tests:
          - not_null
          - accepted_values:
              values: ['STARTED', 'COMPLETED', 'FAILED', 'INITIALIZED']
  
  - name: bz_billing_events
    description: "Bronze layer table containing billing and payment event data"
    columns:
      - name: user_id
        description: "Reference to the user associated with the billing event"
        tests:
          - not_null
      - name: event_type
        description: "Type of billing event"
        tests:
          - not_null
      - name: amount
        description: "Monetary amount associated with the billing event"
        tests:
          - not_null
      - name: event_date
        description: "Date when the billing event occurred"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_feature_usage
    description: "Bronze layer table tracking usage of various Zoom features"
    columns:
      - name: meeting_id
        description: "Reference to the meeting where the feature was used"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature that was used"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times the feature was used"
        tests:
          - not_null
      - name: usage_date
        description: "Date when the feature was used"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_licenses
    description: "Bronze layer table managing license assignments and validity periods"
    columns:
      - name: license_type
        description: "Type of license"
        tests:
          - not_null
      - name: assigned_to_user_id
        description: "User ID to whom the license is assigned"
      - name: start_date
        description: "Date when the license becomes active"
        tests:
          - not_null
      - name: end_date
        description: "Date when the license expires"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_meetings
    description: "Bronze layer table containing core meeting information"
    columns:
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: meeting_topic
        description: "Topic or title of the meeting"
        tests:
          - not_null
      - name: start_time
        description: "Timestamp when the meeting started"
        tests:
          - not_null
      - name: end_time
        description: "Timestamp when the meeting ended"
        tests:
          - not_null
      - name: duration_minutes
        description: "Duration of the meeting in minutes"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_participants
    description: "Bronze layer table tracking participant join/leave times"
    columns:
      - name: meeting_id
        description: "Reference to the meeting the participant joined"
        tests:
          - not_null
      - name: user_id
        description: "User ID of the participant"
        tests:
          - not_null
      - name: join_time
        description: "Timestamp when the participant joined the meeting"
        tests:
          - not_null
      - name: leave_time
        description: "Timestamp when the participant left the meeting"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_support_tickets
    description: "Bronze layer table containing customer support ticket information"
    columns:
      - name: user_id
        description: "User ID who created the support ticket"
        tests:
          - not_null
      - name: ticket_type
        description: "Type or category of the support ticket"
        tests:
          - not_null
      - name: resolution_status
        description: "Current status of the ticket resolution"
        tests:
          - not_null
      - name: open_date
        description: "Date when the support ticket was opened"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_users
    description: "Bronze layer table containing user account and profile information"
    columns:
      - name: user_name
        description: "Display name of the user"
        tests:
          - not_null
      - name: email
        description: "Email address of the user"
        tests:
          - not_null
          - unique
      - name: company
        description: "Company or organization the user belongs to"
      - name: plan_type
        description: "Type of subscription plan the user has"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_webinars
    description: "Bronze layer table containing webinar-specific data"
    columns:
      - name: host_id
        description: "User ID of the webinar host"
        tests:
          - not_null
      - name: webinar_topic
        description: "Topic or title of the webinar"
        tests:
          - not_null
      - name: start_time
        description: "Timestamp when the webinar started"
        tests:
          - not_null
      - name: end_time
        description: "Timestamp when the webinar ended"
        tests:
          - not_null
      - name: registrants
        description: "Number of users registered for the webinar"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
