version: 2

sources:
  - name: raw_zoom
    description: "Raw data from Zoom platform source systems"
    database: DB_POC_ZOOM
    schema: RAW
    tables:
      - name: users
        description: "Raw user profile and subscription information"
        
      - name: meetings
        description: "Raw meeting information and session details"
        
      - name: participants
        description: "Raw meeting participants and session details"
        
      - name: feature_usage
        description: "Raw usage of platform features during meetings"
        
      - name: support_tickets
        description: "Raw customer support requests and resolution tracking"
        
      - name: billing_events
        description: "Raw financial transactions and billing activities"
        
      - name: licenses
        description: "Raw license assignments and entitlements"

models:
  - name: bz_data_audit
    description: "Audit table for comprehensive tracking of all Bronze layer data operations"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for each audit record"
        tests:
          - not_null
          - unique
      - name: source_table
        description: "Name of the Bronze layer table"
        tests:
          - not_null
      - name: load_timestamp
        description: "When the operation occurred"
        tests:
          - not_null
      - name: processed_by
        description: "User or process that performed the operation"
      - name: processing_time
        description: "Time taken to process the operation in seconds"
      - name: status
        description: "Status of the operation (STARTED, COMPLETED, FAILED)"
        tests:
          - not_null
          - accepted_values:
              values: ['STARTED', 'COMPLETED', 'FAILED', 'WARNING']
              
  - name: bz_users
    description: "Bronze layer table storing cleaned user profile and subscription information"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
        
  - name: bz_meetings
    description: "Bronze layer table storing cleaned meeting information and session details"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
        
  - name: bz_participants
    description: "Bronze layer table tracking cleaned meeting participants and session details"
    columns:
      - name: participant_id
        description: "Unique identifier for each meeting participant"
        tests:
          - not_null
          - unique
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
        
  - name: bz_feature_usage
    description: "Bronze layer table recording cleaned usage of platform features"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - not_null
          - unique
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
        
  - name: bz_support_tickets
    description: "Bronze layer table managing cleaned customer support requests"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        tests:
          - not_null
          - unique
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
        
  - name: bz_billing_events
    description: "Bronze layer table tracking cleaned financial transactions"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
        
  - name: bz_licenses
    description: "Bronze layer table managing cleaned license assignments"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        tests:
          - not_null
          - unique
      - name: load_timestamp
        description: "Timestamp when record was loaded into Bronze layer"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when record was last updated"
        tests:
          - not_null
