version: 2

sources:
  - name: raw
    description: "Raw data layer containing unprocessed data from source systems"
    tables:
      - name: users
        description: "Raw user profile and subscription information"
      - name: meetings
        description: "Raw meeting information and session details"
      - name: participants
        description: "Raw meeting participants and their session details"
      - name: feature_usage
        description: "Raw usage of platform features during meetings"
      - name: support_tickets
        description: "Raw customer support requests and resolution tracking"
      - name: billing_events
        description: "Raw financial transactions and billing activities"
      - name: licenses
        description: "Raw license assignments and entitlements"

models:
  - name: bz_data_audit
    description: "Comprehensive audit trail for all Bronze layer data operations"
  - name: bz_users
    description: "Bronze layer table storing cleaned and deduplicated user data"
  - name: bz_meetings
    description: "Bronze layer table storing cleaned and deduplicated meeting data"
  - name: bz_participants
    description: "Bronze layer table storing cleaned and deduplicated participant data"
  - name: bz_feature_usage
    description: "Bronze layer table storing cleaned and deduplicated feature usage data"
  - name: bz_support_tickets
    description: "Bronze layer table storing cleaned and deduplicated support ticket data"
  - name: bz_billing_events
    description: "Bronze layer table storing cleaned and deduplicated billing event data"
  - name: bz_licenses
    description: "Bronze layer table storing cleaned and deduplicated license data"
