version: 2

# Source definitions for RAW layer tables
sources:
  - name: raw
    description: "Raw data layer containing unprocessed data from various source systems"
    tables:
      - name: users
        description: "Raw user profile and subscription information"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
            tests:
              - not_null
              - unique
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user"
          - name: company
            description: "Company or organization the user belongs to"
          - name: plan_type
            description: "Type of subscription plan the user has"
          - name: load_timestamp
            description: "Timestamp when the record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"

      - name: meetings
        description: "Raw meeting information and session details"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
            tests:
              - not_null
              - unique
          - name: host_id
            description: "Reference to the user who hosted the meeting"
          - name: meeting_topic
            description: "Subject or topic of the meeting"
          - name: start_time
            description: "Timestamp when the meeting started"
          - name: end_time
            description: "Timestamp when the meeting ended"
          - name: duration_minutes
            description: "Duration of the meeting in minutes"
          - name: load_timestamp
            description: "Timestamp when the record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"

      - name: participants
        description: "Raw meeting participants and their session details"
        columns:
          - name: participant_id
            description: "Unique identifier for each meeting participant"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to the meeting"
          - name: user_id
            description: "Reference to the user who participated"
          - name: join_time
            description: "Timestamp when the participant joined the meeting"
          - name: leave_time
            description: "Timestamp when the participant left the meeting"
          - name: load_timestamp
            description: "Timestamp when the record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"

      - name: feature_usage
        description: "Raw usage of platform features during meetings"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
            tests:
              - not_null
              - unique
          - name: meeting_id
            description: "Reference to the meeting where the feature was used"
          - name: feature_name
            description: "Name of the feature that was used"
          - name: usage_count
            description: "Number of times the feature was used"
          - name: usage_date
            description: "Date when the feature usage occurred"
          - name: load_timestamp
            description: "Timestamp when the record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"

      - name: support_tickets
        description: "Raw customer support requests and resolution tracking"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "Reference to the user who created the ticket"
          - name: ticket_type
            description: "Category or type of the support ticket"
          - name: resolution_status
            description: "Current status of the ticket resolution"
          - name: open_date
            description: "Date when the ticket was opened"
          - name: load_timestamp
            description: "Timestamp when the record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"

      - name: billing_events
        description: "Raw financial transactions and billing activities"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "Reference to the user associated with the billing event"
          - name: event_type
            description: "Type of billing event (e.g., charge, refund, credit)"
          - name: amount
            description: "Monetary amount of the billing event"
          - name: event_date
            description: "Date when the billing event occurred"
          - name: load_timestamp
            description: "Timestamp when the record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"

      - name: licenses
        description: "Raw license assignments and entitlements"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
            tests:
              - not_null
              - unique
          - name: license_type
            description: "Type of license (e.g., Basic, Pro, Enterprise)"
          - name: assigned_to_user_id
            description: "Reference to the user assigned to this license"
          - name: start_date
            description: "Date when the license becomes active"
          - name: end_date
            description: "Date when the license expires"
          - name: load_timestamp
            description: "Timestamp when the record was loaded into the system"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"

# Model definitions for BRONZE layer tables
models:
  - name: bz_data_audit
    description: "Comprehensive audit trail for all Bronze layer data operations"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for each audit record"
        tests:
          - not_null
          - unique
      - name: source_table
        description: "Name of the Bronze layer table"
        tests:
          - not_null
      - name: load_timestamp
        description: "When the operation occurred"
        tests:
          - not_null
      - name: processed_by
        description: "User or process that performed the operation"
      - name: processing_time
        description: "Time taken to process the operation in seconds"
      - name: status
        description: "Status of the operation (SUCCESS, FAILED, WARNING)"
        tests:
          - not_null

  - name: bz_users
    description: "Bronze layer table storing cleaned user profile and subscription information"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Display name of the user"
        tests:
          - not_null
      - name: email
        description: "Email address of the user"
      - name: company
        description: "Company or organization the user belongs to"
      - name: plan_type
        description: "Type of subscription plan the user has"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null

  - name: bz_meetings
    description: "Bronze layer table storing cleaned meeting information and session details"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Reference to the user who hosted the meeting"
        tests:
          - not_null
      - name: meeting_topic
        description: "Subject or topic of the meeting"
      - name: start_time
        description: "Timestamp when the meeting started"
        tests:
          - not_null
      - name: end_time
        description: "Timestamp when the meeting ended"
      - name: duration_minutes
        description: "Duration of the meeting in minutes"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null

  - name: bz_participants
    description: "Bronze layer table tracking cleaned meeting participants and their session details"
    columns:
      - name: participant_id
        description: "Unique identifier for each meeting participant"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to the meeting"
        tests:
          - not_null
      - name: user_id
        description: "Reference to the user who participated"
        tests:
          - not_null
      - name: join_time
        description: "Timestamp when the participant joined the meeting"
      - name: leave_time
        description: "Timestamp when the participant left the meeting"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null

  - name: bz_feature_usage
    description: "Bronze layer table recording cleaned usage of platform features during meetings"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "Reference to the meeting where the feature was used"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature that was used"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times the feature was used"
        tests:
          - not_null
      - name: usage_date
        description: "Date when the feature usage occurred"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null

  - name: bz_support_tickets
    description: "Bronze layer table managing cleaned customer support requests and resolution tracking"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to the user who created the ticket"
        tests:
          - not_null
      - name: ticket_type
        description: "Category or type of the support ticket"
        tests:
          - not_null
      - name: resolution_status
        description: "Current status of the ticket resolution"
        tests:
          - not_null
      - name: open_date
        description: "Date when the ticket was opened"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null

  - name: bz_billing_events
    description: "Bronze layer table tracking cleaned financial transactions and billing activities"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Reference to the user associated with the billing event"
        tests:
          - not_null
      - name: event_type
        description: "Type of billing event (e.g., charge, refund, credit)"
        tests:
          - not_null
      - name: amount
        description: "Monetary amount of the billing event"
        tests:
          - not_null
      - name: event_date
        description: "Date when the billing event occurred"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null

  - name: bz_licenses
    description: "Bronze layer table managing cleaned license assignments and entitlements"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        tests:
          - not_null
          - unique
      - name: license_type
        description: "Type of license (e.g., Basic, Pro, Enterprise)"
        tests:
          - not_null
      - name: assigned_to_user_id
        description: "Reference to the user assigned to this license"
      - name: start_date
        description: "Date when the license becomes active"
        tests:
          - not_null
      - name: end_date
        description: "Date when the license expires"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into the system"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
