version: 2

sources:
  - name: raw_schema
    description: "Raw data source schema"
    tables:
      - name: customers
        description: "Raw customer data"
        columns:
          - name: customer_id
            description: "Unique customer identifier"
          - name: first_name
            description: "Customer first name"
          - name: last_name
            description: "Customer last name"
          - name: email
            description: "Customer email address"
          - name: phone
            description: "Customer phone number"
          - name: address
            description: "Customer address"
          - name: city
            description: "Customer city"
          - name: state
            description: "Customer state"
          - name: zip_code
            description: "Customer zip code"
          - name: country
            description: "Customer country"
          - name: registration_date
            description: "Customer registration date"
          - name: last_login_date
            description: "Customer last login date"
          - name: is_active
            description: "Customer active status"
          - name: customer_segment
            description: "Customer segment classification"

      - name: orders
        description: "Raw order data"
        columns:
          - name: order_id
            description: "Unique order identifier"
          - name: customer_id
            description: "Customer identifier"
          - name: order_date
            description: "Order date"
          - name: order_status
            description: "Order status"
          - name: total_amount
            description: "Total order amount"
          - name: currency
            description: "Order currency"
          - name: payment_method
            description: "Payment method used"
          - name: shipping_address
            description: "Shipping address"
          - name: billing_address
            description: "Billing address"
          - name: discount_amount
            description: "Discount applied"
          - name: tax_amount
            description: "Tax amount"
          - name: shipping_cost
            description: "Shipping cost"
          - name: order_source
            description: "Order source channel"

      - name: products
        description: "Raw product data"
        columns:
          - name: product_id
            description: "Unique product identifier"
          - name: product_name
            description: "Product name"
          - name: category
            description: "Product category"
          - name: subcategory
            description: "Product subcategory"
          - name: brand
            description: "Product brand"
          - name: price
            description: "Product price"
          - name: cost
            description: "Product cost"
          - name: description
            description: "Product description"
          - name: weight
            description: "Product weight"
          - name: dimensions
            description: "Product dimensions"
          - name: color
            description: "Product color"
          - name: size
            description: "Product size"
          - name: is_active
            description: "Product active status"
          - name: created_date
            description: "Product creation date"
          - name: last_updated_date
            description: "Product last update date"

models:
  - name: audit_log
    description: "Audit log for tracking data processing"
    columns:
      - name: record_id
        description: "Unique audit record identifier"
        tests:
          - unique
          - not_null
      - name: source_table
        description: "Source table name"
      - name: process_start_time
        description: "Process start timestamp"
      - name: process_end_time
        description: "Process end timestamp"
      - name: process_status
        description: "Process status"
      - name: error_message
        description: "Error message if any"
      - name: records_processed
        description: "Number of records processed"
      - name: created_at
        description: "Record creation timestamp"
      - name: updated_at
        description: "Record update timestamp"

  - name: customers
    description: "Bronze layer customer data"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer first name"
      - name: last_name
        description: "Customer last name"
      - name: email
        description: "Customer email address"
      - name: phone
        description: "Customer phone number"
      - name: address
        description: "Customer address"
      - name: city
        description: "Customer city"
      - name: state
        description: "Customer state"
      - name: zip_code
        description: "Customer zip code"
      - name: country
        description: "Customer country"
      - name: registration_date
        description: "Customer registration date"
      - name: last_login_date
        description: "Customer last login date"
      - name: is_active
        description: "Customer active status"
      - name: customer_segment
        description: "Customer segment classification"
      - name: created_at
        description: "Record creation timestamp"
      - name: updated_at
        description: "Record update timestamp"
      - name: process_status
        description: "Processing status"

  - name: orders
    description: "Bronze layer order data"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer identifier"
      - name: order_date
        description: "Order date"
      - name: order_status
        description: "Order status"
      - name: total_amount
        description: "Total order amount"
      - name: currency
        description: "Order currency"
      - name: payment_method
        description: "Payment method used"
      - name: shipping_address
        description: "Shipping address"
      - name: billing_address
        description: "Billing address"
      - name: discount_amount
        description: "Discount applied"
      - name: tax_amount
        description: "Tax amount"
      - name: shipping_cost
        description: "Shipping cost"
      - name: order_source
        description: "Order source channel"
      - name: created_at
        description: "Record creation timestamp"
      - name: updated_at
        description: "Record update timestamp"
      - name: process_status
        description: "Processing status"

  - name: products
    description: "Bronze layer product data"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Product name"
      - name: category
        description: "Product category"
      - name: subcategory
        description: "Product subcategory"
      - name: brand
        description: "Product brand"
      - name: price
        description: "Product price"
      - name: cost
        description: "Product cost"
      - name: description
        description: "Product description"
      - name: weight
        description: "Product weight"
      - name: dimensions
        description: "Product dimensions"
      - name: color
        description: "Product color"
      - name: size
        description: "Product size"
      - name: is_active
        description: "Product active status"
      - name: created_date
        description: "Product creation date"
      - name: last_updated_date
        description: "Product last update date"
      - name: created_at
        description: "Record creation timestamp"
      - name: updated_at
        description: "Record update timestamp"
      - name: process_status
        description: "Processing status"
