version: 2

sources:
  - name: raw_zoom
    description: "Raw data source for Zoom platform analytics"
    database: DB_POC_ZOOM
    schema: RAW
    tables:
      - name: billing_events
        description: "Raw billing and payment event data"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
          - name: user_id
            description: "Reference to the user associated with the billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Monetary amount associated with the billing event"
          - name: event_date
            description: "Date when the billing event occurred"
          - name: load_timestamp
            description: "Timestamp when the record was loaded"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"
      
      - name: feature_usage
        description: "Raw feature usage tracking data"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
          - name: meeting_id
            description: "Reference to the meeting where the feature was used"
          - name: feature_name
            description: "Name of the feature that was used"
          - name: usage_count
            description: "Number of times the feature was used"
          - name: usage_date
            description: "Date when the feature was used"
          - name: load_timestamp
            description: "Timestamp when the record was loaded"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"
      
      - name: licenses
        description: "Raw license management data"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "User ID to whom the license is assigned"
          - name: start_date
            description: "Date when the license becomes active"
          - name: end_date
            description: "Date when the license expires"
          - name: load_timestamp
            description: "Timestamp when the record was loaded"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"
      
      - name: meetings
        description: "Raw meeting information data"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
          - name: host_id
            description: "User ID of the meeting host"
          - name: meeting_topic
            description: "Topic or title of the meeting"
          - name: start_time
            description: "Timestamp when the meeting started"
          - name: end_time
            description: "Timestamp when the meeting ended"
          - name: duration_minutes
            description: "Duration of the meeting in minutes"
          - name: load_timestamp
            description: "Timestamp when the record was loaded"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"
      
      - name: participants
        description: "Raw meeting participant data"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant record"
          - name: meeting_id
            description: "Reference to the meeting the participant joined"
          - name: user_id
            description: "User ID of the participant"
          - name: join_time
            description: "Timestamp when the participant joined the meeting"
          - name: leave_time
            description: "Timestamp when the participant left the meeting"
          - name: load_timestamp
            description: "Timestamp when the record was loaded"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"
      
      - name: support_tickets
        description: "Raw support ticket data"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
          - name: user_id
            description: "User ID who created the support ticket"
          - name: ticket_type
            description: "Type or category of the support ticket"
          - name: resolution_status
            description: "Current status of the ticket resolution"
          - name: open_date
            description: "Date when the support ticket was opened"
          - name: load_timestamp
            description: "Timestamp when the record was loaded"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"
      
      - name: users
        description: "Raw user account data"
        columns:
          - name: user_id
            description: "Unique identifier for each user account"
          - name: user_name
            description: "Display name of the user"
          - name: email
            description: "Email address of the user"
          - name: company
            description: "Company or organization the user belongs to"
          - name: plan_type
            description: "Type of subscription plan the user has"
          - name: load_timestamp
            description: "Timestamp when the record was loaded"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"
      
      - name: webinars
        description: "Raw webinar data"
        columns:
          - name: webinar_id
            description: "Unique identifier for each webinar"
          - name: host_id
            description: "User ID of the webinar host"
          - name: webinar_topic
            description: "Topic or title of the webinar"
          - name: start_time
            description: "Timestamp when the webinar started"
          - name: end_time
            description: "Timestamp when the webinar ended"
          - name: registrants
            description: "Number of users registered for the webinar"
          - name: load_timestamp
            description: "Timestamp when the record was loaded"
          - name: update_timestamp
            description: "Timestamp when the record was last updated"
          - name: source_system
            description: "System from which the data originated"

models:
  - name: bz_audit_log
    description: "Bronze layer audit log for tracking data processing activities"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for audit records"
        tests:
          - not_null
      - name: source_table
        description: "Name of the source table being processed"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when processing started"
        tests:
          - not_null
      - name: processed_by
        description: "System or user that processed the data"
        tests:
          - not_null
      - name: processing_time
        description: "Time taken to process the data in seconds"
      - name: status
        description: "Status of the processing (STARTED, COMPLETED, FAILED)"
        tests:
          - not_null
          - accepted_values:
              values: ['STARTED', 'COMPLETED', 'FAILED', 'INITIALIZED']
  
  - name: bz_billing_events
    description: "Bronze layer billing events data"
    columns:
      - name: user_id
        description: "Reference to the user associated with the billing event"
        tests:
          - not_null
      - name: event_type
        description: "Type of billing event"
        tests:
          - not_null
      - name: amount
        description: "Monetary amount associated with the billing event"
        tests:
          - not_null
      - name: event_date
        description: "Date when the billing event occurred"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_feature_usage
    description: "Bronze layer feature usage data"
    columns:
      - name: meeting_id
        description: "Reference to the meeting where the feature was used"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature that was used"
        tests:
          - not_null
      - name: usage_count
        description: "Number of times the feature was used"
        tests:
          - not_null
      - name: usage_date
        description: "Date when the feature was used"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_licenses
    description: "Bronze layer license data"
    columns:
      - name: license_type
        description: "Type of license"
        tests:
          - not_null
      - name: assigned_to_user_id
        description: "User ID to whom the license is assigned"
      - name: start_date
        description: "Date when the license becomes active"
        tests:
          - not_null
      - name: end_date
        description: "Date when the license expires"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_meetings
    description: "Bronze layer meeting data"
    columns:
      - name: host_id
        description: "User ID of the meeting host"
        tests:
          - not_null
      - name: meeting_topic
        description: "Topic or title of the meeting"
        tests:
          - not_null
      - name: start_time
        description: "Timestamp when the meeting started"
        tests:
          - not_null
      - name: end_time
        description: "Timestamp when the meeting ended"
        tests:
          - not_null
      - name: duration_minutes
        description: "Duration of the meeting in minutes"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_participants
    description: "Bronze layer participant data"
    columns:
      - name: meeting_id
        description: "Reference to the meeting the participant joined"
        tests:
          - not_null
      - name: user_id
        description: "User ID of the participant"
        tests:
          - not_null
      - name: join_time
        description: "Timestamp when the participant joined the meeting"
        tests:
          - not_null
      - name: leave_time
        description: "Timestamp when the participant left the meeting"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_support_tickets
    description: "Bronze layer support ticket data"
    columns:
      - name: user_id
        description: "User ID who created the support ticket"
        tests:
          - not_null
      - name: ticket_type
        description: "Type or category of the support ticket"
        tests:
          - not_null
      - name: resolution_status
        description: "Current status of the ticket resolution"
        tests:
          - not_null
      - name: open_date
        description: "Date when the support ticket was opened"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_users
    description: "Bronze layer user data"
    columns:
      - name: user_name
        description: "Display name of the user"
        tests:
          - not_null
      - name: email
        description: "Email address of the user"
        tests:
          - not_null
          - unique
      - name: company
        description: "Company or organization the user belongs to"
      - name: plan_type
        description: "Type of subscription plan the user has"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
  
  - name: bz_webinars
    description: "Bronze layer webinar data"
    columns:
      - name: host_id
        description: "User ID of the webinar host"
        tests:
          - not_null
      - name: webinar_topic
        description: "Topic or title of the webinar"
        tests:
          - not_null
      - name: start_time
        description: "Timestamp when the webinar started"
        tests:
          - not_null
      - name: end_time
        description: "Timestamp when the webinar ended"
        tests:
          - not_null
      - name: registrants
        description: "Number of users registered for the webinar"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
        tests:
          - not_null
      - name: source_system
        description: "System from which the data originated"
        tests:
          - not_null
