version: 2

sources:
  - name: raw
    description: "Raw data layer containing unprocessed data from source systems"
    tables:
      - name: users
        description: "Raw user profile and subscription information"
      - name: meetings
        description: "Raw meeting information and session details"
      - name: participants
        description: "Raw meeting participants and their session details"
      - name: feature_usage
        description: "Raw usage of platform features during meetings"
      - name: support_tickets
        description: "Raw customer support requests and resolution tracking"
      - name: billing_events
        description: "Raw financial transactions and billing activities"
      - name: licenses
        description: "Raw license assignments and entitlements"

models:
  - name: bz_data_audit
    description: "Comprehensive audit trail for all Bronze layer data operations"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for each audit record"
      - name: source_table
        description: "Name of the Bronze layer table"
      - name: load_timestamp
        description: "When the operation occurred"
      - name: processed_by
        description: "User or process that performed the operation"
      - name: processing_time
        description: "Time taken to process the operation in seconds"
      - name: status
        description: "Status of the operation (SUCCESS, FAILED, WARNING)"

  - name: bz_users
    description: "Bronze layer table storing user profile and subscription information"
    columns:
      - name: user_id
        description: "Unique identifier for each user account"
        tests:
          - not_null
          - unique

  - name: bz_meetings
    description: "Bronze layer table storing meeting information and session details"
    columns:
      - name: meeting_id
        description: "Unique identifier for each meeting"
        tests:
          - not_null
          - unique

  - name: bz_participants
    description: "Bronze layer table tracking meeting participants and their session details"
    columns:
      - name: participant_id
        description: "Unique identifier for each meeting participant"
        tests:
          - not_null
          - unique

  - name: bz_feature_usage
    description: "Bronze layer table recording usage of platform features during meetings"
    columns:
      - name: usage_id
        description: "Unique identifier for each feature usage record"
        tests:
          - not_null
          - unique

  - name: bz_support_tickets
    description: "Bronze layer table managing customer support requests and resolution tracking"
    columns:
      - name: ticket_id
        description: "Unique identifier for each support ticket"
        tests:
          - not_null
          - unique

  - name: bz_billing_events
    description: "Bronze layer table tracking financial transactions and billing activities"
    columns:
      - name: event_id
        description: "Unique identifier for each billing event"
        tests:
          - not_null
          - unique

  - name: bz_licenses
    description: "Bronze layer table managing license assignments and entitlements"
    columns:
      - name: license_id
        description: "Unique identifier for each license"
        tests:
          - not_null
          - unique
