{{
  config(
    materialized='table',
    cluster_by=['LICENSE_KEY'],
    tags=['dimension', 'gold'],
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (AUDIT_LOG_ID, PROCESS_NAME, EXECUTION_START_TIMESTAMP, EXECUTION_STATUS, SOURCE_TABLE_NAME, TARGET_TABLE_NAME, LOAD_DATE, SOURCE_SYSTEM) SELECT '{{ invocation_id }}', 'DIM_LICENSE_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_LICENSES', 'GO_DIM_LICENSE', CURRENT_DATE(), 'DBT_GOLD_PIPELINE' WHERE '{{ this.name }}' != 'go_audit_log'",
    post_hook="UPDATE {{ ref('go_audit_log') }} SET EXECUTION_END_TIMESTAMP = CURRENT_TIMESTAMP(), EXECUTION_STATUS = 'SUCCESS', RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}), EXECUTION_DURATION_SECONDS = DATEDIFF('second', EXECUTION_START_TIMESTAMP, CURRENT_TIMESTAMP()) WHERE AUDIT_LOG_ID = '{{ invocation_id }}' AND '{{ this.name }}' != 'go_audit_log'"
  )
}}

-- License Dimension Transformation
WITH license_data AS (
    SELECT DISTINCT
        {{ dbt_utils.generate_surrogate_key(['LICENSE_TYPE']) }} AS LICENSE_KEY,
        ROW_NUMBER() OVER (ORDER BY LICENSE_TYPE) AS LICENSE_ID,
        INITCAP(TRIM(COALESCE(LICENSE_TYPE, 'Unknown'))) AS LICENSE_TYPE,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%BASIC%' THEN 'Standard'
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%PRO%' THEN 'Professional'
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN 'Enterprise'
            ELSE 'Other'
        END AS LICENSE_CATEGORY,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%BASIC%' THEN 'Tier 1'
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%PRO%' THEN 'Tier 2'
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN 'Tier 3'
            ELSE 'Tier 0'
        END AS LICENSE_TIER,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%BASIC%' THEN 100
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%PRO%' THEN 500
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN 1000
            ELSE 50
        END AS MAX_PARTICIPANTS,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%BASIC%' THEN 5
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%PRO%' THEN 100
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN 1000
            ELSE 1
        END AS STORAGE_LIMIT_GB,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%BASIC%' THEN 40
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%PRO%' THEN 100
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN 500
            ELSE 0
        END AS RECORDING_LIMIT_HOURS,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS ADMIN_FEATURES_INCLUDED,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%PRO%' OR UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS API_ACCESS_INCLUDED,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS SSO_SUPPORT_INCLUDED,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%BASIC%' THEN 14.99
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%PRO%' THEN 19.99
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN 39.99
            ELSE 0.00
        END AS MONTHLY_PRICE,
        CASE 
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%BASIC%' THEN 149.90
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%PRO%' THEN 199.90
            WHEN UPPER(COALESCE(LICENSE_TYPE, '')) LIKE '%ENTERPRISE%' THEN 399.90
            ELSE 0.00
        END AS ANNUAL_PRICE,
        'Standard license benefits for ' || COALESCE(LICENSE_TYPE, 'Unknown') AS LICENSE_BENEFITS,
        COALESCE(START_DATE, CURRENT_DATE()) AS EFFECTIVE_START_DATE,
        COALESCE(END_DATE, '9999-12-31'::DATE) AS EFFECTIVE_END_DATE,
        TRUE AS IS_CURRENT_RECORD,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        COALESCE(SOURCE_SYSTEM, 'SILVER_LAYER') AS SOURCE_SYSTEM
    FROM {{ source('silver', 'si_licenses') }}
    WHERE COALESCE(VALIDATION_STATUS, '') = 'PASSED'
      AND LICENSE_TYPE IS NOT NULL
      AND TRIM(LICENSE_TYPE) != ''
)

SELECT * FROM license_data
