{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'PLAN_CODE_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_CODE_PLAN_TYPES_GENERATE', CURRENT_TIMESTAMP(), 'BUSINESS_RULES', 'GO_CODE_PLAN_TYPES', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, RECORDS_PROCESSED, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'PLAN_CODE_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_CODE_PLAN_TYPES_GENERATE', CURRENT_TIMESTAMP(), 'BUSINESS_RULES', 'GO_CODE_PLAN_TYPES', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, (SELECT COUNT(*) FROM {{ this }}), 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
) }}

-- Gold Layer Plan Types Code Table
-- Business-defined reference data for plan types with costs and features
-- Standardizes plan information for revenue and usage analysis

WITH plan_definitions AS (
    SELECT 'ENT' AS PLAN_CODE, 'Enterprise' AS PLAN_NAME, 'PREMIUM' AS PLAN_TIER, 'Full enterprise features with unlimited participants' AS PLAN_DESCRIPTION, 240.00 AS MONTHLY_COST, 1000 AS MAX_PARTICIPANTS, 'ALL_FEATURES' AS FEATURE_SET
    UNION ALL
    SELECT 'BUS', 'Business', 'PREMIUM', 'Business features with advanced collaboration tools', 120.00, 300, 'BUSINESS_FEATURES'
    UNION ALL
    SELECT 'PRO', 'Professional', 'STANDARD', 'Professional features for small teams', 60.00, 100, 'PRO_FEATURES'
    UNION ALL
    SELECT 'BAS', 'Basic', 'STANDARD', 'Basic meeting features', 20.00, 40, 'BASIC_FEATURES'
    UNION ALL
    SELECT 'FREE', 'Free', 'BASIC', 'Free tier with limited features', 0.00, 3, 'FREE_FEATURES'
    UNION ALL
    SELECT 'EDU', 'Education', 'STANDARD', 'Educational institution features', 30.00, 100, 'EDUCATION_FEATURES'
)

SELECT 
    PLAN_CODE::VARCHAR(50),
    PLAN_NAME::VARCHAR(16777216),
    PLAN_TIER::VARCHAR(100),
    PLAN_DESCRIPTION::VARCHAR(16777216),
    MONTHLY_COST::NUMBER(10,2),
    MAX_PARTICIPANTS::NUMBER(38,0),
    FEATURE_SET::VARCHAR(16777216),
    CURRENT_DATE()::DATE AS LOAD_DATE,
    CURRENT_DATE()::DATE AS UPDATE_DATE,
    'BUSINESS_RULES'::VARCHAR(16777216) AS SOURCE_SYSTEM
FROM plan_definitions
