{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'PLAN_CODE_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_CODE_PLAN_TYPES_GENERATE', CURRENT_TIMESTAMP(), 'BUSINESS_RULES', 'GO_CODE_PLAN_TYPES', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, RECORDS_PROCESSED, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'PLAN_CODE_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_CODE_PLAN_TYPES_GENERATE', CURRENT_TIMESTAMP(), 'BUSINESS_RULES', 'GO_CODE_PLAN_TYPES', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, (SELECT COUNT(*) FROM {{ this }}), 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
) }}

-- Gold Layer Plan Types Code Table
-- Business-defined reference data for plan types with costs and features
-- Standardizes plan information for revenue and usage analysis

WITH plan_definitions AS (
    SELECT 
        'ENT' AS PLAN_CODE, 
        'Enterprise' AS PLAN_NAME, 
        'PREMIUM' AS PLAN_TIER, 
        'Full enterprise features with unlimited participants' AS PLAN_DESCRIPTION, 
        240.00 AS MONTHLY_COST, 
        1000 AS MAX_PARTICIPANTS, 
        'ALL_FEATURES' AS FEATURE_SET
    UNION ALL
    SELECT 
        'BUS' AS PLAN_CODE, 
        'Business' AS PLAN_NAME, 
        'PREMIUM' AS PLAN_TIER, 
        'Business features with advanced collaboration tools' AS PLAN_DESCRIPTION, 
        120.00 AS MONTHLY_COST, 
        300 AS MAX_PARTICIPANTS, 
        'BUSINESS_FEATURES' AS FEATURE_SET
    UNION ALL
    SELECT 
        'PRO' AS PLAN_CODE, 
        'Professional' AS PLAN_NAME, 
        'STANDARD' AS PLAN_TIER, 
        'Professional features for small teams' AS PLAN_DESCRIPTION, 
        60.00 AS MONTHLY_COST, 
        100 AS MAX_PARTICIPANTS, 
        'PRO_FEATURES' AS FEATURE_SET
    UNION ALL
    SELECT 
        'BAS' AS PLAN_CODE, 
        'Basic' AS PLAN_NAME, 
        'STANDARD' AS PLAN_TIER, 
        'Basic meeting features' AS PLAN_DESCRIPTION, 
        20.00 AS MONTHLY_COST, 
        40 AS MAX_PARTICIPANTS, 
        'BASIC_FEATURES' AS FEATURE_SET
    UNION ALL
    SELECT 
        'FREE' AS PLAN_CODE, 
        'Free' AS PLAN_NAME, 
        'BASIC' AS PLAN_TIER, 
        'Free tier with limited features' AS PLAN_DESCRIPTION, 
        0.00 AS MONTHLY_COST, 
        3 AS MAX_PARTICIPANTS, 
        'FREE_FEATURES' AS FEATURE_SET
    UNION ALL
    SELECT 
        'EDU' AS PLAN_CODE, 
        'Education' AS PLAN_NAME, 
        'STANDARD' AS PLAN_TIER, 
        'Educational institution features' AS PLAN_DESCRIPTION, 
        30.00 AS MONTHLY_COST, 
        100 AS MAX_PARTICIPANTS, 
        'EDUCATION_FEATURES' AS FEATURE_SET
)

SELECT 
    PLAN_CODE::VARCHAR(50) AS PLAN_CODE,
    PLAN_NAME::VARCHAR(16777216) AS PLAN_NAME,
    PLAN_TIER::VARCHAR(100) AS PLAN_TIER,
    PLAN_DESCRIPTION::VARCHAR(16777216) AS PLAN_DESCRIPTION,
    MONTHLY_COST::NUMBER(10,2) AS MONTHLY_COST,
    MAX_PARTICIPANTS::NUMBER(38,0) AS MAX_PARTICIPANTS,
    FEATURE_SET::VARCHAR(16777216) AS FEATURE_SET,
    CURRENT_DATE()::DATE AS LOAD_DATE,
    CURRENT_DATE()::DATE AS UPDATE_DATE,
    'BUSINESS_RULES'::VARCHAR(16777216) AS SOURCE_SYSTEM
FROM plan_definitions
