{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'FEATURE_CODE_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_CODE_FEATURE_TYPES_TRANSFORM', CURRENT_TIMESTAMP(), 'SI_FEATURE_USAGE', 'GO_CODE_FEATURE_TYPES', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, RECORDS_PROCESSED, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'FEATURE_CODE_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_CODE_FEATURE_TYPES_TRANSFORM', CURRENT_TIMESTAMP(), 'SI_FEATURE_USAGE', 'GO_CODE_FEATURE_TYPES', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, (SELECT COUNT(*) FROM {{ this }}), 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
) }}

-- Gold Layer Feature Types Code Table
-- Standardizes feature types and categories for consistent analysis
-- Derived from feature usage patterns in Silver layer

WITH source_features AS (
    SELECT DISTINCT
        FEATURE_NAME,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_feature_usage') }}
    WHERE FEATURE_NAME IS NOT NULL
      AND TRIM(FEATURE_NAME) != ''
),

feature_standardization AS (
    SELECT 
        UPPER(REPLACE(TRIM(FEATURE_NAME), ' ', '_'))::VARCHAR(50) AS FEATURE_CODE,
        TRIM(FEATURE_NAME)::VARCHAR(16777216) AS FEATURE_NAME,
        CASE 
            WHEN LOWER(FEATURE_NAME) LIKE '%screen%share%' OR LOWER(FEATURE_NAME) LIKE '%share%screen%' THEN 'COLLABORATION'
            WHEN LOWER(FEATURE_NAME) LIKE '%record%' THEN 'RECORDING'
            WHEN LOWER(FEATURE_NAME) LIKE '%chat%' OR LOWER(FEATURE_NAME) LIKE '%message%' THEN 'COMMUNICATION'
            WHEN LOWER(FEATURE_NAME) LIKE '%breakout%' OR LOWER(FEATURE_NAME) LIKE '%room%' THEN 'ADVANCED'
            WHEN LOWER(FEATURE_NAME) LIKE '%poll%' OR LOWER(FEATURE_NAME) LIKE '%survey%' THEN 'ENGAGEMENT'
            WHEN LOWER(FEATURE_NAME) LIKE '%whiteboard%' OR LOWER(FEATURE_NAME) LIKE '%annotation%' THEN 'COLLABORATION'
            WHEN LOWER(FEATURE_NAME) LIKE '%audio%' OR LOWER(FEATURE_NAME) LIKE '%video%' THEN 'MEDIA'
            ELSE 'BASIC'
        END::VARCHAR(100) AS FEATURE_CATEGORY,
        CONCAT('Feature usage tracking for ', FEATURE_NAME)::VARCHAR(16777216) AS FEATURE_DESCRIPTION,
        CASE 
            WHEN LOWER(FEATURE_NAME) LIKE '%breakout%' 
                OR LOWER(FEATURE_NAME) LIKE '%record%' 
                OR LOWER(FEATURE_NAME) LIKE '%whiteboard%'
                OR LOWER(FEATURE_NAME) LIKE '%poll%'
            THEN TRUE 
            ELSE FALSE 
        END::BOOLEAN AS IS_PREMIUM_FEATURE,
        CASE 
            WHEN LOWER(FEATURE_NAME) LIKE '%record%' OR LOWER(FEATURE_NAME) LIKE '%share%' THEN 'HIGH'
            WHEN LOWER(FEATURE_NAME) LIKE '%chat%' OR LOWER(FEATURE_NAME) LIKE '%poll%' THEN 'MEDIUM'
            ELSE 'LOW'
        END::VARCHAR(50) AS ADOPTION_PRIORITY,
        CURRENT_DATE()::DATE AS LOAD_DATE,
        CURRENT_DATE()::DATE AS UPDATE_DATE,
        SOURCE_SYSTEM::VARCHAR(16777216) AS SOURCE_SYSTEM
    FROM source_features
)

SELECT 
    FEATURE_CODE,
    FEATURE_NAME,
    FEATURE_CATEGORY,
    FEATURE_DESCRIPTION,
    IS_PREMIUM_FEATURE,
    ADOPTION_PRIORITY,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM feature_standardization
