{{ config(materialized='table') }}

SELECT 
    MD5(USER_ID) AS USER_KEY,
    ROW_NUMBER() OVER (ORDER BY USER_ID) AS USER_DIM_ID,
    USER_ID,
    COALESCE(USER_NAME, 'Unknown') AS USER_NAME,
    CASE 
        WHEN EMAIL IS NOT NULL AND POSITION('@' IN EMAIL) > 0 
        THEN UPPER(SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1))
        ELSE 'Unknown'
    END AS EMAIL_DOMAIN,
    COALESCE(COMPANY, 'Unknown') AS COMPANY,
    COALESCE(PLAN_TYPE, 'Unknown') AS PLAN_TYPE,
    CASE 
        WHEN UPPER(PLAN_TYPE) = 'FREE' THEN 'Free'
        ELSE 'Paid'
    END AS PLAN_CATEGORY,
    COALESCE(LOAD_DATE, CURRENT_DATE()) AS REGISTRATION_DATE,
    'Active' AS USER_STATUS,
    'Unknown' AS GEOGRAPHIC_REGION,
    'Unknown' AS INDUSTRY_SECTOR,
    'All Users' AS USER_ROLE,
    CASE 
        WHEN UPPER(PLAN_TYPE) = 'FREE' THEN 'Individual'
        ELSE 'Business'
    END AS ACCOUNT_TYPE,
    'English' AS LANGUAGE_PREFERENCE,
    CURRENT_DATE() AS EFFECTIVE_START_DATE,
    DATE('9999-12-31') AS EFFECTIVE_END_DATE,
    TRUE AS IS_CURRENT_RECORD,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    COALESCE(SOURCE_SYSTEM, 'SILVER') AS SOURCE_SYSTEM
FROM {{ source('silver', 'si_users') }}
WHERE VALIDATION_STATUS = 'PASSED'
  AND USER_ID IS NOT NULL
