{{ config(materialized='table') }}

-- Feature Dimension Table
WITH distinct_features AS (
    SELECT DISTINCT 
        FEATURE_NAME,
        SOURCE_SYSTEM
    FROM SILVER.SI_FEATURE_USAGE
    WHERE FEATURE_NAME IS NOT NULL
        AND TRIM(FEATURE_NAME) != ''
        AND VALIDATION_STATUS = 'PASSED'
)

SELECT 
    ROW_NUMBER() OVER (ORDER BY FEATURE_NAME) AS FEATURE_ID,
    FEATURE_NAME,
    CASE 
        WHEN UPPER(FEATURE_NAME) LIKE '%SCREEN%' THEN 'Collaboration'
        WHEN UPPER(FEATURE_NAME) LIKE '%RECORD%' THEN 'Recording'
        WHEN UPPER(FEATURE_NAME) LIKE '%CHAT%' THEN 'Communication'
        WHEN UPPER(FEATURE_NAME) LIKE '%BREAKOUT%' THEN 'Meeting Management'
        WHEN UPPER(FEATURE_NAME) LIKE '%VIDEO%' THEN 'Media'
        WHEN UPPER(FEATURE_NAME) LIKE '%AUDIO%' THEN 'Media'
        ELSE 'Other'
    END AS FEATURE_CATEGORY,
    CASE 
        WHEN UPPER(FEATURE_NAME) IN ('CHAT', 'AUDIO', 'VIDEO') THEN 'Core'
        ELSE 'Advanced'
    END AS FEATURE_TYPE,
    CASE 
        WHEN UPPER(FEATURE_NAME) IN ('CHAT', 'AUDIO', 'VIDEO') THEN 'Low'
        WHEN UPPER(FEATURE_NAME) LIKE '%SCREEN%' THEN 'Medium'
        ELSE 'High'
    END AS FEATURE_COMPLEXITY,
    CASE 
        WHEN UPPER(FEATURE_NAME) NOT IN ('CHAT', 'AUDIO', 'VIDEO') THEN TRUE
        ELSE FALSE
    END AS IS_PREMIUM_FEATURE,
    '2020-01-01'::DATE AS FEATURE_RELEASE_DATE,
    'Active' AS FEATURE_STATUS,
    'Medium' AS USAGE_FREQUENCY_CATEGORY,
    'Platform feature for enhanced meeting experience' AS FEATURE_DESCRIPTION,
    'All Users' AS TARGET_USER_TYPE,
    'Desktop, Mobile, Web' AS PLATFORM_AVAILABILITY,
    CURRENT_DATE() AS LOAD_DATE,
    CURRENT_DATE() AS UPDATE_DATE,
    SOURCE_SYSTEM
FROM distinct_features
