{{ config(
    materialized='table'
) }}

-- License Dimension Table
-- Transforms Silver layer license data with business rules and entitlements

WITH license_base AS (
    SELECT 
        LICENSE_ID,
        LICENSE_TYPE,
        START_DATE,
        END_DATE,
        SOURCE_SYSTEM,
        VALIDATION_STATUS,
        DATA_QUALITY_SCORE
    FROM SILVER.SI_LICENSES
    WHERE VALIDATION_STATUS = 'PASSED'
        AND DATA_QUALITY_SCORE >= 80
),

license_transformations AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY LICENSE_TYPE, START_DATE) AS LICENSE_ID,
        LICENSE_TYPE,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 'Basic'
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 'Professional'
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 'Business'
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 'Enterprise'
            ELSE 'Other'
        END AS LICENSE_CATEGORY,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 'Tier 1'
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 'Tier 2'
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 'Tier 3'
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 'Tier 4'
            ELSE 'Tier 0'
        END AS LICENSE_TIER,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 100
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 500
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 1000
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 5000
            ELSE 50
        END AS MAX_PARTICIPANTS,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 5
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 100
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 1000
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 10000
            ELSE 1
        END AS STORAGE_LIMIT_GB,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 0
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 100
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 1000
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 10000
            ELSE 0
        END AS RECORDING_LIMIT_HOURS,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' OR UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS ADMIN_FEATURES_INCLUDED,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS API_ACCESS_INCLUDED,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN TRUE
            ELSE FALSE
        END AS SSO_SUPPORT_INCLUDED,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 14.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 19.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 29.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 49.99
            ELSE 0.00
        END AS MONTHLY_PRICE,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 149.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 199.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 299.99
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 499.99
            ELSE 0.00
        END AS ANNUAL_PRICE,
        12 AS LICENSE_DURATION_MONTHS,
        CASE 
            WHEN UPPER(LICENSE_TYPE) LIKE '%BASIC%' THEN 1
            WHEN UPPER(LICENSE_TYPE) LIKE '%PRO%' THEN 5
            WHEN UPPER(LICENSE_TYPE) LIKE '%BUSINESS%' THEN 10
            WHEN UPPER(LICENSE_TYPE) LIKE '%ENTERPRISE%' THEN 50
            ELSE 1
        END AS CONCURRENT_MEETINGS_LIMIT,
        START_DATE AS EFFECTIVE_START_DATE,
        COALESCE(END_DATE, '9999-12-31'::DATE) AS EFFECTIVE_END_DATE,
        CASE 
            WHEN END_DATE IS NULL OR END_DATE >= CURRENT_DATE() THEN TRUE
            ELSE FALSE
        END AS IS_CURRENT_RECORD,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        SOURCE_SYSTEM
    FROM license_base
)

SELECT * FROM license_transformations
ORDER BY LICENSE_ID
