{{ config(
    materialized='table'
) }}

-- Support Category Dimension Table
WITH support_source AS (
    SELECT DISTINCT
        TICKET_TYPE,
        PRIORITY_LEVEL,
        SOURCE_SYSTEM
    FROM DB_POC_ZOOM.SILVER.SI_SUPPORT_TICKETS
    WHERE COALESCE(DATA_QUALITY_SCORE, 1.0) >= 0.8
      AND TICKET_TYPE IS NOT NULL
      AND PRIORITY_LEVEL IS NOT NULL
),

support_transformed AS (
    SELECT 
        'DIM_SUPPORT_CAT_' || MD5(UPPER(TICKET_TYPE || PRIORITY_LEVEL)) AS DIM_SUPPORT_CATEGORY_ID,
        UPPER(REPLACE(TICKET_TYPE, ' ', '_')) AS CATEGORY_KEY,
        INITCAP(TICKET_TYPE) AS TICKET_TYPE,
        CASE 
            WHEN UPPER(TICKET_TYPE) IN ('TECHNICAL', 'BUG REPORT') THEN 'TECHNICAL_SUPPORT'
            WHEN UPPER(TICKET_TYPE) = 'BILLING' THEN 'FINANCIAL_SUPPORT'
            WHEN UPPER(TICKET_TYPE) = 'FEATURE REQUEST' THEN 'PRODUCT_ENHANCEMENT'
            ELSE 'GENERAL_SUPPORT'
        END AS CATEGORY_GROUP,
        UPPER(PRIORITY_LEVEL) AS PRIORITY_LEVEL,
        CASE 
            WHEN UPPER(PRIORITY_LEVEL) = 'CRITICAL' THEN 4
            WHEN UPPER(PRIORITY_LEVEL) = 'HIGH' THEN 24
            WHEN UPPER(PRIORITY_LEVEL) = 'MEDIUM' THEN 72
            WHEN UPPER(PRIORITY_LEVEL) = 'LOW' THEN 168
            ELSE 72
        END AS SLA_HOURS,
        CASE 
            WHEN UPPER(PRIORITY_LEVEL) = 'CRITICAL' THEN 2
            WHEN UPPER(PRIORITY_LEVEL) = 'HIGH' THEN 12
            WHEN UPPER(PRIORITY_LEVEL) = 'MEDIUM' THEN 48
            WHEN UPPER(PRIORITY_LEVEL) = 'LOW' THEN 120
            ELSE 48
        END AS ESCALATION_THRESHOLD_HOURS,
        CASE 
            WHEN UPPER(TICKET_TYPE) IN ('TECHNICAL', 'BUG REPORT') THEN TRUE 
            ELSE FALSE 
        END AS REQUIRES_TECHNICAL_EXPERTISE,
        CURRENT_DATE() AS LOAD_DATE,
        CURRENT_DATE() AS UPDATE_DATE,
        COALESCE(SOURCE_SYSTEM, 'UNKNOWN') AS SOURCE_SYSTEM
    FROM support_source
)

SELECT * FROM support_transformed
