{{ config(
    materialized='table',
    pre_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'LICENSE_DIM_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_DIM_LICENSE_TRANSFORM', CURRENT_TIMESTAMP(), 'SI_LICENSES', 'GO_DIM_LICENSE', CURRENT_TIMESTAMP(), 'STARTED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'",
    post_hook="INSERT INTO {{ ref('go_process_audit') }} (AUDIT_KEY, PIPELINE_NAME, PIPELINE_RUN_TIMESTAMP, SOURCE_TABLE, TARGET_TABLE, EXECUTION_START_TIME, EXECUTION_END_TIME, EXECUTION_DURATION_SECONDS, RECORDS_PROCESSED, EXECUTION_STATUS, PROCESSED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT 'LICENSE_DIM_' || CURRENT_TIMESTAMP()::VARCHAR, 'GO_DIM_LICENSE_TRANSFORM', CURRENT_TIMESTAMP(), 'SI_LICENSES', 'GO_DIM_LICENSE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, (SELECT COUNT(*) FROM {{ this }}), 'COMPLETED', CURRENT_USER(), CURRENT_DATE(), 'DBT_GOLD_LAYER'"
) }}

-- Gold Layer License Dimension Table (SCD Type 2)
-- Transforms Silver layer license data into analytical dimension
-- Implements Slowly Changing Dimension Type 2 for historical tracking

WITH source_licenses AS (
    SELECT 
        LICENSE_ID,
        LICENSE_TYPE,
        ASSIGNED_TO_USER_ID,
        START_DATE,
        END_DATE,
        LICENSE_STATUS,
        DAYS_TO_EXPIRY,
        LOAD_DATE,
        UPDATE_DATE,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_licenses') }}
    WHERE LICENSE_ID IS NOT NULL
      AND LICENSE_TYPE IS NOT NULL
),

license_transformations AS (
    SELECT 
        LICENSE_ID::VARCHAR(16777216) AS LICENSE_KEY,
        CASE 
            WHEN UPPER(LICENSE_TYPE) IN ('BASIC', 'PRO', 'BUSINESS', 'ENTERPRISE', 'EDUCATION') 
            THEN UPPER(LICENSE_TYPE)
            ELSE 'UNKNOWN'
        END::VARCHAR(16777216) AS LICENSE_TYPE,
        CASE 
            WHEN UPPER(LICENSE_TYPE) = 'ENTERPRISE' THEN 'TIER_1'
            WHEN UPPER(LICENSE_TYPE) = 'BUSINESS' THEN 'TIER_2'
            WHEN UPPER(LICENSE_TYPE) = 'PRO' THEN 'TIER_3'
            WHEN UPPER(LICENSE_TYPE) = 'BASIC' THEN 'TIER_4'
            ELSE 'TIER_5'
        END::VARCHAR(100) AS LICENSE_TIER,
        START_DATE::DATE AS START_DATE,
        END_DATE::DATE AS END_DATE,
        CASE 
            WHEN UPPER(LICENSE_STATUS) IN ('ACTIVE', 'EXPIRED', 'SUSPENDED', 'PENDING') 
            THEN UPPER(LICENSE_STATUS)
            ELSE 'UNKNOWN'
        END::VARCHAR(50) AS LICENSE_STATUS,
        COALESCE(DAYS_TO_EXPIRY, 0)::NUMBER(38,0) AS DAYS_TO_EXPIRY,
        CASE 
            WHEN UPPER(LICENSE_TYPE) = 'ENTERPRISE' THEN 240.00
            WHEN UPPER(LICENSE_TYPE) = 'BUSINESS' THEN 120.00
            WHEN UPPER(LICENSE_TYPE) = 'PRO' THEN 60.00
            WHEN UPPER(LICENSE_TYPE) = 'BASIC' THEN 20.00
            ELSE 0.00
        END::NUMBER(10,2) AS LICENSE_COST,
        0.00::NUMBER(5,2) AS UTILIZATION_RATE, -- To be calculated from usage data
        CURRENT_DATE()::DATE AS EFFECTIVE_START_DATE,
        '9999-12-31'::DATE AS EFFECTIVE_END_DATE,
        TRUE::BOOLEAN AS CURRENT_RECORD_FLAG,
        CURRENT_DATE()::DATE AS LOAD_DATE,
        CURRENT_DATE()::DATE AS UPDATE_DATE,
        SOURCE_SYSTEM::VARCHAR(16777216) AS SOURCE_SYSTEM
    FROM source_licenses
)

SELECT 
    LICENSE_KEY,
    LICENSE_TYPE,
    LICENSE_TIER,
    START_DATE,
    END_DATE,
    LICENSE_STATUS,
    DAYS_TO_EXPIRY,
    LICENSE_COST,
    UTILIZATION_RATE,
    EFFECTIVE_START_DATE,
    EFFECTIVE_END_DATE,
    CURRENT_RECORD_FLAG,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM license_transformations
