{{ config(
    materialized='table',
    tags=['dimension', 'gold'],
    pre_hook="INSERT INTO {{ ref('go_audit_log') }} (PROCESS_ID, PROCESS_NAME, PROCESS_TYPE, PROCESS_START_TIME, PROCESS_STATUS, SOURCE_TABLE, TARGET_TABLE, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) VALUES (UUID_STRING(), 'GO_DIM_MEETING_LOAD', 'DIMENSION_LOAD', CURRENT_TIMESTAMP(), 'RUNNING', 'SI_MEETINGS', 'GO_DIM_MEETING', 'DBT_MODEL_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_PIPELINE')",
    post_hook="INSERT INTO {{ ref('go_audit_log') }} (PROCESS_ID, PROCESS_NAME, PROCESS_TYPE, PROCESS_START_TIME, PROCESS_END_TIME, PROCESS_STATUS, SOURCE_TABLE, TARGET_TABLE, RECORDS_PROCESSED, PROCESS_TRIGGER, EXECUTED_BY, LOAD_DATE, SOURCE_SYSTEM) SELECT UUID_STRING(), 'GO_DIM_MEETING_LOAD', 'DIMENSION_LOAD', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'SUCCESS', 'SI_MEETINGS', 'GO_DIM_MEETING', (SELECT COUNT(*) FROM {{ this }}), 'DBT_MODEL_RUN', 'DBT_SYSTEM', CURRENT_DATE(), 'DBT_GOLD_PIPELINE'"
) }}

-- Meeting dimension transformation from Silver layer
WITH meeting_data AS (
    SELECT 
        MEETING_ID,
        START_TIME,
        DURATION_MINUTES,
        DATA_QUALITY_SCORE,
        SOURCE_SYSTEM
    FROM {{ source('silver', 'si_meetings') }}
    WHERE VALIDATION_STATUS = 'PASSED'
      AND MEETING_ID IS NOT NULL
),

meeting_transformed AS (
    SELECT 
        MD5(MEETING_ID) AS MEETING_KEY,
        'Standard Meeting' AS MEETING_TYPE,
        CASE 
            WHEN DURATION_MINUTES <= 15 THEN 'Quick Sync'
            WHEN DURATION_MINUTES <= 60 THEN 'Standard Meeting'
            WHEN DURATION_MINUTES <= 120 THEN 'Extended Meeting'
            ELSE 'Long Session'
        END AS MEETING_CATEGORY,
        CASE 
            WHEN DURATION_MINUTES <= 15 THEN 'Brief'
            WHEN DURATION_MINUTES <= 60 THEN 'Standard'
            WHEN DURATION_MINUTES <= 120 THEN 'Extended'
            ELSE 'Long'
        END AS DURATION_CATEGORY,
        'Unknown' AS PARTICIPANT_SIZE_CATEGORY,
        CASE 
            WHEN HOUR(START_TIME) BETWEEN 6 AND 11 THEN 'Morning'
            WHEN HOUR(START_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
            WHEN HOUR(START_TIME) BETWEEN 18 AND 21 THEN 'Evening'
            ELSE 'Night'
        END AS TIME_OF_DAY_CATEGORY,
        DAYNAME(START_TIME) AS DAY_OF_WEEK,
        CASE WHEN DAYOFWEEK(START_TIME) IN (1, 7) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
        FALSE AS IS_RECURRING, -- To be enhanced with recurring meeting logic
        CASE 
            WHEN DATA_QUALITY_SCORE >= 90 THEN 9.0
            WHEN DATA_QUALITY_SCORE >= 80 THEN 8.0
            WHEN DATA_QUALITY_SCORE >= 70 THEN 7.0
            ELSE 6.0
        END AS MEETING_QUALITY_SCORE,
        'Standard features' AS TYPICAL_FEATURES_USED,
        'Business Meeting' AS BUSINESS_PURPOSE,
        CURRENT_DATE AS LOAD_DATE,
        CURRENT_DATE AS UPDATE_DATE,
        SOURCE_SYSTEM
    FROM meeting_data
)

SELECT 
    MEETING_KEY,
    ROW_NUMBER() OVER (ORDER BY MEETING_KEY) AS MEETING_ID,
    MEETING_TYPE,
    MEETING_CATEGORY,
    DURATION_CATEGORY,
    PARTICIPANT_SIZE_CATEGORY,
    TIME_OF_DAY_CATEGORY,
    DAY_OF_WEEK,
    IS_WEEKEND,
    IS_RECURRING,
    MEETING_QUALITY_SCORE,
    TYPICAL_FEATURES_USED,
    BUSINESS_PURPOSE,
    LOAD_DATE,
    UPDATE_DATE,
    SOURCE_SYSTEM
FROM meeting_transformed
