# =====================================================
# DBT PROJECT CONFIGURATION - BRONZE LAYER (FIXED)
# =====================================================
# Purpose: Main dbt project configuration for Bronze layer
# Author: AAVA
# Created: 2024-11-11
# Version: 1.1 (Fixed Schema Permissions)
# =====================================================
# FIXED: Updated to use UTILITY schema instead of BRONZE to resolve permission issues

name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_bronze_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Variables for the project
vars:
  # Target schema - using UTILITY instead of BRONZE due to permission constraints
  target_schema: 'utility'
  # Bronze layer prefix for table naming
  bronze_prefix: 'bronze_'
  # Environment
  environment: 'dev'

# Model configurations
models:
  zoom_bronze_pipeline:
    # Global model configurations
    +materialized: table
    +schema: utility  # Force all models to use UTILITY schema
    
    # Bronze layer specific configurations
    bronze:
      +materialized: table
      +schema: utility  # Explicitly set schema to UTILITY
      +tags: ['bronze', 'raw_data']
      +pre-hook: "{{ log('Starting Bronze layer model execution', info=True) }}"
      +post-hook: "{{ log('Completed Bronze layer model execution', info=True) }}"
      
      # Performance optimizations for Snowflake
      +snowflake_warehouse: 'WH_POC_Z_DEV_XSMALL'
      +query_tag: 'dbt_bronze_pipeline'

# Test configurations
tests:
  +store_failures: true
  +schema: utility  # Store test results in UTILITY schema

# Snapshot configurations
snapshots:
  zoom_bronze_pipeline:
    +target_schema: utility
    +strategy: timestamp
    +updated_at: updated_at

# Seeds configurations
seeds:
  zoom_bronze_pipeline:
    +schema: utility
    +quote_columns: false

# Documentation
docs:
  generate: true
  
# Dispatch configuration for package compatibility
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['zoom_bronze_pipeline', 'dbt_utils']