# =====================================================
# DBT PROJECT CONFIGURATION - BRONZE LAYER (SIMPLIFIED)
# =====================================================
# Name: Bronze Layer Data Pipeline
# Purpose: Zoom Platform Analytics System - Medallion Architecture
# Author: AAVA
# Created: 2024-11-11
# Version: 1.0 (Simplified)
# =====================================================

name: 'zoom_bronze_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_bronze_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# =====================================================
# MODEL CONFIGURATIONS (SIMPLIFIED)
# =====================================================
models:
  zoom_bronze_pipeline:
    # Global model configurations
    +materialized: table
    +snowflake_warehouse: "WH_POC_Z_DEV_XSMALL"
    
    # Bronze layer specific configurations
    bronze:
      +materialized: table
      +tags: ["bronze", "raw_data"]
      +meta:
        layer: "bronze"
        owner: "data_engineering"
        description: "Raw data ingestion layer with minimal transformations"

# =====================================================
# VARIABLES (SIMPLIFIED)
# =====================================================
vars:
  # Environment variables
  environment: 'dev'
  
  # Bronze layer specific variables
  bronze_schema: 'bronze'
  raw_schema: 'raw'
  source_database: 'DB_POC_AAVA'
  
# =====================================================
# REQUIRE DBT VERSION
# =====================================================
require-dbt-version: [">=1.0.0", "<2.0.0"]

# =====================================================
# FLAGS
# =====================================================
flags:
  send_anonymous_usage_stats: false
  use_colors: true
  partial_parse: true
  static_parser: true
  warn_error: false
  log_format: text