# =====================================================
# DBT PROJECT CONFIGURATION
# Project: Zoom Platform Analytics System - Gold Layer
# Purpose: Transform Silver layer data to Gold layer dimensional model
# Database: DB_POC_ZOOM
# Target Schema: GOLD
# =====================================================

name: 'zoom_gold_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_pipeline:
    # Configuration for all models in this project
    +materialized: table
    +on_schema_change: "fail"
    
    # Audit log model - runs first
    audit:
      +materialized: table
      +pre-hook: "{{ log('Starting audit log execution', info=True) }}"
      +post-hook: "{{ log('Completed audit log execution', info=True) }}"
    
    # Gold layer models configuration
    gold:
      +materialized: table
      +schema: gold
      +database: DB_POC_ZOOM
      +pre-hook: |
        INSERT INTO {{ ref('go_audit_log') }} (
          execution_id,
          model_name,
          execution_start_time,
          execution_status,
          records_processed,
          load_timestamp
        ) VALUES (
          '{{ invocation_id }}',
          '{{ this.name }}',
          CURRENT_TIMESTAMP(),
          'STARTED',
          0,
          CURRENT_TIMESTAMP()
        )
      +post-hook: |
        UPDATE {{ ref('go_audit_log') }}
        SET 
          execution_end_time = CURRENT_TIMESTAMP(),
          execution_status = 'COMPLETED',
          records_processed = (SELECT COUNT(*) FROM {{ this }}),
          execution_duration_seconds = DATEDIFF('second', execution_start_time, CURRENT_TIMESTAMP())
        WHERE execution_id = '{{ invocation_id }}'
          AND model_name = '{{ this.name }}'
      
      # Dimension tables configuration
      dimension:
        +materialized: table
        +tags: ["dimension"]
        +meta:
          owner: "data_engineering"
          refresh_frequency: "daily"
      
      # Fact tables configuration  
      fact:
        +materialized: table
        +tags: ["fact"]
        +meta:
          owner: "data_engineering"
          refresh_frequency: "hourly"

# Global variables
vars:
  # Data quality thresholds
  data_quality_score_threshold: 80
  validation_status_filter: "'PASSED'"
  
  # Date ranges for incremental loads
  start_date: "'2020-01-01'"
  end_date: "'2030-12-31'"
  
  # Source and target schemas
  source_schema: "SILVER"
  target_schema: "GOLD"
  
  # Audit configuration
  enable_audit_logging: true
  
# Seeds configuration
seeds:
  zoom_gold_pipeline:
    +schema: gold
    +database: DB_POC_ZOOM

# Snapshots configuration
snapshots:
  zoom_gold_pipeline:
    +target_schema: gold
    +target_database: DB_POC_ZOOM

# Tests configuration
tests:
  +store_failures: true
  +schema: gold_tests

# Documentation configuration
docs:
  generate: true
  
# Dispatch configuration for package compatibility
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['zoom_gold_pipeline', 'dbt_utils']

# Query comment configuration
query-comment:
  comment: |
    /* 
    {{ node.name }} | {{ node.resource_type }} | {{ run_started_at }}
    Zoom Platform Analytics - Gold Layer Pipeline
    */
  append: true

# Require dbt version
require-dbt-version: [">=1.0.0", "<2.0.0"]

# Flags
flags:
  send_anonymous_usage_stats: false
  use_colors: true
  partial_parse: true
  static_parser: true