name: 'zoom_gold_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_pipeline:
    # Config indicated by + and applies to all files under models/gold/
    gold:
      +materialized: table
      +schema: gold
      +database: DB_POC_ZOOM
      +pre-hook: |
        INSERT INTO {{ ref('go_audit_log') }} 
        (audit_id, model_name, execution_start_time, execution_status, record_count, load_timestamp)
        VALUES (
          MD5(CONCAT('{{ this.name }}', CURRENT_TIMESTAMP()::STRING)),
          '{{ this.name }}',
          CURRENT_TIMESTAMP(),
          'STARTED',
          0,
          CURRENT_TIMESTAMP()
        )
      +post-hook: |
        UPDATE {{ ref('go_audit_log') }}
        SET execution_end_time = CURRENT_TIMESTAMP(),
            execution_status = 'COMPLETED',
            record_count = (SELECT COUNT(*) FROM {{ this }}),
            update_timestamp = CURRENT_TIMESTAMP()
        WHERE model_name = '{{ this.name }}'
          AND execution_status = 'STARTED'
          AND execution_start_time = (
            SELECT MAX(execution_start_time) 
            FROM {{ ref('go_audit_log') }} 
            WHERE model_name = '{{ this.name }}' 
              AND execution_status = 'STARTED'
          )
      # Dimension tables
      dimension:
        +materialized: table
        +tags: ["dimension"]
      # Fact tables  
      fact:
        +materialized: table
        +tags: ["fact"]
        +depends_on:
          - ref('go_dim_date')
          - ref('go_dim_user')
          - ref('go_dim_feature')
          - ref('go_dim_license')
          - ref('go_dim_meeting_type')
          - ref('go_dim_support_category')

# Global variables
vars:
  # Date range for dimension generation
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
  # Audit settings
  enable_audit_logging: true
  
  # Data quality thresholds
  data_quality_threshold: 0.95
  
  # Business rules
  standard_plan_types:
    - 'Basic'
    - 'Pro' 
    - 'Enterprise'

# Seeds configuration
seeds:
  zoom_gold_pipeline:
    +schema: reference_data
    +database: DB_POC_ZOOM

# Snapshots configuration  
snapshots:
  zoom_gold_pipeline:
    +target_schema: snapshots
    +target_database: DB_POC_ZOOM

# Test configurations
tests:
  +store_failures: true
  +schema: test_results
  +database: DB_POC_ZOOM