name: 'zoom_gold_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_pipeline:
    # Config indicated by + and applies to all files under models/gold/
    gold:
      +materialized: table
      +schema: gold
      +pre-hook: |
        {% if this.name != 'go_audit_log' %}
          INSERT INTO {{ ref('go_audit_log') }} 
          (audit_id, table_name, operation_type, operation_timestamp, record_count, user_name, session_id, source_system)
          VALUES 
          ({{ generate_uuid() }}, '{{ this.name }}', 'PRE_LOAD', CURRENT_TIMESTAMP(), 0, CURRENT_USER(), CURRENT_SESSION(), 'DBT_GOLD_PIPELINE')
        {% endif %}
      +post-hook: |
        {% if this.name != 'go_audit_log' %}
          INSERT INTO {{ ref('go_audit_log') }} 
          (audit_id, table_name, operation_type, operation_timestamp, record_count, user_name, session_id, source_system)
          VALUES 
          ({{ generate_uuid() }}, '{{ this.name }}', 'POST_LOAD', CURRENT_TIMESTAMP(), (SELECT COUNT(*) FROM {{ this }}), CURRENT_USER(), CURRENT_SESSION(), 'DBT_GOLD_PIPELINE')
        {% endif %}
      dimension:
        +materialized: table
      fact:
        +materialized: table

# Global variables
vars:
  # Date range for date dimension
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
  # Source system identifier
  source_system: 'ZOOM_SILVER_LAYER'
  
  # Audit configuration
  enable_audit_logging: true

# Macros for common transformations
macros:
  zoom_gold_pipeline:
    +materialized: view

# Seeds configuration
seeds:
  zoom_gold_pipeline:
    +schema: gold
    +materialized: table

# Snapshots configuration
snapshots:
  zoom_gold_pipeline:
    +target_schema: gold
    +strategy: timestamp
    +updated_at: update_timestamp

# Test configurations
tests:
  +store_failures: true
  +schema: gold_tests