# dbt_project.yml
# Zoom Platform Analytics System - Gold Layer DBT Project
# Author: Data Engineering Team
# Description: DBT project configuration for transforming Silver layer data into Gold layer dimension and fact tables

name: 'zoom_gold_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_analytics:
    # Config indicated by + and applies to all files under models/example/
    +materialized: table
    +on_schema_change: "fail"
    
    # Audit log model configuration (runs first)
    audit:
      +materialized: table
      +pre_hook: []
      +post_hook: []
      
    # Gold layer configurations
    gold:
      +materialized: table
      +pre_hook: |
        {% if this.name != 'go_audit_log' %}
          INSERT INTO {{ target.schema }}.go_audit_log (
            execution_id,
            model_name,
            execution_start_time,
            execution_status,
            source_system
          ) VALUES (
            '{{ invocation_id }}',
            '{{ this.name }}',
            CURRENT_TIMESTAMP,
            'STARTED',
            'DBT_GOLD_PIPELINE'
          )
        {% endif %}
      +post_hook: |
        {% if this.name != 'go_audit_log' %}
          UPDATE {{ target.schema }}.go_audit_log 
          SET 
            execution_end_time = CURRENT_TIMESTAMP,
            execution_status = 'COMPLETED',
            records_processed = (SELECT COUNT(*) FROM {{ this }})
          WHERE execution_id = '{{ invocation_id }}' 
            AND model_name = '{{ this.name }}'
            AND execution_status = 'STARTED'
        {% endif %}
      
      # Dimension tables configuration
      dimension:
        +materialized: table
        +tags: ["dimension"]
        
      # Fact tables configuration  
      fact:
        +materialized: table
        +tags: ["fact"]

# Global variables
vars:
  # Source schema configuration
  silver_schema: 'SILVER'
  gold_schema: 'GOLD'
  
  # Date range for initial load
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
  # Data quality thresholds
  min_data_quality_score: 80
  
  # Audit configuration
  enable_audit_logging: true
  
# Seeds configuration
seeds:
  zoom_gold_analytics:
    +schema: seeds
    +quote_columns: false

# Snapshots configuration
snapshots:
  zoom_gold_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: update_timestamp

# Tests configuration
tests:
  +store_failures: true
  +schema: test_failures

# Documentation configuration
docs:
  generate: true
  
# Dispatch configuration for package compatibility
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['zoom_gold_analytics', 'dbt_utils']

# Query comment configuration
query-comment:
  comment: 'Zoom Gold Analytics Pipeline - {{ node.name }} - Run ID: {{ invocation_id }}'
  append: true

# Require dbt version
require-dbt-version: [">=1.0.0", "<2.0.0"]

# Quoting configuration for Snowflake
quoting:
  database: false
  schema: false
  identifier: false