# dbt_project.yml for Zoom Platform Analytics Gold Layer
# Author: Data Engineering Team
# Created: 2024-12-19
# Description: DBT project configuration for transforming Silver Layer data into Gold Layer dimension and fact tables

name: 'zoom_gold_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  zoom_gold_analytics:
    # Global configurations for all models
    +materialized: table
    +on_schema_change: "fail"
    +pre-hook: |
      INSERT INTO {{ ref('go_process_audit') }} (
        AUDIT_LOG_ID,
        PROCESS_NAME,
        EXECUTION_START_TIMESTAMP,
        EXECUTION_STATUS,
        TARGET_TABLE_NAME,
        EXECUTED_BY,
        LOAD_DATE,
        SOURCE_SYSTEM
      )
      VALUES (
        '{{ invocation_id }}',
        '{{ this.name }}',
        CURRENT_TIMESTAMP(),
        'RUNNING',
        '{{ this }}',
        '{{ target.user }}',
        CURRENT_DATE(),
        'DBT_GOLD_PIPELINE'
      )
    +post-hook: |
      UPDATE {{ ref('go_process_audit') }}
      SET 
        EXECUTION_END_TIMESTAMP = CURRENT_TIMESTAMP(),
        EXECUTION_STATUS = 'SUCCESS',
        RECORDS_PROCESSED = (SELECT COUNT(*) FROM {{ this }}),
        UPDATE_DATE = CURRENT_DATE()
      WHERE AUDIT_LOG_ID = '{{ invocation_id }}'
        AND PROCESS_NAME = '{{ this.name }}'
    
    # Gold layer specific configurations
    gold:
      +schema: gold
      +materialized: table
      +cluster_by: ["LOAD_DATE"]
      
      # Dimension tables configuration
      dimension:
        +materialized: table
        +cluster_by: ["LOAD_DATE", "UPDATE_DATE"]
        +tags: ["dimension", "gold_layer"]
        
      # Fact tables configuration  
      fact:
        +materialized: table
        +cluster_by: ["DATE_KEY", "LOAD_DATE"]
        +tags: ["fact", "gold_layer"]
        
    # Audit table configuration
    audit:
      +schema: gold
      +materialized: table
      +cluster_by: ["EXECUTION_START_TIMESTAMP"]
      +tags: ["audit", "gold_layer"]

# Test configurations
tests:
  +store_failures: true
  +schema: gold_tests

# Snapshot configurations
snapshots:
  zoom_gold_analytics:
    +target_schema: gold_snapshots
    +strategy: timestamp
    +updated_at: update_timestamp

# Variables for the project
vars:
  # Date range for incremental loads
  start_date: '2020-01-01'
  end_date: '2030-12-31'
  
  # Audit configuration
  enable_audit_logging: true
  audit_schema: 'gold'
  
  # Data quality thresholds
  data_quality_threshold: 95
  uniqueness_check_enabled: true
  
  # Source system identifiers
  source_system: 'SILVER_TO_GOLD_ETL'
  
  # Clustering configuration
  enable_clustering: true
  
  # Error handling
  fail_on_error: false
  log_errors: true

# Dispatch configuration for cross-database compatibility
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['zoom_gold_analytics', 'dbt_utils']

# Documentation configuration
docs:
  generate: true
  
# Quoting configuration for Snowflake
quoting:
  database: false
  schema: false
  identifier: false

# Seeds configuration
seeds:
  zoom_gold_analytics:
    +schema: gold_seeds
    +quote_columns: false

# Macros configuration
macros:
  zoom_gold_analytics:
    +docs:
      show: true

# On-run-start and on-run-end hooks
on-run-start:
  - "{{ log('Starting Zoom Gold Analytics DBT Pipeline...', info=True) }}"
  - "CREATE SCHEMA IF NOT EXISTS {{ target.schema }}_gold"
  - "CREATE SCHEMA IF NOT EXISTS {{ target.schema }}_gold_tests"

on-run-end:
  - "{{ log('Zoom Gold Analytics DBT Pipeline completed successfully!', info=True) }}"
  - |
    {% if execute %}
      {{ log('Total models processed: ' ~ graph.nodes.values() | selectattr('resource_type', 'equalto', 'model') | list | length, info=True) }}
    {% endif %}

# Freshness configuration
freshness:
  warn_after: {count: 12, period: hour}
  error_after: {count: 24, period: hour}

# Require specific dbt version
require-dbt-version: [">=1.0.0", "<2.0.0"]

# Flags
flags:
  send_anonymous_usage_stats: false
  use_colors: true
  partial_parse: true
  static_parser: true
  warn_error: false
  log_format: text
  debug: false
  write_json: true

# Clean targets
clean-targets:
  - target
  - dbt_packages
  - logs

# Query comment configuration
query-comment:
  comment: "Generated by dbt for Zoom Gold Analytics Pipeline"
  append: true
  job-label: "zoom-gold-analytics"