version: 2

sources:
  - name: silver
    description: "Silver layer containing cleansed and standardized data"
    database: DB_POC_ZOOM
    schema: SILVER
    tables:
      - name: si_users
        description: "Cleansed user profile and subscription information"
        columns:
          - name: user_id
            description: "Unique identifier for each user"
            tests:
              - not_null
          - name: validation_status
            description: "Data validation status"
          - name: data_quality_score
            description: "Quality score from validation process"
            
      - name: si_meetings
        description: "Cleansed meeting information and session details"
        columns:
          - name: meeting_id
            description: "Unique identifier for each meeting"
            tests:
              - not_null
          - name: host_id
            description: "User ID of the meeting host"
          - name: validation_status
            description: "Data validation status"
          - name: data_quality_score
            description: "Quality score from validation process"
            
      - name: si_participants
        description: "Cleansed meeting participants and session details"
        columns:
          - name: participant_id
            description: "Unique identifier for each participant"
            tests:
              - not_null
          - name: meeting_id
            description: "Reference to meeting"
          - name: user_id
            description: "Reference to user who participated"
          - name: validation_status
            description: "Data validation status"
          - name: data_quality_score
            description: "Quality score from validation process"
            
      - name: si_feature_usage
        description: "Cleansed platform feature usage during meetings"
        columns:
          - name: usage_id
            description: "Unique identifier for each feature usage record"
            tests:
              - not_null
          - name: meeting_id
            description: "Reference to meeting where feature was used"
          - name: feature_name
            description: "Name of the feature being tracked"
          - name: validation_status
            description: "Data validation status"
          - name: data_quality_score
            description: "Quality score from validation process"
            
      - name: si_support_tickets
        description: "Cleansed customer support requests and resolution tracking"
        columns:
          - name: ticket_id
            description: "Unique identifier for each support ticket"
            tests:
              - not_null
          - name: user_id
            description: "Reference to user who created the ticket"
          - name: validation_status
            description: "Data validation status"
          - name: data_quality_score
            description: "Quality score from validation process"
            
      - name: si_billing_events
        description: "Cleansed financial transactions and billing activities"
        columns:
          - name: event_id
            description: "Unique identifier for each billing event"
            tests:
              - not_null
          - name: user_id
            description: "Reference to user associated with billing event"
          - name: validation_status
            description: "Data validation status"
          - name: data_quality_score
            description: "Quality score from validation process"
            
      - name: si_licenses
        description: "Cleansed license assignments and entitlements"
        columns:
          - name: license_id
            description: "Unique identifier for each license"
            tests:
              - not_null
          - name: assigned_to_user_id
            description: "User ID to whom license is assigned"
          - name: validation_status
            description: "Data validation status"
          - name: data_quality_score
            description: "Quality score from validation process"
